### ISSUE TITLE
Unable to run coverage on module

### ISSUE THREAD

**Issue by manoadamro** [coveragepy/coveragepy#1000]
**Describe the bug**

Can't run on single module

**To Reproduce**

```
python -m coverage run --source image_matching.py -m pytest

tests\test_image.py ..................

18 passed in 0.40s 

Coverage.py warning: Module image_matching.py was never imported. (module-not-imported)
Coverage.py warning: No data was collected. (no-data-collected)
No data to report.
```

test_image.py ONLY imports  image_matching.py, all the tests passed, so it was definitely imported

This works:
```
python -m coverage run --source . -m pytest
```
but it coveres absolutely everything, venv, and all.

interestingly, omitting the --souce and running:
```
python -m coverage run  -m pytest
```
causes it to cover everything in site packages on C: but none of the actual code in the directory its run from (on V:).

questions below:
1. What version of Python are you using? 
 3.7

1. What version of coverage.py are you using? The output of `coverage debug sys` is helpful.   
5.1

1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.
```
        "connexion==2.7.*",
        "environs==8.0.*",
        "fire==0.3.*",
        "flask==1.1.*",
        "flask_migrate==2.5.*",
        "flask_sqlalchemy==2.4.*",
        "kombu==4.6.*",
        "numpy==1.18.*",
        "opencv-contrib-python==3.4.2.16",
        "pandas==1.0.*",
        "pillow==7.1.*",
        "psycopg2-binary==2.8.*",
        "scipy==1.4.*",
        "waitress==1.4.*"
```

1. What code are you running?  Give us a specific commit of a specific repo that we can check out.

1. What commands did you run?
'python -m coverage run --source image_matching.py -m pytest'

**Expected behavior**
Coverage to run as normal, but on a single module

**Additional context**
Am on windows 10

**Comment by nedbat** [comment]
Hi, sorry this has taken so long.  The `--source` setting should be a directory or module name.  `image_matching.py` is not a directory, and it's not importable as `import image_matching.py`.   It should work if you use `--source=image_matching`.
