### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [coveragepy/coveragepy#1007]
**Summary**
Installing coverage on aarch64 via pip using command "pip3 install coverage" tries to build wheel from source code

**Problem description**
coverage don't have wheel for aarch64 on PyPI repository. So, while installing coverage via pip on aarch64, pip builds wheel for same resulting in it takes more time to install coverage. Making wheel available for aarch64 will benefit aarch64 users by minimizing coverage installation time.

**Expected Output**
Pip should be able to download coverage wheel from PyPI repository rather than building it from source code.

@coverage-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make coverage wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by odidev** [comment]
Gentle Reminder!!!

**Comment by odidev** [comment]
By specifying CentOS7, Manylinux2014 effectively ensures that the wheel is built against the AArch64 v8.0 specification. All AArch64 platforms in the v8 series (and Glibc) maintain backward compatibility with v8.0 so a binary built for v8.0 can run on any v8 platform. Enabling aarch64 support will benefit arm v8 series users by reducing installation time. Could you please let me know if you are interested to see a PR form my end for adding wheel support for aarch64.

**Comment by nedbat** [comment]
Hi, #908 added something for Travis, but since then I've moved to GitHub Actions.  The kit-building action (https://github.com/nedbat/coveragepy/blob/master/.github/workflows/kit.yml) could be updated?

**Comment by nedbat** [comment]
I might be misunderstanding, but I think we now have the wheels you need: https://pypi.org/project/coverage/#files, added by #1165.

If not, feel free to re-open this.
