### ISSUE TITLE
context on dark theme blends in

### ISSUE THREAD

**Issue by gaborbernat** [coveragepy/coveragepy#1009]
Reading the contexts on the dark theme is hard:
![Screenshot 2020-07-06 at 18 26 14459](https://user-images.githubusercontent.com/690238/86621569-51781a00-bfb6-11ea-93d4-550c1c2de926.png)

**Comment by nedbat** [comment]
Oops, sorry! This is fixed in 6ddd8c8e3abf1321277a07ecd2a5b1c857163ee1.

**Comment by gaborbernat** [comment]
@nedbat can we get a release with this? The current state makes the context almost impossible to view.

**Comment by nedbat** [comment]
This is available in [coverage 5.2.1](https://pypi.org/project/coverage/5.2.1).  Glad to know someone is using contexts! :)

**Comment by gaborbernat** [comment]
![thanks](https://media.tenor.co/images/cddcc354993a401d0315d53e61ca13d0/tenor.gif)
