### ISSUE TITLE
Fail under but per file and not global

### ISSUE THREAD

**Issue by patrickelectric** [coveragepy/coveragepy#1032]
**Is your feature request related to a problem? Please describe.**
If the projects has a huge numbers of tests and with 95% of coverage, if someone creates a new file without any tests the coverage goes to 94%, but this specific file has 0% of coverage. The objective of this proposal is to have an option to change fail_under from global to per file if necessary.

**Describe the solution you'd like**
Allow the fail_under configuration be per file or global.

**Describe alternatives you've considered**
Running coverage for each file individually, and that may be terrible to manage.

**Additional context**
Nops.

**Comment by nedbat** [comment]
Is this the same or different than #1018?

**Comment by patrickelectric** [comment]
Yep, same thing.

**Comment by nedbat** [comment]
Check the other issues for examples of standalone tools that do this, including https://nedbatchelder.com/blog/202111/coverage_goals.html
