### ISSUE TITLE
Export for Sonarqube

### ISSUE THREAD

**Issue by axil76** [coveragepy/coveragepy#1033]
Hello,
Is it possible to create an export format for sonarqube?
thank you

**Comment by nedbat** [comment]
@axil76 I know nothing about SonarQube, but this [Test Coverage & Execution](https://docs3.sonarqube.org/latest/analysis/coverage/) page seems to indicate that Cobertura XML files are accepted?  The "coverage xml" command writes a .xml file in Cobertura format.

Can you try it and report back?

**Comment by axil76** [comment]
Hello,
I have the impression that the output XML format is not the same
https://docs3.sonarqube.org/latest/analysis/generic-test/

below the error message

13:50:17.979 ERROR: Error during SonarScanner execution
Error during parsing of the generic coverage report '/tests/coverage.xml'. Look at SonarQube documentation to know the expected XML format.
Caused by: java.lang.IllegalStateException: Unknown report version: 5.3. This parser only handles version 1.

**Comment by nedbat** [comment]
Hmm, coverage uses the version attribute as the version of coverage.py.  Looks like SonarQube uses it as the version of the format, though I thought Cobertura was up to version 3 or 4....

Do you mind editing the xml file to set the version to 1, and see what SonarQube does with it?

**Comment by lucasscheepers** [comment]
Currently facing this [issue](https://stackoverflow.com/questions/69995004/codecoverage-not-showing-in-sonarcloud-in-a-python-project). Since someone referred to this issue, I'm hoping one of you can help me :) @nedbat

**Comment by mattwang44** [comment]
[this answer](https://stackoverflow.com/a/70088360) is still valid today ([SQ's doc](https://docs.sonarsource.com/sonarqube/9.8/analyzing-source-code/test-coverage/python-test-coverage/#analysis-parameter)), I believe this issue is fine to be closed.

**Comment by webknjaz** [comment]
> [this answer](https://stackoverflow.com/a/70088360) is still valid today ([SQ's doc](https://docs.sonarsource.com/sonarqube/9.8/analyzing-source-code/test-coverage/python-test-coverage/#analysis-parameter)), I believe this issue is fine to be closed.

@mattwang44 that answer features incorrect use of pytest args. It suggests that `--junitxml` generates coverage, but that's not true — it generates test report data, which is a different thing that also happens to use XML-based format.
