### ISSUE TITLE
Option to exclude the entire function from coverage calculation

### ISSUE THREAD

**Issue by jerinpetergeorge** [coveragepy/coveragepy#1048]
Suppose we have *two functions* with the same name in two different modules

```python
    # foo/foo.py
    def get_something():
        # fetch something
        # 10 line of branch code
        return "something foo/foo.py"
    

    # bar/foo.py    
    def get_something():
        # fetch something
        # 20 line of branch code
        return "something bar/foo.py"
```

How can we exclude the ***`bar.foo.get_something(...)`*** function "completely" ?

I hope it is nice to have a solution that would exclude the ***entire function*** from coverage calculation.

**Comment by nedbat** [comment]
The way to exclude the function is with a pragma comment:
```
# bar/foo.py    
def get_something():    # pragma: no cover
    # fetch something
    # 20 line of branch code
    return "something bar/foo.py"
```

Your question about two functions with the same name sounds like you have a way to exclude the function by name somewhere else.  Am I forgetting a way to do that?

**Comment by jerinpetergeorge** [comment]
Thanks for the replay @nedbat . I think the ***` # pragma: no cover`*** comment not working as expected

## Steps to reproduce
### 1. Create a simple script
```python
# sample_pragma_test.py
def foo(n: int):  # pragma: no cover
    if n % 2 == 0:
        return "even"
    return "odd"


for _ in range(10):
    print(_)
```
### 2. Run the script using `coverage` command
`coverage run sample_pragma_test.py`

### 3. Generate report
`coverage report`

```
Name                    Stmts   Miss      Cover
-----------------------------------------------
sample_pragma_test.py       6      3    50.000%

```
### 4. Generate HTM report
`coverage html -d .coverage-html`

Now, I have received the report as below,

![image](https://user-images.githubusercontent.com/21334929/97783356-1cbf4c80-1bbd-11eb-9b10-42afc659f2b2.png)

**Comment by nedbat** [comment]
When I try your program, I get:
```
Name                    Stmts   Miss  Cover
-------------------------------------------
sample_pragma_test.py       2      0   100%
```
Do you have a .coveragerc file with an `exclude_lines` setting in it?  If so, you have to make sure to include "pragma: no cover" in that setting because it overrides the default.

**Comment by jerinpetergeorge** [comment]
Wow!! You are right. I have a `.coveragerc` file with an `exclude_lines` setting. That caused the issue.

Once again, thanks a lot @nedbat
