### ISSUE TITLE
Better support for PyPy

### ISSUE THREAD

**Issue by mattip** [coveragepy/coveragepy#1049]
Looking at a comparison of running the tox CI on Ubuntu with [CPython3.6](https://github.com/tox-dev/tox/runs/1336342200?check_suite_focus=true) or [PyPy3.6](https://github.com/tox-dev/tox/runs/1336342209?check_suite_focus=true), the CPython tests take 22secs, the PyPy ones 59 secs. Would it run faster on PyPy without the [CTracer](https://github.com/nedbat/coveragepy/blob/master/coverage/collector.py#L21)?

It would also be nice to provide wheels for PyPy. If c-extensions are not used this could be a pypy-specific pure-python version like `coverage-5.3-pp36-none-none.whl`

xref [PyPy issue 3337](https://foss.heptapod.net/pypy/pypy/-/issues/3337)

**Comment by nedbat** [comment]
> Would it run faster on PyPy without the CTracer?

PyPy doesn't use the CTracer.  It uses PyTracer, which could be the reason for difference in speed.

> It would also be nice to provide wheels for PyPy. If c-extensions are not used this could be a pypy-specific pure-python version like coverage-5.3-pp36-none-none.whl

I'm happy to provide more wheels.  Do you know what I would have to do to make it happen?

**Comment by mattip** [comment]
Ahh, sorry, I missed that [setup.py checks for PyPy](https://github.com/nedbat/coveragepy/blob/0b1dd531f23d8ba313ee685b156b07f76fa680d5/setup.py#L180). 

As for wheels, `pypy3 setup.py bdist_wheel` builds `dist/coverage-5.3.1-py3-none-any.whl`. You don't want to upload that since it will be picked up by any python3, (cpython3.7, pypy3.6, ...), so you need to rename it to `dist/coverage-5.3.1-pp36-none-any.whl`. Unfortunately, pypa/packaging [originally rejected, but is willing to reconsider](https://github.com/pypa/packaging/issues/311) using a `pp3`python tag, so until someone does that work you would need to copy it to `dist/coverage-5.3.1-pp37-none-any.whl` as well. Then you could upload those two packages to PyPI.

**Comment by mattip** [comment]
You could also use `--python-tag` to get wheel to do the renaming for you. So the complete script would be
```
pypy3 -mpip install wheel
pypy3 setup.py bdist_wheel --python-tag pp36
pypy3 setup.py bdist_wheel --python-tag pp37
<upload dist/* to pypi>
```

**Comment by nedbat** [comment]
I recently switched to cibuildwheel to make kits: https://github.com/nedbat/coveragepy/blob/master/.github/workflows/kit.yml
It makes these kits:
```
coverage-5.3.1-cp27-cp27m-macosx_10_9_x86_64.whl
coverage-5.3.1-cp27-cp27m-manylinux1_i686.whl
coverage-5.3.1-cp27-cp27m-manylinux1_x86_64.whl
coverage-5.3.1-cp27-cp27m-manylinux2010_i686.whl
coverage-5.3.1-cp27-cp27m-manylinux2010_x86_64.whl
coverage-5.3.1-cp27-cp27m-win32.whl
coverage-5.3.1-cp27-cp27m-win_amd64.whl
coverage-5.3.1-cp27-cp27mu-manylinux1_i686.whl
coverage-5.3.1-cp27-cp27mu-manylinux1_x86_64.whl
coverage-5.3.1-cp27-cp27mu-manylinux2010_i686.whl
coverage-5.3.1-cp27-cp27mu-manylinux2010_x86_64.whl
coverage-5.3.1-cp35-cp35m-macosx_10_9_x86_64.whl
coverage-5.3.1-cp35-cp35m-manylinux1_i686.whl
coverage-5.3.1-cp35-cp35m-manylinux1_x86_64.whl
coverage-5.3.1-cp35-cp35m-manylinux2010_i686.whl
coverage-5.3.1-cp35-cp35m-manylinux2010_x86_64.whl
coverage-5.3.1-cp35-cp35m-win32.whl
coverage-5.3.1-cp35-cp35m-win_amd64.whl
coverage-5.3.1-cp36-cp36m-macosx_10_9_x86_64.whl
coverage-5.3.1-cp36-cp36m-manylinux1_i686.whl
coverage-5.3.1-cp36-cp36m-manylinux1_x86_64.whl
coverage-5.3.1-cp36-cp36m-manylinux2010_i686.whl
coverage-5.3.1-cp36-cp36m-manylinux2010_x86_64.whl
coverage-5.3.1-cp36-cp36m-win32.whl
coverage-5.3.1-cp36-cp36m-win_amd64.whl
coverage-5.3.1-cp37-cp37m-macosx_10_9_x86_64.whl
coverage-5.3.1-cp37-cp37m-manylinux1_i686.whl
coverage-5.3.1-cp37-cp37m-manylinux1_x86_64.whl
coverage-5.3.1-cp37-cp37m-manylinux2010_i686.whl
coverage-5.3.1-cp37-cp37m-manylinux2010_x86_64.whl
coverage-5.3.1-cp37-cp37m-win32.whl
coverage-5.3.1-cp37-cp37m-win_amd64.whl
coverage-5.3.1-cp38-cp38-macosx_10_9_x86_64.whl
coverage-5.3.1-cp38-cp38-manylinux1_i686.whl
coverage-5.3.1-cp38-cp38-manylinux1_x86_64.whl
coverage-5.3.1-cp38-cp38-manylinux2010_i686.whl
coverage-5.3.1-cp38-cp38-manylinux2010_x86_64.whl
coverage-5.3.1-cp38-cp38-win32.whl
coverage-5.3.1-cp38-cp38-win_amd64.whl
coverage-5.3.1-cp39-cp39-macosx_10_9_x86_64.whl
coverage-5.3.1-cp39-cp39-manylinux1_i686.whl
coverage-5.3.1-cp39-cp39-manylinux1_x86_64.whl
coverage-5.3.1-cp39-cp39-manylinux2010_i686.whl
coverage-5.3.1-cp39-cp39-manylinux2010_x86_64.whl
coverage-5.3.1-cp39-cp39-win32.whl
coverage-5.3.1-cp39-cp39-win_amd64.whl
coverage-5.3.1.tar.gz
```
I guess I need more education: how specifically would the pp37 wheel improve things? I can add the steps you mention, but it would help me to understand the benefit.

**Comment by nedbat** [comment]
I'm trying out your steps in https://github.com/nedbat/coveragepy/pull/1077

**Comment by mattip** [comment]
cool. That is an impressive list of wheels. FWIW, NumPy is planning to drop manylinux1 by July 2021.

I see since this is a "workflow_dispatch" run of github actions, you will have to run it manually. I wonder if there is a way to toggle upload to pypi-test instead of to pypi in order to try it out.

**Comment by nedbat** [comment]
For now, I'm happy to handle the uploading manually (well, automated from my machine).  What is it that we are gaining by having pp36 and pp37 wheels over the source distribution?

**Comment by mattip** [comment]
It could save a few seconds in installing the package since `pip install` will download the source, unpack the `tar.gz`, build a wheel (essentially repacking it in a zip format) and then unpack the wheel into `site-packages`.

**Comment by nedbat** [comment]
The new wheels are now built, as a result of #1077.

**Comment by mattip** [comment]
Thanks
