### ISSUE TITLE
Empty report when using pytest-cov import-mode=importlib

### ISSUE THREAD

**Issue by debeshmandal** [coveragepy/coveragepy#1052]
**Describe the bug**
I have a problem that when I run this command, nothing is reported:
```
pytest --import-mode=importlib --cov=hydrogels --cov-report=xml -s
```
[Repository](https://github.com/debeshmandal/hydrogels/tree/packaging-fix)

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't just link to a failing CI job. Answer the questions below:
1. What version of Python are you using?
1. What version of coverage.py are you using? The output of `coverage debug sys` is helpful.
1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.
1. What code are you running?  Give us a specific commit of a specific repo that we can check out.
1. What commands did you run?

External Libraries: HDF5 (e.g. `sudo apt-get install libhdf5-dev` for Ubuntu)
Python: 3.8
Coverage: 5.3 with C Extension
Packages - installed using pip:
  - `numpy`
  - `scipy`
  - `pandas`
  - `matplotlib`
  - `pytest`
  - `tqdm` 
  - `h5py` 
  - `pybind11`
  - `cmake` 
  - `starpolymers`
  - `pytest-cov`
  - `readdy` - this is tricky to install - it is done by doing the following:

```
# install readdy
pushd /tmp
git clone https://github.com/readdy/readdy
pushd readdy
pip install .
popd
popd
python -c 'from readdy import *'
```

Installing my package and producing the report to the terminal

```
# install hydrogels
git clone https://github.com/debeshmandal/hydrogels
git checkout packaging-fix # or git checkout 8334e03 for desired report
pip install .
pytest --import-mode=importlib --cov term
```

**Expected behavior**
I would expect something like this:
[Expected Coverage](https://codecov.io/gh/debeshmandal/hydrogels/tree/8334e0353220b5a319ae5a3878a653dfb1d0e022)

But instead get something like this:
[Current report](https://codecov.io/gh/debeshmandal/hydrogels/tree/c64f685012c5aac2ad328dbc05a69390a3aa2710)

**Additional context**
The difference between the old and desired coverage report and the new undesired one is the following:

- I am trying to bundle C++ bindings into the `hydrogels`  package
- Before I had a separate library called `hydrogelsbindings` that would allow me to omit the `--import-mode=importlib` from the pytest command
- Now this is included to keep the package as one set of files rather than two

**Comment by debeshmandal** [comment]
I forgot to add, in a `setup.cfg` file I have the following:

```ini
[coverage:report]
omit = *test*, *_version.py
# Regexes for lines to exclude from consideration
exclude_lines =
    # Have to re-enable the standard pragma
    pragma: no cover

    # Don't complain about missing debug-only code:
    def __repr__
    if self\.debug

    # Don't complain if tests don't hit defensive assertion code:
    raise AssertionError
    raise NotImplementedError

    # Don't complain if non-runnable code isn't run:
    if 0:
    if __name__ == .__main__.:
```

**Comment by nedbat** [comment]
Hi, sorry for the delay.  This seems like something that should be reported to pytest-cov: https://github.com/pytest-dev/pytest-cov/
