### ISSUE TITLE
Don't report missing branches to missing lines.

### ISSUE THREAD

**Issue by tolomea** [coveragepy/coveragepy#1065]
This is a small quality of life suggestion that would make coverage reports easier to read.

**Is your feature request related to a problem? Please describe.**
Branch coverage can make missing coverage reports difficult to read.

**Describe the solution you'd like**
Reporting missing branches to missing lines is redundant, if the line didn't get covered then obviously any branches to it didn't either. Omitting these would make coverage reports shorter and easier to read in a lot of cases.

Lets consider one block of 20 lines in one of my files. The missing section of the coverage report looks like this:

496->497, 497, 500->504, 504, 506->510, 510, 512->516, 516

In my humble opinion all of these particular branch reports are unnecessary. Not reporting them would significantly reduce the cognitive load of going through this info and addressing the misses.

497, 504, 510, 516

Of course some branch reports contain useful information. I'm just talking about ones that go to lines that are already going to be reported as missing.

**Comment by nedbat** [comment]
I see your point :)

**Comment by nedbat** [comment]
This is now released as part of [coverage 5.5](https://pypi.org/project/coverage/5.5).

**Comment by tolomea** [comment]
Thank you

**Comment by leon-matthews** [comment]
This fix is very much appreciated, thank you both!
