### ISSUE TITLE
Merging together two coverage reports from same repo?

### ISSUE THREAD

**Issue by jamesbraza** [coveragepy/coveragepy#1074]
**Feature Request**

Merging 2+ `coverage` reports into one.

**Motivation**

- One repo containing two different Python packages
- One unit test suite (via `pytest`) in each package.  Here's a general idea of the structure:
    - `repo_root/pkg1/src`
    - `repo_root/pkg1/test`
    - `repo_root/pkg2/src`
    - `repo_root/pkg2/test`
- One CI pipeline via CircleCI
    - `coverage run -m pytest` is invoked twice --> two `coverage` reports
        - Once in `repo_root/pkg1/test`
        - Once in `repo_root/pkg2/test`
- We use [Codecov](https://codecov.io/) for web visualization of our `coverage` reports

I would like to somehow merge both `coverage` reports into one so that I can submit to the [Codecov CircleCI orb](https://circleci.com/developer/orbs/orb/codecov/codecov) in one go.

This _may_ already be possible, but it's not explicitly stated anywhere in docs.  If it's not possible, then this is a feature request.

**Comment by nedbat** [comment]
You should be able to move the `.coverage` data files to new names (like `.coverage.1` and `.coverage.2`) then use the `coverage combine` command to combine them.  You might need to experiment with the `[paths]` setting in the configuration file to get the file paths properly understood.

Unless I'm missing some detail...

**Comment by jamesbraza** [comment]
Thank you @nedbat for responding!  It has been nearly a year since I made this issue, I ended up going with a workaround.

Looks like `coverage combine` was available at the time, I must have missed that it existed...

I am going to close this issue, thanks again!
