### ISSUE TITLE
CLI --context not used when multiprocessing is enabled(for child processes)

### ISSUE THREAD

**Issue by s0undt3ch** [coveragepy/coveragepy#1079]
**Describe the bug**
When running coverage and passing `--context=foo`, only the main process uses that `foo` static context.
Any sub-processes, which do get coverage because we're setting `COVERAGE_PROCESS_START`, will not use that `foo` context, instead, they report an `empty` context.

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't just link to a failing CI job. Answer the questions below:
1. What version of Python are you using?
It's independent of the python version used.
1. What version of coverage.py are you using? The output of `coverage debug sys` is helpful.
5.3
1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.
A lot, and I don't think they're related to this issue, but I can add that to the issue if strictly necessary.
1. What code are you running?  Give us a specific commit of a specific repo that we can check out.
https://github.com/s0undt3ch/salt/tree/features/coverage-contexts
1. What commands did you run?
```
nox -e 'pytest-zeromq-3(coverage=True)' -- -vv --run-destructive --run-slow --ssh-tests --log-cli-level=debug --showlocals tests/integration/modules/test_config.py --maxfail=1
```

**Expected behavior**
I would expect that the context passed through `--context`, to be "inherited" but any subprocess which has coverage enabled.

**Comment by s0undt3ch** [comment]
I only see a fix for this, coverage set's an environment variable and when `coverage.process_startup()` is called, that environment variable is used to set the initial context.
Know a better way?

**Comment by s0undt3ch** [comment]
@nedbat would you think adding the CLI parsed options as an env variable(json encoded?), which would then be used for when calling `coverage.process_startup()` a proper fix?
I have no issues providing a PR, as long as you see that it's the right path to take.

**Comment by s0undt3ch** [comment]
Or perhaps, why don't we use `Stowawy` to also include the loaded coverage config(and use that config) instead of just the rcfile?

**Comment by nedbat** [comment]
Hi, sorry I haven't responded yet. 

In general, the command-line options are not passed to the subprocesses.  I'm wondering why --context should get special treatment?  Is there a reason you have to specify context on the command line?  Another option is to use an environment variable to set the context, and then use variable expansion in the configuration file to set the context.
