### ISSUE TITLE
Assert not covered

### ISSUE THREAD

**Issue by earonesty** [coveragepy/coveragepy#1083]
So, in a fairly complex code base, I have a line of code - a required abstract method override - and I wanted to be sure that line of code was /never/ covered in any test, even during thousands of integration tests, etc.

While I was grateful to see that it was /not/ in the coverage report, it occurred to me that this would make a good feature.

A way to specify that "no coverage" is the /only/ acceptable result for a line of code that should never be called - in any context and for any test.

```
def handler(self):
    # pragma: assert not covered
    pass
```

(This is not the same as `pragma: no cover`)

Obviously I could mock this function in every test that *might* possibly hit it, and then assert the mock is not called.   But this is, of course, not future proof.   Some new developer might come along, and incorrectly instantiate the class.... and his new tests will pass... and hit the offending code incorrectly.

I think it would be a cool new feature, and not hard to do, unless there's some other way to do this I'm not thinking of.

**Comment by elarivie** [comment]
@earonesty 

Why aren't you using:

```
raise AssertionError("Should never reach this") # pragma: no cover
```

This way you will have the guarantee that this line of code is never run... and if it ever does then you will get an AssertionError

**Comment by nedbat** [comment]
@earonesty I see what you mean about the line that shouldn't execute. I agree with @elarivie that a `raise` would serve your purpose.  What do you think?
