### ISSUE TITLE
Add option to include TOTAL line even if there's only one file

### ISSUE THREAD

**Issue by lordjabez** [coveragepy/coveragepy#1086]
**Is your feature request related to a problem? Please describe.**
Currently the total line is skipped when there's only one file whose coverage was computed. This is annoying when using a regex to report on coverage from a CI/CD build log (e.g. in Gitlab) because one can't use the recommended regex.

**Describe the solution you'd like**
Either always print the TOTAL line, or add an option to force it even when there's only one file.

**Comment by nedbat** [comment]
This has been requested before (#732, #922). I think my mind has changed, and we can go ahead and add an option for this.

**Comment by lordjabez** [comment]
@nedbat I'd be happy to take a crack at coding it up. Do you have a preference on the option name? `--always-show-total` ? `--show-total` ? Something else?

**Comment by nedbat** [comment]
Thanks. I would name it `--always-total`.  Don't forget the .coveragerc option.

**Comment by nedbat** [comment]
I hope this doesn't sound aggravating, but maybe the better path here is to just always output the total line, without an option.

**Comment by lordjabez** [comment]
Not aggravating at all, I'm more than happy to go with a simpler solution.

I'll submit a new PR (and make sure all the tests still pass).

**Comment by nedbat** [comment]
This is now released as part of [coverage 5.4](https://pypi.org/project/coverage/5.4).
