### ISSUE TITLE
Allow overriding skip_covered under the html section

### ISSUE THREAD

**Issue by gaborbernat** [coveragepy/coveragepy#1090]
For a terminal report to not show fully covered lines, one can set skip_covered to True. For HTML reports though you do want to report on all files, so you can see what covers what. Would be good to be able to specify this configuration scenario via the config only, perhaps by allowing to override ``coverage:report`` ``skip_covered`` under ``coverage:html``. Currently, you can only override via the CLI, but for example in ``pytest-cov`` these flags are not exposed to alter. 

PS. pytest-cov ticket solution for this https://github.com/pytest-dev/pytest-cov/issues/449

**Comment by ryboe** [comment]
I'd like to be able to write this in `pyproject.toml`.
```toml
[tool.coverage.html]
skip_covered = true
```

Thank you! 🙏

**Comment by nedbat** [comment]
This is implemented in https://github.com/nedbat/coveragepy/pull/1099.  Does it do what you need?

**Comment by ryboe** [comment]
Yes it does! Thank you! That was so fast! 🙏

**Comment by nedbat** [comment]
This is now released as part of [coverage 5.4](https://pypi.org/project/coverage/5.4).
