### ISSUE TITLE
There is a small typo intgers which should read integers.

### ISSUE THREAD

**Issue by timgates42** [coveragepy/coveragepy#1092]
**Describe the bug**
There is a small typo intgers in
- coverage/htmlfiles/jquery.isonscreen.js
- doc/sample_html/jquery.isonscreen.js
- tests/gold/html/support/jquery.isonscreen.js

It should read integers, the file looks to be externally sourced but I couldn't locate the original source to fix also.

I've prepared a branch with a fix but to avoid wasting CI time if this change is not going to be accepted I have not yet created a PR from...

https://github.com/timgates42/coveragepy/pull/new/bugfix_typo_integers

If the issue is accepted I can create the PR or else feel free to use the link above to create the PR.

**Comment by nedbat** [comment]
Thanks, but since the file is vendored, not mine, I would rather not correct it.
