### ISSUE TITLE
json_report lacks the skip_empty argument

### ISSUE THREAD

**Issue by cnzhujie** [coveragepy/coveragepy#1100]
xml_report and html_report both has the skip_empty argument, but json_report doesn't have this argument.
![image](https://user-images.githubusercontent.com/4935935/104181034-0f3e0280-5449-11eb-8c1b-ed4973a1fe16.png)

**Comment by nedbat** [comment]
My theory about the JSON report is that it is not meant for human eyes, it is meant to be parsed by a program.  That program can choose to skip empty files if it chooses.

How are you using the JSON report?

**Comment by cnzhujie** [comment]
> My theory about the JSON report is that it is not meant for human eyes, it is meant to be parsed by a program. That program can choose to skip empty files if it chooses.
> 
> How are you using the JSON report?

My JSON report will be parsed by my program and users can not see it.
I am just confused that why json_report doesn't have the skip_empty argument when I reading the code.
Your answer resolves my confusion. Thank you
