### ISSUE TITLE
Combine converage reports from different platforms and produce meaningful HTML reports (Windows / Unix-like)

### ISSUE THREAD

**Issue by s-m-e** [coveragepy/coveragepy#1102]
**Is your feature request related to a problem? Please describe.**

When testing code with platform-specific passages e.g. both on Windows and Linux, it would be nice to have a clean way of combining the resulting coverage reports and producing HTML reports. If I am not totally mistaken, this sort of worked until about a year or so ago. I am not entirely sure why though.

Technically, the combination part still "works", but because of the differences between the absolute Windows and the Unix paths contained in `.converage` files, the result is virtually worthless. Generating an HTML report from such a combined coverage file subsequently fails because e.g. the Linux system can not locate the tested Python files based on their Windows paths.

**Describe the solution you'd like**

If `.converage` files would store paths as relative paths, they could probably be matched (despite the differences between Windows and Unix) when combining.

**Describe alternatives you've considered**

Manually rewriting `.converage` files before combining them ...

**Additional context**

I am developing a little Python package called [zugbruecke](https://github.com/pleiszenburg/zugbruecke):

> zugbruecke allows to call routines in Windows DLLs from Python code running on Unices / Unix-like systems such as Linux, MacOS or BSD. zugbruecke is designed as a drop-in replacement for Python's standard library's ctypes module. zugbruecke is built on top of Wine. A stand-alone Windows Python interpreter launched in the background is used to execute the called DLL routines. 

Part of my code runs on a Linux Python interpreter, another part of my code runs on a Windows Python interpreter on top of Wine and some of my code actually runs on both sides. In case anyone wants to experiment with it and coverage, the relevant & latest code can be found in the branch [refactor_moduledesign](https://github.com/pleiszenburg/zugbruecke/tree/refactor_moduledesign). If Wine is present, `make install` and `make test` should be enough. It should produce three `.coverage*` files which are supposed [to be joined into one - plus an HTML report](https://github.com/pleiszenburg/zugbruecke/blob/c7b4b307475b51162777c0ad3e023e875b4d00bc/makefile#L88).

**Comment by nedbat** [comment]
Hi, it sounds like you need to define `[paths]` section for `coverage combine` to use to identify the equivalent paths on different machines.  Is it possible you used to have that defined?

**Comment by s-m-e** [comment]
Thanks for the help - indeed, I had configured this already and totally forgot about it. `setup.cfg` contains the following lines:

```
[coverage:paths]
source =
    src/
    c:\*\site-packages
```

It actually works (**also across platforms**) when invoked with `pytest --cov=packagename --cov-config=setup.cfg`. For some odd reason, the driver letter on Windows/Wine had changed.
