### ISSUE TITLE
have coverage combine output the processed input files

### ISSUE THREAD

**Issue by altendky** [coveragepy/coveragepy#1105]
**Is your feature request related to a problem? Please describe.**
I just added coverage combining within [GitHub Actions for pymodbus](https://github.com/riptideio/pymodbus/runs/1735845507?check_suite_focus=true) and the coverage is lower than I wildly guessed.  My first thought was 'am I collecting all the files I meant to?' 

**Describe the solution you'd like**
I thought it would be helpful for `coverage combine` to output the files it processes via `--verbose` or some other more specific option.

**Describe alternatives you've considered**
I first thought about adding an `ls -la coverage_reports/` to check the contents of the directory I passed to `coverage combine`, but that doesn't say what coverage actually combined.

**Additional context**
n/a

**Comment by nedbat** [comment]
This seems like a good idea.  Somehow, coverage doesn't have any `--verbose` options yet.

**Comment by nedbat** [comment]
It occurred to me today that coverage doesn't have `--verbose`, but it does have `--debug`.  Is there a reason not to use it for this?

**Comment by altendky** [comment]
It strikes me as more diagnostic logging than debugging but...  I'm definitely not going to define the two sufficiently to distinguish them.  `:]`  If you feel `--debug` is the place that fits, I'm game.  It looks like people will have to look to the website to find the debug options, as opposed to being available in the CLI?

**Comment by nedbat** [comment]
I've implemented this in 1f51202a. There's no option or control, the command just prints the messages.

**Comment by altendky** [comment]
Thanks nedbat.  `:]`

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.0](https://pypi.org/project/coverage/6.0).
