### ISSUE TITLE
Coverage XML shows 0% coverage when created from a different program

### ISSUE THREAD

**Issue by seankane-msft** [coveragepy/coveragepy#1109]
**Describe the bug**
I am creating my `.coverage` files in an Azure Pipelines job on one machine, I then save the files and publish them as an artifact. On a different job I download all the `.coverage` files (they are formatted like `.coverage-{library tested}` to not overwrite each other) and attempt a `coverage combine` and finally a `coverage xml` before publishing the code coverage. While doing this I do a string find and replace to make sure the paths to the files are still valid, but the ending `coverage.xml` file shows 0% coverage, but manual inspection of the individual `.coverage` files shows that there are lines that are hit by the tests. 

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't just link to a failing CI job. Answer the questions below:
1. What version of Python are you using?
    Using python 3.7.9
1. What version of coverage.py are you using? The output of `coverage debug sys` is helpful.
    Using coverage==4.5.4
1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.
    tox==3.15.0
    tox-monorepo==0.1.2
    pytest-cov==2.8.1
1. What code are you running?  Give us a specific commit of a specific repo that we can check out.
1. What commands did you run? (combined answer with above question
```
pytest --junitxml=/mnt/vss/_work/1/s/sdk/appconfiguration/azure-appconfiguration/test-junit-whl.xml --verbose --durations=10 --ignore=azure --ignore=.tox --ignore=build --ignore=.eggs --cov=azure.appconfiguration --cov-append --ignore azure_appconfiguration.egg-info /mnt/vss/_work/1/s/sdk/appconfiguration/azure-appconfiguration
```

From the root of the [Azure SDK](https://github.com/Azure/azure-sdk-for-python) repository 

**Expected behavior**
I expect a coverage report reflecting the same data as the `.coverage` file in an xml format.

**Additional context**
We are running coverage from the `pytest-cov` plugin to pytest, and we are running pytest within `tox`. The `pytest-cov` does not allow for the `--parallel` option according to these [docs](https://pytest-cov.readthedocs.io/en/latest/config.html)

**Comment by nedbat** [comment]
You mentioned string search and replace to fix the file paths.  Did you try using the [[paths]](https://coverage.readthedocs.io/en/coverage-5.4/config.html#paths) configuration setting so that `coverage combine` can adjust the paths itself? Maybe I misunderstood what that step was for.

**Comment by seankane-msft** [comment]
@nedbat  I believe this has solved my issue. Thanks for your prompt response!
