### ISSUE TITLE
Different behaviour of coverage xml when source is specified in .coveragerc as opposed to on command line

### ISSUE THREAD

**Issue by slushysnowman** [coveragepy/coveragepy#1117]
**Describe the bug**
When source is specified in .coveragerc, the XML report that is output by `coverage xml` differs from the report that is output by coverage report.

When coverage run is configured via command line:
```
coverage run --source scripts -m unittest discover -s tests
coverage report
coverage xml
```
The output of `coverage report` is:
```
Name                       Stmts   Miss  Cover
----------------------------------------------
scripts/__init__.py            0      0   100%
scripts/sample_script.py       6      0   100%
----------------------------------------------
TOTAL                          6      0   100%
```
and the same name structure can be seen in the XML:
```
<?xml version="1.0" ?>
<coverage version="5.4" timestamp="1613120302851" lines-valid="6" lines-covered="6" line-rate="1" branches-covered="0" branches-valid="0" branch-rate="0" complexity="0">
	<!-- Generated by coverage.py: https://coverage.readthedocs.io -->
	<!-- Based on https://raw.githubusercontent.com/cobertura/web/master/htdocs/xml/coverage-04.dtd -->
	<sources>
		<source>/home/xxx/test-project</source>
	</sources>
	<packages>
		<package name="scripts" line-rate="1" branch-rate="0" complexity="0">
			<classes>
				<class name="__init__.py" filename="scripts/__init__.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines/>
				</class>
				<class name="sample_script.py" filename="scripts/sample_script.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="1" hits="1"/>
						<line number="3" hits="1"/>
						<line number="4" hits="1"/>
						<line number="5" hits="1"/>
						<line number="6" hits="1"/>
						<line number="8" hits="1"/>
					</lines>
				</class>
			</classes>
		</package>
	</packages>
</coverage>
```
However when source is configured in .coveragerc as below:
```
[run]
command_line = -m unittest discover -s tests
source = scripts
```
and the equivalent commands are run again:
```
coverage run
coverage report
coverage xml
```
Coverage report output (the same):
```
Name                       Stmts   Miss  Cover
----------------------------------------------
scripts/__init__.py            0      0   100%
scripts/sample_script.py       6      0   100%
----------------------------------------------
TOTAL                          6      0   100%
```
but the names in the XML differ from when source is defined via command line - the source, 'scripts' is appended to the 'source', instead of being specified in the package name:
```
<?xml version="1.0" ?>
<coverage version="5.4" timestamp="1613120765732" lines-valid="6" lines-covered="6" line-rate="1" branches-covered="0" branches-valid="0" branch-rate="0" complexity="0">
	<!-- Generated by coverage.py: https://coverage.readthedocs.io -->
	<!-- Based on https://raw.githubusercontent.com/cobertura/web/master/htdocs/xml/coverage-04.dtd -->
	<sources>
		<source>/home/xxx/test-project/scripts</source>
	</sources>
	<packages>
		<package name="." line-rate="1" branch-rate="0" complexity="0">
			<classes>
				<class name="__init__.py" filename="__init__.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines/>
				</class>
				<class name="sample_script.py" filename="sample_script.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="1" hits="1"/>
						<line number="3" hits="1"/>
						<line number="4" hits="1"/>
						<line number="5" hits="1"/>
						<line number="6" hits="1"/>
						<line number="8" hits="1"/>
					</lines>
				</class>
			</classes>
		</package>
	</packages>
</coverage>
```
Why is this an issue?

- In cases where multiple sources are defined, the second behaviour of the XML command doesn't make it clear which package relates to which source
- In the second case (and this is actually how I stumbled upon this) importing of coverage reports into SonarQube fails

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't just link to a failing CI job. Answer the questions below:
1. What version of Python are you using? Python 3.8.5
1. What version of coverage.py are you using? The output of `coverage debug sys` is helpful.
```
coverage debug sys
-- sys -------------------------------------------------------
                        version: 5.4
                       coverage: /home/xxx/.local/lib/python3.8/site-packages/coverage/__init__.py
                         tracer: -none-
                        CTracer: available
           plugins.file_tracers: -none-
            plugins.configurers: -none-
      plugins.context_switchers: -none-
              configs_attempted: .coveragerc
                   configs_read: /home/xxx/repo/rabbitmq-to-stackstate/.coveragerc
                    config_file: /home/xxx/repo/rabbitmq-to-stackstate/.coveragerc
                config_contents: b'[run]\nbranch = True\ncommand_line = -m unittest discover -s tests\n\n[report]\nignore_errors = True'
                      data_file: -none-
                         python: 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
                       platform: Linux-5.4.0-56-generic-x86_64-with-glibc2.29
                 implementation: CPython
                     executable: /usr/bin/python3
                   def_encoding: utf-8
                    fs_encoding: utf-8
                            pid: 13905
                            cwd: /home/xxx/repo/rabbitmq-to-stackstate
                           path: /home/xxx/.local/bin
                                 /usr/lib/python38.zip
                                 /usr/lib/python3.8
                                 /usr/lib/python3.8/lib-dynload
                                 /home/xxx/.local/lib/python3.8/site-packages
                                 /home/xxx/repo/harbor-eks-fargate/harbor_eks_fargate
                                 /usr/local/lib/python3.8/dist-packages
                                 /usr/lib/python3/dist-packages
                    environment: -none-
                   command_line: /home/xxx/.local/bin/coverage debug sys
                sqlite3_version: 2.6.0
         sqlite3_sqlite_version: 3.31.1
             sqlite3_temp_store: 0
        sqlite3_compile_options: COMPILER=gcc-9.3.0
                                 ENABLE_COLUMN_METADATA
                                 ENABLE_DBSTAT_VTAB
                                 ENABLE_FTS3
                                 ENABLE_FTS3_PARENTHESIS
                                 ENABLE_FTS3_TOKENIZER
                                 ENABLE_FTS4
                                 ENABLE_FTS5
                                 ENABLE_JSON1
                                 ENABLE_LOAD_EXTENSION
                                 ENABLE_PREUPDATE_HOOK
                                 ENABLE_RTREE
                                 ENABLE_SESSION
                                 ENABLE_STMTVTAB
                                 ENABLE_UNLOCK_NOTIFY
                                 ENABLE_UPDATE_DELETE_LIMIT
                                 HAVE_ISNAN
                                 LIKE_DOESNT_MATCH_BLOBS
                                 MAX_SCHEMA_RETRY=25
                                 MAX_VARIABLE_NUMBER=250000
                                 OMIT_LOOKASIDE
                                 SECURE_DELETE
                                 SOUNDEX
                                 TEMP_STORE=1
                                 THREADSAFE=1
                                 USE_URI
```

1. Run `coverage run`, defining source via command line
2. Run `coverage xml` and look at output
3. Create .coveragerc and define source in the [run] section
4. Run `coverage xml` and look at output

Output for `coverage xml` is different in these 2 cases (look at 'sources' and 'package name')

**Expected behavior**
Even when source is defined in .coveragerc, the output should be the same as when source is defined on command line

**Comment by slushysnowman** [comment]
Code demonstrating behaviour when source defined for `coverage run` via command line: https://github.com/slushysnowman/demonstrate-coverage-xml-bug/tree/coverage-command-line
Code demonstrating behaviour when source defined for `coverage run` via .coveragerc: https://github.com/slushysnowman/demonstrate-coverage-xml-bug/tree/coverage-coveragerc

**Comment by mschmitzer** [comment]
We're experiencing the same behavior. In our case, it happens when passing source directories to `pytest` via the `--cov` option of the `pytest-cov` plugin. The plugin [seems to pass the paths through environment variables](https://github.com/pytest-dev/pytest-cov/blob/5182e5947ebfdd4fbd63fe456ee757c906d33387/src/pytest_cov/engine.py#L91).
The behavior is problematic for us because Gitlab is unable to use the resulting `coverage.xml` to display coverage information in merge request diff views. Since the `filename` values in the XML are not relative to the project root, this seems understandable.
Running `coverage` directly and passing the same source paths on the command line produces a usable `coverage.xml`.

**Comment by nedbat** [comment]
It's definitely strange that the two seemingly equivalent ways of specifying `source` would produce different results, and that should be fixed.

But I'm struggling to understand why either outcome is wrong.  To use a shortened form of the output, with the command line option, you get an XML file like:
```
<source>/System/Volumes/Data/root/src/bug1117/demonstrate-coverage-xml-bug</source>
    <class name="__init__.py" filename="scripts/__init__.py">
    <class name="sample_script.py" filename="scripts/sample_script.py">
```

With the .coveragerc option, you get:
```
<source>/System/Volumes/Data/root/src/bug1117/demonstrate-coverage-xml-bug/scripts</source>
    <class name="__init__.py" filename="__init__.py">
    <class name="sample_script.py" filename="sample_script.py">
```

The output is different, but in both, if you combine the `<source>` value with the `filename=` value, you get a valid file name, don't you?  Why can't the files be found?  Maybe I don't understand how CI systems are using the XML file?

**Comment by nedbat** [comment]
> It's definitely strange that the two seemingly equivalent ways of specifying source would produce different results, and that should be fixed.

I changed my mind: it's not strange at all.  The `coverage xml` command has different settings under the two scenarios.  If you change the "command line" scenario to use `coverage xml --source scripts`, then it works fine.  However you provide the `source` setting, you need to be sure all the coverage commands get it.  Putting it in the .coveragerc file is the easiest way to have consistent settings, but it will also work on the command line, if you use the same setting for all the commands.
