### ISSUE TITLE
Drop jQuery dependency and legacy browsers

### ISSUE THREAD

**Issue by septatrix** [coveragepy/coveragepy#1118]
It came to my attention that `coveragepy` requires jQuery. As most of the features jQuery provides are now supported by all modern (i.e. evergreen) browsers I think it would be nice to get rid of jQuery.

Furthermore does the way how this tools is shipped in debian only list jQuery as recommended leading to a degraded user experience (error messages when generating HTML reports).

I would be willing to perform this transformation if you agree with my points.

**Comment by nedbat** [comment]
I would be happy to use less (or no!) jQuery. Can you explain the browser support and/or fallback that would happen without jQuery?

**Comment by septatrix** [comment]
It would be easiest to drop support for old IE versions. Of you want to we could keep support for Internet Explorer 11 as it already support many modern javascript features. 

Preserving compatibility with even older browser should be possible but would make some things more complicated. As those are rarely used anymore I do not think it is worth the hassle and you could also drop some legacy workarounds.

**Comment by septatrix** [comment]
While working on this I noticed that in bcbdf41c6bb9d4ee30842bd14d45c7d48c2c6d01 you removed the `#n<number>` id on the line numbers. Therefore some of the highlighting functionality when using <kbd>j</kbd>/<kbd>k</kbd> does not seem to work anymore. If this was on purpose I would remove that dead code otherwise I would fix it if you wish.

**Comment by nedbat** [comment]
@septatrix thanks for pointing out that problem with `#n`.  I just fixed that in commit 9c47249d.

**Comment by ckielstra** [comment]
@septatrix How is progress going on? jQuery 1.11.1 pops up as a security vulnerability and less dependencies is always better.

**Comment by septatrix** [comment]
I have not spend any time on this recently as I have exams coming up

**Comment by nedbat** [comment]
@septatrix Do you have a work-in-progress?

**Comment by septatrix** [comment]
I have created a PR with everything I have so far and finished up the few remaining things. See #1248 for that.

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.1](https://pypi.org/project/coverage/6.1).
