### ISSUE TITLE
Can't install v5.5 with Python 3.10.0a5

### ISSUE THREAD

**Issue by cdce8p** [coveragepy/coveragepy#1129]
**Describe the bug**
I noticed that pip can't seem to find version `5.5` when used with Python `3.10.0a5`.
I get the following error:
```
(venv-310) ...:$ pip install coverage==5.5
ERROR: Could not find a version that satisfies the requirement coverage==5.5
ERROR: No matching distribution found for coverage==5.5
```
Python 3.9 works fine.

**To Reproduce**
```bash
python3.10 -m venv venv-310
source venv-310/bin/activate
python -m pip install -U pip setuptools wheel
pip install coverage==5.5
```

```bash
# pip list
Package    Version
---------- -------
pip        21.0.1
setuptools 54.0.0
wheel      0.36.2
```

**Expected behavior**
Installs without error

**Comment by The-Compiler** [comment]
Same here. When installing 5.4, the source archive gets installed:

```
Collecting coverage==5.4
  Downloading coverage-5.4.tar.gz (687 kB)
     |████████████████████████████████| 687 kB 2.7 MB/s 
Building wheels for collected packages: coverage
  Building wheel for coverage (setup.py) ... done
  Created wheel for coverage: filename=coverage-5.4-cp310-cp310-linux_x86_64.whl size=233289 sha256=0b1527531e3952eb26a206d636e08a954e5018870163f3b5b636fde47ea28abd
  Stored in directory: /tmp/pip-ephem-wheel-cache-xp39t3de/wheels/32/5b/33/ab6f1eef05acbd2d1f61c96c207ab3f39ed5b54f43a7e9cdd0
Successfully built coverage
Installing collected packages: coverage
Successfully installed coverage-5.4
```

but for 5.5, even though [a source archive is on PyPI](https://pypi.org/project/coverage/5.5/#files), somehow pip doesn't pick it up?

Trying with `pip install --verbose` reveals:

```
Found link https://files.pythonhosted.org/packages/29/83/9429871de6c7ec9ff113e12246af75aad4f0a7f31c66d0a499a0b7443a71/coverage-5.4.tar.gz#sha256=6d2e262e5e8da6fa56e774fb8e2643417351427604c2b177f8e8c5f75fc928ca (from https://pypi.org/simple/coverage/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <4), version: 5.4
```

for 5.4, but only shows the wheels for 5.5.

And sure enough, https://pypi.org/simple/coverage/ doesn't contain `coverage-5.5.tar.gz` at all? Weird.

As a workaround, doing `pip install https://files.pythonhosted.org/packages/38/df/d5e67851e83948def768d7fb1a0fd373665b20f56ff63ed220c6cd16cb11/coverage-5.5.tar.gz` with the full URL seems to work.

**Comment by nedbat** [comment]
Hmm, the simple URL also doesn't list `coverage-5.5-pp37-none-any.whl`.  The last two files on https://pypi.org/project/coverage/#files are missing from https://pypi.org/simple/coverage/

**Comment by nedbat** [comment]
I've uploaded Python 3.10 wheels to PyPI.  I hope that fixes things.  Interestingly, now the simple URL shows the two files it had been missing, and the three new wheels.

**Comment by oittaa** [comment]
I had the same issue with Python 3.7 on ARM64. So there was also something wrong with that, but it's fixed now. Thanks!

https://github.com/oittaa/avif-converter/pull/17
