### ISSUE TITLE
allow static context to be set via an environment variable

### ISSUE THREAD

**Issue by samuelcolvin** [coveragepy/coveragepy#1137]
**Is your feature request related to a problem? Please describe.**

It's currently not so easy to set static context, especially when us using pytest-cov. And also when test commands are defined in a `Makefile` where extra arguments can't be added.

**Describe the solution you'd like**

If would be great if there was a `CONTEXT` environment variable to match the `--context` command line argument.

**Describe alternatives you've considered**

No current way around this when using pytest-cov that I know of.

**Additional context**

coveragepy is great, thank you again.

In https://github.com/samuelcolvin/pydantic/pull/2580 I'm combining coverage from multiple python versions, OSs and setups, context would be really useful when viewing the report.

**Comment by nedbat** [comment]
Coverage.py configuration files will expand environment variables.  In your setup.cfg, add this:
```
[coverage.run]
context = ${CONTEXT}
```
and it will do what you want.

**Comment by samuelcolvin** [comment]
Amazing thank you, will try it now.

**Comment by samuelcolvin** [comment]
That works really well.

Closing this issue.
