### ISSUE TITLE
coverage debug sys. Result: tracer: -none-

### ISSUE THREAD

**Issue by guettli** [coveragepy/coveragepy#1157]
**Describe the bug**

FAQ: https://coverage.readthedocs.io/en/coverage-5.5/faq.html#q-coverage-py-is-much-slower-than-i-remember-what-s-going-on

The output of `coverage debug sys` should be "tracer: CTracer or tracer: PyTracer"

But my output is different:

```
...
                         tracer: -none-
                        CTracer: available
...
```

I guess the FAQ entry needs an update.

**Comment by nedbat** [comment]
Oops, yes!

**Comment by nedbat** [comment]
Thanks, this is updated in 43e1c64c
