### ISSUE TITLE
Relative paths not working from command line.

### ISSUE THREAD

**Issue by ppiotrow** [coveragepy/coveragepy#1159]
**Describe the bug**
Relative paths supported in SDK but not in the command line

**To Reproduce**
I've prepared minimal example to reproduce the bug. It produces [cov_sdk.xml](https://github.com/ppiotrow/coverage-bug/blob/main/cov_sdk.xml#L6) relative paths report while using Python API. And absolute paths using command line [coverage.xml](https://github.com/ppiotrow/coverage-bug/blob/main/coverage.xml#L6) even if the [relative_files](https://github.com/ppiotrow/coverage-bug/blob/main/.coveragerc#L2) is specified. 
`Python 3.8.2, coverage 5.5`

**Expected behavior**
The reports should be the same.

**Comment by nedbat** [comment]
Thanks for the clear issue report.  The problem is that `--source` only affects the run command, and not subsequent reporting commands.  If you put `source=` into the .coveragerc file, then the XML report correctly uses relative filenames.

I've added this to the docs in commit 50a0e37a.

**Comment by ppiotrow** [comment]
Confirmed, thanks!

**Comment by nedbat** [comment]
To be fair, there are probably things we can do to make this less error-prone:

- Write the `--source` setting into the data file so that reporting can use it?
- Make it an error to use `relative_files` without `source`?
