### ISSUE TITLE
coverage regression with Python 3.6 ?

### ISSUE THREAD

**Issue by rodfersou** [coveragepy/coveragepy#1162]
Can't get coverage with c extension for Python 3.6, using pipenv

```bash
$ pipenv run coverage --version
Coverage.py, version 5.5 without C extension
Full documentation is at https://coverage.readthedocs.io
```

**Comment by nedbat** [comment]
You'll need to tell us more about how you installed coverage.

**Comment by nedbat** [comment]
Feel free to re-open this when you have more information.
