### ISSUE TITLE
Show "files skipped due to complete coverage" warning in HTML report

### ISSUE THREAD

**Issue by lufte** [coveragepy/coveragepy#1163]
I ran into this issue where one of the modules I was testing was disappearing from my HTML coverage report when I wrote tests for it. I couldn't figure this out until I ran the plain text summary which had the following warning: "43 files skipped due to complete coverage". 

I didn't know this feature existed or that it was activated by default. It would help if that warning appeared in all reporting formats.

**Comment by nedbat** [comment]
This is implemented in a99b27f7. 

BTW: this setting is not the default.  You probably have `[report] skip_covered = true` in your .coveragerc file.

**Comment by lufte** [comment]
Thanks for the fix. I checked our repository and we don't have a .coveragerc file anywhere. We are running `Coverage.py, version 5.5 with C extension`.

**Comment by nedbat** [comment]
Hmm, how about a setup.cfg or tox.ini or pyproject.toml?

**Comment by lufte** [comment]
Ah, setup.cfg was the culprit. Sorry for the noise!

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.0](https://pypi.org/project/coverage/6.0).
