### ISSUE TITLE
Remove leading underscore in coverage html

### ISSUE THREAD

**Issue by Luna-Klatzer** [coveragepy/coveragepy#1167]
**Is your feature request related to a problem? Please describe.**
I am currently setting up an automatic Github actions coverage-report system, where I want to automatically create a GitHub page where I can see my coverage report. Doing that though, I encountered an issue with the `coverage html` command where the result HTML-files have a leading underscore making them *private* in the eyes of GitHub and so not visible. 

**Describe the solution you'd like**
Remove the underscore if possible, since I don't expect it to have big importance or requirement to be that way

**Describe alternatives you've considered**
Contacting GitHub / opening an issue, but that would require a lot more change, which is why I am requesting here to possibly change it

**Comment by nedbat** [comment]
Hi, this sounds interesting!  I publish my HTML reports to a GitHub repo too (https://github.com/nedbat/coverage-reports/commits/main), though it isn't served with GitHub Pages.

My file names don't start with underscores, I'll have to refresh my memory about why that might be.

**Comment by nedbat** [comment]
Can you show a sample of your HTML report? Does it have absolute pathnames to your files?

**Comment by Luna-Klatzer** [comment]
Yes, it starts with the absolute pathnames of the files. Here an image of the results of the `coverage html` command used in the GitHub actions job.

![image](https://user-images.githubusercontent.com/61756091/120384153-14cbb480-c326-11eb-80d3-3850e8ca6ff6.png)

**Comment by Luna-Klatzer** [comment]
I also found that underscore when generating the files on Windows, so I thought it was standard

**Comment by nedbat** [comment]
This is fixed in 4d05ddee.

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.0b1](https://pypi.org/project/coverage/6.0b1).

**Comment by Luna-Klatzer** [comment]
> 
> 
> This is now released as part of [coverage 6.0b1](https://pypi.org/project/coverage/6.0b1).

Thank you very much ^^

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.0](https://pypi.org/project/coverage/6.0).
