### ISSUE TITLE
"continue" is wrongly marked as unexecuted

### ISSUE THREAD

**Issue by NJUocean** [coveragepy/coveragepy#1171]
**Describe the bug**
"continue" is wrongly marked as unexecuted

**To Reproduce**
```
def foo():
    for i in range(2):
        a=i
        if a>0:
            b=a*2
            if b<0:
                print("executed-0")        
            continue
        if a==0:
            continue
foo()
```
![image](https://user-images.githubusercontent.com/44373938/120493032-2d52d200-c3ed-11eb-925b-ebd2d10c9146.png)

**Expected behavior**
line 8 continue is executed, however coverage.py reports it unexecuted :(

**Comment by nedbat** [comment]
This was a long-standing issue with CPython, and a duplicate of #198.  It's now fixed in CPython 3.10.
