### ISSUE TITLE
Live code was marked as unexecuted

### ISSUE THREAD

**Issue by NJUocean** [coveragepy/coveragepy#1173]
**Describe the bug**
Live code （e.g. line 698 699）was marked as unexecuted

[601.zip](https://github.com/nedbat/coveragepy/files/6592557/601.zip)

![image](https://user-images.githubusercontent.com/44373938/120667856-79227b80-c4c0-11eb-991e-a676f788c52c.png)
![image](https://user-images.githubusercontent.com/44373938/120667448-15984e00-c4c0-11eb-9b4d-4f90583bdff3.png)
![image](https://user-images.githubusercontent.com/44373938/120667540-2f399580-c4c0-11eb-919b-55a184210f93.png)

**Comment by nedbat** [comment]
Hi, why are you calling `sys.settrace` in your test?  That will interfere with coverage.py's work.

**Comment by NJUocean** [comment]
> Hi, why are you calling `sys.settrace` in your test? That will interfere with coverage.py's work.

Hi, this is just a test that comes with python

**Comment by nedbat** [comment]
OK.  There's nothing coverage.py can do about this.  If you set your own trace function, then coverage.py's trace function is no longer running, and it won't know those lines executed.  

I'll close this issue now, but I am curious whether you really need this to work or not.
