### ISSUE TITLE
Incorrect branch coverage when running two async iterators

### ISSUE THREAD

**Issue by sfstpala** [coveragepy/coveragepy#1176]
**Describe the bug**
When I run two (or more) async iterators in `async for` loops, the second loop will have incorrect branch coverage.

**To Reproduce**
Here's an example:

    import asyncio
    
    class AsyncIter:
    
        def __init__(self, items):
            self.items = items
    
        async def __aiter__(self):
            for i in self.items:
                yield i
    
    async def test():
        async for i in AsyncIter([1, 2, 3]):
            pass
        async for i in AsyncIter([1, 2, 3]):
            pass
    
    asyncio.run(test())

And the result:

<img width="653" alt="Screenshot 2021-06-15 at 05 20 21" src="https://user-images.githubusercontent.com/458321/121987761-64d05f80-cd99-11eb-8aeb-3cefdad23746.png">

I'm running Coverage 5.5 on Python 3.9 ([debug sys output here](https://gist.github.com/sfstpala/f7aba3a3d3679315f3ad8e213d68abc8))

**Expected behavior**
Same as the non-async version:

<img width="545" alt="Screenshot 2021-06-15 at 05 22 14" src="https://user-images.githubusercontent.com/458321/121987891-a7923780-cd99-11eb-9879-d1e044b60078.png">

**Comment by sfstpala** [comment]
I get the same issue when I just put the `async for` in another loop like this:

    async def test():
        for i in [1]:
            async for i in AsyncIter([1, 2, 3]):
                pass

**Comment by sfstpala** [comment]
I also noticed that this works fine in Python 3.8, but not in Python 3.9 and 3.10.

**Comment by nedbat** [comment]
See [this comment on #1158](https://github.com/nedbat/coveragepy/issues/1158#issuecomment-866738102).

**Comment by nedbat** [comment]
I think this is a combination of two CPython bugs:
[async-for loops are traced incorrectly in Python 3.10](https://bugs.python.org/issue44622) and [Python 3.9 traces async for/else incorrectly](https://bugs.python.org/issue44621).
