### ISSUE TITLE
Coverage doesn't report code coverage for PEP 578 runtime audit hooks

### ISSUE THREAD

**Issue by kernelmethod** [coveragepy/coveragepy#1181]
**Describe the bug**
Coverage doesn't report results for functions that are executed as Python runtime audit hooks ([PEP 578](https://www.python.org/dev/peps/pep-0578/)).

**To Reproduce**
- Python version: 3.9 (although I'm experiencing the same issue for 3.8 in my CI pipeline)
- Packages: I'm only using Coverage v5.5:

```
$ pip freeze
coverage==5.5
```

Here's a minimal example to reproduce the issue:

```
$ tree
.
├── example
│   └── __init__.py
└── test
    ├── __init__.py
    └── test_hook.py

2 directories, 3 files
```

```python3
# in example/__init__.py
def my_hook(event: str, args: any):
    if event == "my_event":
        print(f"Hook executed! {event=}, {args=}")
```

```python3
# in test/test_hook.py
import sys, unittest
from example import my_hook

class RuntimeAuditHookTestCase(unittest.TestCase):
    def test_audit_hook(self):
        sys.addaudithook(my_hook)
        sys.audit("my_event")
```

Tests and code coverage report:

```
$ coverage run --source example -m unittest -v
test_audit_hook (test.test_hook.RuntimeAuditHookTestCase) ... Hook executed! event='my_event', args=()
ok

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
$ coverage report -m
Name                  Stmts   Miss  Cover   Missing
---------------------------------------------------
example/__init__.py       3      2    33%   2-3
---------------------------------------------------
TOTAL                     3      2    33%
```

The body of `my_hook` is not reported as part of the code coverage results, event though it was clearly executed.

**Expected behavior**
Lines 2-3 of `example/__init__.py` should report as being covered. E.g., if we changed the test to

```python
    def test_audit_hook(self):
        my_hook("my_event", ())
```

then we would get the following output:

```
$ coverage run --source example -m unittest -v
test_audit_hook (test.test_hook.RuntimeAuditHookTestCase) ... Hook executed! event='my_event', args=()
ok

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
$ coverage report -m
Name                  Stmts   Miss  Cover   Missing
---------------------------------------------------
example/__init__.py       3      0   100%
---------------------------------------------------
TOTAL                     3      0   100%
```

which is the same as I would expect for the case where it's executed as a runtime audit hook.

**Comment by nedbat** [comment]
The [docs for setaudithook](https://docs.python.org/3/library/sys.html#sys.addaudithook) say:

> **CPython implementation detail:** When tracing is enabled (see settrace()), Python hooks are only traced if the callable has a `__cantrace__` member that is set to a true value. Otherwise, trace functions will skip the hook.

If you add this line after the definition, it will be measured:
```
my_hook.__cantrace__ = True
```

**Comment by kernelmethod** [comment]
My bad, I completely missed that. Thanks for pointing that out.

**Comment by nedbat** [comment]
No problem, I learned something myself :)
