### ISSUE TITLE
Richer static context information

### ISSUE THREAD

**Issue by james-smith-za** [coveragepy/coveragepy#1190]
I'd like to be able to use something slightly more interesting as a static context for the coverage run in the `.coveragerc` file.
For instance, I currently get what I want by executing
```
$ coverage run --context=$(git describe --tags --dirty)
```
This tells me in the report (almost) exactly what code was tested, down to whether the commit was dirty or not.

This strategy currently works ok for me, but I'd like to be able to use something that I can check into version control so that my collaborators can use it as well. The `.coveragerc` file seems ideal, but only supports static strings or environment variables.

If I could have the following in my `.coveragerc` file do the same as it does when I put it on the command line, that would be ideal:
```
[run]
context=$(git describe --tags --dirty)
```

I realise that the functionality I'm after is actually added by `bash` parsing the command before `coverage` even sees it, but I feel as though something quite similar might be achievable through the config file, even if the syntax is somewhat different.

I can't promise that I'll have time, but would you consider a pull-request with such functionality?

**Comment by nedbat** [comment]
I have to admit, I'm reluctant to add something like subprocess execution to the coverage.py config file.  I would recommend that instead of telling people to run "coverage", tell them to run "make test" or "tox", or even "run_the_tests.sh", where you have more powerful tools available.  I don't know how that sits with you though.

**Comment by james-smith-za** [comment]
That's a fair point, and I understand the reservation. Of your suggestions I think the Makefile is probably the best, though I'd prefer not to have to add yet another file to my repo to maintain.

I'm going to play around a bit and see if I can get any useful git information without executing subprocesses. Just off the top of my head, something like:
```python
with open('.git/refs/heads/master', 'r') as git_hash:
        print(git_hash.readline()[:8])
```
Obviously that is somewhat over-simplistic but just to illustrate.

The other thing is that we'd need to agree on some kind of unique environment variable that the config parser will understand. Something like `$GIT_DESCRIPTION` maybe.

If you'd be willing to consider some feature like this, I can spend some time trying to implement it. If not, I'll close the issue and revert to using a Makefile as you suggested.

**Comment by nedbat** [comment]
Maybe I'm missing something.  If you do this in a Makefile, then we don't need any change to coverage.py. Your suggested line will just work, won't it?:
```
# The Makefile
coverage:
        coverage run --context=$$(git describe --tags --dirty)
```

**Comment by james-smith-za** [comment]
Using a Makefile has the advantage of simplicity, as you point out.

My motivations for getting the functionality into coverage.py are two-fold.
One is quite minor: yet another boilerplate file to maintain if I want to have a similar configuration across projects.
The other is that if you are using a plugin such as `pytest-cov`, there's not a facility (as far as I am aware) to pass command-line arguments to coverage.py. The config files are parsed just fine though, so that would be the best of both worlds.

Neither of these is a deal-breaker, it would just make my life a bit better. I'm willing to implement the feature myself and raise a PR, but if it won't be considered for inclusion then that's also fine, I will find a workaround that will suit me.

**Comment by nedbat** [comment]
You can read environment variables in the coverage config file, so your next option is:
```
# The Makefile
coverage:
        STATIC_CONTEXT=$$(git describe --tags --dirty) pytest --cov --whatever
```
with:
```
# .coveragerc
[run]
    context = ${STATIC_CONTEXT}
```

**Comment by james-smith-za** [comment]
That... is actually a pretty good idea. It will work for my purposes.

Thanks!
