### ISSUE TITLE
Github action with docker-compose 

### ISSUE THREAD

**Issue by bandirom** [coveragepy/coveragepy#1191]
**Describe the bug**
When I set github action for upload coverage data to codecov in I've got an errors when run coverage run manage.py test 
Project [https://github.com/bandirom/DjangoTemplateWithDocker](https://github.com/bandirom/DjangoTemplateWithDocker)
**django==3.1.7
coverage==5.5**

`docker-compose -f docker-compose.yml -f debug.yml run web coverage run manage.py test
`

----------------------------------------------------------------------
Ran 13 tests in 3.759s

OK
Destroying test database for alias 'default'...
Traceback (most recent call last):
  File "/usr/local/bin/coverage", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/coverage/cmdline.py", line 871, in main
    status = CoverageScript().command_line(argv)
  File "/usr/local/lib/python3.9/site-packages/coverage/cmdline.py", line 588, in command_line
    return self.do_run(options, args)
  File "/usr/local/lib/python3.9/site-packages/coverage/cmdline.py", line 753, in do_run
    self.coverage.save()
  File "/usr/local/lib/python3.9/site-packages/coverage/control.py", line 659, in save
    data = self.get_data()
  File "/usr/local/lib/python3.9/site-packages/coverage/control.py", line 727, in get_data
    if self._collector and self._collector.flush_data():
  File "/usr/local/lib/python3.9/site-packages/coverage/collector.py", line 442, in flush_data
    self.covdata.add_lines(self.mapped_file_dict(self.data))
  File "/usr/local/lib/python3.9/site-packages/coverage/sqldata.py", line 438, in add_lines
    self._choose_lines_or_arcs(lines=True)
  File "/usr/local/lib/python3.9/site-packages/coverage/sqldata.py", line 495, in _choose_lines_or_arcs
    with self._connect() as con:
  File "/usr/local/lib/python3.9/site-packages/coverage/sqldata.py", line 300, in _connect
    self._create_db()
  File "/usr/local/lib/python3.9/site-packages/coverage/sqldata.py", line 249, in _create_db
    with db:
  File "/usr/local/lib/python3.9/site-packages/coverage/sqldata.py", line 1037, in __enter__
    self._connect()
  File "/usr/local/lib/python3.9/site-packages/coverage/sqldata.py", line 1019, in _connect
    self.con = sqlite3.connect(filename, check_same_thread=False)
sqlite3.OperationalError: unable to open database file

When I tryed to run:
`docker-compose -f docker-compose.yml -f debug.yml run web python manage.py test`
this command **pass** success

When I changed version to **coverage==4.5.4** it fix the issues
For testing I use db container (postgres) why I've got a sqlite Error?

**To Reproduce**
List of failed jobs https://github.com/bandirom/DjangoTemplateWithDocker/actions/workflows/codecov.yml
command to reproduce the b

How can we reproduce the problem?  Please *be specific*. Don't just link to a failing CI job. Answer the questions below:
1. What version of Python are you using?
Python3.9.1-alpine image
2. What version of coverage.py are you using? The output of `coverage debug sys` is helpful.
coverage==5.5
3. What code are you running?  Give us a specific commit of a specific repo that we can check out.
4. 
```
name: Coverage

on:
  push:
    branches: [ master ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Run coverage.py"
        run: |
          docker-compose build
          docker-compose -f docker-compose.yml -f debug.yml run web python manage.py test --no-input
#          docker-compose exec -T web coverage xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./web/
```
1. What commands did you run?
docker-compose -f docker-compose.yml -f debug.yml run web python manage.py test --no-input

**Comment by nedbat** [comment]
Coverage.py uses SQLite to record its data.  I don't know why this would be happening.  Is it reproducible?

**Comment by bandirom** [comment]
> Coverage.py uses SQLite to record its data. I don't know why this would be happening. Is it reproducible?

I can try to reproduce again

**Comment by urtubia** [comment]
Hello!
I was running into this same issue as well and the problem was that inside `docker-compose` the user running `coverage` did not have permissions to write to the `.coverage` file on the working directory.
I solved it by setting the environment variable `COVERAGE_FILE` to `/tmp/.coverage`, to ensure the user running the coverage command will be able to write the data file.

**Comment by nedbat** [comment]
@bandirom I'll guess that the permissions were the problem.  If they weren't, and you get more information, please re-open the issue. Thanks!
