### ISSUE TITLE
Coverage randomly fails with `INTERNALERROR> coverage.misc.CoverageException: Can't combine line data with arc data`

### ISSUE THREAD

**Issue by jacek-jablonski** [coveragepy/coveragepy#1194]
**Describe the bug**
Running pytest with pytest-cov plugin or coverage standalone randomly results in error:
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/jacek/temp/coverage-error/.venv/lib/python3.8/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/jacek/temp/coverage-error/.venv/lib/python3.8/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/jacek/temp/coverage-error/.venv/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/jacek/temp/coverage-error/.venv/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/jacek/temp/coverage-error/.venv/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Users/jacek/temp/coverage-error/.venv/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/Users/jacek/temp/coverage-error/.venv/lib/python3.8/site-packages/pytest_cov/plugin.py", line 271, in pytest_runtestloop
INTERNALERROR>     self.cov_controller.finish()
INTERNALERROR>   File "/Users/jacek/temp/coverage-error/.venv/lib/python3.8/site-packages/pytest_cov/engine.py", line 44, in ensure_topdir_wrapper
INTERNALERROR>     return meth(self, *args, **kwargs)
INTERNALERROR>   File "/Users/jacek/temp/coverage-error/.venv/lib/python3.8/site-packages/pytest_cov/engine.py", line 230, in finish
INTERNALERROR>     self.cov.stop()
INTERNALERROR>   File "/Users/jacek/temp/coverage-error/.venv/lib/python3.8/site-packages/coverage/control.py", line 701, in combine
INTERNALERROR>     combine_parallel_data(
INTERNALERROR>   File "/Users/jacek/temp/coverage-error/.venv/lib/python3.8/site-packages/coverage/data.py", line 117, in combine_parallel_data
INTERNALERROR>     data.update(new_data, aliases=aliases)
INTERNALERROR>   File "/Users/jacek/temp/coverage-error/.venv/lib/python3.8/site-packages/coverage/sqldata.py", line 574, in update
INTERNALERROR>     raise CoverageException("Can't combine line data with arc data")
INTERNALERROR> coverage.misc.CoverageException: Can't combine line data with arc data
``` 

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't just link to a failing CI job. Answer the questions below:
1. What version of Python are you using?
Python 3.8
1. What version of coverage.py are you using? The output of `coverage debug sys` is helpful.
coverage 5.5
1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.
Provided in a minimal example
1. What code are you running?  Give us a specific commit of a specific repo that we can check out.
Provided in a minimal example
1. What commands did you run?
`poetry run pytest -s --cov=poetry_tools/ --cov-report=xml --cov-report=term`

**Expected behavior**
coverage runs without any errors.

**Additional context**
Here is a minimal example reproducing this error. It pops up randomly, so please try several times. https://github.com/jacek-jablonski/coverage-test-error

**Comment by nedbat** [comment]
Can you show how you ran coverage standalone?  When I remove the `[tool.pytest.ini_options]` section from pyproject.toml, and then run `coverage run -m pytest`, it never fails.

**Comment by jacek-jablonski** [comment]
I have run it just like you but without removing `[tool.pytest.ini_options]`.
I have also noticed that setting `branch = false` also helps with the problem.

**Comment by nedbat** [comment]
If you don't remove the `--cov=` pytest option from the toml file, then you are still running it with pytest-cov.  I think this is a pytest-cov bug.

**Comment by sodul** [comment]
We are experiencing the very same bug with green. We have not updated our dependencies recently so this is very odd.

**Comment by nedbat** [comment]
@sodul what is "green"? Can you provide a reproducible scenario?

**Comment by sodul** [comment]
Green is a test runner for python: https://github.com/CleanCut/green
I prefer it over pytest to run unittests for various reasons.

I ran into the issue and since pytest started running into the error just a few days ago I suspect the problem is outside of pytest and green. It is just too close to each other to be just random.

I do not have a reproducible scenario just yet (our code is private). I'll update you when I get more details. All our test targets are impacted which is definitely abnormal.

**Comment by sodul** [comment]
Update: cleaning up our test report output directory seems to fix the problem. I'll try to see which files are clashing so I can report it here.

Apparently it was caused by a single stale .coveragerc file. I cannot seem to reproduce now that the file has been cleaned up.
