### ISSUE TITLE
coverage html: This command should print a line

### ISSUE THREAD

**Issue by guettli** [coveragepy/coveragepy#1195]
**Is your feature request related to a problem? Please describe.**

If you use `coverage` for the first time in your life, than I think it would be very helpful, if the command `coverage html` does output a line like:

 > See output in htmlcov/index.html

If you agree to this proposal, then I could create a pull-request.

What do you think?

**Comment by nedbat** [comment]
I think this is a good idea.  I may do it soon.

**Comment by nedbat** [comment]
I did it soon :)  This is implemented in 4ef91bd9

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.0](https://pypi.org/project/coverage/6.0).
