### ISSUE TITLE
Not really an issue, but not sure where to place it -  6.0 release timing question

### ISSUE THREAD

**Issue by DaniilAnichin** [coveragepy/coveragepy#1199]
**Is your feature request related to a problem? Please describe.**
We have both coverage and safety check set up in CI pipeline. It seems like several days ago safety flagged any coverage version prior to 6.0b1 as unsafe due to update in hashing algorithm mentioned here (https://github.com/nedbat/coveragepy/issues/1189) - seems like safety assumes having md5 in older versions is a problem.

**Describe the solution you'd like**
Surely, there is option of pinning coverage to 6.0b1 in requirements or either skipping it in some way; But i'd like to understand, how far we are from having stable 6 release? I understand from prior issues it will has breaking changes, so in no way will ask to speed up such release.

**Describe alternatives you've considered**
I understand that ci tools actually must not test each other; 

**Additional context**
I think no other context can be applied right now, but will be happy to answer questions, if any.

**Comment by nedbat** [comment]
Safety DB says they are removing the false alarm about coverage 5.5: https://github.com/pyupio/safety-db/issues/2335.  I think this means this won't be a concern any more.

But to answer your question, 6.0 will be released within a week.
