### ISSUE TITLE
Unable to install coverage[toml(i)] for 6.0b1

### ISSUE THREAD

**Issue by staticdev** [coveragepy/coveragepy#1202]
**Describe the bug**
I see on change-log that there was a change on the lib to tomli and now I can't install the latest version using TOML extra. On 6.0b1 docs, I see the [installation instructions](https://coverage.readthedocs.io/en/6.0b1/config.html) still points to installing the extra:
`pip install coverage[toml]`

I also tried with `tomli` as I saw https://github.com/nedbat/coveragepy/commit/80bfea74c10dec30a0fa64e1379b80c897b060a9 from @graingert and @hukkin.

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't just link to a failing CI job. Answer the questions below:
1. What version of Python are you using? 3.9.6
1. What version of coverage.py are you using? 6.0b1
1. What versions of what packages do you have installed? N/A
1. What code are you running?  N/A
1. What commands did you run?

```
% pip install coverage[toml]==6.0b1
no matches found: coverage[toml]==6.0b1
 % pip install coverage[tomli]==6.0b1
no matches found: coverage[tomli]==6.0b1
```

**Expected behavior**
Candidate installation found.

**Additional context**
I am trying to upgrade to 6.0b1 to fix hash vulnerability on previous versions.

**Comment by hukkin** [comment]
I'm unable to reproduce: `pip install coverage[toml]==6.0b1` works perfectly for me.

**Comment by graingert** [comment]
@staticdev what's your `% pip --version`?

**Comment by nedbat** [comment]
The name of the extra is still "toml". It means, "I want TOML support".  The library that gets installed is different, but the install command is the same.

You probably need to quote the command.  I know this is true with zsh:
```
pip install 'coverage[toml]==6.0b1'
```

**Comment by graingert** [comment]
Ah
> no matches found

That's definitely zsh looking at the `[`

**Comment by staticdev** [comment]
@nedbat and @graingert thanks a lot.. you are completely right. zsh problem, quotes solved it =)
