### ISSUE TITLE
Settings issue running coverage against a single file in a Django app

### ISSUE THREAD

**Issue by jpsingleton** [coveragepy/coveragepy#1203]
**Describe the bug**

Recently upgraded to coverage 6.0b1 from 5.5 and having some issues with running it against a single file in a Django app (Python 3.9.4 on Linux).

**To Reproduce**

`coverage erase && coverage run --source=your.source.module manage.py test --parallel 1 --keepdb your.test.module && coverage report`

This results in the following error since upgrading to the beta:
`django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.`

This suggests that manage isn't being run properly or something isn't being passed through.

**Expected behaviour**
Runs the tests and outputs report of coverage for the file under test.

**Additional context**
This works fine without the `--source=your.source.module` parameter so that may be where things are going wrong. This was working on v5.5.

**Comment by nedbat** [comment]
Thanks for the bug report. Do you have a repo that demonstrates the problem fully?

**Comment by jpsingleton** [comment]
Thanks. Not that I can share, unfortunately. I'll try and put a sample together if I can find some time.

**Comment by asedeno** [comment]
https://github.com/asedeno/django-coverage6-breakage-demo has a barebones example.

**Comment by nedbat** [comment]
@asedeno Thanks, that was very helpful.  The error is happening because coverage.py imports the source module before starting your program, to find where it is.  In commit 79753a14 I've suppressed exceptions that happen during that early import.  Please try it on your real programs, and let me know if it works.

**Comment by asedeno** [comment]
Works to fix this issue in the project where I encountered it. Thanks! 🎉

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.2](https://pypi.org/project/coverage/6.2).

**Comment by Crystallinejackson38** [comment]
> [@asedeno](https://github.com/asedeno) Thanks, that was very helpful. The error is happening because coverage.py imports the source module before starting your program, to find where it is. In commit [79753a1](https://github.com/nedbat/coveragepy/commit/79753a1476a407b4fe1fad69081395c497d53d21) I've suppressed exceptions that happen during that early import. Please try it on your real programs, and let me know if it works.





https://pathname577.github.io/balustrade8/
