### ISSUE TITLE
Coverage regressions for "with" statement on CPython 3.10

### ISSUE THREAD

**Issue by skirpichev** [coveragepy/coveragepy#1211]
[Per request](https://github.com/nedbat/coveragepy/issues/1205#issuecomment-897278850) I've opened a separate issue.

There are regressions in the [diofant/integrals/rde.py](https://app.codecov.io/gh/diofant/diofant/compare/1162/tree/diofant/integrals/rde.py) on lines with the "with" statement (e.g. L309 and L546).  On the CPython 3.9 & the latest coveragepy release - these lines are marked as covered.

To reproduce issue, [install the diofant](https://diofant.readthedocs.io/en/latest/install.html#from-sources) e.g. with `pip install -e .[develop]` in the git tree, install pytest and coveragepy from git (I use coveragepy at 57a691f) and run:
```
pytest -n0 -m 'not slow and not xfail and not regression' --cov diofant \
    diofant/tests/integrals/test_rde.py diofant/tests/integrals/test_risch.py
coverage html
```
Here are two examples (there are four such "with" statements).  The function bound_degree():
![1](https://user-images.githubusercontent.com/2155800/129137467-a0b6fba7-bce8-4c89-91df-bc28a9b1b6fd.png)

The function cancel_primitive():
![2](https://user-images.githubusercontent.com/2155800/129137486-8c046b25-0d73-4138-9fac-a5195ad5ef30.png)

The first one you may view as a new "feature" of the coveragepy.  But not too helpful, as it looks for me, since L320 and L342 (i.e. ValueError exceptions) were marked as uncovered before.  Maybe it's a documentation issue: how works the branch coverage here - seems unclear for me (wrt "if" statements, for example).  For instance, why there are (and on L546) 3 branches:
```
<line number="309" hits="1" branch="true" condition-coverage="66% (2/3)" missing-branches="exit"/>
<line number="546" hits="1" branch="true" condition-coverage="66% (2/3)" missing-branches="exit"/>
```

But the second example looks definitely wrong.  The NotImplementedError on L552 is ignored by the coveragepy configuration.  I think, then this "branch" of the "with" statement on L546 - should be ignored too (as it happens for if/elif/else statements).

**Comment by nedbat** [comment]
Thanks.  This was coverage.py being over-zealous about warning about missed branches.  I've fixed it in commit f6d3e88b.
