### ISSUE TITLE
For loop inside with statement, using Coverage v5.5 and CPython v3.10.0rc1

### ISSUE THREAD

**Issue by johnbywater** [coveragepy/coveragepy#1213]
I'm seeing missing branch coverage reported against for loops inside with statements in the [Python eventsourcing library](https://github.com/johnbywater/eventsourcing).

Coverage version is 5.5. This doesn't happen with CPython versions 3.7, 3.8, or 3.9. I just discovered it when trying out CPython 3.10.0.rc1 for the first time with this library. That is, this seems to be something that's new in CPython which is causing this to show up.

The actual code where this showed up is [here](https://github.com/johnbywater/eventsourcing/blob/main/eventsourcing/sqlite.py#L190) and [here](https://github.com/johnbywater/eventsourcing/blob/main/eventsourcing/sqlite.py#L242) and [here](https://github.com/johnbywater/eventsourcing/blob/main/eventsourcing/sqlite.py#L293) and [here](https://github.com/johnbywater/eventsourcing/blob/main/eventsourcing/postgres.py#L252) and [here](https://github.com/johnbywater/eventsourcing/blob/main/eventsourcing/postgres.py#L378) and [here](https://github.com/johnbywater/eventsourcing/blob/main/eventsourcing/postgres.py#L453). There are various other "for" loops and various other "with" statements, but these six places are the only places a for loop is used within a with statement and without any further statements in the block. I didn't experience any other issues.

I boiled things down to the following code, which is reported in PyCharm as "didn't jump to exit" (screenshots below) with missing branch coverage on the line beginning `for ...`:

```
from contextlib import nullcontext

with nullcontext():
    for _ in [1]:
        pass
```

Curiously enough, full branch coverage is reported when the extra statement `a = 1` is added after the for loop:

```
with nullcontext():
    for _ in [1]:
        pass
    a = 1
```

This happens both when running coverage from a command line terminal, and when running tests with coverage in PyCharm.

Screenshots of the above in PyCharm:

<img width="683" alt="Screenshot 2021-08-12 at 21 19 50" src="https://user-images.githubusercontent.com/3607503/129264234-c25e837a-6ef2-4048-8341-d6ba5c36c2ff.png">

Code above in a Python module in PyCharm showing message for missing branch coverage:

<img width="653" alt="Screenshot 2021-08-12 at 21 20 11" src="https://user-images.githubusercontent.com/3607503/129264262-8bc248ec-2603-42f0-a599-8700d2b62eee.png">

Not entirely sure if this is a bug, or if there's something I don't fully understand...

**Comment by nedbat** [comment]
I believe this is fixed by running a newer coverage (unreleased):  `pip install coverage==6.0b1`

**Comment by johnbywater** [comment]
Oh great! Thank you 💯 very much! :)
