### ISSUE TITLE
Relative paths cause Coverage.analysis() to say that all lines are un-executed

### ISSUE THREAD

**Issue by adamalton** [coveragepy/coveragepy#1224]
**Describe the bug**
When the `relative_paths` options is used for running coverage, the data file correctly contains relative paths, but if you then try to use `Coverage("/somewhere/.coverage").analysis("/somewhere/file.py")` it will only work if Python's working directory is the `/somewhere/` directory, otherwise it will tell you that none of the lines have been executed.

**To Reproduce**

Using this config, saved as "myconfig":

```
[run]
relative_files = True

[paths]
source =
	/absolute/path/to/project/
	# You would probably have other paths here, such as the path to the files when they're inside a
	# Docker container, hence your reason for using relative paths, but those other paths aren't
	# required to reproduce this issue.
```

Run:

```
cd /absolute/path/to/project/
coverage run --rcfile=myconfig my_tests.py
```

Check the data file to ensure that the saved file paths in the sqlite file are relative:

```
sqlite .coverage
> SELECT * FROM file where path='relative/path.py';
118|relative/path.py
```

Running `coverage report --rcfile=myconfig` works perfectly. (But note that it only works with the config, because without the `[paths]` part of the config, the relative paths in the sqlite DB don't get mapped back correctly, even though the paths in the sqlite DB are relative to the current directory.)

Now try to use the `Coverage` class to get the analysis for that file:

```python
from coverage import Coverage
cov = Coverage(
    data_file="/absolute/path/to/project/.coverage",
    config_file="/absolute/path/to/project/myconfig"
)
cov.load()
print(cov.analysis("/absolute/path/to/project/relative/path.py"))
```

This will work *only* if it's executed with `/absolute/path/to/project/` as Python's current working directory. If you try to execute that Python code from anywhere else (e.g. inside an editor plugin!) then it won't work, but will instead report every line in the file as being not executed.

If you're running your tests inside a Docker container (with the directory that contains your python files being linked with a Docker volume) then when the tests are run, the python files are on a different path to when they're in your code editor. So I was hoping that some combination of the `relative_files` flag and the `[paths] sources` configuration would allow me to run my tests inside Docker and then have my editor pick up the `.coverage` file and show me the coverage in the editor. But after many hours of trying every possible combination, it seems that there isn't a way to have:

* Files stored at `/path/A/`,
* those files executed with coverage when they're located in `/path/B/`,
* `Coverage(".coverage").analysis(file_path)` run when Python's working directory is `/path/C/` when the files are at `/path/A/`,
* and the result be correct.

Python version: 3.8.7  
Coverage version: 5.5

If there's a workaround for this that I haven't found then I'd love to know what it is, but if not then it seems like a bit of a limitation for what I'm hoping isn't an entirely unusual use case!

Thanks for the great tool.

**Comment by nedbat** [comment]
I'm having trouble reproducing what you are seeing. Can you provide a more complete example, including the code being run?  I created a "relative/foo.py" file to import, but "coverage report" works fine with or without the rcfile specified, so I don't think I have it right yet.

**Comment by nedbat** [comment]
Feel free to re-open this if you get more information.
