### ISSUE TITLE
Moving NoSource exception from coverage.misc to coverage.exceptions broke coveralls reporting.

### ISSUE THREAD

**Issue by haakenlid** [coveragepy/coveragepy#1226]
**Describe the bug**
I'm trying to contribute to an open source project, but my pull request fails CircleCI test pipeline because it tries to use the latest version of coveragepy. 

```
#!/bin/bash -eo pipefail
COVERALLS_REPO_TOKEN=Q58WdUuZOi89XHyDeDsGE2lxUGQ2IfqP3 coveralls
Traceback (most recent call last):
  File "/home/circleci/.local/bin/coveralls", line 5, in <module>
    from coveralls.cli import main
  File "/home/circleci/.local/lib/python3.8/site-packages/coveralls/__init__.py", line 1, in <module>
    from .api import Coveralls
  File "/home/circleci/.local/lib/python3.8/site-packages/coveralls/api.py", line 14, in <module>
    from .reporter import CoverallReporter
  File "/home/circleci/.local/lib/python3.8/site-packages/coveralls/reporter.py", line 5, in <module>
    from coverage.misc import NoSource
ImportError: cannot import name 'NoSource' from 'coverage.misc' (/home/circleci/.local/lib/python3.8/site-packages/coverage/misc.py)

Exited with code exit status 1
CircleCI received exit code 1
```

It would be better if it was possible to import the exceptions from the old `misc` namespace for a couple of versions before deprecation. Changes like this affects a lot of downstream users who might not be able to pin this library at version <6.0

I've also submitted an issue with coveralls-python about this.
https://github.com/TheKevJames/coveralls-python/issues/326

**Comment by nedbat** [comment]
> It would be better if it was possible to import the exceptions from the old misc namespace for a couple of versions before deprecation.

Just to be clear: these names were never meant as part of a public supported API.  Coveralls is using many internal names...

**Comment by haakenlid** [comment]
> Just to be clear: these names were never meant as part of a public supported API. Coveralls is using many internal names...

Ok. I would normally consider any Exception type that could be raised by a public callable to also be part of the public api.

**Comment by pandafy** [comment]
We are also facing this problem at @OpenWISP. How can I help? 

For reference, the configuration responsible for installing coveralls packages in our CI: 
https://github.com/openwisp/openwisp-controller/blob/af4efe92fe1a6a025e5ecbbd898dc4c01faf5677/.github/workflows/ci.yml#L85-L96

**Comment by nedbat** [comment]
@pandafy can you link me to a job that is failing in this way?

**Comment by nedbat** [comment]
The coveralls code uses a number of internal names.  I don't know if fixing this one import will fix the problem.  You can help by 1) commenting on the [coveralls bug report](https://github.com/TheKevJames/coveralls-python/issues/326), and 2) trying out a fix for coverage.py.  Change line 20 in misc.py from:
```
from coverage.exceptions import CoverageException
```
to:
```
from coverage.exceptions import *
```
and see if that solves the problem.

**Comment by tom-bowles** [comment]
FYI, this also breaks teamcity-messages, which imports NotPython from coverage.misc. Since the module and class names here don't start with underscores, and the exceptions are thrown into calling code, I think these classes *are* part of the public API, regardless of the intention. That said, this was a major version increment (but it doesn't look like semver so I'm not sure what the meaning of the versions is wrt to backward compatibility).

**Comment by nedbat** [comment]
(I'm not sure what "doesn't look like semver" means: I'm trying to conform to semver expectations.)

Perhaps I've needed to explain this more clearly: the supported API is what is documented in the documentation.  I didn't intend for people to use the finely sliced exceptions in their own code.  But we can talk about adding them to the public API in the future.

For now, I've made the exceptions available from coverage.misc again in commit a309f082.  I don't know if that will be enough to get these other projects unstuck.

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.0.1](https://pypi.org/project/coverage/6.0.1).

**Comment by pandafy** [comment]
I missed notifications for this issue. 
Sorry, I am not able to find the logs for failing CI build, since we re-run the workflow after binding coverage version to <6.0.0. 

Thank you @nedbat for releasing a fix. 👏🏼

**Comment by tom-bowles** [comment]
> (I'm not sure what "doesn't look like semver" means: I'm trying to conform to semver expectations.)

I was referring to the two-part version numbers on some releases, eg. 5.5, 6.0  (and I wasn't aware that 3-part numbers were also used for some releases). Two part version numbers aren't valid semver - from the [spec](https://semver.org/):

> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes.

I therefore  wasn't clear on what the intention was for compatibility, although breaking the public API would actually be fine under both reasonable interpretations for the 2-part numbers (0.5.5 -> 0.6.0 or 5.5.0 -> 6.0.0).

Anyway, thanks for the fix! I don't think there was actually anything wrong with the change by semver or PEP8, but it's much more convenient for us this way :-)
