### ISSUE TITLE
Regression: "No data was collected" with 6.0 when run with tox and namespaces

### ISSUE THREAD

**Issue by ampedandwired** [coveragepy/coveragepy#1231]
**Describe the bug**
Coverage 6.0 fails with `CoverageWarning: No data was collected` when run with tox against a namespaced package. The same test run with coverage 5.5 works correctly and reports 100% coverage.

**To Reproduce**
1. What version of Python are you using?
   3.6

1. What version of coverage.py are you using? The output of `coverage debug sys` is helpful.
  6.0

1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.
I've reproduced this in a virtualenv with only "tox" and "coverage" installed.

1. What code are you running?  Give us a specific commit of a specific repo that we can check out.
I've created a minimal repo to reproduce the problem here: https://gitlab.com/ampedandwired/coverage-6-bug

1. What commands did you run?
Check out this repo and run `tox -e cov6`. This will fail with a "no data" warning.
To compare to the 5.5 behaviour run `tox -e cov5`. This will show 100% coverage.
Both commands use the same code, only difference is the "coverage" version.

**Expected behavior**
I expect coverage 6.0 to behave the same way as coverage 5.5 when it comes to namespace packages.
Perhaps there's a new way of configuring these in 6.0?

**Additional context**
Coverage 6.0 works OK if run without tox, or without namespaces, so it seems to be something in the combination of those that triggers this problem.

There are some more details in the README of the repo.

**Comment by nedbat** [comment]
Thanks for the great reproduction repo!  I've made a fix in #1236.  I don't have much experience with namespace packages, so I hope it works for your use.

**Comment by nedbat** [comment]
This is fixed in 9b54389d91c68b27913ded2898f3a03df7e8e90d.

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.0.2](https://pypi.org/project/coverage/6.0.2).

**Comment by ampedandwired** [comment]
Thanks very much for looking at this issue, it is much appreciated. I can confirm that your fix works for us.
