### ISSUE TITLE
Suppress "Combined data file" etc

### ISSUE THREAD

**Issue by owillebo** [coveragepy/coveragepy#1254]
With coverage version 6+ our test framework started outputting;

Lot's of; `Combined data file .coverage.DESKTOP-G28B0IU.9900.358097`
and `Wrote HTML report to htmlcov\index.html`

The Coverage constructor has a message parameter to suppress this, the CoverageScript::command_line however unconditionally sets this message parameter to True.

Please provide a way to suppress these messages via the command line or configuration.

Running; `Coverage.py, version 6.0.2 with C extension`

**Comment by nedbat** [comment]
Good idea, I'll add a -q option.

**Comment by nedbat** [comment]
This is implemented in 93c9ca9f.

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.1](https://pypi.org/project/coverage/6.1).
