### ISSUE TITLE
ModuleMatcher does not handle calling a module file via a subprocess

### ISSUE THREAD

**Issue by gaborbernat** [coveragepy/coveragepy#1257]
If I call a child module file in a subprocess that's no longer recognized as part of the module when using the module matcher. That's because it only takes the final part of the filename, and considers that the module https://github.com/nedbat/coveragepy/blob/master/coverage/inorout.py#L90-L95

```python
import the_module
subprocess.check_output([sys.executable, inspect.getsourcefile(the_module.a)])
```

**Comment by nedbat** [comment]
I'm not sure I'd be able to recreate the scenario you're describing. Could you provide a small complete example showing what goes wrong?

**Comment by gaborbernat** [comment]
IMHO the explanation above is fairly accurate, I don't have more time to allocate to this. My TLDR was never to use relative paths with coveragepy configs, you're going to have a bad time https://twitter.com/gjbernat/status/1452419408668897284.

**Comment by gaborbernat** [comment]
No longer relevant for me.
