### ISSUE TITLE
Relative paths in subprocesses should not be classified as modules

### ISSUE THREAD

**Issue by gaborbernat** [coveragepy/coveragepy#1258]
The source or pkg check here https://github.com/nedbat/coveragepy/blob/master/coverage/inorout.py#L218 is easy to break for a subprocess. If the parent process has a relative source tree passed in as coverage target (e.g. ./tests) and there's a child process that changes the current working directory the child will incorrectly classify the tree as a module.

E.g. this
```
<ModuleMatcher source_pkgs ['pyproject_api']> <TreeMatcher source ['/home/bernat/git/pyproject-api/tests']>
```
translates to:
```
<ModuleMatcher source_pkgs ['.tox/py310/lib/python3.10/site-packages/pyproject_api', 'tests']>
```

Perhaps we need a COVERAGE_PROCESS_CWD to set the root folder...

**Comment by nedbat** [comment]
I'm not sure I'd be able to recreate the scenario you're describing. Could you provide a small complete example showing what goes wrong?

**Comment by gaborbernat** [comment]
IMHO the explanation above is fairly accurate, I don't have more time to allocate to this. My TLDR was never to use relative paths with coveragepy configs, you're going to have a bad time https://twitter.com/gjbernat/status/1452419408668897284.

**Comment by nedbat** [comment]
I understand you were frustrated when you wrote this.  I'm sorry for that.  I would like to address the problem you describe here, but I could really use some more information.

You must have had a project that was failing, can you give me a commit that was failing in the way you describe?

**Comment by gaborbernat** [comment]
Not frustrated, more relieved to figure out the issue and find a workaround to move on to other challenges. And actually I no longer have the code because the version I was failing with was a Dev version that never got published on its own. The project is pyproject-api from tox-dev org. You probably can replicate it if you replace my absolute --cov paths with relative ones; though I believe my initial posts points out the issue with link to the coveragepy code.

**Comment by gaborbernat** [comment]
No longer relevant for me.
