### ISSUE TITLE
add time elapsed to coverage report

### ISSUE THREAD

**Issue by av603** [coveragepy/coveragepy#1269]
As a developer, I want to add the test duration to the coverage report, so I can identify and then optimise the longest running tests.

Shorter test duration leads to a quicker feedback loop. Long running tests create a development anti pattern. Larger projects result in longer test duration, leading to more throw-away code to understand how the test duration is split across modules. 

Current solution is to implement something like this: 
https://stackoverflow.com/questions/39739045/how-to-measure-the-time-profile-of-each-django-test

However, the problem is generic and common enough to justify adding the test duration to the coverage report.

**Comment by nedbat** [comment]
Coverage.py generally doesn't know about tests.  You can use it to measure programs that have nothing to do with testing, for example.  The test runner is the right place to get this information. For example, pytest has an option to show the slowest test steps and their durations.  Is there a reason why that won't work?

**Comment by av603** [comment]
There are a few different approaches that work e.g. pytest to show the slowest running test, cProfile to show the most time consuming method, passing log files etc. The idea was more to add an 'elapsed duration' column to the coverage summary table as a concise way of presenting the information, but it sounds like coverage does not have access to this information?

**Comment by nedbat** [comment]
Right, this is not how coverage.py is organized now.  The test runner is really the best place.
