### ISSUE TITLE
Backwards incompatible debug change

### ISSUE THREAD

**Issue by cdce8p** [coveragepy/coveragepy#1273]
**Describe the bug**
The change done in https://github.com/nedbat/coveragepy/commit/16f54a935a1c41618e098bebdbcb77b638f40c6c (adding a `name` argument to `TreeMatcher`, `ModuleMatcher`, and `FnmatchMatcher`) makes it difficult for projects to support both versions `5.x` and `6.x` as the signature is incompatible.

For example `coveralls-python` doesn't currently pass the `name` argument.
https://github.com/TheKevJames/coveralls-python/blob/e03a2de15e65cafc3fe583b1ab15e3e0b6478722/coveralls/reporter.py#L70-L78

This obviously results in a `TypeError` when using `6.x`: https://github.com/TheKevJames/coveralls-python/issues/333

**Possible resolutions**
1. `coveralls-python` could drop support for `5.x`.
2. It could detect the version of `coveragepy` and act accordingly.
3. Or a default value is added to `TreeMatcher`, `ModuleMatcher`, and `FnmatchMatcher`.

Although options (1) and (2) would work, I think (3) is be preferable. `name` is only used in the `__repr__` functions. I don't think that justifies breaking existing code.

**Comment by nedbat** [comment]
Another possible resolution:

4. Stop using internal undocumented interfaces, and ask for support for the features you need.

A default value is not unreasonable, but it is tiresome having to think about people using undocumented interfaces.

**Comment by cdce8p** [comment]
> Another possible resolution:
> 
> 1. Stop using internal undocumented interfaces, and ask for support for the features you need.
> 
> A default value is not unreasonable, but it is tiresome having to think about people using undocumented interfaces.

True. Although I only debugged the error, I know this to all to well from my own experience in Open Source.

**Comment by DanielNoord** [comment]
Thanks @nedbat I saw the discussion in the original issue about `coveralls-python` and `coveragepy` `6.0` which is why I reported against them initially. 
Completely agree with you and very grateful that you are willing to take this up! Much appreciated!

**Comment by nedbat** [comment]
Fixed in e3e637c9.  (it's nicer with the default value anyway...)

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.1.2](https://pypi.org/project/coverage/6.1.2).

**Comment by TheKevJames** [comment]
Hey @nedbat, `coveralls-python` maintainer here. Sorry for the issues this caused! I'd thought I managed to switch away from using any undocumented internal coverage-py functionality back around the v5 release, but I'd forgotten entirely about some of the workarounds we still needed. It looks like you've actually tackled [a couple of the things we were relying on](https://github.com/nedbat/coveragepy/commit/f3a70c951e838e3cfab706b9a2d0459d783e5a4f) recently anyway, so now is definitely the right time for me to take a look.

The gist of the issue [is described here](https://github.com/TheKevJames/coveralls-python/blob/c35bf51671a9608b6b5610e61a1510bf1924882c/coveralls/reporter.py#L33-L111). We're pretty close to being able to use [get_analysis_to_report](https://github.com/nedbat/coveragepy/blob/f3a70c951e838e3cfab706b9a2d0459d783e5a4f/coverage/report.py#L48) directly, and it looks like the `config.ignore_errors` boolean is the last piece.

What are your thoughts on `coveralls-python` setting `ignore_errors=True` unconditionally? I've erred away from doing so as I really only wanted to avoid errors in this specific function call, but I don't want to affect behavioural changes to `coverage-py` in eg. [places like this](https://github.com/TheKevJames/coveralls-python/blob/c35bf51671a9608b6b5610e61a1510bf1924882c/coveralls/api.py#L400-L402). What are your thoughts on expected usage here?

The only other (minor!) question would be whether [this exception](https://github.com/nedbat/coveragepy/blob/f3a70c951e838e3cfab706b9a2d0459d783e5a4f/coverage/report.py#L68) could be made more granular. There are plenty of other `CoverageException`s which we wouldn't want to catch, but this one is OK for our use-case. Note this is just a nitpick, I could certainly do `except CoverageException as e: if str(e) != 'No data to report.': raise` or such, but it throwing, say, a `NoDataException` might be easier to reason about.

**Comment by nedbat** [comment]
About ignoring errors: you can certainly do that if you want, you know your users' needs.

About exceptions: good idea! I've sliced them up better in commit 1c29ef3e.  Let me know if it looks like what you were thinking.

**Comment by nedbat** [comment]
@TheKevJames btw, I just rediscovered #921, so I'm glad to be re-connecting on this.  I should have paid more attention to that issue when you first opened it, sorry about that.
