### ISSUE TITLE
Is there a watch option to watch test file changes and automatically re run the tests?

### ISSUE THREAD

**Issue by edchelstephens** [coveragepy/coveragepy#1276]
Hi,

Just curious to know if there's a watch option in coverage? 
To watch test file changes and automatically re-run the tests?

Thanks a lot,
Ed

P.S.
Awesome package! :)
Thanks Ned and all contributors/maintainers.

**Comment by nedbat** [comment]
Coverage is not a test runner: it monitors the execution of any program, and knows very very little about tests.  Re-running when files change is something your test runner, or another process executor can do.

**Comment by edchelstephens** [comment]
> Coverage is not a test runner: it monitors the execution of any program, and knows very very little about tests. Re-running when files change is something your test runner, or another process executor can do.

Thank you for answering my question. 👍
