### ISSUE TITLE
How to I explicitly install coverage with tracer set to Ctracer with coverage 5.5?

### ISSUE THREAD

**Issue by edchelstephens** [coveragepy/coveragepy#1277]
Hi,

I've read this on the FAQ,

[Coverage.py is much slower than I remember, what’s going on?](https://coverage.readthedocs.io/en/coverage-5.5/faq.html#q-coverage-py-is-much-slower-than-i-remember-what-s-going-on
)
Following the faq:

Running `coverage debug sys`
I got:

-- sys -------------------------------------------------------
                        version: 5.5
                       coverage: /home/myuser/miniconda3/envs/myproject/lib/python3.6/site-packages/coverage/__init__.py
                         tracer: -none-
                        CTracer: available
           plugins.file_tracers: -none-
            plugins.configurers: -none-
      plugins.context_switchers: -none-

I'm using [Miniconda](https://docs.conda.io/en/latest/miniconda.html#linux-installers) for virtual environment:

I removed the package from the environment and also tried, pip --force-reinstall coverage==5.5

But I still get the `tracer: -none-`

**How can I explicitly install coverage with tracer:Ctracer?**

Is this because I'm using conda?

Any help is much appreciated,

Thanks,
Ed

**Comment by edchelstephens** [comment]
This should be labelled as `install` or `general question` But  I don't know how to manually set the github issue label, sorry.

**Comment by nedbat** [comment]
Your installation is fine.  It was the 5.5 docs that were wrong.  They are fixed now: https://coverage.readthedocs.io/en/stable/faq.html#q-coverage-py-is-much-slower-than-i-remember-what-s-going-on

The key line in the output is `CTracer: available`, so you are all set.

**Comment by edchelstephens** [comment]
> Your installation is fine. It was the 5.5 docs that were wrong. They are fixed now: https://coverage.readthedocs.io/en/stable/faq.html#q-coverage-py-is-much-slower-than-i-remember-what-s-going-on
> 
> The key line in the output is `CTracer: available`, so you are all set.
Thank you! 👍
