### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [coveragepy/coveragepy#1279]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

```diff
diff --git a/lab/genpy.py b/lab/genpy.py
index f968c916..05a31749 100644
--- a/lab/genpy.py
+++ b/lab/genpy.py
@@ -137,14 +137,14 @@ class RandomAstMaker:
                     body[-1].append(self.make_body("ifelse"))
             elif stmt == "for":
                 old_allowed = self.bc_allowed
-                self.bc_allowed = self.bc_allowed | {"break", "continue"}
+                self.bc_allowed |= {"break", "continue"}
                 body.append(["for", self.make_body("for")])
                 self.bc_allowed = old_allowed
                 if self.roll():
                     body[-1].append(self.make_body("forelse"))
             elif stmt == "while":
                 old_allowed = self.bc_allowed
-                self.bc_allowed = self.bc_allowed | {"break", "continue"}
+                self.bc_allowed |= {"break", "continue"}
                 body.append(["while", self.make_body("while")])
                 self.bc_allowed = old_allowed
                 if self.roll():
@@ -152,7 +152,7 @@ class RandomAstMaker:
             elif stmt == "try":
                 else_clause = self.make_body("try") if self.roll() else None
                 old_allowed = self.bc_allowed
-                self.bc_allowed = self.bc_allowed - {"continue"}
+                self.bc_allowed -= {"continue"}
                 finally_clause = self.make_body("finally") if self.roll() else None
                 self.bc_allowed = old_allowed
                 if else_clause:
diff --git a/tests/test_parser.py b/tests/test_parser.py
index d5f43197..3ca40fe7 100644
--- a/tests/test_parser.py
+++ b/tests/test_parser.py
@@ -440,7 +440,7 @@ class ParserFileTest(CoverageTest):
         counts = { 2:1, 3:1, 4:2, 5:1, 7:1, 9:1, 10:1 }
         name_endings = (("unix", "\n"), ("dos", "\r\n"), ("mac", "\r"))
         for fname, newline in name_endings:
-            fname = fname + ".py"
+            fname += ".py"
             self.make_file(fname, text, newline=newline)
             parser = self.parse_file(fname)
             assert parser.exit_counts() == counts, "Wrong for %r" % fname
```

**Comment by nedbat** [comment]
Did you run a tool to generate this diff?  Would you like to make a pull request?

**Comment by elfring** [comment]
>Did you run a tool to generate this diff?

The shown update candidates were found with the help of a tiny Perl command (which I constructed for this transformation approach).


>Would you like to make a pull request?

:thought_balloon: Can such source code adjustments be also integrated directly?

**Comment by nedbat** [comment]
> 💭 Can such source code adjustments be also integrated directly?

I'm not sure what you mean by integrated directly.  If you mean run them automatically on pull requests, then I would rather not, especially if they are home-grown.  I use pylint to find certain kinds of problems, and rely on my own review to find other possibilities for improvement.

This type of change is not a bug, it's a stylistic issue.  Maintaining a new tool to find them is not worth the effort, in my opinion.

**Comment by elfring** [comment]
>I use pylint to find certain kinds of problems, …

There are feature requests in the waiting queues for such source code analysis tools.

>This type of change is not a bug, it's a stylistic issue.

Do any factors hinder the wider application of [functionality which became generally available with Python 2](https://docs.python.org/3/whatsnew/2.0.html#augmented-assignment "Augmented assignments")? :thinking:

**Comment by nedbat** [comment]
>>I use pylint to find certain kinds of problems, …
>
> There are feature requests in the waiting queues for such source code analysis tools.

I don't know what that means? Are you saying pylint has feature requests for this kind of source code analysis? Sounds great.

>>This type of change is not a bug, it's a stylistic issue.
>
> Do any factors hinder the wider application of [functionality which became generally available with Python 2](https://docs.python.org/3/whatsnew/2.0.html#augmented-assignment "Augmented assignments")? :thinking:

There's nothing stopping us from using more augmented assignment.  My point about stylistic issue is that it's not critical to use augmented assignment everywhere you can.  It's nice, and I'd merge a pull request like that, but I'm not willing to adding tooling to find more things like that.

**Comment by elfring** [comment]
>There's nothing stopping us from using more augmented assignment.

Thanks for such a positive feedback.


>It's nice,

:thought_balloon: Can such a view influence also the interpretation of assignment variants by other software developers?


>and I'd merge a pull request like that,

I became also affected by special dependencies for my software development systems.
Thus it will probably take a while until I am ready again to submit another merge request.
:thought_balloon: I am curious if others could get into the mood to pick discussed change suggestions up.


>but I'm not willing to adding tooling to find more things like that.

Source code analysis and transformation tools can eventually be extended accordingly, can't they? :thinking:

**Comment by nedbat** [comment]
It feels like this is a philosophical discussion about source analysis tools now, and not something about coverage.py in particular.  I'm not sure how I can help you.

**Comment by elfring** [comment]
* I got the impression that your concrete indications for another bit of change acceptance can be helpful already.
* I imagine that development interests can grow for related tools.

**Comment by nedbat** [comment]
Looking more closely at the diff, the changes proposed for genpy.py would break it.  There is a difference between `s = s | x` and `s |= x`.  The first makes a new set, the second modifies the existing set in-place.  Notice how `old_allowed` is used to save and restore the value of `self.bc_allowed`.  If we modify `self.bc_allowed` in-place, that wouldn't work.

**Comment by nedbat** [comment]
The string augmented assignment got swept up in e30a444a.

**Comment by elfring** [comment]
>There is a difference between `s = s | x` and `s |= x`. The first makes a new set, the second modifies the existing set in-place.

* :thought_balloon: I suggest to reconsider this programming concern a bit more also according to [the rationale of the Python enhancement proposal 203](https://www.python.org/dev/peps/pep-0203/#rationale "Proposal for augmented assignments") (from 2000-07-13).
* Would you eventually like to introduce additional variable names for intermediate computation results? :thinking:

**Comment by nedbat** [comment]
>>There is a difference between `s = s | x` and `s |= x`. The first makes a new set, the second modifies the existing set in-place.
>
> * :thought_balloon: I suggest to reconsider this programming concern a bit more also according to [the rationale of the Python enhancement proposal 203](https://www.python.org/dev/peps/pep-0203/#rationale "Proposal for augmented assignments") (from 2000-07-13).
> * Would you eventually like to introduce additional variable names for intermediate computation results? :thinking:

I'm not sure what there is to consider? The code works as it is, and would not work if we applied your change.  Introducing additional variable names would only let us use augmented assignment if we first copied the set.  That's more lines of code, with more names, to what end?

I appreciate you looking at coverage.py and thinking about ways to improve it, but this particular change isn't needed.

**Comment by elfring** [comment]
>…, and would not work if we applied your change.

I recommend to reconsider also such an interpretation of the shown control flow.
:thought_balloon: Variable assignments are performed with known data processing effects, aren't they?

**Comment by nedbat** [comment]
Yes, I'm sure you could re-write this code to manage this problem differently.  But really, what is the obsession with finding ways to use augmented assignment? If you want to refactor this code so that it is clearer, or has fewer bugs, or runs faster, do it.  

But it seems like you are just hammering on the idea that we should use more augmented assignment?  Please stop.

**Comment by elfring** [comment]
>But really, what is the obsession with finding ways to use augmented assignment?

:thought_balloon: I imagine that this implementation detail can benefit from another bit of collateral evolution.


>If you want to refactor this code so that it is clearer, …, or runs faster, do it.

I hope that something can be achieved also in such design directions by this issue. :thinking:
