### ISSUE TITLE
pytest plugin combination 'pylint-pytest' and 'pytest-cov' deletes coverage result files

### ISSUE THREAD

**Issue by lhupfeldt** [coveragepy/coveragepy#1282]
**Describe the bug**
When running `pylint` with the `pylint-pytest`plugin active, `.coverage.*` files are deleted.
I'm not sure if this bug belongs here or in the `pylint-pytest` project, but my **guess** is that it happens because the plugin causes execution of some `coverage` code.

**To Reproduce**
Project attached
[pylint-cov-error.zip](https://github.com/nedbat/coveragepy/files/7563692/pylint-cov-error.zip)

```
nox -s unit
ls -l .coverage.*
nox -s pylint
ls -l .coverage.*
```

Python 3.10
coverage 6.1.2 and 5.5

**Expected behavior**
`.coverage.*` files should not disapear when running pylint

**Comment by nedbat** [comment]
It seems that the pylint-pytest plugin imports pytest, and the pytest-cov plugin deletes the coverage files when pytest is imported.

I verified this by making a new requirements file in your test that omits pytest-cov, and using that requirements file in the pylint nox session.  When I do that, the files remain.  I guess this should be reported to pytest-cov.

**Comment by lhupfeldt** [comment]
Thank you for analyzing this Ned.
I have added a bug report to `pytest-cov` and changed the title.

I think it might be an idea to keep this bug open here though until the problem is resolved. May save some people a lot of time if they have the same problem. And also prevent new bug reports about this.

**Comment by nedbat** [comment]
TBH, I'm not sure how people would find this bug report from their own experiences, but if they search for "pylint-pytest", they will find it even if it's closed.
