### ISSUE TITLE
Feature request: measuring the coverage of a PR's added/modified lines of code

### ISSUE THREAD

**Issue by lsorber** [coveragepy/coveragepy#1284]
It would be interesting to be able to measure the coverage of a PR's _added/modified lines of code_ so that we can tell if the code introduced or modified by a PR is covered by tests. Additionally, it would be great if you could require a minimum coverage for these changes.

**Comment by nedbat** [comment]
This is provided by [diff-cover](https://pypi.org/project/diff-cover/).  Give it a try and let me know if it doesn't work for you.

**Comment by lsorber** [comment]
Thank you @nedbat!
