### ISSUE TITLE
Unable to install it with django 4.x release

### ISSUE THREAD

**Issue by tbhaxor** [coveragepy/coveragepy#1295]
**Describe the bug**
Getting the following error after upgrading Django to 4 to fix the vulnerabilities

```
ERROR: No matching distribution found for Django==4.0
```

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't just link to a failing CI job. Answer the questions below:

All you need to do is install Django 4.x and then coverage 6.2 (the latest version atm)

**Expected behavior**
_That's axiomatic_

**Additional context**
The latest version supported in the package is `3.2.10`. Please upgrade it to support django 4 as well

For more context you can check out this failed CI job https://github.com/tbhaxor/DonorGrid/runs/4621954558?check_suite_focus=true

**Comment by nedbat** [comment]
I don't see how this could be caused by coverage.py, since it doesn't mention Django at all.  Can you give me the exact steps you used to produce the problem?  Installing Django 4.0 and then installing coverage 6.2 works fine.

**Comment by tbhaxor** [comment]
Yeah, my bad. Seems like it is a Django issue that doesn't support python <= 3.8
