### ISSUE TITLE
coverage not running with subprocess.Popen

### ISSUE THREAD

**Issue by pyturn** [coveragepy/coveragepy#1327]
Hi, I am running coverage command with subprocess Popen , But getting the unexpected output.  Below is my code. 

Code :
`coverage_cmd = "coverage run manage.py test && coverage report -m"`
`process = Popen([coverage_cmd], stdout=PIPE, stderr=PIPE,  
                        cwd=working_dir)`
`coverage_compute, stderr = process.communicate()`
`print("Coverage is {}".format(coverage_compute))`

Outupt:
`Coverage is b''`

The above code runs fine if I am passing shell = True, or using os.popen()

I already tried passing the command as sequence , but after this also I am getting unexpected output. Below is the code - 

`coverage_cmd = "coverage run manage.py test && coverage report -m"`
`process = Popen(coverage_cmd.split(), stdout=PIPE, stderr=PIPE,  
                        cwd=working_dir)`
`coverage_compute, stderr = process.communicate()`
`print("Coverage is {}".format(coverage_compute))`

Outupt:
`Coverage is b''`

Can anyone can help me in resolving this ? 

`Python  : 3.9.10`
`coverage : 6.3.1`

**Comment by Arglanir** [comment]
Your usage of `&&` shows really that only a shell can run and parse your command.
Run the first process `coverage run manage.py`, using `Popen(command.split(), ...`, and then depending on `process.returncode`, you can then run `coverage report -m`, using also `Popen(command.split(), ...`

**Comment by nedbat** [comment]
@pyturn I'm sorry, I don't understand.  If i runs file with `shell=True`, then you should use that.  I'll close this, feel free to re-open if I've misunderstood and you still have a problem.
