### ISSUE TITLE
How to use coverage in fastapi？

### ISSUE THREAD

**Issue by leoyyer** [coveragepy/coveragepy#1346]
I want to use coverage in fastapi,So, I used the following method:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/13775385/160050314-4a8a3a2a-114f-4e93-a59f-7c0367f80347.png">

I tried to start coverage with the following way: 
coverage run --source=test -m uvicorn test_3:app --reload,
coverage run -m  uvicorn test_3:app --reload  
but:
 CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")

So, does coverage not support the startup method of the command? how should i handle it

**Comment by nedbat** [comment]
I'm not an expert at FastAPI, but `--reload` usually means that a subprocess is spawned to actually serve requests. Try without it.
Also, are you using both the API in your Python file and the coverage command line? You shouldn't need both.

**Comment by leoyyer** [comment]
> I'm not an expert at FastAPI, but `--reload` usually means that a subprocess is spawned to actually serve requests. Try without it. Also, are you using both the API in your Python file and the coverage command line? You shouldn't need both.

Thanks a lot for the guidance, I have found the solution。I want to start the project through gunicorn, so I should set in gunicorn。 so i should write config file:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/13775385/160114547-8bfdb816-62d1-4bfb-8c53-b5744beabf4a.png">
and run by "gunicorn -c gunicorn.py test_3:app -k uvicorn.workers.UvicornWorker"
from "https://stackoverflow.com/questions/19025336/how-to-get-coverage-data-from-a-django-app-when-running-in-gunicorn" help

**Comment by madilu-technologies** [comment]
Thank you so much @leoyyer. Your thread helped me a lot. I wanted to measure the coverage in FastAPI. It worked like a charm.
