### ISSUE TITLE
MacOS Monterey Support

### ISSUE THREAD

**Issue by cpvandehey** [coveragepy/coveragepy#1349]
**Describe the bug**
Pip hangs while installing coverage on mac Monterey. [From the release files](https://pypi.org/project/coverage/#files), there isn't any release made yet for mac os Monterey builds. Only 10.x and 11.x versions are available.

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't link to a failing CI job. Answer the questions below:
1. What version of Python are you using? 

Python 3.9.6

1. What version of coverage.py shows the problem? The output of `coverage debug sys` is helpful.

`FileExistsError: [Errno 17] File exists: '/private/var/folders/xb/_35pkyz50bq0k3dcbr60j3n00000gn/T/pip-req-build-rv4dmazf/.eggs/coverage-6.3.2-py3.9-macosx-11.5-x86_64.egg'`
Surprisingly, 10.9 actually works on install. /shrug

**Expected behavior**
The install step should work

**Comment by nedbat** [comment]
Hmm, I would have expected to hear about this long before now if Monterey can't install coverage.py.  Perhaps there are other factors coming into play?  What version of pip are you using? If it's not the latest, can you try upgrading it?

**Comment by cpvandehey** [comment]
I used the latest of setuptools (61.2.0) and pip (22.0.4).

Maybe this is obvious to note, but the C libraries are OS dependent. Those make for some potentially hairy situations when upgrades happen.

**Comment by nedbat** [comment]
> the C libraries are OS dependent. Those make for some potentially hairy situations when upgrades happen.

I'm sorry, I don't know what you mean by this?

**Comment by nedbat** [comment]
I've tried on a handful of machines, and they all install fine.  Something else is going on for you, but I don't know what.  If you get more information, please re-open the issue.
