### ISSUE TITLE
Option to excluded no-context lines from total calculation

### ISSUE THREAD

**Issue by bbeattie-phxlabs** [coveragepy/coveragepy#1350]
**Is your feature request related to a problem? Please describe.**

When I run coverage against my code that has _zero_ tests run, it's frustrating to see a coverage total above 0%.

As a simple example:

```
$ cat myfile.py

def foo(a, b):
    return a + b
```

```
$ pytest myfile.py --cov=. --cov-report term-missing:skip-covered --quiet

---------- coverage: platform linux, python 3.10.2-final-0 -----------
Name        Stmts   Miss  Cover   Missing
-----------------------------------------
myfile.py       2      1    50%   2
-----------------------------------------
TOTAL           2      1    50%

no tests ran in 0.01s
```

**Describe the solution you'd like**

Executed lines are annotated with their contexts as per https://coverage.readthedocs.io/en/latest/contexts.html#dynamic-contexts. An option could use this to say "consider lines with no context as though they were commented with `# pragma: no cover`, excluding them from total calculations."

**Describe alternatives you've considered**

Alternative solutions would be to take the resultant `.coverage` sqlite DB and manually compute the contextless-excluded total from there, but that seems notably hackier and wouldn't affect any of the generated reported numbers

**Additional context**

I'm happy to put the work into a pull request to address this feature request if the maintainers see value in pursuing it!

**Comment by bbeattie-phxlabs** [comment]
At first glance, augmenting `Analysis.__init__` with 

```
self.no_context = set(
    line
    for line, contexts in self.data.contexts_by_lineno(self.filename).items()
    if not any(contexts)
)
```

and the instantiation of self.numbers with

```            
  n_statements=len(self.statements - self.no_context),
  n_excluded=len(self.excluded - self.no_context),
  n_missing=len(self.missing - self.no_context),
```

which results in an output of 

```
---------- coverage: platform linux, python 3.10.2-final-0 -----------
Name        Stmts   Miss  Cover   Missing
-----------------------------------------
myfile.py       1      1     0%   2
-----------------------------------------
TOTAL           1      1     0%
```

where 0% is the result I'm looking for. I've written no tests so far.

The above snipped needs to sit behind a configuration option, but figured I'd get clear go-ahead before creating a PR.

**Comment by nedbat** [comment]
This is an interesting idea, but I'm not sure you'd be happy with the result.  The flip side of only counting lines in contexts is that you could never get to 100% coverage.  You have non-zero coverage with no tests because the imports, class definitions, and function definitions are all executed when your module is imported.  Those are the lines giving you non-zero coverage.  If you exclude those lines, then they will always be considered uncovered, and you couldn't get to 100%.

In this scenario, what goal would you choose for your coverage?  Maybe the simpler solution is to accept that in Python, there is code that executes during import, and that is fine.  The actual value of the numerical results aren't significant. That is, there's no objective scale that says 40 is bad and 50 is good. All we know is that 50 is better than 40 because 50 is more than 40.

**Comment by bbeattie-phxlabs** [comment]
Double-checking the assessment, I think [the above code snippet](https://github.com/nedbat/coveragepy/issues/1350#issuecomment-1083646903) actually addresses the concern you raise! By removing lines without context from `n_statements`, the ratio can indeed go to 100%.

## With my proposed change and with a test

```
import math

def foo(a, b):
    return a + b
```
```
from your_package_name.myfile import foo

def test_main():
    assert foo(1, 2) == 3
```
```
tests\test_myfile.py .                                                                             [100%]

---------- coverage: platform win32, python 3.10.4-final-0 -----------
Name                                Stmts   Miss Branch BrPart  Cover   Missing
-------------------------------------------------------------------------------
src\your_package_name\__init__.py       0      0      0      0   100%
src\your_package_name\myfile.py         1      0      0      0   100%
-------------------------------------------------------------------------------
TOTAL                                   1      0      0      0   100%

Required test coverage of 1% reached. Total coverage: 100.00%
```

## With my proposed change and without a test

```
def test_main():
    assert True
```
```
tests\test_myfile.py .                                                                             [100%]

---------- coverage: platform win32, python 3.10.4-final-0 -----------
Name                                Stmts   Miss Branch BrPart  Cover   Missing
-------------------------------------------------------------------------------
src\your_package_name\__init__.py       0      0      0      0   100%
src\your_package_name\myfile.py         1      1      0      0     0%   4
-------------------------------------------------------------------------------
TOTAL                                   1      1      0      0     0%

FAIL Required test coverage of 1% not reached. Total coverage: 0.00%
```


## Motivation

So I think the above shows that it would indeed work! My motivation is to coax developers in my org towards best practices without immediately requiring 100% code coverage. So a project template that says `--cov-fail-under=1` requires new projects to at least write _one_ test, and we can go from there. But given coverage's current inclusion of let's call it "contextless code", I can't set a stable lower threshold at the moment.

Happy to throw together a PR, but wanted to get your approval before moving forward. Thanks much for your attention to this issue. :)

**Comment by nedbat** [comment]
I see what you are getting at. It feels like there will be unforeseen consequences of excluding those lines, but we need to get some other eyes on it to know.  Go ahead and make a PR and we can ask people for opinions.

I guess `Analysis` will need to take the full config object in order to have the information it needs.

**Comment by bbeattie-phxlabs** [comment]
Looking deeper into the codebase, I see in cmdline.py:59 that the following already exists!

```
    contexts = optparse.make_option(
        '', '--contexts', action='store', metavar="REGEX1,REGEX2,...",
        help=(
            "Only display data from lines covered in the given contexts. " +
            "Accepts Python regexes, which must be quoted."
        ),
    )
```

```
# coverage report -m
Name        Stmts   Miss  Cover   Missing
-----------------------------------------
myfile.py       2      1    50%   2
-----------------------------------------
TOTAL           2      1    50%

# coverage report -m --contexts=test
Name        Stmts   Miss  Cover   Missing
-----------------------------------------
myfile.py       2      2     0%   1-2
-----------------------------------------
TOTAL           2      2     0%
```

I suspect the feature enhancement is really just to get [pytest-cov](https://pytest-cov.readthedocs.io/en/latest/config.html) to accept something akin to `--cov-report-context=test` to match their `--cov-context=test`.

I'll reopen this ticket if that approach isn't as fruitful as I'm hoping.

**Comment by bbeattie-phxlabs** [comment]
My now-deleted comment about using `coverage report --contexts=test` was premature. Continuing with the PR...

**Comment by bbeattie-phxlabs** [comment]
https://github.com/nedbat/coveragepy/pull/1389 up as an initial draft.
