### ISSUE TITLE
In HTML report, display coverage creation time at the top of the page.

### ISSUE THREAD

**Issue by Mariatta** [coveragepy/coveragepy#1351]
**Is your feature request related to a problem? Please describe.**
Often I found myself not realizing that I was looking at an outdated coverage report.

I know that the the report includes the creation time at the bottom of the page. When working in large codebase, we would need to scroll down first before seeing that information. It's not too obvious that the info exists, and it's not always the first thing I'd look at.

I think it would be great if the creation time can be displayed at the top of the page as well.

**Describe the solution you'd like**
Display the "created at .." at the top.

Sample mockup:

index.html
![Screen Shot 2022-04-05 at 1 43 53 PM](https://user-images.githubusercontent.com/5844587/161846274-5373b6d8-6904-488b-a322-4e67d028c00d.png)

module coverage report
![Screen Shot 2022-04-05 at 1 45 25 PM](https://user-images.githubusercontent.com/5844587/161846270-0fb6621e-341b-458f-b936-8b6e5d263039.png)

**Comment by nedbat** [comment]
This is now done, in commit 53e5dd3e

**Comment by Mariatta** [comment]
This is great! Thank you!

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.4](https://pypi.org/project/coverage/6.4).
