### ISSUE TITLE
Wrong warning about `--source` is set and printed coverage summary does not match with generated coverage xml

### ISSUE THREAD

**Issue by gro1m** [coveragepy/coveragepy#1355]
**Describe the bug**
This describes 2 bugs, which are possibly interrelated:
- I get `CoverageWarning: --include is ignored because --source is set (include-ignored)
    self.warn("--include is ignored because --source is set", slug="include-ignored")` although only `include` is specified in pytest.ini and nowhere `--source` is specified.
- The console summary prints filename with file path prefix included whereas the generated xml file does not include the file path prefix in the filename.

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't link to a failing CI job. Answer the questions below:
1. What version of Python are you using?
`3.9.7` and `3.10.4`
1. What version of coverage.py shows the problem? The output of `coverage debug sys` is helpful.2. 
`6.3.2`
1. What versions of what packages do you have installed? The output of `pip freeze` is helpful. 
You should check environment.yaml of repo referenced below, but for completeness, I also provide the output of `pip freeze`:
```
attrs @ file:///opt/conda/conda-bld/attrs_1642510447205/work
certifi==2021.5.30
coverage @ file:///opt/concourse/worker/volumes/live/6d8c776a-ac30-4777-7698-aa9485387efe/volume/coverage_1645539123521/work
iniconfig @ file:///home/linux1/recipes/ci/iniconfig_1610983019677/work
packaging @ file:///tmp/build/80754af9/packaging_1637314298585/work
pluggy @ file:///opt/concourse/worker/volumes/live/8277900c-164a-49c8-6f2a-f55c3c0154be/volume/pluggy_1648042581708/work
py @ file:///opt/conda/conda-bld/py_1644396412707/work
pyparsing @ file:///tmp/build/80754af9/pyparsing_1635766073266/work
pytest==7.1.1
pytest-cov @ file:///tmp/build/80754af9/pytest-cov_1637159997573/work
toml @ file:///tmp/build/80754af9/toml_1616166611790/work
tomli @ file:///tmp/build/80754af9/tomli_1637314251069/work
```
1. What code shows the problem?  Give us a specific commit of a specific repo that we can check out. If you've already worked around the problem, please provide a commit before that fix.
<https://github.com/gro1m/coverageminimalexample>
NOTE: I substituted my HOME PATH with `~` on line 6 in the generated `coverage.xml`, this is an alteration I did after the program has been run.
1. What commands did you run?
`pytest`

**Expected behavior**

The following line is *not* printed on the console, when `source` is not set:
```
../../opt/anaconda3/envs/coverageminimalexample/lib/python3.10/site-packages/coverage/inorout.py:472
  /Users/michaelgross/opt/anaconda3/envs/coverageminimalexample/lib/python3.10/site-packages/coverage/inorout.py:472: CoverageWarning: --include is ignored because --source is set (include-ignored)
    self.warn("--include is ignored because --source is set", slug="include-ignored")
```

and the file paths is prefixed when written to the `coverage.xml` as shown in the console output:
```
---------- coverage: platform darwin, python 3.10.4-final-0 ----------
Name                                 Stmts   Miss  Cover   Missing
------------------------------------------------------------------
coverageminimalexample/__init__.py       0      0   100%
coverageminimalexample/fun.py            2      0   100%
------------------------------------------------------------------
TOTAL                                    2      0   100%
Coverage XML written to file coverage.xml
```

**Additional context**
There were attempts to solve the problem here: https://github.com/nedbat/coveragepy/issues/578, but we could not use this in https://github.com/aconrad/pycobertura (see also discussion here: https://github.com/aconrad/pycobertura/pull/140), as the problems above occurred, also using the `include`-trick mentioned here: https://github.com/nedbat/coveragepy/issues/578#issuecomment-413881957.
Unfortunately I am not sure how to debug this, but I just see an inconsistency between what is written to the console and what is written to the `coverage.xml` file.

**Comment by nedbat** [comment]
I believe pytest-cov sets the `source` setting, which is why you are getting that warning about include being ignored.  Do you need to use the pytest plugin?

**Comment by gro1m** [comment]
Hi @nedbat 
Thank you very much.
Indeed that was the problem, removing `pytest-cov` and then basically going from:
```
pytest --cov=pycobertura --cov-report=xml --cov-report=term-missing --cov-config=.coveragerc
```

to 

```
coverage run -m pytest
coverage report -m
coverage xml
```

resolved the problem.

So I guess the issue is more with `pytest-cov` than with `coverage` library.

**Comment by gro1m** [comment]
I will open a ticket over at `pytest-cov` and close this issue.
