### ISSUE TITLE
Data files not getting created from tox on Github CI

### ISSUE THREAD

**Issue by demberto** [coveragepy/coveragepy#1360]
Please see [this](https://stackoverflow.com/q/71901290) question.

coverage.py - 6.3.2
Python - 3.10.0

I tried using the tox's `changedir` option (instead of `setenv`) also but it doesn't work either.

The `list -al` command below tox shows no `.coverage` file.

**Comment by nedbat** [comment]
Isn't the problem that your .coverage.* files are in a .tox/coverage subdirectory, but you are asking GitHub actions to upload those files from the current directory?

**Comment by demberto** [comment]
Nope, they get created in the current directory i.e. the correct place **locally** but not on Github Actions.

**Comment by demberto** [comment]
Nope, they get created in the current directory i.e. the correct place **locally** but not on Github Actions.

**Comment by nedbat** [comment]
Try defining COVERAGE_DEBUG=dataio in your environment. It will log messages about what data files it is reading and writing.  Maybe that will clear things up.

**Comment by demberto** [comment]
I can't reproduce this issue anymore, closing
