### ISSUE TITLE
Show / hide fully covered files in HTML report

### ISSUE THREAD

**Issue by knyghty** [coveragepy/coveragepy#1384]
**Is your feature request related to a problem? Please describe.**
Usually when I'm reading the HTML report I only really care about files without full coverage. So it would be nice to be able to toggle whether fully covered files are visible in the report.

**Describe the solution you'd like**
I think a checkbox near the filter input could work, so you can toggle showing covered files on/off. Presumably the JS would be relatively simple. It would be nice if the state of the toggle could be remembered, perhaps in local storage.

**Describe alternatives you've considered**
Of course I could generate the report to only show files that are not fully covered in the first place, but I think this is more flexible. Often I want to see the whole file list so I can check files aren't missing (though finding these can be tricky, admittedly). I can also already sort by the covered column, which is probably enough, but there is I think something to be gained by watching the files go away when adding coverage, and still being able to see things in directory tree order is a bit more useful.

**Comment by nedbat** [comment]
I agree with you, this would be useful.  Maybe someone would like to contribute it?

**Comment by nedbat** [comment]
This is now implemented in commit a507c3aa8c3d64ff65ee4f4e806ec4e49dfcca69, though it's not yet merged to master, and will be a different commit when it is.

**Comment by nedbat** [comment]
The commit on master is 3d47c9fe947a75f9cf11675b375635246117eb18.

**Comment by nedbat** [comment]
This is now released as part of [coverage 7.5.0](https://pypi.org/project/coverage/7.5.0).
