### ISSUE TITLE
ModuleNotFoundError: No module named 'tomllib'

### ISSUE THREAD

**Issue by LostInDarkMath** [coveragepy/coveragepy#1390]
**Describe the bug**
When I run tests in Travis CI against `Python3.11-dev` I get the following error:
```
$ coverage run --branch pedantic/tests/tests_main.py

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.11-dev/bin/coverage", line 5, in <module>

    from coverage.cmdline import main

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/travis/virtualenv/python3.11-dev/lib/python3.11/site-packages/coverage/__init__.py", line 15, in <module>

    from coverage.control import Coverage, process_startup

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/travis/virtualenv/python3.11-dev/lib/python3.11/site-packages/coverage/control.py", line 20, in <module>

    from coverage.collector import Collector, CTracer

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/travis/virtualenv/python3.11-dev/lib/python3.11/site-packages/coverage/collector.py", line 10, in <module>

    from coverage.config import CoverageConfig

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/travis/virtualenv/python3.11-dev/lib/python3.11/site-packages/coverage/config.py", line 16, in <module>

    from coverage.tomlconfig import TomlConfigParser, TomlDecodeError

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/travis/virtualenv/python3.11-dev/lib/python3.11/site-packages/coverage/tomlconfig.py", line 16, in <module>

    import tomllib      # pylint: disable=import-error

    ^^^^^^^^^^^^^^

ModuleNotFoundError: No module named 'tomllib'
```

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't link to a failing CI job. Answer the questions below:
1. What version of Python are you using? `Python 3.11.0a3+`
1. What version of coverage.py shows the problem? `6.4`
1. What code shows the problem? Does not matter.
1. What commands did you run? `coverage run --branch pedantic/tests/tests_main.py`

**Expected behavior**
Run tests with coverage.

**Additional context**
Nothing.

**Comment by nedbat** [comment]
Hmm, we switched to use tomllib since it's in 3.11, but we check for version >= 3.11, and tomllib was added in 3.11.0a7.  You are running 3.11.0a3+.  Can you update to a more recent 3.11?  3.11.0b2 is now out.

**Comment by LostInDarkMath** [comment]
Thank you for your fast reply! Unfortunately, this in the hands of Travis CI. So I cannot do anything and I'll wait for the newer version at Travis.

**Comment by nedbat** [comment]
I fixed the check for tomllib to be more precise in commit 3a23d8ace3a38dc51ca6336834da03e5d15d8e4d.  If you install coverage from GitHub, it should work for you.

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.4.1](https://pypi.org/project/coverage/6.4.1).

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.4.1](https://pypi.org/project/coverage/6.4.1).

**Comment by hugovk** [comment]
> Unfortunately, this in the hands of Travis CI. So I cannot do anything and I'll wait for the newer version at Travis.

I've asked Travis CI to update their 6-month-old `3.11-dev` development branch:

https://travis-ci.community/t/update-python-3-11-dev/13039

**Comment by hugovk** [comment]
And Travis CI have now updated `3.11-dev` and it now points to:

```
3.11.0b3+ (heads/3.11:fae93ab, Jun  3 2022, 16:03:01) [GCC 9.3.0]
```

:tada:

https://travis-ci.community/t/update-python-3-11-dev/13039/2?u=hugovk

**Comment by LostInDarkMath** [comment]
Thank you very much @hugovk!
