### ISSUE TITLE
Add "also_exclude_lines" configuration option

### ISSUE THREAD

**Issue by ikonst** [coveragepy/coveragepy#1391]
When overriding `exclude_lines` e.g. to exclude `pytest.fail` or `...`, we often include the existing `DEFAULT_EXCLUDE` pattern (currently `\#\s*(pragma|PRAGMA)[:\s]?\s*(no|NO)\s*(cover|COVER)`) to maintain the effect of existing "pragma: no cover"s.

This is cumbersome (the regex is large) and doesn't capture the intention, i.e. I have to explain to my team mates what this regex is and where it came from.

Introducing an `also_exclude_lines` configuration option (alternative name: "additional_exclude_patterns", which might do better to convey that those are regex patterns), that would be appended to the default list, could address that.

**Comment by nedbat** [comment]
I like this idea, but I'm not sure when I'll be able to get to it.  And I'm not sure what a good name would be.  The choices all seem a bit clunky.

**Comment by ikonst** [comment]
Maybe following the example of flake8's [extend_ignore](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-extend-ignore)?

**Comment by nedbat** [comment]
This is implemented as `exclude_also` in commit 2a0e7bc1.
