### ISSUE TITLE
coverage report -m reports "No source for code:"

### ISSUE THREAD

**Issue by joaompinto** [coveragepy/coveragepy#1393]
**Describe the bug**
While trying to produce the coverage report for a package the following error is produced:
No source for code: '/home/janito/dinterpol/Expression: "a["b"]"'.

**To Reproduce**
```sh
git clone git@github.com:joaompinto/dinterpol.git
cd dinterpol
pip install coverage
coverage run -m pytest
coverage report -m
```

1. What version of Python are you using?
3.8.10

2. -- sys -------------------------------------------------------
               coverage_version: 6.4.1
                coverage_module: /home/janito/.local/lib/python3.8/site-packages/coverage/__init__.py
                         tracer: -none-
                        CTracer: available
           plugins.file_tracers: -none-
            plugins.configurers: -none-
      plugins.context_switchers: -none-
              configs_attempted: .coveragerc
                                 setup.cfg
                                 tox.ini
                                 pyproject.toml
                   configs_read: /tmp/dinterpol/setup.cfg
                                 /tmp/dinterpol/tox.ini
                    config_file: None
                config_contents: -none-
                      data_file: -none-
                         python: 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
                       platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29
                 implementation: CPython
                     executable: /usr/bin/python3
                   def_encoding: utf-8
                    fs_encoding: utf-8
                            pid: 3232
                            cwd: /tmp/dinterpol
                           path: /home/janito/.local/bin
                                 /usr/lib/python38.zip
                                 /usr/lib/python3.8
                                 /usr/lib/python3.8/lib-dynload
                                 /home/janito/.local/lib/python3.8/site-packages
                                 /usr/local/lib/python3.8/dist-packages
                                 /usr/lib/python3/dist-packages
                    environment: HOME = /home/janito
                   command_line: /home/janito/.local/bin/coverage debug sys
                sqlite3_version: 2.6.0
         sqlite3_sqlite_version: 3.31.1
             sqlite3_temp_store: 0
        sqlite3_compile_options: COMPILER=gcc-9.3.0, ENABLE_COLUMN_METADATA, ENABLE_DBSTAT_VTAB,
                                 ENABLE_FTS3, ENABLE_FTS3_PARENTHESIS, ENABLE_FTS3_TOKENIZER, ENABLE_FTS4,
                                 ENABLE_FTS5, ENABLE_JSON1, ENABLE_LOAD_EXTENSION, ENABLE_PREUPDATE_HOOK,
                                 ENABLE_RTREE, ENABLE_SESSION, ENABLE_STMTVTAB, ENABLE_UNLOCK_NOTIFY,
                                 ENABLE_UPDATE_DELETE_LIMIT, HAVE_ISNAN, LIKE_DOESNT_MATCH_BLOBS,
                                 MAX_SCHEMA_RETRY=25, MAX_VARIABLE_NUMBER=250000, OMIT_LOOKASIDE,
                                 SECURE_DELETE, SOUNDEX, TEMP_STORE=1, THREADSAFE=1, USE_URI

**Expected behavior**
A report being generated.

**Comment by nedbat** [comment]
You haven't provided a way to reproduce the problem.  To get some more data, can you run with `COVERAGE_DEBUG=trace` in your environment variables?  It will write data to stderr that shows the tracing decisions being made.

Are you running some unusual packages? It looks like you have something like `Expression: "a["b"]"` which has code being executed. What does that?

BTW: you can probably just simply work around this by using the `coverage report --ignore-errors` option.

**Comment by joaompinto** [comment]
Hi, I presume you missed the "To Reproduce" section :) those commands should result in the error.
In short you can test with the "https://github.com/joaompinto/dinterpol" library.

Yes, I am using the -i for workaround but would be nice to fix the bug :)

Thanks

**Comment by nedbat** [comment]
Looks like "enclosed" is being used in an unusual way. I even installed it from GitHub:
```
ImportError while importing test module '/private/tmp/bug1393/dinterpol/dinterpol/test_template.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/pyenv/pyenv/versions/3.8.13/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
dinterpol/__init__.py:1: in <module>
    from .template import Template
dinterpol/template.py:1: in <module>
    from enclosed import Parser, TokenType
E   ImportError: cannot import name 'TokenType' from 'enclosed' (/usr/local/virtualenvs/tmp-5545f1cbf614fba/lib/python3.8/site-packages/enclosed/__init__.py)
```

**Comment by nedbat** [comment]
I fixed that with: 
```
diff --git a/dinterpol/template.py b/dinterpol/template.py
index 2d6f073..a60b71d 100644
--- a/dinterpol/template.py
+++ b/dinterpol/template.py
@@ -1,4 +1,4 @@
-from enclosed import Parser, TokenType
+from enclosed.parser import Parser, TokenType
 from .attr2key import attr2key
```
I would recommend changing these lines:
```
diff --git a/dinterpol/template.py b/dinterpol/template.py
index 2d6f073..ed2dfcf 100644
--- a/dinterpol/template.py
+++ b/dinterpol/template.py
@@ -64,7 +64,7 @@ def f_string_compile(self, tokens):
             if self.attribute_convert:
                 token_text = attr2key(token_text)
             code = compile(
-                token_text, filename='Expression: "%s"' % token_text, mode="eval"
+                token_text, filename='<dinterpol expression: "%s">' % token_text, mode="eval"
             )
             return code
         f_string = ""
@@ -79,7 +79,7 @@ def f_string_compile(self, tokens):
                 token_text = attr2key(token_text)

                 f_string += "f'{%s}'" % token_text
-        code = compile(f_string, filename='Expression: "%s"' % token_text, mode="eval")
+        code = compile(f_string, filename='<dinterpol expression: "%s">' % token_text, mode="eval")
         return code

     def render(self, mapping):
```
Coverage.py assumes that "file names" starting with an angle bracket are synthetic and reading them should not be attempted.  I'm not sure what other way I can change its behavior.

**Comment by joaompinto** [comment]
Will do. Thanks for the help.
