### ISSUE TITLE
On 3.11.0a7, when coverage is used, error message for "maximum recursion depth exceeded in comparison" is misleading (it considers that we are in a comparison)

### ISSUE THREAD

**Issue by SylvainDe** [coveragepy/coveragepy#1396]
**Describe the bug**

When the following code is run:

```
def endlessly_recursive_func(n):
    return endlessly_recursive_func(n - 1)

endlessly_recursive_func(0)
```

the following error is expected:

```
RecursionError: maximum recursion depth exceeded
```

However, when:

- 3.11.0a7 is used

AND

- Coverage is used

Then, the error message is somehow more precise and more wrong:

```
   File "/opt/hostedtoolcache/Python/3.11.0-alpha.7/x64/lib/python3.11/site-packages/coverage/pytracer.py", line 130, in _trace
    if event == 'call':
       ^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded in comparison```
```

**To Reproduce**

From my CI runs, it looks like only 3.11.0-alpha.7 is affected - https://github.com/SylvainDe/DidYouMean-Python/actions/runs/2455223356 (based on a dedicated branch to try to understand the issue).

I've tried to simplify the procedure and now, one can reproduce the issue with the following commands:

```
$ python dummy_code.py
$ python -m coverage run dummy_code.py
```

on the following code

```
$ cat dummy_code.py 
def endlessly_recursive_func(n):
    """Call itself recursively with no end."""
    # http://stackoverflow.com/questions/871887/using-exec-with-recursive-functions
    return endlessly_recursive_func(n - 1)

endlessly_recursive_func(0)
```

Installed version is: coverage-6.4.1.tar.gz .

**Expected behavior**

Error message should not be affected by the usage of coverage.

**Additional context**

In the past, I've opened an issue where an error message was different with/without coverage and it ended up being caused by the fact that trace was used: https://github.com/nedbat/coveragepy/issues/773 . Hence, I've tried the same thing here: https://github.com/SylvainDe/DidYouMean-Python/blob/issue_maxrecurdepthmsg_3.11.0a7withcoverage/dummy_code_with_trace.py . Somehow, this code works fine with and without coverage.

**Comment by nedbat** [comment]
I don't think there's anything coverage.py can do to affect this message.  If you look at the line of Python reported with the error, it is a comparison: `if event == 'call':`.

**Comment by nedbat** [comment]
Also, you are using the Python tracer in this case.  Perhaps you only see it on 3.11.0a7 because only that version is using the Python tracer rather than the C tracer?

**Comment by SylvainDe** [comment]
Thanks for the very quick answer and the additional details. It is probably an issue with the Python tracer then - I'm not aware of this subtlety. I'll investigate a bit more and probably open a Python issue/close this issue.

**Comment by nedbat** [comment]
> It is probably an issue with the Python tracer

The Python tracer is code in coverage.py to support environments that can't run C extensions.  I don't think it's a problem with that code.  The recursion error happens during a comparison, doesn't it?

**Comment by SylvainDe** [comment]
Ho I see, I had misunderstood your remark about the Python version and the tracer. Thanks for the clarification.

It is still weird that the issue is reported as if it was happening during a comparison but this is probably not a coveragepy issue per se. I should aim to make this behavior reproducible with a non-coverage tracer.

(Then, the fact that this wrong value is used to generate a more precise - and more wrong - error message is a side-effect)

**Comment by nedbat** [comment]
But the line *is* a comparison:  `if event == 'call':`    I'm not sure why it's being report on that particular line, but it is a comparison.

**Comment by SylvainDe** [comment]
Agree - this is what I meant but expressed in a very poor way...

**Comment by SylvainDe** [comment]
It probably corresponds to:

- issue https://github.com/python/cpython/issues/92118
- commit https://github.com/python/cpython/commit/e61330b44f22b11a71f5bbcc17e309dd80e3e95f (integrated between v3.11.0a7 and v3.11.0b1 )

I'm not quite sure what went wrong between v3.11.0a6 and v3.11.0a7 but in any case:

- it looks like this is fixed (on all but one very minor version)
- this is nothing for coveragepy to handle
- once again, you've been very helpful - thank you very much
