### ISSUE TITLE
No source for code: '/x/y/z/<not an actual file>'. (couldnt-parse)

### ISSUE THREAD

**Issue by ShaheedHaque** [coveragepy/coveragepy#1408]
**Describe the bug**
When I run the `coverage xml -i` command, I get a number of errors of the form:
```
/usr/local/lib/python3.10/dist-packages/coverage/report.py:87: CoverageWarning: Couldn't parse '/main/srhaque/...not an actual file': No source for code: '/main/srhaque/...not an actual file'. (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")
```
where the path printed (twice) has a valid `dirname(path)`, but the `basename(path)` of has values like `Works id`, `Units`, `Date`, `bankdetail.sort_code`. These names are not the names of any files, but *do* exist in the codebase as strings.

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't link to a failing CI job. Answer the questions below:
1. What version of Python are you using? 3.10
1. What version of coverage.py shows the problem? 6.4.1 The output of `coverage debug sys` is helpful.
```
$ coverage debug sys
-- sys -------------------------------------------------------
               coverage_version: 6.4.1
                coverage_module: /usr/local/lib/python3.10/dist-packages/coverage/__init__.py
                         tracer: -none-
                        CTracer: available
           plugins.file_tracers: -none-
            plugins.configurers: -none-
      plugins.context_switchers: -none-
              configs_attempted: .coveragerc
                   configs_read: /main/srhaque/Innovatieltd/source/.coveragerc
                    config_file: /main/srhaque/Innovatieltd/source/.coveragerc
                config_contents: b'# .coveragerc to control coverage.py\n[run]\nbranch = True\nparallel = True\nomit =\n    /usr/*\n    paiyroll/migrations/*\nconcurrency =\n    thread\n    multiprocessing\n'
                      data_file: -none-
                         python: 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
                       platform: Linux-5.15.0-37-generic-x86_64-with-glibc2.35
                 implementation: CPython
                     executable: /usr/bin/python3
                   def_encoding: utf-8
                    fs_encoding: utf-8
                            pid: 3840835
                            cwd: /main/srhaque/Innovatieltd/source
                           path: /usr/local/bin
                                 /usr/lib/python310.zip
                                 /usr/lib/python3.10
                                 /usr/lib/python3.10/lib-dynload
                                 /usr/local/lib/python3.10/dist-packages
                                 /usr/lib/python3/dist-packages
                    environment: HOME = /main/srhaque
                   command_line: /usr/local/bin/coverage debug sys
                sqlite3_version: 2.6.0
         sqlite3_sqlite_version: 3.37.2
             sqlite3_temp_store: 0
        sqlite3_compile_options: ATOMIC_INTRINSICS=1, COMPILER=gcc-11.2.0, DEFAULT_AUTOVACUUM,
                                 DEFAULT_CACHE_SIZE=-2000, DEFAULT_FILE_FORMAT=4,
                                 DEFAULT_JOURNAL_SIZE_LIMIT=-1, DEFAULT_MMAP_SIZE=0, DEFAULT_PAGE_SIZE=4096,
                                 DEFAULT_PCACHE_INITSZ=20, DEFAULT_RECURSIVE_TRIGGERS,
                                 DEFAULT_SECTOR_SIZE=4096, DEFAULT_SYNCHRONOUS=2,
                                 DEFAULT_WAL_AUTOCHECKPOINT=1000, DEFAULT_WAL_SYNCHRONOUS=2,
                                 DEFAULT_WORKER_THREADS=0, ENABLE_COLUMN_METADATA, ENABLE_DBSTAT_VTAB,
                                 ENABLE_FTS3, ENABLE_FTS3_PARENTHESIS, ENABLE_FTS3_TOKENIZER, ENABLE_FTS4,
                                 ENABLE_FTS5, ENABLE_JSON1, ENABLE_LOAD_EXTENSION, ENABLE_MATH_FUNCTIONS,
                                 ENABLE_PREUPDATE_HOOK, ENABLE_RTREE, ENABLE_SESSION, ENABLE_STMTVTAB,
                                 ENABLE_UNLOCK_NOTIFY, ENABLE_UPDATE_DELETE_LIMIT, HAVE_ISNAN,
                                 LIKE_DOESNT_MATCH_BLOBS, MALLOC_SOFT_LIMIT=1024, MAX_ATTACHED=10,
                                 MAX_COLUMN=2000, MAX_COMPOUND_SELECT=500, MAX_DEFAULT_PAGE_SIZE=32768,
                                 MAX_EXPR_DEPTH=1000, MAX_FUNCTION_ARG=127, MAX_LENGTH=1000000000,
                                 MAX_LIKE_PATTERN_LENGTH=50000, MAX_MMAP_SIZE=0x7fff0000,
                                 MAX_PAGE_COUNT=1073741823, MAX_PAGE_SIZE=65536, MAX_SCHEMA_RETRY=25,
                                 MAX_SQL_LENGTH=1000000000, MAX_TRIGGER_DEPTH=1000,
                                 MAX_VARIABLE_NUMBER=250000, MAX_VDBE_OP=250000000, MAX_WORKER_THREADS=8,
                                 MUTEX_PTHREADS, OMIT_LOOKASIDE, SECURE_DELETE, SOUNDEX, SYSTEM_MALLOC,
                                 TEMP_STORE=1, THREADSAFE=1, USE_URI
```
1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.
1. What code shows the problem?  Give us a specific commit of a specific repo that we can check out. If you've already worked around the problem, please provide a commit before that fix.
1. What commands did you run?
    - Coverage is run programmantically via the API on a set of code including Django, Celery, subprocesses.
    - `coverage combine -q`
    - `coverage xml -i`
**Expected behavior**
The XML file should be produced without needing the "-i" option.

**Additional context**
- The overall coverage result seems to be missing some covered lines of some files, but is generally plausible.
- The coverage.xml file contains none of the strings I mentioned, suggesting this is related to file scanning.
- I tried debugging, and can see the bad entries being read from the database at https://github.com/nedbat/coveragepy/blob/2cf1981a06ac597aacf826b56db0d50a2ee0ea0b/coverage/sqldata.py#L295
- But I have not been able to determine where (and thus why) the database entry is created.
   - I could probably track the issue down if I could be helped on this point.

**Comment by nedbat** [comment]
Hi this seems a continuation of #1318.  Can you give me a way to reproduce the problem? 

Typically, phantom file names like this are due to dynamically compiling code.  The `compile()` builtin takes a "file name", but when there is no actual file, people create a fake one based on something about the origin of the code.  Perhaps your project is also doing this?

Coverage will ignore a file name if it starts with an angle bracket: `<`.  This is a convention used by many people when dynamically compiling code.

As an example, see #1393.

**Comment by ShaheedHaque** [comment]
I had completely forgotten filing #1318! At any rate, the big difference from then is that I'm now able to get somewhat plausible coverage numbers having hacked around the Celery fork-vs-spawn issue (see #689).

You are indeed correct, I do use `compile()`, and the filename is exactly the strings I cited. I added the "<" prefix you suggested and the errors are gone!
