### ISSUE TITLE
Code Coverage percentage for each sub-directory

### ISSUE THREAD

**Issue by tanmayzengit** [coveragepy/coveragepy#1424]
**Is your feature request related to a problem? Please describe.**
I am currently trying to generate a code coverage report for a monolith which gives me the percentage at each file level. What i want is to get the coverage percentage at each directory and sub-directory level.

**Describe the solution you'd like**
```
Directory A-------90%
        |
        |Sub-directory A-----------------> 95%
        |                 |File A1--------------------------->90%
                          |File A2--------------------------->100%
        |Sub-directory B-----------------> 85%
```
I would want something like i have mentioned above if that helps in understanding. Currently i get only the top level percentage and coverage for each file i.e Directory A and File A1 , File A2 if we take the above example with the entire path.

**Describe alternatives you've considered**
For doing the above i am currently using the --include flag to do for some important directories but this method is not feasible for all the directories and sub-directories.

**Additional context**
If there a quick fix to the above will appreciate if someone can let me know or if you can let me know how do i do that using coverage.py will really appreciate. 
p.s Coverage version--->4.0a6

**Comment by nedbat** [comment]
Coverage.py doesn't offer per-directory totals, but you can use the JSON report to analyze the collected data. An example is at [Coverage goals](https://nedbatchelder.com/blog/202111/coverage_goals.html) where I show a simple program to enforce goals on subsets of the code.

BTW, version 4.0a6? Why? It's an alpha version from seven years ago!

**Comment by tanmayzengit** [comment]
This was being a target for an intermediate goal for generating a code coverage for each pull request in github. Looks like there is no easy way to make it intuitively arrange the data in folders. Btw would appreciate any suggestions on how to report coverage metrics on every pr. 
Regarding version 4.0a6 planning to move away from it. There could be interlinked dependencies that would make the entire house of cards fall. So just cautious.
