### ISSUE TITLE
coverage report error

### ISSUE THREAD

**Issue by SmartPycg** [coveragepy/coveragepy#1435]
Hi,I am interested in your project and want to count your test code's coverage but I failed to generate coverage report.

![image](https://user-images.githubusercontent.com/105635378/184321727-ccb72035-6711-4fa2-a348-86958f4d6bf9.png)

I used the following commands in python:3.7 docker：

```
python setup.py install
pip install -r requirements/dev.txt 
pip install -r requirements/docs.txt
pip install -r requirements/tests.txt
pip install -r requirements/typing.txt
coverage run -m pytest tests
coverage report
```

Can you help me？

**Comment by nedbat** [comment]
I can't help with this error unless you provide full details of how to reproduce it.  What project are you running? You've shown `python setup.py install`, but I don't know what repo/project that is being run in.

**Comment by nedbat** [comment]
Feel free to re-open this when you come back to it.
