### ISSUE TITLE
Continuous fuzzing by way of OSS-Fuzz

### ISSUE THREAD

**Issue by DavidKorczynski** [coveragepy/coveragepy#1436]
**Is your feature request related to a problem? Please describe.**

My feature request is for integrating continuous fuzzing by way of OSS-Fuzz? Fuzzing is a way to automate test-case generation and can be used to find unexpected exceptions in Python.

I did an initial integration here: https://github.com/google/oss-fuzz/pull/8161 I did an initial integration into OSS-Fuzz.

The current fuzzer is targetting the `parse_source` function for the `PythonParser` class.

**Describe the solution you'd like**

The fuzzing will run continuously and emails will be sent out with links to reports when a bug is found. As such, if you would like to integrate, the only thing I need is a list of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats. Notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

Down the line we can move fuzzers from OSS-Fuzz and upstream into the coveragepy repository.

**Comment by nedbat** [comment]
(oops, I commented on the oss-fuzz PR).   You can use my email address for reports: ned@nedbatchelder.com.  I'm also wondering how best to connect to this from the coverage.py repo?

**Comment by DavidKorczynski** [comment]
Thanks @nedbat I added it in the OSS-Fuzz repo now!

I think the best way to connect the coveragepy repository with OSS-Fuzz would be to place the fuzzer source code somewhere e.g. `tests/fuzz` and then have the oss-fuzz `build.sh` script build the fuzzers using the source code from here.

The fuzzers are written to use Atheris: https://github.com/google/atheris

In the OSS-Fuzz repository we have to compile the fuzzers using `pyinstaller` and the reason being OSS-Fuzz will run the fuzzers continuously in an environment that is different than the one where the fuzzers gets build. However, once you have `atheris` installed (which can be done by way of `pip`) then you can run the fuzzers locally as well. By "fuzzer" I mean this code: https://github.com/google/oss-fuzz/pull/8161/files#diff-c15265aa2ea458493da915659a527d7a818f62c4709c498d81662226d1953328 Depending on what you prefer, we could do various things too, e.g. integrate it into the testing suite or the CI (OSS-Fuzz provides CI support as well).

I suggest the first thing we do is merge https://github.com/google/oss-fuzz/pull/8161 then you will get experience with OSS-Fuzz when emails are sent out (assuming some issue will be found), then follow up with integrating it into the codebase here.

**Comment by nedbat** [comment]
I've fixed the [first bug found](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50381) in https://github.com/nedbat/coveragepy/commit/3703bae58b53efec3314bc07b9de157049ad8b70.  

I'm happy to let Google continue running the fuzzer, I don't need to do it locally I don't think.

**Comment by DavidKorczynski** [comment]
> I've fixed the [first bug found](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=50381) in [3703bae](https://github.com/nedbat/coveragepy/commit/3703bae58b53efec3314bc07b9de157049ad8b70).
> 
> I'm happy to let Google continue running the fuzzer, I don't need to do it locally I don't think.

Wonderful @nedbat ! Looking forward to providing more fuzzers then!
