### ISSUE TITLE
Set changed size during iteration

### ISSUE THREAD

**Issue by agroszer** [coveragepy/coveragepy#1439]
Running a pretty sophisticated jenkins job to check our codebase.

```
Set changed size during iteration

  File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/var/lib/jenkins/workspace/app-pipeline/ve3.9/lib/python3.9/site-packages/coverage/collector.py", line 392, in switch_context
    self.flush_data()
  File "/var/lib/jenkins/workspace/app-pipeline/ve3.9/lib/python3.9/site-packages/coverage/collector.py", line 460, in flush_data
    for packed in packeds:
```

**To Reproduce**
python 3.9.13 on ubuntu, coverage==6.4.2

Repro is tough, of course it fails only on jenkins with that job. Sometimes in a row of 4-5 runs. Most of the time all is fine.

Anyone seen this before? Any ideas?

**Comment by nedbat** [comment]
Can you tell us any more about your situation?  Are you using coverage commands, or the pytest-cov plugin, or your own Python calling the coverage.py API?  Is this a multi-threaded program?

**Comment by agroszer** [comment]
Yes, this is a multi-threaded situation, we're running a paste webserver in one thread, the tests are running against that on the main thread. The test suite is run by `zope.testrunner`, we basically use `bin/coverage run -p bin/test --all -t selected_tests`.

Investigating further... Wanted to check whether anyone has ran into this.

**Comment by agroszer** [comment]
After some more investigation (did not get fully to the bottom) looks like our webserver does something in `paste.httpserver.SecureHTTPServer` while `flush_data` is iterating over `data` in the main thread.
It's a huge pain to figure what's going on in the webserver thread so we opted to omit that piece of code (and actually the complete test support code) from being covered.
