### ISSUE TITLE
pip coverage rate cannot be collected

### ISSUE THREAD

**Issue by alittlesir** [coveragepy/coveragepy#1441]
**Describe the bug**
i code some self test case about `pip`. and i want to cout coverage of pip, but  maybe it is some wrong

**To Reproduce**
1. cd /usr/lib/python3.9/site-packages/pip
2. coverage run `__main__`.py install numpy

**Expected behavior**
cout coverage

**Additional context**
```python
[root@localhost pip]# coverage run __main__.py install numpy
WARNING: Running pip install with root privileges is generally not a good idea. Try `python3 -m pip install --user` instead.
Looking in indexes: http://mirrors.tools.douban.com/pypi/simple
Collecting numpy
  Downloading http://mirrors.tools.douban.com/pypi/packages/f8/ea/ff38168d6565a8549f819699cac4d89bbc38fc5b27fb94f8e92bcd713348/numpy-1.23.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
     |████████████████████████████████| 17.1 MB 6.2 MB/s            
Installing collected packages: numpy
Successfully installed numpy-1.23.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
/usr/local/lib64/python3.9/site-packages/coverage/control.py:794: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")
```

**Comment by nedbat** [comment]
If I understand correctly, you are trying to measure the code coverage of the pip test suite itself?  How are its tests usually run? Do they not use coverage already in their configurations?

**Comment by alittlesir** [comment]
yes, you are right, but if i input `pip install numpy`, and i only want to the command's coverage. how do i use?

as we know, if i code test.py, and i measure the file of coverage, i can input `coverage run test.py`, so i input `coverage run __main__.py install numpy`, why does it output `No data was collected.", slug="no-data-collected`

**Comment by nedbat** [comment]
It will depend on how you have configured coverage measurement in your .coveragerc file.  Try `coverage run -m pip install numpy` perhaps?

**Comment by alittlesir** [comment]
it still is not ok, maybe it is some wrong with `pip`

**Comment by nedbat** [comment]
I still want to understand what you are trying to do: are you making a change to pip and want to run its test suite? Have you read this?  https://github.com/pypa/pip/blob/main/docs/html/development/getting-started.rst#running-tests

**Comment by alittlesir** [comment]
Thank you for your reply. maybe i know how to measure with `coverage`

yes, i read it, but it is a bug with the test suite of pip,https://github.com/pypa/pip/issues/11415

and the pip measure  coverage with `pytest-cov` in its test suite,  and i found it is some wrong with `pytest-cov`, https://github.com/pytest-dev/pytest-cov/issues/552. I don't know if it's a bug.

**Comment by nedbat** [comment]
You've linked to pypa/pip#11415, which clearly shows coverage data being collected for pip, so I'm going to close this issue.  It sounds like you need to write some tests for the pip test suite.
