### ISSUE TITLE
Doesn't seem to work in Pyodide

### ISSUE THREAD

**Issue by hoodmane** [coveragepy/coveragepy#1450]
**Describe the bug**
Doesn't work as expected in Pyodide. I was hoping one of you could look into it.

**To Reproduce**
1. Go to https://pyodide.org/en/latest/console.html
2. Open browser console
3. Paste the following code into it:
```js
await pyodide.loadPackage("coverage");
pyodide.runPython(`
from coverage import Coverage
from pyodide.code import eval_code

cov = Coverage()
cov.start()
eval_code("1+1")
cov.stop()
cov.save()
`);
```

**Expected behavior**
It should collect the coverage. Instead, it seems not to have done so and it prints `CoverageWarning: No data was collected.`
If I run the same code in native Python it collects coverage data.  Building with `WHAT_LOG` and/or `TRACE_LOG` prints a bunch of stuff confirming that the tracer is running.

If you have any suggestions for what might be going on I'd appreciate it. (Maybe there are some test cases that tease this apart a bit further.)

**Comment by nedbat** [comment]
Help me learn how to use pyodide :)  When I paste your code into the console, I have to `import pyodide` first, but then I'm told, `AttributeError: module 'pyodide' has no attribute 'runPython'`.

You say:
> If I run the same code in native Python it collects coverage data. Building with WHAT_LOG and/or TRACE_LOG prints a bunch of stuff confirming that the tracer is running.

Those are C defines, are those used in the pyodide environment?

**Comment by dbritto-dev** [comment]
Hey folks I would like to help :).

**Comment by dbritto-dev** [comment]
I got some news doesn't work on codesandbox

**Comment by dbritto-dev** [comment]
@hoodmane looks like the only way to **analyse** something using **The Coverage class** is by calling `.analysis()` method and that currently only accept a file/module. To make it works we need to create a file and then pass the filename to `.analysis()` method. 

Here's the example:

```js
await pyodide.loadPackage("coverage");
await pyodide.runPythonAsync(`
from coverage import Coverage

def write_test(filename, content):
    with open(filename, 'w') as f:
        f.write(content)

cov = Coverage()
cov.start()

write_test("testing.py", "1+1")

cov.analysis("testing.py")
cov.stop()
cov.save()
cov.report()
`);
```

> **Note**: apart from that the first time for some reason returns the warning in the console but the second time works without any warnings/errors.

Maybe I'm wrong. What you think @nedbat ?

**Comment by hoodmane** [comment]
Ah if I've just been using it wrong that's great. What confuses me is I don't get the same warning when I use it in native Python.

By the way I have two use cases for this:

Currently we are using coverage in the Pyodide test suite but we are only using the native version of coverage not the wasm version so lines of code that are covered in wasm tests but not native tests don't get counted. I would like to fix this.

Second, it'd be great for people using pytest to test their packages with Pyodide to be able to get code coverage info in the same way as with native Python. I think last I tested this isn't working quite right. I'll probably be back to ask for help on this once I've looked into it a bit more.

**Comment by dbritto-dev** [comment]
@hoodmane tag me if you need some help. I'll be available to play with pyodide and coverage.

**Comment by hoodmane** [comment]
Thanks for your help @dbritto-dev @nedbat much appreciated.

@dbritto-dev I tried your example and it raised an error.
```
coverage.exceptions.NoDataError: No data to report.
```
Did it behave differently when you tried it?
<details>
<summary>Screenshot</summary>

![Screenshot from 2022-09-20 20-55-17](https://user-images.githubusercontent.com/8739626/191410897-d8ae25f7-2f9d-4344-9788-6d4b8a471b88.png)

</details>

**Comment by dbritto-dev** [comment]
@hoodmane did you tried using my version? I haven't tried with pathlib package

**Comment by hoodmane** [comment]
> Help me learn how to use pyodide :) When I paste your code into the console, I have to import pyodide first, but then I'm told, AttributeError: module 'pyodide' has no attribute 'runPython'.

Right, you have to paste the code into the browser console, not into the "Pyodide terminal emulator" you see on screen. (I set up my code examples this way because the browser console is a much better console than our "terminal emulator".)

> Those are C defines, are those used in the pyodide environment?

I mean I defined them by compiling with `-DWHAT_LOG -DTRACE_LOG`.

**Comment by hoodmane** [comment]
Yeah I tried your version and the error is the same. Both write the same file, so it shouldn't make a difference:

<details>
<summary>Screenshot</summary>



![Screenshot from 2022-09-20 21-01-03](https://user-images.githubusercontent.com/8739626/191411627-0c57f974-c5a3-4d4d-9d90-cad86ee5825a.png)


</details>

**Comment by dbritto-dev** [comment]
> Yeah I tried your version and the error is the same. Both write the same file, so it shouldn't make a difference:
> 
> <details>
> <summary>Screenshot</summary>
> 
> 
> 
> ![Screenshot from 2022-09-20 21-01-03](https://user-images.githubusercontent.com/8739626/191411627-0c57f974-c5a3-4d4d-9d90-cad86ee5825a.png)
> 
> 
> </details>

@hoodmane interesting. In my case works without any issues. I agree with you, with pathlib package should works as well.

**Comment by hoodmane** [comment]
Are you using https://pyodide.org/en/latest/console.html? Could you post a similar screenshot showing what happens when you run the code? It is surprising that we don't get the same results.

**Comment by dbritto-dev** [comment]
> Are you using https://pyodide.org/en/latest/console.html? Could you post a similar screenshot showing what happens when you run the code? It is surprising that we don't get the same results.

@hoodmane I'll do it tomorrow as soon as possible

**Comment by dbritto-dev** [comment]
@hoodmane I did some research and I found this: 

This version doesn't work

```js
await pyodide.loadPackage("coverage");
await pyodide.runPythonAsync(`
from pathlib import Path
from coverage import Coverage

cov = Coverage()
cov.erase()
cov.start()

Path("test_demo.py").write_text("1+1")

cov.analysis("test_demo.py")
cov.stop()
cov.save()
cov.report()
`);
```

This version works

```js
await pyodide.loadPackage("coverage");
await pyodide.runPythonAsync(`
from pathlib import Path
from coverage import Coverage

cov = Coverage(source=".")
cov.erase()
cov.start()

Path("test_demo.py").write_text("1+1")

cov.analysis("test_demo.py")
cov.stop()
cov.save()
cov.report()
`);
```

> **Note**: the only difference is that the second one specify source of tests as the current directory (`source="."`). My guest about the warnings is that those warnings are OK since we don't have any tests.

![Screenshot from 2022-09-21 07-53-51](https://user-images.githubusercontent.com/1697714/191509084-9c7b146e-740c-444d-8750-1634ae387bca.png)

Alternative version

```js
await pyodide.loadPackage("coverage");
await pyodide.runPythonAsync(`
from pathlib import Path
from coverage import Coverage

Path("test_demo.py").write_text("1+1")

cov = Coverage(source=".")
cov.erase()
cov.start()
cov.stop()
cov.save()
cov.report()
`);
```

**Comment by dbritto-dev** [comment]
@nedbat @hoodmane I got some news I've been doing some experiments following the pattern that coverage is using in they're tests ->

```js
await pyodide.loadPackage("coverage");
await pyodide.runPythonAsync(`
import sys
import importlib
import pathlib
from coverage import Coverage

pathlib.Path("test_demo.py").write_text("""
def fun1(x):
    if x == 1:
        print("one")
    else:
        print("not one")
    print("done")           # pragma: nocover

def fun2(x):
    print("x")
""")

cov = Coverage(source=".", branch=True)
cov.erase()
cov.start()

spec = importlib.util.spec_from_file_location("test_demo", "test_demo.py")
mod = importlib.util.module_from_spec(spec)
sys.modules["test_demo"] = mod
spec.loader.exec_module(mod)

cov.stop()
cov.report(show_missing=True)
`);
```

**Comment by dbritto-dev** [comment]
@hoodmane let me know if that works for you

**Comment by hoodmane** [comment]
Yup works for me. Thanks!
