### ISSUE TITLE
Config via pyproject.toml should be builtin and not require coverage[toml]

### ISSUE THREAD

**Issue by cclauss** [coveragepy/coveragepy#1451]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I want to configure tools using `pyproject.toml` but I have to change how coverage is installed.

The docs currently say:
> If coverage.py is installed with the toml extra (pip install coverage[toml]), it will automatically read from “pyproject.toml”

As more projects consolidate their configuration using [PEP 621](https://peps.python.org/pep-0621) this compatibility should be built into coveragepy and no longer require a special install.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by nedbat** [comment]
On Python3.11, you don't need the extra.  I'm reluctant to add a dependency which isn't needed.  If you know you need toml support in pre-Python3.11, is it a burden to state that? Or, leave off the extra, knowing that you already have tomli installed in your environment.
