### ISSUE TITLE
"No data to report." when using coverage alone

### ISSUE THREAD

**Issue by marcuscop** [coveragepy/coveragepy#1452]
**Describe the bug**
When using coverage without pytest, I cannot generate a report.

**To Reproduce**
1. What version of Python are you using?
Python 3.7.11
2. What version of coverage.py shows the problem? 
coverage=5.5
4. What versions of what packages do you have installed?
pytest = "6.2.5"
pytest-asyncio = "0.19.0"
pytest-cov = "3.0.0"
pytest-xdist = "2.5.0"
coverage = "5.5"
5. What commands did you run?
`pytest --cov-config=.coveragerc myproj/main.py --option1`
gives a report but
`coverage run myproj/main.py --option1`
outputs "No data to report."

**Expected behavior**
A report to be generated.

**Additional context**
Using --debug=trace I can see that myproj/main.py is traced.

**Comment by nedbat** [comment]
I don't understand: `coverage run` won't try to make a report, so I'm not sure how it can output "No data to report."?  Can you provide me with a reproducible case? That is, a repo to clone, and commands to run?

Also, why use coverage==5.5? That's 18 months old.

**Comment by marcuscop** [comment]
Hi, thanks for the reply. I meant coverage report followed by those commands gives that message. Before I go further to make an example, I will try latest version.

**Comment by marcuscop** [comment]
@nedbat My .coveragerc contained this line: 
```
[run]
data_file = ./reports/.coverage
``` 
so it couldn't find the report under that directory when doing a `coverage report`. I removed this line and it works now.
