### ISSUE TITLE
Some multiprocessing processes not covered (but were covered by pytest-cov 3.0.0)

### ISSUE THREAD

**Issue by elParaguayo** [coveragepy/coveragepy#1458]
**Describe the bug**
I am one of the developers of [qtile](https://github.com/qtile/qtile). We have a fairly large test suite that we ran with `pytest-cov`. Since they dropped `multiprocessing` support in 4.0.0, I have followed [their advice](https://pytest-cov.readthedocs.io/en/latest/changelog.html#id1) to use `coverage`. The `.coveragerc` file looks like this:
```
[run]
source = libqtile
concurrency = multiprocessing
parallel = true
sigterm = true

[report]
omit =
    libqtile/interactive/*
    libqtile/scripts/*
    libqtile/ffi_build.py
    test/*
```

I am getting a few discrepancies which I'm struggling to debug but I'm pretty sure they arise from lines that were executed by a subprocess not being covered.

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't link to a failing CI job. 

To be honest, I'm not expecting you to recreate the problem but, if you do, you would need to clone our repo and run the suite and run the following test: `test/widgets/test_openweather.py`). Previously the file `libqtile/widget/open_weather.py` had 91.3% coverage, now it's 40%.

At this stage, though, I'd be happy with some pointers as to how debug this more myself.

Answer the questions below:
1. What version of Python are you using? `3.10`
1. What version of coverage.py shows the problem? The output of `coverage debug sys` is helpful.  `coverage_version: 6.5.0`
1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.
```
appdirs==1.4.4
attrs==22.1.0
bowler==0.9.0
cairocffi==1.4.0
cffi==1.15.1
click==8.1.3
coverage==6.5.0
dbus-next==0.2.3
fissix==21.11.13
iniconfig==1.1.1
moreorless==0.4.0
packaging==21.3
pluggy==1.0.0
py==1.11.0
pycairo==1.21.0
pycparser==2.21
PyGObject==3.42.2
pyparsing==3.0.9
pytest==7.1.3
pywayland==0.4.14
pywlroots==0.15.22
qtile==0.22.2.dev7+gfec84938.d20221001
six==1.16.0
tomli==2.0.1
volatile==2.1.0
xcffib==0.12.1
xkbcommon==0.4
```
1. What code shows the problem?  Give us a specific commit of a specific repo that we can check out. If you've already worked around the problem, please provide a commit before that fix.
My current working on this issue is here: https://github.com/elParaguayo/qtile/tree/pin-pytest-cov
1. What commands did you run?
```
coverage run -m pytest --backend=x11 --backend=wayland -k test_openweather
coverage combine -q
coverage report -m
```

**Expected behavior**
I would expect the coverage to remain unchanged at 91.3%. The [existing coverage](https://coveralls.io/builds/52732848/source?filename=libqtile%2Fwidget%2Fopen_weather.py) shows multiple hits per line but this drops when using coverage.

**Additional context**
We launch subprocesses via a fixture with `multiprocessing.Process`. When the test ends, the fixture cleans up with a `terminate` call to that process which, I understand, should trigger the writing of the coverage data for that process.

**Comment by elParaguayo** [comment]
Been playing some more with this.

Firstly, I know the code in the subprocess is being executed as I can include a print statement and see the output when passing the `-s` flag to pytest. Despite that, the line is not shown as covered by `coverage report -m`.

However, if I explicitly add an extra call to run the uncovered code (we can communicate with the subprocess via a command interface) then the print statement is displayed twice but now the line **is** shown as covered by `coverage`.

It feels ugly and unnecessary to have to trigger the function again and wasn't needed with `pytest-cov` but I just can't work out why this is happening.

**Comment by nedbat** [comment]
Hi, I only just saw that pytest-cov 4.0.0 dropped support for multiprocessing, and they dropped it because it didn't always work.  To be honest, I'm not sure what to suggest to you.  The sigterm support in coverage.py was a problem also, which is why it's an option rather than always enabled.

**Comment by elParaguayo** [comment]
Thanks for the reply. That's fine and makes sense given python-cov's position too.

I'll close this as it doesn't sound like there's necessarily a fix.

I'll also take a look at the python-cov code to see if I can work out what they added as we did get consistent results with that.
