### ISSUE TITLE
I want to read the coverage report programatically , is there any API?

### ISSUE THREAD

**Issue by ishandutta2007** [coveragepy/coveragepy#1469]
**Is your feature request related to a problem? Please describe.**
I want to read coverage data programatically , is there any API?

**Describe the solution you'd like**
Ideally I would like an API but for the time being if someone helps me on how to read the report opening the ".coverage" file that  should suffice.

**Describe alternatives you've considered**
Currently I am running "coverage report -m" via python program and then scraping the output. It is really painful to write logic by scaping data from a cli command.

**Comment by nedbat** [comment]
Use the JSON report: https://coverage.readthedocs.io/en/6.5.0/cmd.html#cmd-json, or the data API: https://coverage.readthedocs.io/en/6.5.0/api_coveragedata.html
