### ISSUE TITLE
coveragepy can only work on CPython or PyPy?

### ISSUE THREAD

**Issue by timfel** [coveragepy/coveragepy#1474]
At the top of the `env.py` file, Jython and IronPython are recognized besides CPython and PyPy. However, line 88 (linked in this issue) assumes that coveragepy runs on either PyPy or CPython - if `CPYTHON` is `False` (as it is on e.g. Jython and IronPython, but also on [GraalPy](https://github.com/oracle/graalpython)), this raises `NameError: name 'PYPYVERSION' is not defined`

https://github.com/nedbat/coveragepy/blob/a3c8683f8e46590c145e16c1aebf7a7766513890/coverage/env.py#L88

**Comment by nedbat** [comment]
The logic on these lines can get convoluted, and maybe I messed this one up.  Are you running into a problem on another platform?

(BTW: how did you create this issue? Usually there's a "needs triage" label on new issues...)

**Comment by timfel** [comment]
> The logic on these lines can get convoluted, and maybe I messed this one up. Are you running into a problem on another platform?

Yes, this line crashes when we run on GraalPy :)

> (BTW: how did you create this issue? Usually there's a "needs triage" label on new issues...)

Hm, I just selected the line in the code view and clicked "Reference in new issue"

**Comment by timfel** [comment]
I guess it could just be `report_absolute_files = ((CPYTHON or (PYPY and PYPYVERSION >= (7, 3, 10))) and PYVERSION >= (3, 9))`

**Comment by nedbat** [comment]
This is fixed in 4668a92c.

**Comment by timfel** [comment]
Thank you!

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.6.0b1](https://pypi.org/project/coverage/6.6.0b1).

**Comment by nedbat** [comment]
This is now released as part of [coverage 7.0.0b1](https://pypi.org/project/coverage/7.0.0b1).
