### ISSUE TITLE
Ability to specify the absolute source path in the source tags of the coverage.xml file generated

### ISSUE THREAD

**Issue by Cephas-Kingori** [coveragepy/coveragepy#1475]
**Is your feature request related to a problem? Please describe.**
When the gitlab pipeline runs in a normal pipeline and generates the coverage.xml file, the following is a sample of the output file generated: 
```
<sources>
	<source>/builds/{project_group}/{project_name}/{source directory1}</source>
        <source>/builds/{project_group}/{project_name}/{source directory2}</source>
</sources>

<packages>
...
</packages>
```
This is good and works well to integrate it with the gitlab code visualization. 
However, in a scenario where  the coverage command is not being run from the /builds path in gitlabci; the coverage visualization does not work.

For Example:
This is a sample output when coverage is run inside a docker in docker container with the project having been copied in the /mnt path.
```
<sources>
    <source>/mnt/{project_name}/{source_folder}</source>
</sources>
<packages>
...
</packages>
```
In such a case, coverage visualization in gitlab will not work.

**Describe the solution you'd like**
During the generation of coverage.xml, it would be good to also be able to specify the absolute path to be placed in the <sources>...</sources> tag

E.g 

`coverage xml --path="/builds/my_project/src"
`
**Describe alternatives you've considered**
I have considered editing the xml file using bash commands and setting it to the one I want

**Comment by nedbat** [comment]
Have you tried using the `[paths]` configuration option with the `coverage combine` command?  https://coverage.readthedocs.io/en/6.5.0/config.html#paths

**Comment by nedbat** [comment]
Feel free to re-open this if you can provide more information.
