### ISSUE TITLE
Automatically ignore lines containing just an ellipsis

### ISSUE THREAD

**Issue by nickeldan** [coveragepy/coveragepy#1476]
It is common practice, when defining a `typing.Protocol`, to put in an ellipsis as a method stub:

```python
class Proto(typing.Protocol):
    def func(self) -> int:
        ...
```

Since the stubs are never actually called, I have to manually put `# pragma: no cover` after each ellipsis.

Would it make sense for coverage to automatically not cover a line that is just an ellipsis?

**Comment by nedbat** [comment]
You don't have to add a comment to each line.  You can add to your [exclude_lines setting](https://coverage.readthedocs.io/en/6.5.0/config.html#report-exclude-lines):
```
[report]
exclude_lines:
    ^\s+\.\.\.
```
Keep in mind that you have to also add the default settings here as well, since your setting will override the defaults.
