### ISSUE TITLE
Coverage on `break` keyword missing in some Python versions

### ISSUE THREAD

**Issue by Rogdham** [coveragepy/coveragepy#1480]
**Describe the bug**

Consider the following code:
```python
def foo(bar):
    while True:
        if bar:
            bar -= 1
        else:
            break  # <--------- here
    return bar

foo(42)
```

Coverage on the `break` keyword is missing in Python 3.8 and 3.9, but working in other versions:
 - ✔️ Python 3.7.15
 - ❌ Python 3.8.15
 - ❌ Python 3.9.15
 - ✔️ Python 3.10.8
 - ✔️ Python 3.11.0rc2

**To Reproduce**
Save the previous code snippet as `a.py` and run `coverage run a.py && coverage report -m`.

```
Name    Stmts   Miss  Cover   Missing
-------------------------------------
a.py        6      1    83%   6
-------------------------------------
TOTAL       6      1    83%
Coverage failure: total of 83 is less than fail-under=100
```

Testing different Python versions with tox, here is the `tox.ini`:
```ini
[tox]
skipsdist = true
envlist = py37, py38, py39, py310, py311

[testenv]
deps =
    coverage
setenv =
    COVERAGE_FILE = {toxworkdir}/{envname}/.coverage
commands =
    coverage run a.py
    coverage report -m --fail-under=100
```

**Expected behavior**
As with Python 3.7/3.10/3.11
```
Name    Stmts   Miss  Cover   Missing
-------------------------------------
a.py        7      0   100%
-------------------------------------
TOTAL       7      0   100%
```
happen.

**Additional context**
Coverage version 6.5.0 (but also replicated on 6.3.3, 6.4.4)

**Comment by nedbat** [comment]
This is an artifact of differences in how different Python versions optimize code, and trace code.  The else/break was optimized away starting in 3.8, and tracing was improved in 3.10 to make it apparent again.  There's nothing coverage.py can do about this.

**Comment by Rogdham** [comment]
Thank you so much for the quick reply!

I can now see that this seems to be a common problem but I didn't think about searching closed issues, only open ones :man_facepalming:  Sorry for the noise!
