### ISSUE TITLE
the code coverage of Cloud-Init is incorrect. What's wrong?

### ISSUE THREAD

**Issue by ghost** [coveragepy/coveragepy#1485]
**Describe the bug**
Test cases are executed, but coverage data is not collected.
![image](https://user-images.githubusercontent.com/42333849/201114820-8f87c725-08f8-492f-82df-e6073cf00d70.png)
![image](https://user-images.githubusercontent.com/42333849/201114903-60e8ff6d-11cd-47e1-9969-f009177d0995.png)
These functions are invoked in the test case. However, the coverage rate obtained is problematic, as shown in the figure above.

**To Reproduce**
Only one test case is used as an example.
1、install coverage （I use coverage-5.5)
2、Install the cloud-init source code and set PYTHONPATH.
3、coverage run cloudinit/config/tests/test_set_passwords.py
4、coverage html -d html 

**Expected behavior**
Get the correct function coverage

**Comment by nedbat** [comment]
It's hard to diagnose the problem without seeing the code or the test suite.  

I cloned https://github.com/canonical/cloud-init, and ran `tox -e py3; .tox/py3/bin/coverage html -i`, and got this result:

<img width="533" alt="image" src="https://user-images.githubusercontent.com/23789/201331162-40f99a52-1da2-44be-8b39-5b48eddc9ab9.png">

I notice that my line numbers are different than yours, so I'm not sure what code you are running.

Can you provide more specific details about exactly what you are doing? Why coverage 5.5? Why running just one test as you are (pytest has options for selecting tests)? Have you asked the project developers the best way to focus on a particular test?

**Comment by ghost** [comment]
Sorry, I'm not using the latest version. I know why the problem occurred before. I run coverage run test_xxx.py, but test_xxx.py does not have the main function entry.

**Comment by ghost** [comment]
Sorry, I did not use tox. After using tox, the problem was solved. Thanks.
