### ISSUE TITLE
Requesting alternative to sqlite database

### ISSUE THREAD

**Issue by TAAPArthur** [coveragepy/coveragepy#1492]
**Is your feature request related to a problem? Please describe.**
I'm running an a somewhat minimal system and would like to use coveragepy but don't have sqlite. I could install it but it seems overkill for just code coverage. Would it be possible to have a fallback that just stores data in json or something?

**Describe the solution you'd like**
coveragepy notices that I don't have `sqlite` and stores all its result in json or some other plain text format that it can also read. Honestly it doesn't have to be plain text so long as it doesn't require non-standard tools to read it.

**Alternative solution**
A somewhat hacky alternative would be to use file + line number as a key in a map and increment it every time that line is visited (or really just set it to true) and then dump the map.  Would be a bonus if it outputted the complement.

**Additional context**
If it matters, for my usecase I'm only using the report and run subcommands.
I'm just looking for line coverage.
To be clear, I'm not running on a system where sqlite can't be used. I would just prefer not to install it just to get code coverage

**Comment by nedbat** [comment]
I understand what you are asking for, but I'm unlikely to implement it.  sqlite3 is in the Python standard library.  I get that you can build Python without it, but maintaining multiple storage backends will add complexity to coverage.py that will have to be maintained forever.

#764 has a similar goal, but would still be a relational database, so isn't quite the same.

**Comment by TAAPArthur** [comment]
Fair enough.
Thanks for the quick response.
