### ISSUE TITLE
Ability to calculate and display coverage on current changed code (diff)

### ISSUE THREAD

**Issue by ssbarnea** [coveragepy/coveragepy#1495]
As total project coverage may not be so relevant to a specific change, it would extremely useful if `coverage report` could measure and report relative to last commit.

Basically now we use codecov.io but it would be great not to have to wait for CI to run to get a report. If we could set a higher bar for coverage for changes, we could naturally improve the coverage.

Measuring the coverage at project level is quite tricky because it can happen to get false-positive errors regarding reduction of coverage, just due to rounding errors. A good example is if you remove a bigger piece of code that was covered, the overall project coverage goes down. That makes sense, but does not make sense to report it a problem such coverage reduced from `88.44%` to `88.43%`.

If we could measure just the code that was modified in last commit, we would be able to provide very useful feedback regarding what is not covered and report this locally.

Do you think that could be possible to achieve?

**Comment by nedbat** [comment]
There's a separate package for this: https://pypi.org/project/diff-cover/ .   Try it and let me know if it works for you.  If there are gaps, I can work with the maintainer to keep it working well.

**Comment by ssbarnea** [comment]
I will look at it. For the moment I tuned https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters to make it work as it did not work out of the box. I usually do not want to display any coverage data on a normal tox run, unless there is a regression, just to keep the console clean.
