### ISSUE TITLE
coverage report --skip-covered should have no output when coverage is 100%

### ISSUE THREAD

**Issue by ssbarnea** [coveragepy/coveragepy#1496]
**Describe the bug**
When running with `--skip-covered`, we do not expect to see any report table if the table would have no rows. A project with 100% coverage, should produce zero output.

Why is this important? We want to include coverage run with every test run and notify engineers about lack of coverage, but at the same time prevent spamming the stdout with output that is not actionable.

As seen below, there are 6 stdout lines present, which are not expected to be present.

**To Reproduce**

This was obtained with coverage 6.5.0:
```
coverage report --skip-covered --fail-under=88
Name    Stmts   Miss  Cover
---------------------------
---------------------------
TOTAL      31      0   100%

2 files skipped due to complete coverage.
```

**Expected behavior**
No output when coverage is 100% and 

**Additional context**

**Comment by nedbat** [comment]
I've recently fixed the problem of two consecutive rules, so now the table looks like this:
```
% coverage report --skip-covered --fail-under=88
Name    Stmts   Miss  Cover
---------------------------
TOTAL      31      0   100%

2 files skipped due to complete coverage.
```
I think this is the correct output. I would be surprised if I asked for a report and got absolutely nothing.

> Why is this important? We want to include coverage run with every test run and notify engineers about lack of coverage, but at the same time prevent spamming the stdout with output that is not actionable.

You might need to do something more sophisticated. You could use the JSON report to extract information and then decide what to do from there.
