### ISSUE TITLE
change history page link broken on PyPI

### ISSUE THREAD

**Issue by altendky** [coveragepy/coveragepy#1500]
**Describe the bug**

When you visit https://pypi.org/project/coverage/7.0.0b1/ the `change history page` link is broken.  It links to https://coverage.readthedocs.io/en/7.0.0b1/en/latest/changes.html but should be https://coverage.readthedocs.io/en/7.0.0b1/changes.html.

**To Reproduce**
1. Visit https://pypi.org/project/coverage/7.0.0b1/
1. Click the `change history page` link
1. Observe the 404 error on the readthedocs page

**Expected behavior**

Link references https://coverage.readthedocs.io/en/7.0.0b1/changes.html which works.

**Additional context**

I'm guessing something in the vicinity of this link rewriting code.

https://github.com/nedbat/coveragepy/blob/e45309911bac7917ad70ce8d97f0b56afba55359/setup.py#L67-L74

**Comment by nedbat** [comment]
Thanks, that code you showed is the fix!  Just need to wait for a new release to update PyPI.

**Comment by altendky** [comment]
Oof, would help if I had done a blame on that code first...  Thanks.
