### ISSUE TITLE
Publish a PyPy3.9-compatible wheel

### ISSUE THREAD

**Issue by edgarrmondragon** [coveragepy/coveragepy#1510]
The latest PyPy wheel supports versions 3.6-3.8, but not 3.9

**Comment by nedbat** [comment]
The PyPy wheel now installs on 3.7, 3.8, and 3.9, as of 5c5caa24.

**Comment by edgarrmondragon** [comment]
Thanks @nedbat!

**Comment by nedbat** [comment]
This is now released as part of [coverage 7.0.1](https://pypi.org/project/coverage/7.0.1).
