### ISSUE TITLE
Combining coverage across platforms on coverage 7

### ISSUE THREAD

**Issue by gaborbernat** [coveragepy/coveragepy#1516]
This worked with coverage<7, but seems broke with 7.0. Any ideas about what's the issue here? The changelog seems unhelpful.
 
See:	https://github.com/platformdirs/platformdirs/actions/runs/3789103896/jobs/6442564756

The main problem seems to be that paths in the report are absolute and not relative so we can map it back to existing files, see https://github.com/platformdirs/platformdirs/blob/main/pyproject.toml#L57

**Comment by nedbat** [comment]
It stopped working because you moved the coverage settings from setup.cfg to pyproject.toml.  Coverage looks in .coveragerc, setup.cfg, tox.ini, pyproject.toml in that order. It's finding the tox.ini file, and seeing no settings, so using the defaults.  I thought it would use the first of those files that had actual coverage settings, so it should read the pyproject.toml.  I'm still looking into that.

**Comment by gaborbernat** [comment]
> It stopped working because you moved the coverage settings from setup.cfg to pyproject.toml. Coverage looks in .coveragerc, setup.cfg, tox.ini, pyproject.toml in that order. It's finding the tox.ini file, and seeing no settings, so using the defaults. I thought it would use the first of those files that had actual coverage settings, so it should read the pyproject.toml. I'm still looking into that.

It did not work with setup.cfg neither 😊 but while debugging decided to move it. See https://github.com/platformdirs/platformdirs/actions/runs/3786100702/jobs/6436710769 that fails with setup.cfg too 😊

**Comment by nedbat** [comment]
I fixed a bug in coverage.py that failed to warn you that you had settings in a .toml file, but no toml library to read them with.  This is fixed in 3823cc6d.   I also made changes in platformdirs: https://github.com/platformdirs/platformdirs/pull/121

**Comment by gaborbernat** [comment]
Given 3.11 has toml library built-in why do we need the extra?

**Comment by nedbat** [comment]
You don't need the extra if you run on 3.11, but your [combine step is running on 3.10](https://github.com/platformdirs/platformdirs/blob/main/.github/workflows/check.yml#L86).

**Comment by gaborbernat** [comment]
Ah good spot, thank you!

**Comment by nedbat** [comment]
This is now released as part of [coverage 7.0.2](https://pypi.org/project/coverage/7.0.2).
