### ISSUE TITLE
Boolean option configuration via Pyproject.toml is case-sensitive 

### ISSUE THREAD

**Issue by tyleretheridge** [coveragepy/coveragepy#1518]
**Describe the bug**
When setting the branch flag to true in run options via a pyproject.toml, an error occurs when parsing the toml file if the boolean value casing is "True". 

**Python Version:** 3.11 in a Poetry venv
**Coverage.py Version**: 7.0.1

**To Reproduce**

Create a `pyproject.toml` file with the following configuration option:

```
[tool.coverage.run]
branch = "True"
```

Console Output:
```
(dashboard-py3.11) PS C:\Users\**********\repos\dashboard> coverage run -m pytest   
Couldn't read config file pyproject.toml: Option [tool.coverage.run]branch couldn't convert to a boolean: 'True'
```

My full `pyproject.toml`: 
```
[tool.poetry]
name = "dashboard"
version = "0.1.0"
description = ""
authors = [<OMITTED>]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^2.2.2"
flask-login = "^0.6.2"
requests = "^2.28.1"
pytest = "^7.2.0"
python-dotenv = "^0.21.0"
coverage = "^7.0.1"
black = {extras = ["d"], version = "^22.12.0"}
flask-sqlalchemy = "^3.0.2"
flask-dance = {extras = ["sqla"], version = "^6.2.0"}
blinker = "^1.5"
pytest-flask-sqlalchemy = "^1.1.0"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
branch = "true"
source = ["app"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

**Expected behavior**
The [configuration documentation](https://coverage.readthedocs.io/en/7.0.1/config.html) states: 
"Coverage.py will read from `pyproject.toml` if TOML support is available . . . Environment variable expansion in values is available, but only within quoted strings, even for non-string values. " 
This indicates that Boolean values should be enclosed within quotes as a string since the TOML standard does not support native Boolean Types. 

In the documentation section below this `pyproject.toml` compatibility note titled "Syntax", it states: 
"Boolean values can be specified as on, off, true, false, 1, or 0 and are case-insensitive."

Following these examples of using an all lowercase "true" does solve the problem and coverage will run perfectly fine; however, the documentation does indicate that it is case-insensitive and considering that the Python bool value `True` doesn't work, it may be  counterintuitive at first to write `true` in this way. 
 
It is not so much a bug that prevents coverage from running but moreso a difference in the documentation that creates confusion. 
I do not know if this TOML case-sensitive parsing behavior is intended and the documentation fails to mention this pyproject.toml specific case, or if the parsing needs to be adjusted to match the current documentation of being case-insensitive.

**Comment by nedbat** [comment]
BTW, toml does have native booleans (https://toml.io/en/v1.0.0#boolean), but you are right that the configuration values should be a bit more flexible.

**Comment by nedbat** [comment]
The documentation should be clarified. The paragraph about syntax (https://coverage.readthedocs.io/en/7.0.1/config.html#syntax) is about the .ini format (.coveragerc, setup.cfg, or tox.ini).  The TOML syntax is different, but is not explicitly described.

**Comment by A-UNDERSCORE-D** [comment]
@nedbat This appears to be closable unless you want to also make some changes code side to make the config also handle the strings well in all cases?

**Comment by nedbat** [comment]
You are right, thanks.  The docs were updated a while ago to describe the TOML syntax, with examples.
