### ISSUE TITLE
Trying to use relative files

### ISSUE THREAD

**Issue by gaborbernat** [coveragepy/coveragepy#1519]
I'm trying to set relative file paths, but failing 😄

https://coverage.readthedocs.io/en/7.0.1/cmd.html#re-mapping-paths Am I right to assume this removes the need for `paths.source`?

When I look at here https://coverage.readthedocs.io/en/7.0.1/config.html#paths, I do not see `paths.other` explained (as you set it here -  https://github.com/platformdirs/platformdirs/blob/main/pyproject.toml#L59, so it's not clear why that fixed platformdirs).

I ran into this while trying to fix https://github.com/pypa/virtualenv/pull/2477 

PS. this is not really a bug, but I couldn't open a discussion or q/a here, perhaps it would be nice to enable that feature for the repo :thinking: 

I've tried without the relative coverage, but I'm failing to get virtualenv CI pass with 7.0 https://github.com/pypa/virtualenv/actions/runs/3805116230/jobs/6472857177, even after moving from * to **.

**Comment by nedbat** [comment]
I didn't see relative_files in your repo, but when I added it and tried to get it to work, i saw coverage.py needed another fix.

**Comment by nedbat** [comment]
This is fixed in d08e6d08.

**Comment by nedbat** [comment]
This is now released as part of [coverage 7.0.2](https://pypi.org/project/coverage/7.0.2).

**Comment by gaborbernat** [comment]
@nedbat part of this was that seems `paths.other` is not documented :blush: should we address that?

**Comment by nedbat** [comment]
The `[paths]` setting can be confusing.  The name (source, other) is irrelevant and doesn't matter.  What matters is that each setting is a list.  Maybe the docs aren't clear about how the setting is used? https://coverage.readthedocs.io/en/7.0.2/config.html#paths

**Comment by gaborbernat** [comment]
Ah I see 😊

**Comment by gaborbernat** [comment]
> The `[paths]` setting can be confusing. The name (source, other) is irrelevant and doesn't matter. What matters is that each setting is a list. Maybe the docs aren't clear about how the setting is used? [coverage.readthedocs.io/en/7.0.2/config.html#paths](https://coverage.readthedocs.io/en/7.0.2/config.html#paths)

I find it would be easier to understand this config by moving the first value to the key, something like:


```toml
paths.src = ["**/site-packages"]
```

instead of the current

```toml
paths.source = ["src", "**/site-packages"]
```

Granted, this would be a breaking change, but perhaps something we can pivot to in the long term.
