### ISSUE TITLE
Convert context.context to file and test name

### ISSUE THREAD

**Issue by MarcoGorelli** [coveragepy/coveragepy#1529]
**Is your feature request related to a problem? Please describe.**

If I query the `.coverage` sqlite database, then `context.context` shows, for example:
```
pandas.tests.io.json.test_pandas.TestPandasContainer.test_read_jsonl_unicode_chars
```

**Describe the solution you'd like**
To convert this to
```
pandas/tests/io/json/test_pandas.py::TestPandasContainer::test_read_jsonl_unicode_chars
```
so it can be directly execute by `pytest`

**Describe alternatives you've considered**
Writing my own converter, though I'd have thought that a feature like this might be useful to others

**Additional context**

A minimal reproducible example demonstrating this is: https://github.com/MarcoGorelli/which-tests-executed-this-code

Running `python query.py` I see `test_t.test_sum` rather than `test_t.py::test_sum`

**Comment by nedbat** [comment]
Hi, I'm not sure what you are asking for.  I'm not going to store the contexts in a pytest-specific format.  If you have a program to query the database, can't use also adjust the format of the output to be what you need?

**Comment by MarcoGorelli** [comment]
Sure, I'll do that in my program then, thanks for your reply!
