### ISSUE TITLE
coverage per class methods

### ISSUE THREAD

**Issue by ynikitenko** [coveragepy/coveragepy#1532]
**Is your feature request related to a problem? Please describe.**

I have a class with many methods that I regularly test with *pytest*. Unfortunately, it outputs missing lines for the whole class (module), like

> yarsync/yarsync.py     1031    259    75%   60, 69-70, 77, 160-167, ...

It would be great to split the output based on class methods.

**Describe the solution you'd like**

Provide an option to print class methods (as is done for different files, but now for different scopes in one file).

**Describe alternatives you've considered**

I tried [annotate](https://coverage.readthedocs.io/en/6.4.4/cmd.html#text-annotation-coverage-annotate), but that seems redundant (and already discouraged).
I asked [StackOverflow](https://stackoverflow.com/a/75095704/952234), and they proposed `coverage html`, but for me it's much easier to run the command from terminal and use no browser for html (1 command vs 2).

**Additional context**

I write a Python script for file synchronization. It is one file (because it is a script), but it gets more complicated because the class has many methods.

**Comment by devdanzin** [comment]
I believe this is a duplicate of https://github.com/nedbat/coveragepy/issues/1793, not sure which one to keep open if that's the case.

**Comment by nedbat** [comment]
This data is now available in the JSON report as of commit ab609ef0fb235454050cf8383427ce5f1b0ec8e9.

**Comment by nedbat** [comment]
(And in the HTML report as of version 7.5.0).

**Comment by nedbat** [comment]
This is now released as part of [coverage 7.6.0](https://pypi.org/project/coverage/7.6.0).
