### ISSUE TITLE
Coverage() constructor no longer accepts Path-like objects as config_file

### ISSUE THREAD

**Issue by JD-Veiga** [coveragepy/coveragepy#1552]
Hi,

I have just discovered that `Coverage()` constructor only accepts a string as a `config_file` path now. I have built some automations around coverage and, until now, these scripts can pass a `pathlib.Path` as `config_file` to `Coverage()` —and it works.

Specifically, coverage now asserts that `config_file` is a string (coverage/config.py line 555).

I rather prefer that `config_file` can accept any Path-like object. I understand that coverage is mostly invoked via CLI a string seems a natural solution. However, when coverage is invoked programmatically it makes sense —at least to me— that Coverage() accepts strings and `pathlib.Path`s as well.

Of course, this is a minor issue —not really a bug.

I am running coverage 7.1.0 on Python 3.11.1

Thank you for your time.

**Comment by nedbat** [comment]
Oops, sorry about that.  Static typing for the lose....  I'll have to brush up on how to accept path-like things properly.

**Comment by nedbat** [comment]
This is fixed in commit f77be1770a9d93ed69d6b5a26dcbe5dbfe14e380.

**Comment by nedbat** [comment]
This is now released as part of [coverage 7.2.0](https://pypi.org/project/coverage/7.2.0).
