### ISSUE TITLE
Failing to omit files through setup.cfg

### ISSUE THREAD

**Issue by SebastienMorais** [coveragepy/coveragepy#1558]
**Describe the bug**
In my `setup.cfg` file, I specify that i want to omit my test files when measuring coverage:

```python
[coverage:run]
omit = *tests/*
```
While this worked a few version ago (at least in 6.5), current version (7.1.0) does not omit the tests files.
This can be fixed with the following setup

```python
[coverage:run]
omit = my_package/tests/*
```
Although it is possible to make everything work (as specified), I am surprised that my previous configuration no longer works. 

**To Reproduce**
I'm using python 3.8.14 with coverage 6.5 and pytest 7.2.1.
The command used is:
`coverage run -m pytest --cov=my_package --cov-fail-under=95 --cov-config=setup.cfg`

**Expected behavior**
I would expect that omit through `*tests/*` would omit every files contained in `my_package/tests/`

**Comment by nedbat** [comment]
The interpretation of wildcards changed between 6.x and 7.x.  It will work if you use `omit =  */tests/*` I think.  In 6.x, `*` would match a directory separator, but now it does not.

**Comment by nedbat** [comment]
I think we could use a more complete description of the wildcard changes, and how to adjust settings when moving from 6.x to 7.x.

**Comment by paxnovem** [comment]
Working on this for the Pycon2023 sprints

**Comment by SebastienMorais** [comment]
> The interpretation of wildcards changed between 6.x and 7.x. It will work if you use `omit = */tests/*` I think. In 6.x, `*` would match a directory separator, but now it does not.

Indeed, it works :+1:

**Comment by nedbat** [comment]
@paxnovem added migration notes in commit d6e621aa.  I hope that will avoid future confusion.
