### ISSUE TITLE
I wanna use  coveragepy without sqlite

### ISSUE THREAD

**Issue by FuyuanChen** [coveragepy/coveragepy#1561]
**Is your feature request related to a problem? Please describe.**
No. I just wanna use it without sqlite.

**Describe the solution you'd like**
In my project, i need to delete all code of not be runed. But Sqlite does not support in In our environment. 

**Describe alternatives you've considered**
just coveragepy now

**Additional context**
Thanks for lot

**Comment by nedbat** [comment]
Coverage.py doesn't have an option to run without SQLite.  I don't know how much work it would be to make it possible.  You could try using the [trace module in the stdlib](https://docs.python.org/3/library/trace.html) instead.

**Comment by nedbat** [comment]
Coverage.py doesn't have an option to run without SQLite.  I don't know how much work it would be to make it possible.  You could try using the [trace module in the stdlib](https://docs.python.org/3/library/trace.html) instead.
