### ISSUE TITLE
Contributing To Doc Update Need:  Getting The Code

### ISSUE THREAD

**Issue by ProsperousHeart** [coveragepy/coveragepy#1589]
**Describe the bug**
Item 4 is unclear - could indicate that you must install multiple versions. This was also written prior to GitHub Actions.

**To Reproduce**
Review documentation [here](https://coverage.readthedocs.io/en/latest/contributing.html#getting-the-code).

![image](https://user-images.githubusercontent.com/20706498/226425931-9ef253b2-183d-48d1-b5c3-da0d3245eb3d.png)

**Expected behavior**
This should not be an item on how to get the code and install requirements. Once `pip install -r requirements/dev.in` is done, that should be the end. If the 4th item has valid info, it should be more of a side note as a suggestion but not a "rule" for getting started.

**Comment by ProsperousHeart** [comment]
no work has been done on my part because someone else was working on fixing this - not sure if they are going to include this.

**Comment by nedbat** [comment]
This has been improved in 14beae2e and 1469085b.
