### ISSUE TITLE
[QUESTION] How to get lines not covered?

### ISSUE THREAD

**Issue by Kludex** [coveragepy/coveragepy#1594]
Hi @nedbat :wave: 

I'm not sure if this is the right forum for it, but I have a question, and I didn't know where to ask.

I'd like to create a package that adds `# pragma: <custom>` to all lines that are not covered that actually execute code. So, for example, if I have the following code:

```python
def is_banana(fruit: str) -> bool:
    if fruit == "banana":
        return True
    return False

is_banana("banana")
```
The package that I want to create would modify the above code as:

```python
def is_banana(fruit: str) -> bool:
    if fruit == "banana":
        return True
    return False  # pragma: <custom>

is_banana("banana")
```
I'm using the following logic:

```python
from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

from coverage import CoverageData, FileReporter


@dataclass
class UncoveredFile:
    filename: str
    lines: set[int]


def uncovered_files() -> Iterable[UncoveredFile]:
    data = CoverageData(".coverage")
    data.read()
    for filename in data.measured_files():
        for token_line in FileReporter(filename=filename).source_token_lines():
            print(token_line)  # This doesn't help... :sweat_smile: 
        with open(filename) as f:
            lines = f.readlines()
        total_lines = len(lines)
        data_lines = data.lines(filename=filename)

        lines_executed = set(data_lines) if data_lines else set()
        lines_not_executed = set(range(1, total_lines + 1)) - lines_executed

        # Strip empty lines - I actually want to remove all lines that weren't executed
        for line_num in lines_not_executed.copy():
            if not lines[line_num - 1].strip():
                lines_not_executed.remove(line_num)

        if lines_not_executed:
            yield UncoveredFile(filename=filename, lines=lines_not_executed)


for uncovered_file in uncovered_files():
    print(uncovered_file)
```
What I'm missing is: how do I ignore comments, and other lines that don't execute?

**Comment by nedbat** [comment]
The API provides this information from [`analysis2()`](https://coverage.readthedocs.io/en/7.2.2/api_coverage.html#coverage.Coverage.analysis2).  Another option is to generate a JSON report, and use the data from there.

Though I have to ask why you want to add a pragma to all the executable but unexecuted lines?  It sounds like a way to fake 100% coverage!

**Comment by Kludex** [comment]
Thanks @nedbat ! I'm going to check it tonight.

> It sounds like a way to fake 100% coverage!

The idea is to solve the problem of "how to increase test coverage on an old project". In the current strategies to achieve that, we have a side effect of adding uncovered lines, even if the percentage of covered lines on the project goes up. I don't want those uncovered lines to be added.

The idea is to create a tool that will do the following:
1. Add `# pragma: <custom>` on uncovered lines to set test coverage to 100%.
2. Then the user can set the `fail-under` to 100.
3. Give real report ignoring the `# pragma: <custom>`. - I may need to create a plugin as well (?)

**Comment by nedbat** [comment]
I see, thanks for the detail.  You might also find [diff-cover](https://pypi.org/project/diff-cover/) useful.

**Comment by Kludex** [comment]
Thanks @nedbat :pray:
