### ISSUE TITLE
Can we get info about the number of times a statement is executed in xml reports?

### ISSUE THREAD

**Issue by MisterGlass** [coveragepy/coveragepy#1601]
I'd like accurate hit counts in the xml export. Currently the hits value can only be a zero or one, representing whether the line was executed instead of how many times.

I'm specifically speaking about this section of the code:
https://github.com/nedbat/coveragepy/blob/5a94109e646870aef6188de25ba314f73fa1245d/coverage/xmlreport.py#L213
```
            # Q: can we get info about the number of times a statement is
            # executed?  If so, that should be recorded here.
            xline.setAttribute("hits", str(int(line not in analysis.missing)))
```

Can we get that info? It looks like this segment of code was written 14 years ago, so I'm hoping it is now possible.

**Comment by nedbat** [comment]
I'm sorry, but coverage.py still doesn't collect information about the number of times a line is run. See #669.
