### ISSUE TITLE
Version 7.2.3 introduced asyncio package. This breaks Django applications using Python versions with async support

### ISSUE THREAD

**Issue by IshamMohamed** [coveragepy/coveragepy#1603]
**Describe the bug**
This was not a problem previous to this particular version. But I found installing 7.2.3 also installs asyncio package. This is conflicting with import asyncio statement for the later python versions on which async is a reserved keyword. 

Workaround is to rollback to a version such as 7.2.1.

**Comment by nedbat** [comment]
Coverage.py has no run-time dependencies.  It does not pull in asyncio:
```
% pip install coverage==7.2.3
Collecting coverage==7.2.3
  Downloading coverage-7.2.3-cp310-cp310-macosx_10_9_x86_64.whl (200 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━ 200.0/200.0 kB 3.2 MB/s eta 0:00:00
Installing collected packages: coverage
Successfully installed coverage-7.2.3
```

Can you show me how you installed it? Maybe something else is pulling in asyncio?

**Comment by IshamMohamed** [comment]
Yes it was another package.
