### ISSUE TITLE
Cannot extract line number information from the coverage report.

### ISSUE THREAD

**Issue by AS-Data-Analysis** [coveragepy/coveragepy#1618]
**Describe the bug**
A clear and concise description of the bug.

I am running code coverage a simple function and extracting data about the line numbers that are executed. However, the output is always 'None'.

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't link to a failing CI job. Answer the questions below:
1. What version of Python are you using?
1. What version of coverage.py shows the problem? The output of `coverage debug sys` is helpful.

-- sys -------------------------------------------------------
               coverage_version: 7.2.3
                coverage_module: C:\Users\ashar523\AppData\Local\Programs\Python\Python311\Lib\site-packages\coverage\__init__.py
                         tracer: -none-
                        CTracer: available
           plugins.file_tracers: -none-
            plugins.configurers: -none-
      plugins.context_switchers: -none-
              configs_attempted: .coveragerc
                                 setup.cfg
                                 tox.ini
                                 pyproject.toml
                   configs_read: -none-
                    config_file: None
                config_contents: -none-
                      data_file: -none-
                         python: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]    
                       platform: Windows-10-10.0.22000-SP0
                 implementation: CPython
                     executable: C:\Users\ashar523\AppData\Local\Programs\Python\Python311\python.exe
                   def_encoding: utf-8
                    fs_encoding: utf-8
                            pid: 420
                            cwd: C:\Users\ashar523\Desktop\ai_test_automation\Scripts_for_code_coverage
                           path: C:\Users\ashar523\AppData\Local\Programs\Python\Python311\Scripts\coverage.exe      
                                 C:\Users\ashar523\AppData\Local\Programs\Python\Python311\python311.zip
                                 C:\Users\ashar523\AppData\Local\Programs\Python\Python311\DLLs
                                 C:\Users\ashar523\AppData\Local\Programs\Python\Python311\Lib
                                 C:\Users\ashar523\AppData\Local\Programs\Python\Python311
                                 C:\Users\ashar523\AppData\Local\Programs\Python\Python311\Lib\site-packages
                    environment: HOME = C:\Users\ashar523
                                 TEMP = C:\Users\ashar523\AppData\Local\Temp
                                 TMP = C:\Users\ashar523\AppData\Local\Temp
                   command_line: C:\Users\ashar523\AppData\Local\Programs\Python\Python311\Scripts\coverage debug sys
         sqlite3_sqlite_version: 3.40.1
             sqlite3_temp_store: 0
        sqlite3_compile_options: ATOMIC_INTRINSICS=0, COMPILER=msvc-1934, DEFAULT_AUTOVACUUM,
                                 DEFAULT_CACHE_SIZE=-2000, DEFAULT_FILE_FORMAT=4,
                                 DEFAULT_JOURNAL_SIZE_LIMIT=-1, DEFAULT_MMAP_SIZE=0, DEFAULT_PAGE_SIZE=4096,
                                 DEFAULT_PCACHE_INITSZ=20, DEFAULT_RECURSIVE_TRIGGERS,
                                 DEFAULT_SECTOR_SIZE=4096, DEFAULT_SYNCHRONOUS=2,
                                 DEFAULT_WAL_AUTOCHECKPOINT=1000, DEFAULT_WAL_SYNCHRONOUS=2,
                                 DEFAULT_WORKER_THREADS=0, ENABLE_FTS3, ENABLE_FTS4, ENABLE_FTS5,
                                 ENABLE_MATH_FUNCTIONS, ENABLE_RTREE, MALLOC_SOFT_LIMIT=1024,
                                 MAX_ATTACHED=10, MAX_COLUMN=2000, MAX_COMPOUND_SELECT=500,
                                 MAX_DEFAULT_PAGE_SIZE=8192, MAX_EXPR_DEPTH=1000, MAX_FUNCTION_ARG=127,
                                 MAX_LENGTH=1000000000, MAX_LIKE_PATTERN_LENGTH=50000,
                                 MAX_MMAP_SIZE=0x7fff0000, MAX_PAGE_COUNT=1073741823, MAX_PAGE_SIZE=65536,
                                 MAX_SQL_LENGTH=1000000000, MAX_TRIGGER_DEPTH=1000,
                                 MAX_VARIABLE_NUMBER=32766, MAX_VDBE_OP=250000000, MAX_WORKER_THREADS=8,
                                 MUTEX_W32, OMIT_AUTOINIT, SYSTEM_MALLOC, TEMP_STORE=1, THREADSAFE=1

1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.

contourpy==1.0.7
coverage==7.2.3
cycler==0.11.0
fonttools==4.39.3
kiwisolver==1.4.4
matplotlib==3.7.1
mpmath==1.3.0
numpy==1.24.2
packaging==23.1
pandas==2.0.1
Pillow==9.5.0
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2023.3
scikit-opt==0.6.6
scipy==1.10.1
six==1.16.0
sympy==1.11.1
tzdata==2023.3

1. What code shows the problem?  Give us a specific commit of a specific repo that we can check out. If you've already worked around the problem, please provide a commit before that fix.

```python
# My function
def calculate_price(product_type, quantity):
    if product_type == "book":
        price = 10
    elif product_type == "electronics":
        price = 50
    elif product_type == "clothing":
        price = 20
    else:
        return "invalid product type"
    if quantity < 0:
        return "invalid quantity"
    if quantity <= 10:
        return price * quantity
    elif quantity <= 20:
        return price * quantity * 0.9
    else:
        return price * quantity * 0.8
``` 
1. What commands did you run?

```python
# coverage_report_generator.py file
from coverage import Coverage,CoverageData
from price_calculator import calculate_price

def coverage_calculator():
    cov = Coverage()
    cov.start()
    
    price = calculate_price('book',5)
    
    d = dict(cov.sys_info())
    cov.stop()
    cov.save()
    covdata = CoverageData()
    covdata.read()
    return covdata.lines(d['data_file'])

result = coverage_calculator()
print(result)
``` 

**Expected behavior**

```python
$ python coverage_report_generator.py 
None
``` 
Running my coverage file outputs just None even though the line numbers were expected to be displayed. Looking at the output of 'coverage debug sys' command, I see that the data_file parameter has no file path. I see that the .coverage file is generated in my directory but this parameter does not retrieve it for some reason.

**Additional context**

I don't know what I am missing. I want to extract this data for a larger project that is why I am testing it first with a simpler function. Can you help me out?

**Comment by nedbat** [comment]
Hi, sorry the API was confusing.  You have:
```python
return covdata.lines(d['data_file'])
```
This is asking what the collected data was for the ".coverage" file.  That's where the data is stored, but it's not a file that was measured.

You want:
```python
return covdata.lines(os.path.abspath("price_calculator.py"))
```
When I make that change, I get this output:
```
[3, 4, 11, 13, 14]
```

**Comment by AS-Data-Analysis** [comment]
Ah I see! Yes that fixes it, thank you so much :)
