### ISSUE TITLE
Unable to Skip NoDataError Exception and continue with generating the report vs. Bash

### ISSUE THREAD

**Issue by EDataScriptware** [coveragepy/coveragepy#1625]
**Describe the bug**
If one file has no data to report, this exception `coverage.exceptions.NoDataError: No data to report.`  is triggered. You cannot skip or iterate over this exception to the next file. Try/Except will not assist and workarounds by iterating through files will increase computation time. 

**To Reproduce**

```py
def begin_coverage_analytics():
    cov = coverage.Coverage(data_file=None)
    cov.start()

    # In bash, you execute `pytest -s --cov=./integrations`, and you'll be able to get the report. 
    pytest.main(['-s', '--cov=./integrations'])

    cov.stop()
    cov.report()
    return cov

```

**Expected behavior**
I expect the code to continue generating the report even if one file has no data to report. I should be able to see the results in Python as I do in Bash.

**Additional context**
Stack Trace
```bash
  File "/code_coverage_headstart.py", line 17, in compile_code_coverage
    master_dict = {'total_code_coverage': round(cov.report().real, 2)}
  File "/virtualenvs/data-services-ImW0IdHD/lib/python3.9/site-packages/coverage/control.py", line 1059, in report
    return reporter.report(morfs, outfile=file)
  File "/virtualenvs/data-services-ImW0IdHD/lib/python3.9/site-packages/coverage/summary.py", line 181, in report
    for fr, analysis in get_analysis_to_report(self.coverage, morfs):
  File "/virtualenvs/data-services-ImW0IdHD/lib/python3.9/site-packages/coverage/report.py", line 94, in get_analysis_to_report
    raise NoDataError("No data to report.")
coverage.exceptions.NoDataError: No data to report.
```

**Comment by nedbat** [comment]
I don't understand what you are trying to do with the shown code.  `pytest --cov` will start and manage coverage.py for you, but you are also starting coverage before using pytest.  Can you say more about the big picture here  What does code_coverage_headstart.py do? There might be an easier approach.

Also, you haven't given me a way to reproduce the "one file has no data" scenario you describe.

(As an aside: the code in your traceback has `cov.report().real`: you don't need the `.real`, report returns a float.)

**Comment by EDataScriptware** [comment]
I understand the bash command `pytest --cov` handles the coverage.py for me. I am looking to automate the process through Python scripting, allowing me to generate and access the metrics directly to reflect them as a .JSON. This allows me and the interested parties to observe the potential churn.

In summary, the code should set up the coverage library, run the code coverage analysis over the measured files in a directory, and generate a dictionary in memory containing the code coverage percentages for each file so they can be uploaded to different areas in the infrastructure rather as a stored file.

Surely, there is a better approach to this?

**File `code_coverage_headstart.py` Dump**
```py
import coverage
import pytest
import json


def calculate_code_coverage(analysis_var: tuple):
    stmt, miss = analysis_var[1], analysis_var[3]
    if len(stmt) == 0:
        return 1.0
    individual_percentage = round(1 - len(miss) / len(stmt), 2)

    return individual_percentage


def compile_code_coverage(cov):
    file_paths = cov.get_data().measured_files()
    master_dict = {'total_code_coverage': round(cov.report(), 2)}
    for file_path in file_paths:
        analysis = cov.analysis2(file_path)
        calculated_code_coverage = calculate_code_coverage(analysis)

        # print(calculated_code_coverage)
        # print(f"{file_path} {calculated_code_coverage}")

        master_dict[file_path] = calculated_code_coverage

    return master_dict


def main():
    cov = begin_coverage_analytics()
    code_coverage_report = compile_code_coverage(cov)
    json.dump(code_coverage_report, open('code_coverage.json', 'w'), indent=4)


def begin_coverage_analytics():
    cov = coverage.Coverage(data_file=None)
    cov.start()

    # pytest --cov=integrations
    pytest.main(['--cov=integrations'])

    cov.stop()
    return cov

# cov.json_report() # Creates JSON file report.
# cov.xml_report() # Creates XML file report.
# cov.html_report() # Creates HTML batch reports
# cov.lcov_report() # Creates LCOV file report.

main()
```


> (As an aside: the code in your traceback has cov.report().real: you don't need the .real, report returns a float.)

(I did bad code trying to find a workaround by accessing the object attributes directly.)

**Comment by nedbat** [comment]
Your description sounds like you want the `coverage json` command.  I'm guessing you tried this, but I don't know how this isn't what you want:
```
pytest --cov=integrations
coverage json
cat coverage.json
```

**Comment by EDataScriptware** [comment]
Hi @nedbat - it appears that I do want the bash command to perform the `coverage json` rather than attempting to create a Python script and redoing the wheel. I may have missed this out on the [documentation](https://coverage.readthedocs.io/en/7.2.5/cmd.html#json-reporting-coverage-json) you provided.

Thanks, I'll close this issue!
