### ISSUE TITLE
Reducing the need for multiple coverage commands (UX)

### ISSUE THREAD

**Issue by ssbarnea** [coveragepy/coveragepy#1627]
**Is your feature request related to a problem? Please describe.**
As this moment user might need to call coverage multiple times after the effective `coverage run` to perform post-processing and reporting. This makes coverage usage harder and is prone to introduce errors or at least make maintenance harder.

Example of current usage from within a `tox.ini` file:

```ini
[testenv]
commands_pre =
  # cleaning needed to prevent errors between runs
  sh -c "rm -f .coverage {toxworkdir}/.coverage.* 2>/dev/null || true"
commands =
  coverage run -m pytest {posargs:}
  sh -c "coverage combine -a -q --data-file=.coverage {toxworkdir}/.coverage.*"
  -sh -c "COVERAGE_FILE= coverage xml --ignore-errors -q --fail-under=0"
  sh -c "COVERAGE_FILE= coverage report"
setenv =
  COVERAGE_FILE = {env:COVERAGE_FILE:{toxworkdir}/.coverage.{envname}}
  COVERAGE_PROCESS_START={toxinidir}/pyproject.toml
```

**Describe the solution you'd like**

I would like to make it possible for coverage to allow chaining of multiple commands. Probably https://click.palletsprojects.com/en/8.0.x/advanced/ article could provide some hints about how thi scan be achieved (not sure yet).

For example user should be allowed to do something like:
```
coverage combine -a -- xml -- report
```
Note that use of `--` is a POSIX convention for signaling end of current command arguments and that next one will follow. As you probably know that is used by tox and ssh to pass extra arguments to underlying process. Still, they can be used for chaining too.

**Additional context**

While I can myself debug and address most surprises coming from use of coverage, I would want to make its use as simple as possible for *any* python engineers, so they would not have to dig in order to discover why their coverage did not happen, or why they got confusing errors like "Can't combine line data with arc data" after they switched one configuration argument.

I do think that parallel execution and coverage of subprocess is probably the cause of the extra complexity in behavior as that needs tricks like setting COVERAGE_FILE for `coverage run` but unsetting it for `combine` and `report` commands.

What can we do to reduce the current setup and minimize the number of hacks someone needs to do to run coverage? While my example used tox, we can also wonder if we can improve the situation in a way that would make it "just-work" even when not using tox.

**Comment by nedbat** [comment]
I am not interested in making the coverage command line more complex by somehow chaining commands.  Git requires multiple invocations to run separate git commands.  Coverage can do the same.  People who want everything in one line already have the pytest-cov command.  For other uses, there is tox, or make, or shell scripts.
