### ISSUE TITLE
Mark typing.assert_never as unreachable and therefore covered.

### ISSUE THREAD

**Issue by CharString** [coveragepy/coveragepy#1633]
**Is your feature request related to a problem? Please describe.**
I'm always ~~frustrated~~ mildly annoyed when `typing.assert_never` or `typing_extensions.assert_never` lines are marked as not covered.

**Describe the solution you'd like**
The [reachability analysis](https://coverage.readthedocs.io/en/6.6.0b1/howitworks.html#analysis) to improve.

**Describe alternatives you've considered**
`# pragma: no cover`

**Comment by nedbat** [comment]
There's a better alternative to `# pragma: no cover`: [the `exclude_also` setting](https://coverage.readthedocs.io/en/7.2.6/config.html#report-exclude-also)
```ini
[report]
exclude_also = 
    typing.assert_never
```
This will automatically exclude any line containing `typing.assert_never`.
