### ISSUE TITLE
Add CITATION.cff

### ISSUE THREAD

**Issue by schackartk** [coveragepy/coveragepy#1639]
**Is your feature request related to a problem? Please describe.**
I am unsure of how to properly cite coveragepy in a research article.

**Describe the solution you'd like**
I would like to see a CITATION.cff file in the root of the repository.

[GitHub recommends](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files), and integrates support for, [CITATION.cff](https://citation-file-format.github.io/) files. Inclusion of this file would immediately have these benefits:

- Users will have the necessary metadata to properly cite mypy.
- GitHub can automatically generate both APA and BibTeX formatted citations. A "Cite this repository" option will automatically appear on the repo's sidebar when viewed on a desktop browser.
- Reference managers like Zotero will automatically detect the metadata so the user can save the citation to their library.

**Describe alternatives you've considered**
The other main options are to supply a suggested citation in the README or other documentation, or to have a BibTeX formatted citation file. However, GitHub has better support for CFF formatted citations.

**Additional context**
Examples of popular packages using this are [pandas](https://github.com/pandas-dev/pandas) and [tensorflow](https://github.com/tensorflow/tensorflow).

I would be happy to create an initial version of this and open a PR if there is interest in possibly merging it after refinement.

**Comment by nedbat** [comment]
I'm fine with adding this file.  It would be nice if it didn't need to be a separate file, but I understand.

**Comment by schackartk** [comment]
Yeah, it can always be a pain adding yet another file to the root of the repo.

I will draft one up and submit a pull request though.
