### ISSUE TITLE
How to use coverage to get the test execution report?

### ISSUE THREAD

**Issue by MbProg** [coveragepy/coveragepy#1654]
**Is your feature request related to a problem? Please describe.**
We have to use sonarqube as part of our deployment cycle. Sonarqube needs as input a test coverage report and test execution report. I am using written all my tests using python unittest and coverage to create the coverage report. But it seems that coverage does not provide the test execution report to feed it to sonarqube.

**Describe the solution you'd like**
A parameter to add to coverage command to get the test execution report.

**Additional context**
If I am wrong and there is already a solution for this in coverage, please tell me.

**Comment by nedbat** [comment]
I'm not sure what test execution report you're looking for.  Keep in mind that coverage doesn't run your tests.  Your test runner (pytest, unittest, etc) runs the tests, knows what tests were run, and which succeeded and failed.  I think perhaps you are looking for a report from your test runner.
