### ISSUE TITLE
Question -- Can coveragepy work in my scenario?

### ISSUE THREAD

**Issue by anna-mazhar** [coveragepy/coveragepy#1660]
Hi,

I want to trace the execution of a cloud service emulator called [Localstack](https://github.com/localstack/localstack), which is run as a separate process and then I invoke it by API calls made from another Python script. My goal is to measure the code coverage as different parts of the emulator's code are triggered by these API calls. To achieve this, I start the emulator process in a script with coveragepy. I also load all the modules of the emulator in this script so that they are traced by coveragepy (I thought if I include source=localstack, coveragepy would trace all the modules in localstack(emulator) but turned out that I need to explicitly load them). To end the emulator's process, I explicitly send a SIGTERM signal to terminate the process and then I obtain the coverage data.

The issue I'm facing is when I run the API calls. Even though I can see the traffic on the terminal for the emulator when I make the API calls from the other script, the coverage results remain the same as if I had simply run the emulator and loaded its modules without the API calls. My hypothesis is that the API calls' code coverage is not being recorded, and it seems that coveragepy is only capable of covering code that is executed sequentially in one go.

So, my question is: Can I use coveragepy in my scenario to achieve the desired code coverage results for the emulator's code invoked through API calls? Or am I trying to do something with a tool that it's not designed for or supports?

Thank you for your time.

**Comment by nedbat** [comment]
I don't know anything about Localstack, but it's possible they are executing the requests in subprocesses.  See the coverage.py docs for how to make sure they are measured: https://coverage.readthedocs.io/en/latest/subprocess.html

**Comment by anna-mazhar** [comment]
Thank you for replying.

I am measuring subprocesses, however, it may be possible that these subprocesses do not end gracefully since I send a SIGTERM to the main process which prevents coveragepy from writing the latest data to the file (as per the doc). Is there any other way that I can grab the data and verify?

**Comment by nedbat** [comment]
Are you using `--parallel` and `coverage combine`?

**Comment by anna-mazhar** [comment]
Yes

**Comment by nedbat** [comment]
And also the `[run] sigterm = True` setting?  If so, I'm not sure what else to suggest.  I don't suppose you can give me a way for me to reproduce your issue?

**Comment by anna-mazhar** [comment]
`sigterm`, I believe is by default `True` but I do set it to `True` in the config file as well.

I am trying to find a simpler way for you to reproduce it. I will get back to you if I manage one. Thanks for your help.

**Comment by yi-guo-546** [comment]
> `sigterm`，我相信是默认的，但我也在配置文件中将`True`其设置为。`True`
> 
> 我正在尝试找到一种更简单的方法让您重现它。如果我成功了，我会回复你。感谢您的帮助。

hi, master. I have the same requirement.I feel that coverage tool is suitable for handling single test coverage, but it seems inappropriate for integration test coverage. Do you have other ways to handle this requirement?
