### ISSUE TITLE
Gunicorn with Flask application not generating correct coverage report.

### ISSUE THREAD

**Issue by shilpy0401** [coveragepy/coveragepy#1679]
I have a dev setup where the application is running.

I am trying to get coverage report for functional tests/regression tests with coverage API in a gunicorn wsgi server.
I have followed https://github.com/nedbat/coveragepy/issues/1346  and created test.py and gunicorn.py scripts.

I am running below command : 
gunicorn -b 0.0.0.0:8000 -c gunicorn.py "test:make_app('dev')" -k gevent --timeout 600 --log-level debug
where test is a file and make_app('dev') is an entry point to the application. 

After running this command the server was up and running and I was able to execute APIs(tests) from browser. In order to shut down gracefully I killed the gunicorn process from another terminal and upon shutting down it has generated .coverage file in the root directory. 
then I ran coverage report which gives same coverage 31%  everytime.
I had tested it on 3 scenarios : 
Executed ~5-6 APIs APIs 
Executed  1 API 
executed 0 API

for in all the above case the coverage is 31%. (Note : everytime I deleted .coverage file before running gunicorn command)

I am missing something here. Could any of the experts help me on this ? 
Let me know if you want to look into the scripts.

**Comment by nedbat** [comment]
Try setting the `[run] sigterm=True` setting (https://coverage.readthedocs.io/en/7.3.1/config.html#run-sigterm).  If that doesn't help, share the code with us so we can look into it.

**Comment by nedbat** [comment]
Closing as stale.
