### ISSUE TITLE
`branch=True` renders the last `case` statement as missing

### ISSUE THREAD

**Issue by dycw** [coveragepy/coveragepy#1698]
**Describe the bug**
I've put everything in a standalone [repo](https://github.com/dycw/test-coverage-on-match/tree/1a7059b5dc2081143ca34b53daf131096e072bcd). But essentially we have a singular function 

```python
from typing import Literal


def map_abc(x: Literal["a", "b", "c"]) -> Literal["a", "b", "c"]:
    match x:
        case "a":
            return "a"
        case "b":
            return "b"
        case "c":
            return "c"
```

to be tested. With no configuration, a test calling `map_abc` with each of the three letters `a`, `b`, `c` renders

```console
Name                                     Stmts   Miss  Cover   Missing
----------------------------------------------------------------------
src/test_coverage_on_match/__init__.py       9      0   100%
```

However, under the configuration

```toml
# pyproject.toml
[tool.coverage.run]
branch = true
```

this becomes

```console
Name                                     Stmts   Miss Branch BrPart  Cover   Missing
------------------------------------------------------------------------------------
src/test_coverage_on_match/__init__.py       9      0      6      1    93%   10->exit
```

**To Reproduce**
Clone the standalone [repo](https://github.com/dycw/test-coverage-on-match/tree/1a7059b5dc2081143ca34b53daf131096e072bcd). Use Python 3.10.13 and `pip install requirements.txt` (giving you `coverage` 7.3.2 and `pytest` 7.4.3. Now run the shell scripts `./run-tests-without-branch.sh` or `./run-tests-with-branch.sh`.

**Expected behavior**
Full coverage.

**Additional context**

**Comment by nedbat** [comment]
You know that the value must be a, b, or c, but coverage.py doesn't know that. You will need to use a pragma comment of some sort to indicate that the branch from `case "c":` can't be taken.  https://coverage.readthedocs.io/en/7.3.2/branch.html#structurally-partial-branches .

Coverage.py doesn't use type annotation, or understand "data coverage" at all.
