### ISSUE TITLE
is this option  `COVERAGE_STORAGE=json` still available on latest version

### ISSUE THREAD

**Issue by sathnaga** [coveragepy/coveragepy#1703]
seeing coverage file format as SQLite even after setting env variable `COVERAGE_STORAGE=json` on 6.5.0 version, is it available? 

thanks!

**Comment by edgarrmondragon** [comment]
I think it was removed:

> SQLite data storage is now faster. There’s no longer a reason to keep the JSON data file code, so it has been removed.

https://coverage.readthedocs.io/en/7.3.2/changes.html#version-5-0a6-2019-07-16

**Comment by sathnaga** [comment]
Thanks!

**Comment by sathnaga** [comment]
Thanks!
