### ISSUE TITLE
Question: Include all files in --source even unloaded

### ISSUE THREAD

**Issue by buhtz** [coveragepy/coveragepy#1708]
X-Post: https://discuss.python.org/t/coverage-py-100-but-unused-python-files-not-detected/39040/6

My question in short is how do I include all py-files into the report specificed via `--source`. The problem is that py-files in the source that are not loaded by a test file are ignored and not measured.

I am in the middle of setup a technical demo about the usage of coverage.
https://codeberg.org/buhtz/tech-demo-python-packaging/src/branch/main/06_test_coverage

That is the folder layout
```
06_test_coverage
├── LICENSE
├── pyproject.toml
├── README.md
├── src
│   └── fruits
│       ├── foo.py
│       ├── __init__.py
│       └── __main__.py
└── tests
    ├── __init__.py
    └── test_fruits.py
```

See the file `foo.py`. That file is not loaded and used by the test suite. Technically it makes sense that this file is not measured.

The coverage setup in my `pyproject.toml`:
```
[tool.coverage.run]
command_line = "--module pytest"
source = ["."]
omit = ["*/tests/*"]
```

The source is specified and as a user I would expect that all py-files in that source are used and not only the ones loaded by the test suite. I do accept that your design goals are different from my expectations. I just want to understand how I have to setup coverage to fulfill my goals.

I want to have all py-files from source folder included without naming them explicit.

The `source_pkg` behave the same and ignores `foo.py`. I also tried `include = ["./src/*/*.py"]
` without success.

From my users perspective coverage should be able to detected untested (not covered) files.

**Comment by nedbat** [comment]
Please show what command you used to run coverage, and in what directory.

**Comment by buhtz** [comment]
> Please show what command you used to run coverage, and in what directory.

I am in the root of the project folder `06_test_coverage` and call `coverage run` and `coverage report`. The config is in the `pyproject.toml`.

**Comment by nedbat** [comment]
If you use `source = ["src"]`, it will work as you want, and you delete the `omit` line.  The docs say:
> Only importable files (ones at the root of the tree, or in directories with a __init__.py file) will be considered. 

The src directory is not importable, so `"."` won't explore into it. I can add to the quick start about it.

**Comment by buhtz** [comment]
Ah, I understand the logic.
IMHO today it is unusual to think about files and path's when it comes to `import`.

I do handle my development process with the _Development Mode_ means installing a package with `pip` using `--editable` flag. In that case the tools around don't need to know where the py-files are located. They just need to know the name of the package, importing and doing the job.

Maybe you can improve coveralls that way? It would make its configuration much more easy.

**Comment by nedbat** [comment]
The `source` option will also accept importable module names.  This also works:
```toml
[tool.coverage.run]
command_line = "--module pytest"
source = ["fruits"]
```

The docs say:
> You can specify source to measure with the --source command-line switch, or the [run] source configuration value. The value is a comma- or newline-separated list of directories or importable names (packages or modules).

**Comment by buhtz** [comment]
Thanks for your patience.
