### ISSUE TITLE
7.3.3 isn't "latest" on Read the Docs

### ISSUE THREAD

**Issue by adamchainz** [coveragepy/coveragepy#1720]
**Describe the bug**

Opening https://coverage.readthedocs.io/en/latest/changes.html doesn't show 7.3.3, because it isn't marked as the "latest" release there.

**To Reproduce**
As above.

**Expected behavior**
It is the latest.

**Additional context**
n/a

**Comment by nedbat** [comment]
Thanks, I had the settings right, but it wasn't taking.  I changed the settings again, and now the pages are right.

**Comment by adamchainz** [comment]
Weird. Thanks!
