### ISSUE TITLE
sysmon coverage core is slower than default

### ISSUE THREAD

**Issue by alex** [coveragepy/coveragepy#1724]
I've tested using `COVERAGE_CORE=sysmon` on the pyca/cryptography test suite and it is considerably slower than the default core.

These measurements were done with Python 3.12.1 on an MBP M1 Pro.

Running the test suite with no coverage:

```
3063 passed, 179 skipped in 12.07s
3063 passed, 179 skipped in 11.06s
3063 passed, 179 skipped in 11.05s
3063 passed, 179 skipped in 11.11s
3063 passed, 179 skipped in 10.92s
```

With default coverage:

```
3063 passed, 179 skipped in 13.65s
3063 passed, 179 skipped in 13.90s
3063 passed, 179 skipped in 13.73s
3063 passed, 179 skipped in 13.84s
3063 passed, 179 skipped in 14.68s
```

And with `COVERAGE_CORE=sysmon`:

```
3063 passed, 179 skipped in 22.05s
3063 passed, 179 skipped in 21.90s
3063 passed, 179 skipped in 21.83s
3063 passed, 179 skipped in 22.89s
3063 passed, 179 skipped in 21.72s
```

They can be reproduced with the code from: https://github.com/pyca/cryptography by using `nox -e tests` (or `-e tests-coverage`). Requires having `rustc` and `nox` available on your system.

It looks like the `sysmon` implementation is pure python while the default is an extension module, so perhaps this is the source of the difference, and it'd show a win compared to the pure-Python tracer.

Hopefully this is a helpful test case.

**Comment by nedbat** [comment]
Currently, branch coverage does not get the same speed benefits as line coverage.  Cryptography is measuring branch coverage, so it doesn't surprise me that it's slower.

**Comment by alex** [comment]
Got it! May be helpful to note that in the changelog or somewhere.

**Comment by nedbat** [comment]
I've updated the changelog entry and the GitHub release. I'll close this for now. I'll be loud about when branch coverage is improved.  Thanks for jumping on it!

**Comment by alex** [comment]
Always happy to try a new option! Thanks for your work on this. Happy New Year!
