### ISSUE TITLE
100% covered when much is uncovered

### ISSUE THREAD

**Issue by mpenning** [coveragepy/coveragepy#1729]
I'm using:
- Python 3.11.2
- coveragepy version 7.4.0
- pytest version 7.4.3
- pytest-cov 4.1.0

I'm trying to get [coveragepy](https://github.com/nedbat/coveragepy) to work, but I can't seem to get the coverage portion to see uncovered lines.

Assume I clone [this ciscoconfparse2 repo](https://github.com/mpenning/ciscoconfparse2) (ref git hash `2feeff184d4dee6a2c3b10ff756e0e1151f2ffd2`) and then edit ciscoconfparse2/models_cisco.py. I currently see `Coveragepy ==> 100% covered` when I run `:Coveragepy show`, but that's obviously not true. There are loads of uncovered methods in that file.

How do I debug / fix what is wrong?

![image](https://github.com/nedbat/coveragepy/assets/36991/81cb6d90-4f90-4487-93b8-c3bca9c34175)

**Comment by nedbat** [comment]
I don't know what is printing `Coveragepy ==> 100% covered`, it looks like some kind of vim integration?  Can you use the coverage.py command-line tools to reproduce the situation?

**Comment by mpenning** [comment]
I just
- unloaded every plugin that I had (most were related to [ale](https://github.com/dense-analysis/ale)); I also ran `:PlugClean` to delete them from disk.
- renamed my `~/.vimrc` to `~/.vimrc.orig`

I still get that same `Coveragepy ==> 100% covered` message when I run `:Coveragepy show`, but I definitely don't show 100% coverage here...

```none
$ coverage report
Name                                                                      Stmts   Miss  Cover
---------------------------------------------------------------------------------------------
/home/mpenning/fixme/ciscoconfparse2/ciscoconfparse2/__init__.py             32      3    91%
/home/mpenning/fixme/ciscoconfparse2/ciscoconfparse2/ccp_abc.py             683    166    76%
/home/mpenning/fixme/ciscoconfparse2/ciscoconfparse2/ccp_util.py           3100   1583    49%
/home/mpenning/fixme/ciscoconfparse2/ciscoconfparse2/ciscoconfparse2.py    1555    559    64%
/home/mpenning/fixme/ciscoconfparse2/ciscoconfparse2/errors.py               88     40    55%
/home/mpenning/fixme/ciscoconfparse2/ciscoconfparse2/models_asa.py          838    239    71%
/home/mpenning/fixme/ciscoconfparse2/ciscoconfparse2/models_base.py         483    128    73%
/home/mpenning/fixme/ciscoconfparse2/ciscoconfparse2/models_cisco.py       1442    437    70%    <------
/home/mpenning/fixme/ciscoconfparse2/ciscoconfparse2/models_iosxr.py        646    315    51%
/home/mpenning/fixme/ciscoconfparse2/ciscoconfparse2/models_junos.py        348    126    64%
/home/mpenning/fixme/ciscoconfparse2/ciscoconfparse2/models_nxos.py         946    510    46%
/home/mpenning/fixme/ciscoconfparse2/ciscoconfparse2/protocol_values.py       5      0   100%
conftest.py                                                                 116     22    81%
test_Ccp_Abc.py                                                             408     20    95%
test_Ccp_Util.py                                                            425      0   100%
test_CiscoConfParse.py                                                      942      9    99%
test_Models_Asa.py                                                          122     14    89%
test_Models_Cisco.py                                                        635      6    99%
test_Models_Junos.py                                                         74      2    97%
---------------------------------------------------------------------------------------------
TOTAL                                                                     12888   4179    68%
```

Interestingly `:Coveragepy show` doesn't highlight any missing coverage lines.

What should I do next to debug this?

**Comment by nedbat** [comment]
It sounds like the vim plugin is buggy. I don't know which plugin it is, but I would contact that project.

**Comment by dwenjii** [comment]
> sounds like the vim plugin is buggy

That may be true, but I still don't see coverage gap highlights in vim even when I unload all other plugins.  The vim coverage highlights were the selling point to install coveragepy.  Is there a setting that I could be missing to make highlights work?
