### ISSUE TITLE
Different result between using coverage API and command line

### ISSUE THREAD

**Issue by feixiangdejiahao** [coveragepy/coveragepy#1731]
**Describe the bug**
I get different coverage results from coverage API and command line.

**To Reproduce**
Python 3.9.6, coverage_version: 7.4.0
```
def test():
    R = int(input())
    G = int(input())
    Target = (G * 2) - R
    print(Target)
test()
```
If I use the command line,  `coverage run test.py; coverage report`, I get the correct result.
```
1
2
3
Name          Stmts   Miss  Cover
---------------------------------
solution.py       6      0   100%
---------------------------------
TOTAL             6      0   100%
```
However, the coverage result is incorrect when I use the coverage API.
```
import coverage
cov = coverage.coverage()
cov.start()
def test():
    R = int(input())
    G = int(input())
    Target = (G * 2) - R
    print(Target)
test()
cov.stop()
result = cov.report()
print(result)
```
```
1
2
3
Name          Stmts   Miss  Cover
---------------------------------
solution.py      12      8    33%
---------------------------------
TOTAL            12      8    33%
33.333333333333336
```

**Comment by nedbat** [comment]
The different result is because you have a number of lines outside of the coverage measurement:
<img width="544" alt="image" src="https://github.com/nedbat/coveragepy/assets/23789/6e084b37-a9e7-4adf-8d44-fdeea4fb7855">
