### ISSUE TITLE
coverage report might raise FileNotFoundError when test patches glob

### ISSUE THREAD

**Issue by itamaro** [coveragepy/coveragepy#1735]
**Describe the bug**
When upgrading coverage internally from 5.4 to 7.4.0, I hit a `FileNotFoundError` being raised from [here](https://github.com/nedbat/coveragepy/blob/23a015c4a04bb61340273a42583f79aceb397f15/coverage/data.py#L153) that was not happening with 5.4.

Here's a sanitized partial traceback

```
...
  File "../coverage_integration_adapter..py", line ..., in coverage_report
    cov.combine(glob.glob(os.path.join(additional_coverage_dir, "*")))
  File ".../coverage/control.py", line 834, in combine
    combine_parallel_data(
  File ".../coverage/data.py", line 153, in combine_parallel_data
    with open(f, "rb") as fobj:
FileNotFoundError: [Errno 2] No such file or directory: '.../base_dir/some_path'
...
```

I think the issue is that the test patches glob to return non-existing `some_path` (and doesn't restore it during cleanup).

**To Reproduce**
I don't have a straightforward way to extract a sharable repro from the internal codebase where I ran into this issue.
I hit this using Python 3.10 and coverage 7.4.0 (when upgrading our version of coverage from 5.4).

**Expected behavior**
In coverage 5.4 the same potential issue exists (a patched glob can return non-existing files), but this doesn't result any exceptions - maybe because coverage 5.4 didn't try to compute hashes for "files to combine".

**Additional context**
It would be fair and reasonable to say this is an issue with the test misbehaving, not with coverage, and the test should be fixed.
I thought it might be worthwhile reporting it because the same (misbehaving) test works with earlier versions of coverage.
I could also workaround this without fixing the test itself by applying this patch to coverage:

```patch
diff --git a/coverage/data.py b/coverage/data.py
--- a/coverage/data.py
+++ b/coverage/data.py
@@ -150,11 +150,14 @@
             # we print the original value of f instead of its relative path
             rel_file_name = f

-        with open(f, "rb") as fobj:
-            hasher = hashlib.new("sha3_256")
-            hasher.update(fobj.read())
-            sha = hasher.digest()
-            combine_this_one = sha not in file_hashes
+        try:
+            with open(f, "rb") as fobj:
+                hasher = hashlib.new("sha3_256")
+                hasher.update(fobj.read())
+                sha = hasher.digest()
+                combine_this_one = sha not in file_hashes
+        except FileNotFoundError:
+            combine_this_one = False

         delete_this_one = not keep
         if combine_this_one:
```

**Comment by nedbat** [comment]
I would rather not try to make coverage defensive against aggressive monkeypatching in tests.  How hard would it be to update the test? If you could patch the fake implementation where you use glob instead of in the glob module itself, it will have a more localized effect.

**Comment by itamaro** [comment]
> How hard would it be to update the test?

That's definitely the right thing to do :)

I'm sure it's not *that* hard to fix the specific test (it will require overhauling the patching strategy in that test though).
For context, I am upgrading the "one and only version of coverage" in the Meta monorepo, so I am not an expert on most of the millions of the affected tests.

> If you could patch the fake implementation where you use glob instead of in the glob module itself, it will have a more localized effect.

looks like the test was actually trying to do that. glob was being imported in `app/util.py`, and the test was patching `app.util.glob.glob`. I guess this is one of those mock footguns, where the right thing to patch was `app.util.glob`, and patching `app.util.glob.glob` actually patches the `glob` function in the builtin `glob` module.
Interestingly, even calling `mocked_glob.stop()` doesn't unpatch the builtin `glob.glob`... but that's definitely out of scope for a coverage-specific issue :)

In any case, I'm totally ok with this being closed as "not a bug" / "user doing clowny things"!

**Comment by nedbat** [comment]
> I am upgrading the "one and only version of coverage" in the Meta monorepo

Wow, OK!   Let me know if other issues arise.
