### ISSUE TITLE
notes on our experience upgrading coverage 5.4 -> 7.4

### ISSUE THREAD

**Issue by itamaro** [coveragepy/coveragepy#1739]
following @nedbat's suggestion, I wanted to share a few notes from our experience (@bowiechen and I) upgrading coverage from 5.4 to 7.4 in the Meta monorepo, which means upgrading the version used by O(millions) of tests in one go.

this is not really a feature request nor a bug report!

overall, considering the scale of usage and the range of versions skipped, the upgrade was quite smooth.

## drop in coverage

by a large margin, the most significant issue we experienced was an "unexplained and unexpected drop in coverage across many tests". this ended up being the same issue reported and investigated [here](https://github.com/nedbat/coveragepy/issues/1300), and required a one line change (add `"thread"` to the `--concurrency` config flag) to fix.
unfortunately, going from "we're seeing hundreds of coverage regressions" to "oh this is upstream issue 1300 and there's a one line fix" was quite the journey.
I think that over the last ~year we have made several attempts at upgrading coverage, and abandoned those attempts after seeing the amount and scope of regressions (it's a constant struggle between "putting in the effort to complete an upgrade" and "applying a patch to the old version to work for us", and when the effort to upgrade looks more significant than initially expected, it's not uncommon to opt for the latter).
we spent several weeks chasing different theories, most of which focused on the regressing tests themselves ("are they doing clowny things?"), or the layers of internal integrations between our testing infrastructure and coverage (how we're running it, how we're processing the reports, what are all these monkeypatches that someone added 8 years ago), until @bowiechen tried bisecting coverage versions and found that 6.2 was the first version with regressions. @bowiechen then performed some neat tricks to "swap" the pypi-provided coverage with a git clone (ftr: we don't use either of those directly), which allowed us to bisect across the commits that went in between 6.1.2 and 6.2 and find [the offending commit](https://github.com/nedbat/coveragepy/commit/c9d821deba6f7ee5eef30fef5355f7c93808b4f9).  from there I found that we were passing `--concurrency multiprocessing` and that needed to be `--concurrency multiprocessing,thread` to preserve the pre-6.2 semantics ([more analysis](https://github.com/nedbat/coveragepy/issues/1300#issuecomment-1902274700)).

## new coverage run failures

the next issue we ran into was some tests that were fine before suddenly failing when running with coverage.
it took a few hours to root cause to misbehaving mocks, which I shared in greater detail [here](https://github.com/nedbat/coveragepy/issues/1735).

## coverage.misc.contract

the next issue we hit was existing code starting to complain about non-existing imports, specifically this one:

```python
from coverage.misc import contract
```

this was pretty easy to trace to the removal of `contract` from coverage. the offending code (that contained this import) should have never relied on importing it from coverage (like, why? just import `contract` directly), but 🤷‍♂️
while root causing and fixing it was easy, it led to exposing pre-existing typing issues. since the `contract` decorator from `coverage.misc` was effectively a no-op decorator, it served to hide type issues with the functions it was applied to, so this required some more fixing.

## .. and that's about it!

for such a widely-used library, running into "only" three problems is not bad, so great job coverage maintainers (👋 @nedbat) with keeping backwards compatibility!

**Comment by nedbat** [comment]
Thanks for the notes, and all your work.  I've responded on #1300 about the accidental change in behavior.
