### ISSUE TITLE
"No data was collected" when passing --source containing new line separated list

### ISSUE THREAD

**Issue by tsvtt** [coveragepy/coveragepy#1743]
In the `coverage.py` documentation, it's [said](https://coverage.readthedocs.io/en/latest/source.html#execution):  

> You can specify source to measure with the --source command-line
> switch, or the [run] source configuration value. The value is a comma-
> or **newline-separated list of directories or importable names** (packages
> or modules).

But when I try to run (exactly like this, with new lines):
```
coverage run --source='app.module1
app.module2
' -m unittest discover
```
I get: 
```
......../site-packages/coverage/control.py:887: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")
```
It works with commas instead of new lines:
```
coverage run --source='app.module1,app.module2' -m unittest discover
```
1. What version of Python are you using? 3.9/3.11 on Linux
1. What version of coverage.py shows the problem? version 7.4.1 with C extension.

**Comment by nedbat** [comment]
The docs could be clearer.  The command-line option is only comma-separated.  The configuration file option can be commas or newlines.  Is it important to be able to use newlines on the command line? That's definitely an unusual approach.

**Comment by tsvtt** [comment]
> Is it important to be able to use newlines on the command line? That's definitely an unusual approach.

I was trying to pass output of `git diff --name only ....` to the `source` option

**Comment by nedbat** [comment]
BTW: you might like [diff-cover](https://pypi.org/project/diff-cover/) if you want coverage on only the code you changed.

**Comment by nedbat** [comment]
Did you also get a warning, `Module SOMETHING was never imported. (module-not-imported)`?

Does the `paste` command help you make it work properly? https://stackoverflow.com/a/6539865/14343

**Comment by tsvtt** [comment]
> Did you also get a warning, `Module SOMETHING was never imported. (module-not-imported)`?
>
> Does the `paste` command help you make it work properly? https://stackoverflow.com/a/6539865/14343

Yes, I got a warning.

`paste` would probably help but `source` also accepts only dotted paths and doesn't accept slashed paths with extensions... It's indeed simpler to use `diff-cover`
