### ISSUE TITLE
How to exclude external packages from coverage report when using coverage.py API ?

### ISSUE THREAD

**Issue by AkashKumar7902** [coveragepy/coveragepy#1745]
when I use coverage.py API, it includes the coverage report for the external packages too. 

For example:
```
    /usr/lib/python3/dist-packages/yaml/reader.py:
    - 135
    - 139
    - 140
    - 147
    - 148
   ```
I don't want to include external packages in my coverage report.

**Comment by AkashKumar7902** [comment]
cover_pylib=False

will solve this issue.

**Comment by nedbat** [comment]
The usual way to do this is to use the ``--source=`` option to limit coverage.py's focus to your own directory: https://coverage.readthedocs.io/en/7.4.1/source.html#execution

**Comment by nedbat** [comment]
Closing as stale.
