### ISSUE TITLE
Exclude_lines unable to exclude entire if block from coverage.py in 5.5 version.

### ISSUE THREAD

**Issue by arbu16** [coveragepy/coveragepy#1756]
**Have you asked elsewhere?**
No
There are other good places to ask for help using coverage.py. These places let
other people suggest solutions, are more likely places for people to find your
question:

I am using exactly same thing as mentioned here https://github.com/nedbat/coveragepy/issues/831#issuecomment-517778185 in my .coveragerc file but my report is not as expected showing uncovered for lines inside if block.But when I used pragma: no cover it was able to exclude entire if block but I need if condition:  to be excluded in whole repository without using pragma: no cover in from of if block in codebase.

**Comment by nedbat** [comment]
Please provide a link to your code, there must be an error in it somewhere.  Can you try using the latest version of coverage? Why are you using 5.5?

**Comment by arbu16** [comment]
I can upgrade to 7.4.4 latest version so it is that in coverage 5.5 version it cannot exclude entire if block ?
Just FYI: I am exactly using same code ref:https://github.com/nedbat/coveragepy/issues/831#issuecomment-517778185.

**Comment by nedbat** [comment]
It would be easier to help if you could give us a link to your whole repo.  Can you at least show us the code that you wanted to exclude, but you weren't able to exclude?

**Comment by arbu16** [comment]
Hi @nedbat,I did upgrade coverage version from 5.5 to 7.4.4 but still same issue.

Because of privacy concern I will not be able to share link. Below I have reproduced the issue(Pasted the same code)
My .coveragerc file
[run]
concurrency = multiprocessing
parallel = True
[report]
exclude_lines = 

> 	pragma: no cover
>     	if TYPE_CHECKING:
>     	if typing.TYPE_CHECKING:

    	    	
  And my coverage for  if TYPE_CHECKING:  block
              
  if TYPE_CHECKING:                                                         --covered
    

> from x import y                                                               --uncovered
>     logging.info("Test Type check ignore for coverage") --uncovered

**Comment by nedbat** [comment]
Thanks. I hate to nit-pick, but please fix the formatting in the comment, and show the commands you used to run coverage, and show the output of `coverage report -m`.  Thanks.

**Comment by nedbat** [comment]
If you get more information, feel free to add it here, and I can re-open the issue.
