### ISSUE TITLE
Coverage html complains about parsing Aenum's _py2.py

### ISSUE THREAD

**Issue by amaranthjinn** [coveragepy/coveragepy#1760]
I ran 'coverage html' after 'coverage run --source=<third party directory> <some pytest in src directory'.
'coverage run' succeeds, but when running 'coverage html', I see an error:
coverage html --ignore-errors
/usr/local/home/.virtualenvs/p/lib/python3.11/site-packages/coverage/report.py:81: CoverageWarning: Couldn't parse Python file '/usr/local/home/.virtualenvs/p/lib/python3.11/site-packages/aenum/_py2.py' (couldnt-parse)
  coverage._warn(msg, slug="couldnt-parse")

the file complained on is https://github.com/ethanfurman/aenum/blob/master/aenum/_py2.py, which seems like a working simple python script?

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't link to a failing CI job. Answer the questions below:
1. What version of Python are you using?
    3.11.7
1. What version of coverage.py shows the problem? The output of `coverage debug sys` is helpful.
    6.3.2 without C extension
1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.
    aenum version is 3.1.15
1. What code shows the problem?  Give us a specific commit of a specific repo that we can check out. If you've already worked around the problem, please provide a commit before that fix.
   it seems agnostic of what my pytest does, simply set coverage run's source to the 3rd party directory that has the aenum will show the error.

1. What commands should we run to reproduce the problem? *Be specific*. Include everything, even `git clone`, `pip install`, and so on. Explain like we're five!
     If aenum is deployed to a third party package directory like
     /usr/local/home/.virtualenvs/p/lib/python3.11/site-packages
     run:
     coverage run --source=/usr/local/.virtualenvs/p/lib/python3.11/site-packages /usr/local/home/Workspace/p/xxj_test.py

     coverage html
    
**Expected behavior**
coverage html to succeed without error?

**Comment by amaranthjinn** [comment]
from coverage debug sys:

-- sys -------------------------------------------------------
               coverage_version: 6.3.2
                coverage_module: /usr/local/home/.virtualenvs/p/lib/python3.11/site-packages/coverage/__init__.py
                         tracer: -none-
                        CTracer: unavailable
           plugins.file_tracers: -none-
            plugins.configurers: -none-
      plugins.context_switchers: -none-
              configs_attempted: .coveragerc
                                 setup.cfg
                                 tox.ini
                                 pyproject.toml
                   configs_read: /usr/local/home/Workspace/p/pyproject.toml
                    config_file: None
                config_contents: -none-
                      data_file: -none-
                         python: 3.11.7 (main, Jan 14 2024, 00:38:57) [GCC 10.2.1 20210110]
                       platform: Linux-6.6.13-1rodete3-amd64-x86_64-with-glibc2.37
                 implementation: CPython
                     executable: /usr/local/home/.virtualenvs/p/bin/python3
                   def_encoding: utf-8
                    fs_encoding: utf-8
                            pid: 1007324
                            cwd: /usr/local/home/Workspace/p
                           path: /usr/local/home/.virtualenvs/p/bin
                                 /usr/local/home/Workspace/p/src
                                 /usr/local/buildtools/current/sitecustomize
                                 /opt/python3.11.7/lib/python311.zip
                                 /opt/python3.11.7/lib/python3.11
                                 /opt/python3.11.7/lib/python3.11/lib-dynload
                                 /usr/local/home/.virtualenvs/p/lib/python3.11/site-packages
                    environment: HOME = /usr/local/home/
                                 PYTHONPATH = /usr/local/buildtools/current/sitecustomize
                                 PYTHON_KEYRING_BACKEND = keyrings.gauth.GooglePythonAuth
                                 VIRTUALENVWRAPPER_PYTHON = /usr/bin/python3
                   command_line: /usr/local/home/.virtualenvs/p/bin/coverage debug sys
                sqlite3_version: 2.6.0
         sqlite3_sqlite_version: 3.45.0
             sqlite3_temp_store: 0
        sqlite3_compile_options: ATOMIC_INTRINSICS=1; COMPILER=gcc-13.2.0; DEFAULT_AUTOVACUUM
                                 DEFAULT_CACHE_SIZE=-2000; DEFAULT_FILE_FORMAT=4; DEFAULT_JOURNAL_SIZE_LIMIT=-1
                                 DEFAULT_MMAP_SIZE=0; DEFAULT_PAGE_SIZE=4096; DEFAULT_PCACHE_INITSZ=20
                                 DEFAULT_RECURSIVE_TRIGGERS; DEFAULT_SECTOR_SIZE=4096; DEFAULT_SYNCHRONOUS=2
                                 DEFAULT_WAL_AUTOCHECKPOINT=1000; DEFAULT_WAL_SYNCHRONOUS=2; DEFAULT_WORKER_THREADS=0
                                 DIRECT_OVERFLOW_READ; ENABLE_COLUMN_METADATA; ENABLE_DBSTAT_VTAB
                                 ENABLE_FTS3; ENABLE_FTS3_PARENTHESIS; ENABLE_FTS3_TOKENIZER
                                 ENABLE_FTS4; ENABLE_FTS5; ENABLE_LOAD_EXTENSION
                                 ENABLE_MATH_FUNCTIONS; ENABLE_PREUPDATE_HOOK; ENABLE_RTREE
                                 ENABLE_SESSION; ENABLE_STMTVTAB; ENABLE_UNLOCK_NOTIFY
                                 ENABLE_UPDATE_DELETE_LIMIT; HAVE_ISNAN; LIKE_DOESNT_MATCH_BLOBS
                                 MALLOC_SOFT_LIMIT=1024; MAX_ATTACHED=10; MAX_COLUMN=2000
                                 MAX_COMPOUND_SELECT=500; MAX_DEFAULT_PAGE_SIZE=32768; MAX_EXPR_DEPTH=1000
                                 MAX_FUNCTION_ARG=127; MAX_LENGTH=1000000000; MAX_LIKE_PATTERN_LENGTH=50000
                                 MAX_MMAP_SIZE=0x7fff0000; MAX_PAGE_COUNT=0xfffffffe; MAX_PAGE_SIZE=65536
                                 MAX_SCHEMA_RETRY=25; MAX_SQL_LENGTH=1000000000; MAX_TRIGGER_DEPTH=1000
                                 MAX_VARIABLE_NUMBER=250000; MAX_VDBE_OP=250000000; MAX_WORKER_THREADS=8
                                 MUTEX_PTHREADS; SECURE_DELETE; SOUNDEX
                                 SYSTEM_MALLOC; TEMP_STORE=1; THREADSAFE=1
                                 USE_URI

**Comment by nedbat** [comment]
Can you try with the latest coverage? 6.3.2 is two years old.  Also, if you could provide me with specific instructions of exactly what code is where, including the directory layout and how to install the packages you use, it will be easier for me to replicate the problem

**Comment by nedbat** [comment]
Oh, hmm: you aren't getting an error, you are getting a warning.  The command succeeds and produces an HTML report, doesn't it?  If you want, you can suppress the warning: https://coverage.readthedocs.io/en/7.4.4/cmd.html#warnings

**Comment by amaranthjinn** [comment]
Yeah, I was able to bypass the html report failure with 'ignore error'.
I ran into some weird issues with updating the coverage version. Because my project is managed by Poetry, it seems like the coverage.py is brought in as a dependency of a dependency that's specified in my project's toml (coverage is not directly specified in the toml). I updated the pytest and pytest-cov to the latest release, but the updated poetry.lock still shows coverage on the old version. What do you suggest may be the issue (is coverage bundled with some standard python libraries) or ways to correct this?

**Comment by amaranthjinn** [comment]
The pytest related dependencies that are specified in the toml:
pytest = "^8.1.1"
pytest-asyncio = "0.19.*"
pytest-benchmark = "^3.4"
pytest-cov = "^5.0.0"
pytest-qt = "^4.0.2"
pytest-timeout = "^2.1.0"
pytest-xdist = "^2.5.0"

**Comment by nedbat** [comment]
Thanks for confirming that this is not a failure of the html report.  I'll close this issue.

I don't know why you are locking to an old version of coverage.py.  I thought it could be because you run on an old version of Python, but 6.3.2 is not the last version to support 3.7 (7.2.7 was) or 3.6 (6.2 was), and you are running on 3.11 in any case.  I don't use poetry so I don't know what might affect its locking.
