### ISSUE TITLE
get coverage data fail

### ISSUE THREAD

**Issue by 850319644** [coveragepy/coveragepy#1761]
**Describe the bug**
Use the coverage api to count code coverage, and call erase after each data acquisition. The code coverage can be counted for a while. After a while, it is found that the code coverage cannot be counted. When calling the get_data function, it will prompt that the data is not obtained.

Error info:
Coverage.py warning: No data was collected. (no-data-collected)

Code:
cov = coverage.Coverage(branch=True, data_suffix=True, config_file=".coveragerc", include=[u'/data/ibox/app/cgi/*'])
cov.start()

  while True:
      time.sleep(report_frequency)
      try:
          cover.stop()
          LOG.log_info("stop coverage")
          reporter.report()
      except Exception as e:
          LOG.log_exception("report data error: %s", e)
      cover.erase()
      LOG.log_info("start coverage")
      cover.start()
      LOG.log_info("start coverage")

**Comment by nedbat** [comment]
Hi, sorry you are having trouble.  We'll need more information.  You haven't said what your main program is doing.  Perhaps it's not running any more after some time?  Can you provide a reproducible example?

**Comment by nedbat** [comment]
When you get more information, feel free to add it, and I can re-open the issue.
