### ISSUE TITLE
NoSource error when running coverage in Jupyter notebook

### ISSUE THREAD

**Issue by sunscorch** [coveragepy/coveragepy#1762]
**Describe the bug**
when run coverage in juypter, I got '/tmp/ipykernel_8207/132322275.py

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't link to a failing CI job. Answer the questions below:
1. What version of Python are you using? 3.10
1. What version of coverage.py shows the problem?  7.4.4
 run below code in local python ide works fine , but only fails in juypter:
```
import unittest
import coverage



def add(a, b):
    return a + b


def subtract(a, b):
    return a - b


def multiply(a, b):
    return a * b


def divide(a, b):
    if b == 0:
        raise ValueError("Cannot divide by zero.")
    return a / b



class TestCalculator(unittest.TestCase):
    def test_add(self):
        self.assertEqual(add(1, 2), 3)

    def test_subtract(self):
        self.assertEqual(subtract(10, 5), 5)

    def test_multiply(self):
        self.assertEqual(multiply(3, 7), 21)

    def test_divide(self):
        self.assertEqual(divide(10, 2), 5)
        self.assertRaises(ValueError, divide, 10, 0)



#cov = coverage.Coverage()
cov = coverage.Coverage()
cov.start()


suite = unittest.TestLoader().loadTestsFromTestCase(TestCalculator)
unittest.TextTestRunner().run(suite)


cov.stop()
cov.save()

cov.report()
cov.html_report()  
```

**Comment by nedbat** [comment]
When I run your code, I see this error:
```
NoSource: No source for code: '/private/var/folders/6j/khn0mcrj35d1k3yylpl8zl080000gn/T/ipykernel_35674/3088881885.py'.
```
Perhaps this is the error you saw, but you didn't include the whole message.

Do you need to run a test suite inside a Jupyter notebook? It's an unusual approach.

**Comment by nedbat** [comment]
The source file doesn't even exist while the cell is running...

**Comment by sunscorch** [comment]
> The source file doesn't even exist while the cell is running...
thx for your time to look into this
yes , this is pretty interesting. 
reg NoSource: No source for code: '/private/var/folders/6j/khn0mcrj35d1k3yylpl8zl080000gn/T/ipykernel_35674/3088881885.py'.
I guess this is due to different os uses different path to store the temp file..

**Comment by chmp** [comment]
To continue our discussion on mastodon: the file names are a hack by IPython. These files are never found on disk and are simply used as a stand-in for the notebook cells. However to support tracebacks, IPython stores the cell contents in the `linecache.cache` object (see also [here](https://cprohm.de/article/better-test-output-with-ast-rewriting-and-a-patched-standard-library.html/)). Using the line cache allows to hack together a quick solution:

```python
import linecache
import coverage.python

def add_coverage_ipython_support():
    if coverage.python.get_python_source is get_python_source:
        return

    coverage.python._get_python_source = coverage.python.get_python_source
    coverage.python.get_python_source = get_python_source


def get_python_source(filename: str) -> str:
    if filename in linecache.cache:
        return "".join(linecache.cache[filename][2])

    return coverage.python._get_python_source(filename)
```

After executing `add_coverage_ipython_support()`, the example in the first post, seems to give sensible results (albeit it with random filenames).

**Comment by chmp** [comment]
I started to write a [more robust version of this code](https://github.com/chmp/ipytest/pull/110) as a coverage plugin. Using it with a `.coveragerc` file or via `cov.config.plugins.append("ipytest.coverage_plugin")` adds support for coverage collection in notebooks. In principle it also works with `pytest-cov`, but I have to figure out how to make it ergonmic to use.

**Comment by chmp** [comment]
I pushed `ipytest==0.14.1` with coverage.py support via a small plugin. For usage, see for example the corresponding [integration test](https://github.com/chmp/ipytest/blob/main/tests/TestCoverage.ipynb).

**Comment by nedbat** [comment]
@sunscorch Let us know if ipytest solves your problem.

**Comment by sunscorch** [comment]
> @sunscorch Let us know if ipytest solves your problem.

LGTM,  thanks a lot for your help!!!!!!!!! cheers
