### ISSUE TITLE
is there a go sdk for coveragepy ?

### ISSUE THREAD

**Issue by AkashKumar7902** [coveragepy/coveragepy#1763]
**Describe your situation**
Is there a go sdk for coveragepy so that I can invoke commands like `coverage run app.py` without using os/exec package from go ecosystem.

**Comment by nedbat** [comment]
Coverage.py is a Python program.  I don't know Go, are there SDKs to invoke Python programs?  Why not use the os/exec package?

**Comment by nedbat** [comment]
If you can help me understand what is needed, we can talk about how to solve your problem.  Comment here with more details when you have them.
