### ISSUE TITLE
HTML column sorting is inconsistent across index pages

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#1766]
**Describe the bug**

1. Visit the sample HTML report: https://nedbatchelder.com/files/sample_coverage_html/index.html
2. Click the "coverage" column to sort by total coverage percentage
3. Click the "Functions" tab at the top to switch to the by-function index page.
4. Now the "partial" column is sorted.

This is because the number of the column is stored, but the function and class index pages have one more column, so the numbering is off.

This is with coverage.py 7.5.0.

**Expected behavior**
If you've sorted by a column, the same-named column should be sorted when switching to another page.

**Comment by devdanzin** [comment]
Seems like the simple way to do it would be adding `id`s the the headers, getting the `th` from (and storing) it in `sortColumn` and loading it in `coverage.wire_up_sorting` (which would also pass the `id` from the click event).

I can work on a PR tonight if it's still open.

**Comment by nedbat** [comment]
Thanks! Extra-credit homework: if you sort the function page by function name, the file index page doesn't have that column, so what should the sort order be?

**Comment by devdanzin** [comment]
We could store the last column the index page was sorted by and sort on it again. But then we'd have one more question when the user goes back to the function page. We have two scenarios:
 - The user didn't re-sort by another column: should the function page now be sorted by function (as it was last time the user was there) or by whatever was the last sort column on the index page?
 - The user sorted by some other column: then we can sort the function/class page by that new column.

I think it would be easier to keep storing the last column to sort with, while adding a flag that means "sort the function or class pages by function/class" when set. Let me give it a try.

**Comment by nedbat** [comment]
This is now released as part of [coverage 7.5.1](https://pypi.org/project/coverage/7.5.1).
