### ISSUE TITLE
7.5.0 broke coverage-badge

### ISSUE THREAD

**Issue by ErwinJunge** [coveragepy/coveragepy#1767]
**Describe the bug**
The recent release of 7.5.0 broke our usage of coverage-badge

**To Reproduce**

1. What version of Python are you using?  `3.12`
1. What version of coverage.py shows the problem?  `7.5.0`
1. What versions of what packages do you have installed? `coverage-7.5.0 coverage-badge-1.1.0`
1. What code shows the problem?  https://github.com/dbrgn/coverage-badge/commit/db8de11bb126699b58c14e44040c22ddd6d9dc52
1. What commands should we run to reproduce the problem? 

```
# first, run pytest with coverage enabled
python3 -m pip install coverage-badge # this pulls in coverage
coverage-badge -o badge.svg
Traceback (most recent call last):
  File "/usr/local/bin/coverage-badge", line 8, in <module>
    sys.exit(main())
             ^^^^^^

  File "/usr/local/lib/python3.12/site-packages/coverage_badge/__main__.py", line 171, in main
    total = get_total()
            ^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/coverage_badge/__main__.py", line 76, in get_total
    return coverage.results.Numbers(precision=cov.config.precision).display_covered(total)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Numbers' object has no attribute 'display_covered'
```

**Expected behavior**
Command generates coverage badge

**Additional context**
Issue likely caused by dropping of method in https://github.com/nedbat/coveragepy/commit/4e5027338b93fc893c5e6e82c8a234c48f0b95e7#diff-9ecbfd6fa815c19afb2ab33c252cab155422453c975ed61f671617eb95ef840eL230

**Comment by ErwinJunge** [comment]
This issue is potentially invalid, since `coverage-badge` updated to match coverage 7.5.0 in https://github.com/dbrgn/coverage-badge/pull/28.

My remaining question is now just whether the dropping of `Numbers.display_covered` was intentional, or accidental. If it was intentional, this issue is definitely invalid and can be closed.

**Comment by nedbat** [comment]
The dropping was intentional, a refactoring of an internal interface.  I'm happy to talk to people who need other supported interfaces.
