### ISSUE TITLE
pragma: no cover ignored and coverage wrongly calculated

### ISSUE THREAD

**Issue by Zethson** [coveragepy/coveragepy#1795]
**Describe the bug**

![image](https://github.com/codecov/feedback/assets/21954664/846bd53d-aab2-43d4-9905-37e7b615f107)

![image](https://github.com/codecov/feedback/assets/21954664/2ee59e80-1ea7-45aa-ae08-cde1425f5d34)

`pragma: no cover` sections are not covered

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't link to a failing CI job. Answer the questions below:
1. What version of Python are you using?

3.10

1. What version of coverage.py shows the problem? The output of `coverage debug sys` is helpful.

coverage==7.5.1

1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.

```quote
+ aiobotocore==2.13.0
 + aiohttp==3.9.5
 + aioitertools==0.11.0
 + aiosignal==1.3.1
 + anndata==0.10.7
 + anyio==4.3.0
 + appdirs==1.4.4
 + array-api-compat==1.6
 + asciitree==0.3.3
 + asgiref==3.8.1
 + asttokens==2.4.1
 + attrs==23.2.0
 + beautifulsoup4==4.12.3
 + bionty-base==0.37.2
 + bleach==6.1.0
 - boto3==1.34.110
 + boto3==1.34.106
 - botocore==1.34.110
 + botocore==1.34.106
 + certifi==2024.2.2
 + cfgv==3.4.0
 + chardet==5.2.0
 + charset-normalizer==3.3.2
 + click==8.1.7
 + comm==0.2.2
 + coverage==7.5.1
 + debugpy==1.8.1
 + decorator==5.1.1
 + defusedxml==0.7.1
 + deprecation==2.1.0
 + dj-database-url==2.1.0
 + django==5.0.6
 + executing==2.0.1
 + faker==25.2.0
 + faker-biology==0.6.4
 + faker-python==0.0.1
 + fasteners==0.19
 + fastjsonschema==2.19.1
 + fastobo==0.12.3
 + fcsparser==0.2.8
 + frozenlist==1.4.1
 + fsspec==2024.3.1
 + gotrue==2.4.2
 + graphviz==0.20.3
 + h11==0.14.0
 + h5py==3.11.0
 + httpcore==0.17.3
 + httpx==0.24.1
 + identify==2.5.36
 + idna==3.7
 + importlib-metadata==7.1.0
 + iniconfig==2.0.0
 + ipykernel==6.29.4
 + ipython==8.24.0
 + jedi==0.19.1
 + jinja2==3.1.4
 + jsonschema==4.22.0
 + jsonschema-specifications==2023.12.1
 + jupyter-client==8.6.1
 + jupyter-core==5.7.2
 + jupyterlab-pygments==0.3.0
 + lamindb==0.72.0 (from file:///home/runner/work/lamindb/lamindb)
 + markdown-it-py==3.0.0
 + markupsafe==2.1.5
 + matplotlib-inline==0.1.7
 + mdurl==0.1.2
 + mistune==3.0.2
 + mudata==0.2.3
 + multidict==6.0.5
 + natsort==8.4.0
 + nbclient==0.10.0
 + nbconvert==7.16.4
 + nbformat==5.10.4
 + nbproject==0.10.3
 + nbproject-test==0.5.1
 + nbstripout==0.6.1
 + nest-asyncio==1.6.0
 + networkx==3.3
 + nodeenv==1.8.0
 + numcodecs==0.12.1
 + numpy==1.26.4
 + orjson==3.10.3
 + pandas==1.5.3
 + pandocfilters==1.5.1
 + parso==0.8.4
 + pexpect==4.9.0
 + pluggy==1.5.0
 + postgrest==0.13.2
 + pre-commit==3.7.1
 + prompt-toolkit==3.0.43
 + pronto==2.5.5
 + psutil==5.9.8
 + psycopg2-binary==2.9.9
 + ptyprocess==0.7.0
 + pure-eval==0.2.2
 + pyarrow==16.1.0
 + pydantic==1.10.15
 + pygments==2.18.0
 + pytest==8.2.1
 + pytest-cov==5.0.0
 + python-dotenv==1.0.1
 + pytz==2024.1
 + pyzmq==26.0.3
 + rapidfuzz==3.9.1
 + readfcs==1.1.8
 + realtime==1.0.4
 + referencing==0.35.1
 + requests==2.32.2
 + rich==13.7.1
 + rich-click==1.8.2
 + rpds-py==0.18.1
 + s3fs==2024.3.1
 + scipy==1.12.0
 + sniffio==1.3.1
 + soupsieve==2.5
 + sqlparse==0.5.0
 + stack-data==0.6.3
 + storage3==0.7.4
 + strenum==0.4.15
 + supabase==2.2.1
 + supafunc==0.3.3
 + tinycss2==1.3.0
 + tornado==6.4
 + traitlets==5.14.3
 + typing-extensions==4.11.0
 + universal-pathlib==0.1.4
 - urllib3==2.2.1
 + urllib3==1.26.18
 + wcwidth==0.2.13
 + webencodings==0.5.1
 + websockets==12.0
 + wrapt==1.16.0
 + yarl==1.9.4
 + zarr==2.18.1
 + zipp==3.18.2
```

1. What code shows the problem?  Give us a specific commit of a specific repo that we can check out. If you've already worked around the problem, please provide a commit before that fix.

https://github.com/laminlabs/lamindb/commit/aa3ace125be6b4d2a2d167318d6c9056800c0002

1. What commands should we run to reproduce the problem? *Be specific*. Include everything, even `git clone`, `pip install`, and so on. Explain like we're five!

1. git clone https://github.com/laminlabs/lamindb
2. run coverage on it

**Expected behavior**

I expect the `#pragma: no cover` sections to be covered

**Additional context**

This issue was discussed with the codecov team who think that this is likely to be a coveragepy bug https://github.com/codecov/feedback/issues/390

**Comment by nedbat** [comment]
> What commands should we run to reproduce the problem? Be specific. Include everything, even git clone, pip install, and so on. Explain like we're five!
> run coverage on it

I'm sorry, "run coverage on it" is not specific enough.  Can you show the exact commands you ran after `git clone` that caused the output you saw?

**Comment by Zethson** [comment]
Sorry @nedbat .

I'm having a hard time summarizing the steps which are documented here: https://github.com/laminlabs/lamindb/blob/main/.github/workflows/build.yml

If this isn't good enough, I'll see whether I can find a way to write it up more clearly.

**Comment by devdanzin** [comment]
Cannot reproduce from a very streamlined test. Can you run this same test?

First, create a file, e.g. "_anncov.py" with:
```python
import coverage
cov = coverage.Coverage()
cov.start()
from lamindb import _annotate
cov.stop()
cov.save()
cov.html_report()
```

Then run `python _anncov.py` and check the generated HTML report. It works as expected for me, what do you get?

![image](https://github.com/nedbat/coveragepy/assets/74280297/a26afd00-768f-419c-9c8a-d0974c878a34)

Running through pytest-cov also seems to work correctly.

Is postgres necessary for running the test suite?

**Comment by Zethson** [comment]
(Will answer after my holidays)

**Comment by Zethson** [comment]
Running what you suggested, I get 30% coverage (which is totally not enough) and the `#pragma: no cover` are still ignored. 

I think that there's something tricky with our CI setup and this will be hell to debug. It's not terribly urgent and I'll report back if I ever find an easier way to reproduce the issue or have more information.

Thanks and sorry again for the bad issue.
