### ISSUE TITLE
How to exclude a line without the block it introduces?

### ISSUE THREAD

**Issue by Apakottur** [coveragepy/coveragepy#1797]
I am working on a big project where we often use the the match statement like so:
```python
match something:
    case type_1():
        logic_1()
    case type_2():
        logic_2():
    case _:
        assert_never(something)
```

In this code example the default case should never happen, but sometimes we also have:
```python
match something:
    case type_1():
        logic_1()
    case type_2():
        logic_2():
    case _:
        print("Default case")
```

When running coverage, I want to exclude all the `assert_never` lines because they should never run, so I use this configuration option:
```ini
exclude_lines =
    assert_never
```

This removes these lines from the coverage report, but the `case _` lines are still reported as missing.

If I do this:
```ini
exclude_lines =
    case _
```

Then the entire block is excluded, including the print statement, which I do want to ensure coverage on.

Another approach is to use the `# pragma: no cover` comment, but we have hundreds of these cases and that would be very inconvenient to use.

How can I configure coverage to exclude `case _` when the only thing I have inside is `assert_never`, but not exclude it in other cases?

**Comment by nedbat** [comment]
This is now possible in 7.6.0 with multi-line exclusion regexes: https://coverage.readthedocs.io/en/7.6.0/excluding.html#multi-line-exclusion-regexes
