### ISSUE TITLE
how to write a parser for raw coverage file (.coverage) and a json reporter in golang ?

### ISSUE THREAD

**Issue by AkashKumar7902** [coveragepy/coveragepy#1806]
Is the current parser solely depends on raw coverage file to get every possible coverage information ?

**Comment by nedbat** [comment]
Can you say more about why you want to re-write `coverage json` in Golang?  What is missing from it?

**Comment by AkashKumar7902** [comment]
I initially was downloading python, pip and coverage in dockerfile of a go project which increased the image size, so I was hoping that if the parser can be written in go, i would not need to download these things. But recently i found coverage package in apt, which is increasing negligible size of image. This is not required now.
