### ISSUE TITLE
Overall Branch and Function coverage percentage in json report 

### ISSUE THREAD

**Issue by AkashKumar7902** [coveragepy/coveragepy#1817]
is there a way to get overall branch and function coverage percentage for each file as well as total across all files by analyzing json report ?

Edit: I gone through the codebase and found this https://github.com/nedbat/coveragepy/blob/4b59ba259fd3a11357814e05a7691f5cd76b1b56/coverage/results.py#L284C1-L289C1

so, in json report summary, line coverage % equals `covered_lines/num_statements*100` and branch coverage % equals `covered_branches/num_branches*100`, right ?

A sample summary for reference:
```json
      "summary": {
        "covered_lines": 10,
        "num_statements": 10,
        "percent_covered": 91.66666666666667,
        "percent_covered_display": "92",
        "missing_lines": 0,
        "excluded_lines": 0,
        "num_branches": 2,
        "num_partial_branches": 1,
        "covered_branches": 1,
        "missing_branches": 1
      },
```

can something like covered_functions and num_functions be added to this summary ?

**Comment by nedbat** [comment]
Try the version we just released this week, 7.6.0.  It adds per-function and per-class statistics to the JSON report.

**Comment by AkashKumar7902** [comment]
Hey @nedbat  

https://pastebin.com/d0hfha9p

the above is the json generated by 7.6.0 but i don't know how to calculate overall function of each file and throughout all files, in the json report the function section in each file, in the summary its still the same as previous (only info to calculate branch and line coverage % is present)

**Comment by nedbat** [comment]
I guess I don't know what you are trying to calculate.  Can you give a concrete example of the program you are running, and what result you want to get?

**Comment by AkashKumar7902** [comment]
https://github.com/keploy/keploy/blob/e5ab5a470d24e65a2171275cadbeaf272c801b78/pkg/models/testrun.go#L19
the above is the struct which I want to populate for python. 

And this is how I am calculating the line & branch coverage % from json report. 
https://github.com/keploy/keploy/blob/e5ab5a470d24e65a2171275cadbeaf272c801b78/pkg/platform/coverage/python/python.go#L66

I was wondering can I calculate the function percentage per file and overall ?

**Comment by nedbat** [comment]
`num_functions` can be counted from the JSON report.  I don't know what you want `covered_functions` to be? The number of functions that are 100% covered?

**Comment by devdanzin** [comment]
I believe you can calculate covered_functions and num_functions from the JSON data, does that help? If so, here's how you'd do it in Python:

```python
import json
from pprint import pprint

FILENAME = r"coverage.json"
report = json.load(open(FILENAME))

total_functions_num = 0
total_functions_covered = 0
coverage_threshold = 70

summary = {}

for file in report["files"]:
    summary[file] = {"functions": 0, "covered_functions": 0}
    for function in report["files"][file]["functions"]:
        func_res = report["files"][file]["functions"][function]
        total_functions_num += 1
        summary[file]["functions"] += 1
        if func_res["summary"]["percent_covered"] >= coverage_threshold:
            total_functions_covered += 1
            summary[file]["covered_functions"] += 1
    summary[file]["percent_covered_functions"] = summary[file]["covered_functions"] * 100 / summary[file]["functions"]


pprint(summary)
print(f"Total functions: {total_functions_num}")
print(f"Total functions covered: {total_functions_covered}")
print(f"Percent functions covered: {total_functions_covered * 100 / total_functions_num}")

```

**Comment by AkashKumar7902** [comment]
@devdanzin thanks for this. how to get covered_functions was a  main blocker for me. thanks for pointing towards threshold approach to calculate it.
