### ISSUE TITLE
Setup.py attempts to import obsolete 'distutils'

### ISSUE THREAD

**Issue by bignose-debian** [coveragepy/coveragepy#1820]
The Python 'distutils' library has been [deprecated for a long time](https://peps.python.org/pep-0632/), is [prominently documented as obsolescent](https://docs.python.org/3.11/distutils/index.html), and [as of Python 3.12, the 'distutils' import is no longer available](https://docs.python.org/3/whatsnew/3.12.html#distutils).

> Note
> The entire distutils package has been deprecated and will be removed in Python 3.12. This documentation is retained as a reference only, and will be removed with the package. See the [What’s New](https://docs.python.org/3.11/whatsnew/3.10.html#distutils-deprecated) entry for more information.

The Coverage.py `setup.py` program still imports from `distutils`; this relies on a temporary magic work-around in the `setuptools` library.

The `setup.py` should be improved to no longer attempt to import `distutils` at all.

**Comment by devdanzin** [comment]
Thanks for the report! I've tried to fix this in #1823.
