### ISSUE TITLE
`coverage html` creates HTML files that contain duplicate `id` attributes.

### ISSUE THREAD

**Issue by kkotenko** [coveragepy/coveragepy#1831]
**Describe the bug**
`coverage html` creates HTML files that contain duplicate `id` attributes.

**To Reproduce**
1. **What version of coverage.py shows the problem?** 7.4.4, 7.6.1
2. **What commands should we run to reproduce the problem?** 
2.1. Run coverage in a way that will provide coverage on at least one file.
2.2. Run `coverage html`
2.3. Review the source code of the generated HTML files.
2.4. Note that the HTML files each contain 2 instances of `<a id="prevFileLink"`, `<a id="indexLink"` and `<a id="nextFileLink"`. Project-wide inspections in IDEs may report these as 6 errors per file.

**Expected behavior**
id attributes are expected to be unique per HTML document. ([W3C link](https://www.w3schools.com/html/html_id.asp))

**Comment by nedbat** [comment]
Hmm, I'm not seeing that.  Here's the sample HTML for 7.6.1: https://nedbatchelder.com/files/sample_coverage_html/index.html  The page for each .py file (like https://nedbatchelder.com/files/sample_coverage_html/z_7b071bdc2a35fa80_makefiles_py.html) has two "prev" links, but they are different in the source:
```html
<a id="prevFileLink" class="nav" href="z_7b071bdc2a35fa80_cogapp_py.html">&#xab; prev</a>
...
<a class="nav" href="z_7b071bdc2a35fa80_cogapp_py.html">&#xab; prev</a>
```
Can you share one of the files where you see the duplicate ids?

**Comment by kkotenko** [comment]
My apologies. It seems some of the files I was looking at were created with an older version of coverage. 7.6.1, at least, does not produce this behavior. 

Thanks for looking into it.
