### ISSUE TITLE
Setting COVERAGE_CORE to sysmon does not generate dynamic contexts

### ISSUE THREAD

**Issue by DarkaMaul** [coveragepy/coveragepy#1844]
As noted in the answer below, this is not a bug because the feature is not yet supported.

~~**Describe the bug**~~ 

~~When setting `COVERAGE_CORE=sysmon`, dynamic contexts are not generated.~~

~~**To Reproduce**~~
~~How can we reproduce the problem?  Please *be specific*. Don't link to a failing CI job. Answer the questions below:~~ 
~~1. What version of Python are you using?~~ 
~~3.12.5~~

~~1. What version of coverage.py shows the problem? The output of `coverage debug sys` is helpful.~~
~~`Coverage.py, version 7.4.4 with C extension`~~

~~1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.~~
~~A simple hello-world package~~

~~1. What code shows the problem?  Give us a specific commit of a specific repo that we can check out. If you've already worked around the problem, please provide a commit before that fix.~~

~~Install the reproduction repository~~
```shell
git clone git@github.com:DarkaMaul/coverage-reproduction.git /tmp/coverage-reproduction
cd /tmp/coverage-reproduction
python3 -m venv env
source ./env/bin/activate
pip install -e '.[dev]'
```

~~Bug:~~
```
COVERAGE_CORE=sysmon python -m coverage run -m pytest . --strict-markers
python -m coverage html --show-contexts                
```
```
/private/tmp/coverage-reproduction/env/lib/python3.12/site-packages/coverage/html.py:123: CoverageWarning: No contexts were measured
  self.coverage._warn("No contexts were measured")
Wrote HTML report to htmlcov/index.html
```

~~**Expected behavior**~~

~~Changing the `COVERAGE_CORE` variable should not modify how contexts are generated.~~

```
COVERAGE_CORE=ctrace python -m coverage run -m pytest . 
python -m coverage html --show-contexts
```
```
Wrote HTML report to htmlcov/index.html
```

~~**Additional context**~~

~~The issue was first discovered when trying to use sysmon in https://github.com/pypi/warehouse/pull/16621~~

**Comment by nedbat** [comment]
Correct, dynamic contexts are not yet supported with the sysmon core, as noted in the docs and [changelog](https://coverage.readthedocs.io/en/7.6.1/changes.html#version-7-4-0-2023-12-27):

> - In Python 3.12 and above, you can try an experimental core based on the new [sys.monitoring](https://docs.python.org/3/library/sys.monitoring.html#module-sys.monitoring) module by defining a COVERAGE_CORE=sysmon environment variable. This should be faster for line coverage, but not for branch coverage, and plugins and dynamic contexts are not yet supported with it. I am very interested to hear how it works (or doesn’t!) for you.

**Comment by DarkaMaul** [comment]
Oh, my bad - I overread this line.
Sorry for the noise here.
