### ISSUE TITLE
Generating coverage report outside source code?

### ISSUE THREAD

**Issue by oerp-odoo** [coveragepy/coveragepy#1865]
Is it mandatory to have access to source code when generating report?

I thought I could do this: execute `coverage run` in my docker container. Get the `.coverage` file and then use it to generate report. But if I try that outside of container (e.g. `coverage lcov --data-file=src/common/test/coverage/.coverage -o coverage.lcov`), I get errors like: 

```
No source for code: '/opt/odoo/projects/custom/demo_module/__init__.py'.
```

If I generate report inside container, then it works fine. I thought `.coverage` file has everything you need to generate report? Or it still needs to access source code during generation?

**Comment by nedbat** [comment]
Your source code is only used during the report generation, not while running the code.  You need to run the reporting commands (`report`, `html`, `xml`, `json`, or `lcov`) somewhere that the source is available.  You might need a `[paths]` section in your configuration file to tell coverage how to map the paths between the running environment and the reporting environment.
