### ISSUE TITLE
The lines in the .coverage file do not match the executed line numbers in the report.

### ISSUE THREAD

**Issue by zhuangzehua** [coveragepy/coveragepy#1872]
**Describe the bug**

The Python environment is 2.7.13. When using coverage 4.4.1, I encountered a discrepancy between the lines data in the generated .coverage file and the executed line numbers shown in the HTML report. For example:
`"/usr/zk/sync.py": [
    297,
    298,
    57,
    22,
    687
]
`
However, the file /usr/zk/sync.py has fewer than 100 lines, and line 22 was not executed.

**Comment by nedbat** [comment]
Coverage 4.4.1 is quite old.  Coverage 5.5 still supported Python 2.  Try upgrading to 5.5.  I can't support Python 2 anymore, but that version might work for you.

**Comment by zhuangzehua** [comment]
> Coverage 4.4.1 is quite old. Coverage 5.5 still supported Python 2. Try upgrading to 5.5. I can't support Python 2 anymore, but that version might work for you.

I remember that the .coverage file in coverage version 5.5 is a binary file, which means it cannot be directly accessed to extract data. In version 4.4.1, I can directly read the content and convert it to JSON. I need to access the lines data in the .coverage file for further processing.

**Comment by nedbat** [comment]
You should take a look at the `coverage json` command.  It writes a supported JSON data file.
