### ISSUE TITLE
"if True" or "if False" coverage show error.

### ISSUE THREAD

**Issue by luoyue2087** [coveragepy/coveragepy#1890]
**Describe the bug**
As shown in the following picture：

![image](https://github.com/user-attachments/assets/c4c3a528-1c7e-4bb4-b725-97ec00cd3e49)

**Comment by nedbat** [comment]
You'll need to say more.  What is wrong with the picture? What did you expect instead of this?

**Comment by luoyue2087** [comment]
Sorry，my question is ：
why not report lines is miss which from line 2 to line 8，and mark as red line？

**Comment by nedbat** [comment]
The `if False` on line 1 means the rest of the code is not compiled at all. It doesn't exist in the bytecode.

**Comment by luoyue2087** [comment]
Thanks a lot. ^_^
