### ISSUE TITLE
`coverage[toml]` requires Python <= 3.11.0a6

### ISSUE THREAD

**Issue by d-m** [coveragepy/coveragepy#1893]
Is the pin to Python 3.11.0a6 still required here? 

https://github.com/nedbat/coveragepy/blob/ee1948033bfcda24072579c5694d8621e3f7de9d/setup.py#L99

I'm using Python 3.12 and am trying to install pytest-cov which has a dependency on `coverage[toml]` and this line is causing an error.

**Comment by nedbat** [comment]
Can you show us the commands you use, and their output?  I don't seem to have a problem:
```
% python -V
Python 3.12.7

% pip install pytest-cov
Collecting pytest-cov
  Using cached pytest_cov-6.0.0-py3-none-any.whl.metadata (27 kB)
Collecting pytest>=4.6 (from pytest-cov)
  Using cached pytest-8.3.3-py3-none-any.whl.metadata (7.5 kB)
Collecting coverage>=7.5 (from coverage[toml]>=7.5->pytest-cov)
  Using cached coverage-7.6.7-cp312-cp312-macosx_11_0_arm64.whl.metadata (8.2 kB)
Collecting iniconfig (from pytest>=4.6->pytest-cov)
  Using cached iniconfig-2.0.0-py3-none-any.whl.metadata (2.6 kB)
Collecting packaging (from pytest>=4.6->pytest-cov)
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pluggy<2,>=1.5 (from pytest>=4.6->pytest-cov)
  Using cached pluggy-1.5.0-py3-none-any.whl.metadata (4.8 kB)
Using cached pytest_cov-6.0.0-py3-none-any.whl (22 kB)
Using cached coverage-7.6.7-cp312-cp312-macosx_11_0_arm64.whl (207 kB)
Using cached pytest-8.3.3-py3-none-any.whl (342 kB)
Using cached pluggy-1.5.0-py3-none-any.whl (20 kB)
Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Using cached packaging-24.2-py3-none-any.whl (65 kB)
Installing collected packages: pluggy, packaging, iniconfig, coverage, pytest, pytest-cov
Successfully installed coverage-7.6.7 iniconfig-2.0.0 packaging-24.2 pluggy-1.5.0 pytest-8.3.3 pytest-cov-6.0.0
```

**Comment by nedbat** [comment]
Feel free to add more information when you have it.  I don't want coverage.py details to be a friction point in your workflow.

**Comment by d-m** [comment]
Sorry, it took me a few days to get back to this. I'm using pants to manage a python monorepo. This is the error I'm getting once I add `pytest-cov` to my dependencies, which has a dependency on `coverage[toml]`:

```
Dependency on tomli (via: pytest-cov>=6.0.0 -> coverage[toml]>=7.5 -> tomli; python_full_version <= "3.11.0a6" and extra == "toml") not satisfied, no candidates found.
```

I'm currently using Python 3.12. I downgraded to 3.10 and the install completed.

**Comment by nedbat** [comment]
I don't use pants, so I don't know how it installs things.  I think it is interpreting the spec differently than other tools.

**Comment by nedbat** [comment]
Can we try writing an issue for pants to get to the bottom of it?

**Comment by snmishra** [comment]
> Is the pin to Python 3.11.0a6 still required here? 
> 
> 
> 
> https://github.com/nedbat/coveragepy/blob/ee1948033bfcda24072579c5694d8621e3f7de9d/setup.py#L99
> 
> 
> 
> I'm using Python 3.12 and am trying to install pytest-cov which has a dependency on `coverage[toml]` and this line is causing an error.

I think your problem is the `[toml]` extra. Python 3.12 comes with toml in the standard library, so no extra is needed.

**Comment by nedbat** [comment]
> I think your problem is the [toml] extra. Python 3.12 comes with toml in the standard library, so no extra is needed.

The extra is there so that people installing coverage.py on 3.10 (and below) will install tomli.  It doesn't mean `coverage[toml]` requires 3.10.

**Comment by d-m** [comment]
It looks like perhaps Pants isn't parsing the conditional dependency correctly. Thanks for your help. I'll open up a ticket with them.
