### ISSUE TITLE
Add a way to sort the text report

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#199]
Hi Ned,

 

The HTML output looks very good, however I’m running the coverage tool on a VMware and just want to mail the output as plain text to my colleagues.

Sending all those HTML files to all of them (or copy them to a server) is too much, so I need another trick - maybe just a python filter that sorts it out.

 

Thanks for your time!

Rob

 

From: Ned Batchelder [mailto:ned@nedbatchelder.com]
Sent: Friday, September 28, 2012 14:56
To: Tillaart, Rob van den
Subject: Re: question about coverage tool

 

Hi Rob,

In the HTML report, you can click on the column headers to sort by the column you're interested in.

--Ned.

On 9/28/2012 7:33 AM, Tillaart, Rob van den wrote:

    Hi Ned,

     

    Just new to python development I found the coverage tool which does a good job for Q&A.

     

    Q: is there an option to sort the output on coverage %?

    If not I would like to put it on the “wishlist” for next release.

     

    A sorted list makes it easier to see which files needs attention most,

     

    Thanks in advance,

    Rob Tillaart

    Netherlands

     

 

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/199

**Comment by nedbat** [comment]
Thanks Ned for creating the ticket,
    
     
    
    I made a list of my requirements, made them as generic as possible
    
    
    (1) enable sorting on coverage %column  (default seems to be name)
    
       =>  ideally on any column  [name, statements, miss, coverage]
    
    (2) ascending sorting (default)
    
    (3) descending sorting
    
     
    
    Optional
    
    (4) remove the lines with 100% coverage from the overview -> show only tests that need attention, useful for big projects to minimize output
    
    (5) show only topN  lines, eg top 10 or top 20  -> minimizes output
    
    (6) Total  #files  versus  #files@100%  -> indicator of the fragmentation of the coverage
    
     
    
    Calls could look like:
    
     
    
    Coverage report  --sort=coverage --descending  --no100% ...
    
    Coverage report  --sort=statements --…
    
    Coverage report  --sort=miss --no100% ...
    
    Coverage report  --sort=name --descending   ... 
    
    Coverage report  --sort=coverage --no100%  --top=15 ...
    
     
    
    Think no short version needed (like –s) as the word sort is already short
    
     
    
    (you might add above to the ticket)
    
     
    
    Thanks again,
    
    Rob

**Comment by nedbat** [comment]
*Original comment by* **bachmann1234 (Bitbucket: [bachmann1234](https://bitbucket.org/bachmann1234), GitHub: [bachmann1234](https://github.com/bachmann1234))**

----------------------------------------

I took a look into this ticket. The currently implementation does not store coverage numbers. They are computed by the fly.

It seems expensive to compute and store all this to sort on other properties and this could be better achieved though command line tools or other post processing.

**Comment by nedbat** [comment]
FYI, changeset [b7762d1a6614 (bb)](https://bitbucket.org/ned/coveragepy/commits/b7762d1a6614) introduced the `report --skip-covered` option, which leaves out any file with 100% coverage.

**Comment by nedbat** [comment]
Control over the sorting column is available in the report:sort option in the .coveragerc.  This work is completed in [f4001cd0cd52 (bb)](https://bitbucket.org/ned/coveragepy/commits/f4001cd0cd52).  It doesn't provide the option to sort descending, or to control it from the command line.  We'll see if there is interest in adding that support.

**Comment by nedbat** [comment]
*Original comment by* **Max Nordlund (Bitbucket: [maxnordlund](https://bitbucket.org/maxnordlund), GitHub: [maxnordlund](https://github.com/maxnordlund))**

----------------------------------------

Fast forward a year later, and at least I would like to see that feature. I tend to run my tests in a small split, and getting the files with the lowest coverage last makes it easy to see what I need to work on.

I propose `-cover`/`+cover` (or just `cover`)  to specify direction.

**Comment by jerinpetergeorge** [comment]
I have made a couple of changes to source code and it seems working (I haven't done broad tests :wink: )

[source-code reference](https://github.com/nedbat/coveragepy/blob/b436f4459a2fbc69f7a1376693782c7bd115b2bd/coverage/summary.py#L105)
<pre><code>        # Sort the lines and write them out.
        if getattr(self.config, 'sort', None):
            <b>field = self.config.sort.lower()
            if field[0] == '-':
                field = field[1:]
                reverse = True
            else:
                reverse = False</b>
            position = column_order.get(field)
            if position is None:
                raise CoverageException("Invalid sorting option: {0!r}".format(self.config.sort))
            lines.sort(key=lambda l: (l[1][position], l[0]), <b>reverse=reverse</b>)</code></pre>

and the **`.coveragerc`** config
<pre><code>[report]
sort = <b>-</b>Cover</code></pre>

**Comment by jerinpetergeorge** [comment]
@nedbat Any update on this feature? Why this issue was closed?

**Comment by nedbat** [comment]
I closed it when I added `report:sort`.  But it seems like there is interest in more control. Would you like to make a pull request? Or I might get to it in the next few weeks.

**Comment by jerinpetergeorge** [comment]
Yeah, I will try my best to make a PR asap.
