### ISSUE TITLE
Create Way to force package even if filepath exists

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#268]
*Originally reported by* **Donald Stufft (Bitbucket: [dstufft](https://bitbucket.org/dstufft), GitHub: [dstufft](https://github.com/dstufft))**

----------------------------------------

When using tox to run tests the preferred way to run tests creates throw away virtual environments and installs the package to be tested into them. This means that the code to be running is actually inside .tox/venvname/lib/pythonX.Y/site-packages/library. 

Normally coverage.py could support this BUT when doing --source library it sees the library/ directory in the current directory (which isn't being used) and doesn't do the package resolution. This leads to 0% coverage reports always when using tox. It would be great if there was a way to say "No really this is a package".

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/268

**Comment by blueyed** [comment]
What about supporting a `pkg:` prefix?

Or allowing to specify `source_pkgs` (used internally) directly?

For reference, the code is: https://github.com/nedbat/coveragepy/blob/4113a321b239c0da518c6a8ae8bc96409f216fa9/coverage/inorout.py#L133-L137

**Comment by Julian** [comment]
I didn't know this issue existed, though yeah I've fought with this in the past -- FWIW, I count this as yet another reason not to run tox out of cwd.

That's perhaps a less desirable internal (to coverage) solution if it means "tell users of coverage to change their tox.ini", but just to chime in, yeah, that's exactly what I do and recommend.

(So I have `changedir = {envtmpdir}` in every tox.ini, for this and many other reasons, and then coverage is perfectly happy with `source =` lines finding the `site-packages` version of the package).

(EDIT: sample here if you want something runnable: https://github.com/Julian/regret/blob/main/tox.ini#L33-L42 and https://github.com/Julian/regret/blob/main/.coveragerc#L4, and yeah `tox -e coverage` works fine there.)

**Comment by nedbat** [comment]
Fixed in ecd6ab19

**Comment by nedbat** [comment]
This is now released as part of [coverage 5.3](https://pypi.org/project/coverage/5.3).
