### ISSUE TITLE
Running programmatically with .pyw files

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#290]
*Originally reported by* **Okko Willeboordse (Bitbucket: [owillebo](https://bitbucket.org/owillebo), GitHub: [owillebo](https://github.com/owillebo))**

----------------------------------------

I have two files;

test.py;

```
#!python
import coverage
cov = coverage.coverage(source = ['target'])
cov.start()
import target
cov.stop()
print cov.html_report()
```
and target.py(w);

```
#!python
def foo():
  pass
```
When I run test.py with target.py it outputs, as expected;
50.0
But when I rename target.py in to target.pyw, test.py outputs;

```
#!python

Coverage.py warning: Module target has no Python source.
Coverage.py warning: No data was collected.
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    print cov.html_report()
  File "c:\Python27\lib\site-packages\coverage\control.py", line 662, in html_report
    return reporter.report(morfs)
  File "c:\Python27\lib\site-packages\coverage\html.py", line 113, in report
    self.report_files(self.html_file, morfs, self.config.html_dir)
  File "c:\Python27\lib\site-packages\coverage\report.py", line 76, in report_files
    raise CoverageException("No data to report.")
coverage.misc.CoverageException: No data to report.
```
How do I run coverage programmatically with .pyw files?

Note that Python imports both target.py and with .pyw just the same.

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/290

**Comment by nedbat** [comment]
This is fixed as of [666c65a26ee27d072823234befa8701967e82149 (bb)](https://bitbucket.org/ned/coveragepy/commits/666c65a26ee27d072823234befa8701967e82149)

**Comment by owillebo** [comment]
Please adjust the documentation. [https://coverage.readthedocs.io/en/coverage-5.5/source.html](https://coverage.readthedocs.io/en/coverage-5.5/source.html) says;

`"You can specify source to measure with the --source command-line switch, or the [run] source configuration value. ... Files that do not end with .py or .pyo or .pyc will also be skipped.`

Please add .pyw to this list.

**Comment by nedbat** [comment]
Done: 4401a6c182a15c11042ba67153516e067063d406
