### ISSUE TITLE
Add LICENSE file containing 2, 3 or 4-clause BSD License text

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#313]
*Originally reported by* **Kubilay Kocak (Bitbucket: [koobs](https://bitbucket.org/koobs), GitHub: [koobs](https://github.com/koobs))**

----------------------------------------

Add a LICENSE file to the repository containing the chosen license text, to indicate explicitly which of the BSD Licenses [1] is specified:

 * 2-clause ("Simplified" or "FreeBSD")
 * 3-clause ("Revised", "New" or "Modified"), or
 * 4-clause ("Original")

I am currently creating a FreeBSD Port for the lazy package, and need to specify this for our license framework requirements.

 * Update Trove classifiers to suite (for bonus points)

[1] https://en.wikipedia.org/wiki/BSD_licenses

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/313
- This issue had attachments: coverage.patch.  See the [original issue](https://bitbucket.org/ned/coveragepy/issue/313) for details.

**Comment by nedbat** [comment]
*Original comment by* **Ben Finney (Bitbucket: [bignose](https://bitbucket.org/bignose), GitHub: [bignose](https://github.com/bignose))**

----------------------------------------

There are numerous licenses applying to different parts of the code base. MIT (presumably Expat), GPL (various versions), and BSD (various flavours).

I agree there should be a clear ‘COPYING’ document at the top of the code base, and separate ‘LICENSE.FOO’ files in the same location giving the explicit license texts in each case.

**Comment by nedbat** [comment]
I agree making the license as clear as possible is a good thing.  Ben, what do you mean by numerous licenses applying to different parts of the code?

**Comment by nedbat** [comment]
*Original comment by* **Sam Clegg (Bitbucket: [sbc100](https://bitbucket.org/sbc100), GitHub: [sbc100](https://github.com/sbc100))**

----------------------------------------

I'm also interested in seeing clearer licensing applied to the codebase.  I'm in the process of attempting to import the code into the chromium repo and there are some fairly strict import requirement.  The proposed change is here: https://codereview.chromium.org/727003004/.

As far as I can tell all the code is currently covered by the 2-clause license in coverage/__init__.py.  I've created a patch that adds minimal license information to each file and moves the full BSD license already in __init__.py to the top of the file.  In my initial version of this patch I attempted to create an external LICENSE.txt file instead but I had trouble finding a suitable way to include this when doing "setup.py bdist" so I decided to stick with the inline license.

In terms of the MIT/GPL licenses that Bin is referring too it looks like that only applies the jquery html and js files.   Is that right Ben?

**Comment by nedbat** [comment]
*Original comment by* **Sam Clegg (Bitbucket: [sbc100](https://bitbucket.org/sbc100), GitHub: [sbc100](https://github.com/sbc100))**

----------------------------------------

Adds basic license info to all source files.

**Comment by nedbat** [comment]
@sbc100 I'm confused: why must coverage be added to the chromium source tree? Do they not support installing needed packages with standard installation tools?  And why must every file have a copyright at the top?  What rules govern this 4-line declaration?  Why are all the dates 2014? Am I expected to change all these files each calendar year?

**Comment by nedbat** [comment]
*Original comment by* **Sam Clegg (Bitbucket: [sbc100](https://bitbucket.org/sbc100), GitHub: [sbc100](https://github.com/sbc100))**

----------------------------------------

Hi ned.  Yes, the way chromium is setup is that it pulls all its dependencies in either from external git repos (like submodules) or by checking the code directly into chromium. At least this is what we have done for other python modules such as mock.  We don't rely on external tools like pip and virtualenv. I imagine the motivation is keep things simple and hermetic.  The rules we use are here: http://www.chromium.org/developers/adding-3rd-party-libraries.

Apparently the requirement is only that the license be mentioned in each file (the reference to the BSD license that is).  The copyright line is not needed.  I can re-upload the patch without those.

(and no, in chromium at least, we don't update the copyright year at all).

**Comment by nedbat** [comment]
I've switched the license to Apache, and added notice at the top of each file, in [5fdd6e15db25 (bb)](https://bitbucket.org/ned/coveragepy/commits/5fdd6e15db25)

**Comment by Devjulius080** [comment]
Great project
