### ISSUE TITLE
Code executed by exec excluded from coverage

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#380]
*Originally reported by* **mb2297 (Bitbucket: [mb2297](https://bitbucket.org/mb2297), GitHub: Unknown)**

----------------------------------------

It might be unrealistic to expect this to work, but python files that are read and then executed with exec (or with execfile) aren't counted towards the coverage report.

Example:

```
#!python
# impl.py

def foo():
    print "foo"
 
def bar():
    print "bar"
```

```
#!python
# impl2.py

print "the answer to life, the universe and everything is: {}".format(undeclared_var)
```

```
#!python
# test.py

from impl import foo
 
foo()
 
namespace = {
    'undeclared_var': 42
}
 
with open('impl2.py') as f:
    code = compile(f.read(), 'impl2.py', 'exec')
    exec(code, globals(), namespace)
```

Results in the following on both OS X and Ubuntu:

```
$ coverage run --source . test.py
foo
the answer to life, the universe and everything is: 42
```

```
$ coverage report
Name    Stmts   Miss  Cover
---------------------------
impl        4      1    75%
impl2       1      1     0%
test        6      0   100%
---------------------------
TOTAL      11      2    82%
```

The example is also at https://gist.github.com/mattbennett/f57a5286bd77ee52651e if you want to clone and verify.

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/380

**Comment by nedbat** [comment]
Looks like exec'ing code gets the called code and the calling code confused in the frame.  I've added a warning when this happens here: [b981d945481a (bb)](https://bitbucket.org/ned/coveragepy/commits/b981d945481a).  There's probably a way to get this right, still working on it.

**Comment by nedbat** [comment]
If __file__ disagrees with the frame, use the frame info.  Fixes #380.

→ <<cset [2372daa1d74b (bb)](https://bitbucket.org/ned/coveragepy/commits/2372daa1d74b)>>

**Comment by nedbat** [comment]
Fixed in [2372daa1d74b12e217be90daf73b7f2274e8a0ac (bb)](https://bitbucket.org/ned/coveragepy/commits/2372daa1d74b12e217be90daf73b7f2274e8a0ac)

**Comment by blueyed** [comment]
I've just came across this, and wanted to note that it does not work when the exec'd (base) filename is the same, as with pdbpp's hack: https://github.com/pdbpp/pdbpp/pull/321/commits/f67ad89d25bca80015e6b0f53703bb99b7b83a6b
Setting `__file__` explicitly helped, and I wanted to do this anyway already.
Also renaming the exec'd (main) file to `pdbpp.py` is planned.

**Comment by brondsem** [comment]
Another note: I had code like `exec(fp.read())` which wasn't working.  I had to change it to `exec(compile(fp.read(), filename, 'exec'))` for coverage to be recorded.  I didn't have to set `__file__`.

**Comment by rohitsharma1113** [comment]
How can I include code executed with exec ? 
The links in this discussion are broken (bit bucket)
