### ISSUE TITLE
Measure coverage of jupyter notebook

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#569]
*Originally reported by* **Martin Scherer (Bitbucket: [marscher](https://bitbucket.org/marscher), GitHub: [marscher](https://github.com/marscher))**

----------------------------------------

I'm using a pytest plugin (pytest-nbval) to execute a Jupyter notebook calling into my Python package, which I want to measure. I just wonder if it is possible to get some results for this configuration.

I've tried wrapping the invocation of pytest with coverage run like this:

coverage run --source molpx -m pytest --nbval-lax molpx/notebooks/

However none of the lines in molpx are marked as executed, however they are. Is this configuration just impossible to achieve or can it be done somehow?

I guess this problem arises because jupyter spawns another process to run the actual code of interest in.

Thank you in advance!

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/569

**Comment by nedbat** [comment]
Thanks, this is an interesting new scenario. I'm not much of a Jupyter user: could you help me out by making a reproducible test case?  Even if it's "clone this repo, then run these commands", that would be great.

**Comment by nedbat** [comment]
*Original comment by* **Martin Scherer (Bitbucket: [marscher](https://bitbucket.org/marscher), GitHub: [marscher](https://github.com/marscher))**

----------------------------------------

On 08.03.2017 15:43, Ned Batchelder wrote:
>
>

I will create a minimal testing environment. Do you prefer virtualenv 
over conda?

**Comment by nedbat** [comment]
*Original comment by* **Martin Scherer (Bitbucket: [marscher](https://bitbucket.org/marscher), GitHub: [marscher](https://github.com/marscher))**

----------------------------------------

It seems like this has already been solved: 
https://github.com/bukzor/coverage_enable_subprocess/blob/master/setup.py

But of course it would be great to have it directly available in coveragepy

**Comment by nedbat** [comment]
*Original comment by* **Martin Scherer (Bitbucket: [marscher](https://bitbucket.org/marscher), GitHub: [marscher](https://github.com/marscher))**

----------------------------------------

Here is a test example:
https://bitbucket.org/marscher/coverage_jupyter_notebook/

I could not get it to work with the previously linked hack for enabling 
subprocesses. Thanks for looking into this!

**Comment by nedbat** [comment]
Thanks for the detailed instructions.  I see what you mean.  It looks to me like Jupyter or nbval is using a subprocess to run the code, but is not letting the subprocess finish properly, so it doesn't write its data.

It looks like nbval already has an issue written about it: https://github.com/computationalmodelling/nbval/issues/7

**Comment by nedbat** [comment]
*Original comment by* **Martin Scherer (Bitbucket: [marscher](https://bitbucket.org/marscher), GitHub: [marscher](https://github.com/marscher))**

----------------------------------------

Thank you for the link. I've tested the proposed fix on Github and it works. I think this issue can be closed, since the general handling of subprocesses is fine, but not handled right in the subsequent software.

**Comment by gitgithan** [comment]
Is there an example of how to setup coverage to run in jupyter notebooks?
I pasted code from a .py file that works with coverage into 
a notebook, replacing the line `# .. call your code ..` (directly copied from https://coverage.readthedocs.io/en/latest/api.html)

```
import coverage

cov = coverage.Coverage()
cov.start()

# .. call your code ..

cov.stop()
cov.save()

cov.html_report()
```

I'm getting 0% coverage, all things that should have ran are missing. 
It shouldn't be a `source` issue since the same coveragerc works when the code is in .py 

Thread above seems to be saying nbval has a solution to this, but i only see a PR at https://github.com/computationalmodelling/nbval/pull/53/files with many code changes. 
Not sure how to integrate those changes into coverage as a user
