### ISSUE TITLE
Only first line of multi-line statements reported by coverage xml

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#571]
*Originally reported by* **Anonymous**

----------------------------------------

This is a issue first submit in codecov: https://github.com/codecov/support/issues/93

but I find that this sonar-python plugins sonarqube can not color the proper lines when there are multi-line statements.

It seems the coverage parser only show the first line of multiline coverage info, so many third-party software can not recognize the multiline statements, cause the mistake color info

Can we add a option to fix this problem?

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/571
- This issue had attachments: coverage.png.  See the [original issue](https://bitbucket.org/ned/coveragepy/issue/571) for details.

**Comment by nedbat** [comment]
This seems to me to be a bug in the third-party software.  The XML file does not say there is a missed line. Does it also color docstrings as missed?

**Comment by nedbat** [comment]
*Original comment by* **Ijaz Sarwar (Bitbucket: [isarwar](https://bitbucket.org/isarwar), GitHub: [isarwar](https://github.com/isarwar))**

----------------------------------------

The problem in this case is that `coverage.xml` only reports that line 18 is covered and nothing else. If you do `coverage html` even then line 19 to 23 would be shown as Not Executable. 

I have the exact same problem and it is not related to 3rd party:
![UncoveredLinesIssue.png](https://bitbucket.org/repo/Ee7X/images/421179933-UncoveredLinesIssue.png) 

Any suggestions here?

**Comment by nedbat** [comment]
@isarwar why is it a problem that the lines are marked as not executable? They don't subtract from your coverage measurement, and they aren't indicated as something you need to write tests for.

**Comment by nedbat** [comment]
*Original comment by* **Ijaz Sarwar (Bitbucket: [isarwar](https://bitbucket.org/isarwar), GitHub: [isarwar](https://github.com/isarwar))**

----------------------------------------

thanks for the fast response! 
In my case coverage.xml does not say anything about line 58 to 71. All it says is line 57 is covered. When I annotate line 57 to 71 comes up with `!`(meaning not covered). So if I have my own program (in PHP) that takes these two as input then I would declare 1 line covered out of 15 (which is incorrect). 

Also I don't understand why coverage.xml does not have information about all the lines?

**Comment by nedbat** [comment]
@isarwar Sorry, I can't reproduce what you are describing.  Can you provide a reproducible test case?  Annotate won't make a line as not executed if the other reports don't mark it as not executed.

**Comment by nedbat** [comment]
*Original comment by* **Ijaz Sarwar (Bitbucket: [isarwar](https://bitbucket.org/isarwar), GitHub: [isarwar](https://github.com/isarwar))**

----------------------------------------

ahh my bad. I could not reproduce that exact thing. But I am still seeing the difference between what annotation is reporting and what xml is reporting. 

1) Multi line comments are marked  as executed. why?
2) Line 57 to 71 is all executed in annotation (which is fine) but in xml only line 57 is mentioned and rest are missing. 

![AnnotationVsXml.png](https://bitbucket.org/repo/Ee7X/images/2812998220-AnnotationVsXml.png)

**Comment by nedbat** [comment]
I'll look into the difference.

**Comment by nedbat** [comment]
The annotate algorithm does better on lines 58-71, but as you note, it also shows false positives on lines 89, and 103-112.

What is the real problem here? Do you use "annotate"? If I had to choose between the way html works and the way annotate works, I'd choose html.  I can make annotate the same as html.  I'm not sure there's a way to get it to be perfect (that is, mark lines 58-71, but not 103-112.

**Comment by nedbat** [comment]
*Original comment by* **Eric Kever (Bitbucket: [suddenlychloe](https://bitbucket.org/suddenlychloe), GitHub: Unknown)**

----------------------------------------

I believe the primary problem here is that if I were to feed the XML into a tool such as SonarQube, it would yield incorrect coverage results because the XML is only showing the first line of a multi-line statement as being covered, when in reality, all of those lines should be considered covered.

**Comment by nedbat** [comment]
@suddenlychloe Can you elaborate on the "incorrect result" that SonaqQube would display?

**Comment by nedbat** [comment]
*Original comment by* **Eric Kever (Bitbucket: [suddenlychloe](https://bitbucket.org/suddenlychloe), GitHub: Unknown)**

----------------------------------------

Given a 10 line Python script with no empty lines, completely uncovered except for 1 multi-line statement that was 5 lines long, the XML would only state that the first line of it was covered. In reality all 5 lines were covered because they were part of the same statement. Feeding the XML into SonarQube, however, would yield that I have 10% coverage instead of 50%, because the XML only states that the first line of that multi-line statement is covered.

**Comment by nedbat** [comment]
@suddenlychloe I see what you mean.  I'm not that interested in the difference between a 1-line statement, and a 5-line statement.  Coverage.py really measures statement coverage.  I'll take a look at the possibilities for counting all 5 of the lines, but I'm not personally unhappy with the way it is now.

**Comment by nedbat** [comment]
*Original comment by* **Michael Dougherty (Bitbucket: [smishsmashio](https://bitbucket.org/smishsmashio), GitHub: [smishsmashio](https://github.com/smishsmashio))**

----------------------------------------

Hi Ned & Eric - I've been following this ticket for a little while now, glad to see there's some discussion on it :)

It sounds like the issue is that the coverage XML format is line-based, and downstream consumers of it treat it as such. But of course python is statement-based, and a statement can be multiple lines OR you can even have multiple statements per line. In this case the reporting format loses some of fidelity of the underlying data, but IMO that's a decision users have to make when they opt to use the XML format. However, I think I agree with Eric in that I would want my report-consumer (we also use sonarqube!) to correctly show that the entire multi-line statement is covered. The 10-line script with 5-line statement I think is a good example -- I would expect all of the statement (= all of the lines) to be shown as "covered" in whatever view I might have. It doesn't seem to make sense to show the start of a dictionary (`{`) on one line as covered and to show that the individual entries (`'foo': 'bar'`) as not covered.

Hope that helps, at least to add another perspective.

**Comment by nedbat** [comment]
I agree that in an ideal world, all 5 lines would be marked as executed.  But looked at another way, there was really only one choice: to run all five lines, or to run none of them.  There weren't 5 opportunities to execute code, there was only one.

But really, the limiting factor here is the information that Python provides to us.  I'd have to research what information it's giving me, but I'm guessing it only reports on the first line of the statement.

**Comment by dtomas** [comment]
This also affects diff-cover, see https://github.com/Bachmann1234/diff-cover/issues/83

**Comment by StevenMapes** [comment]
I've noticed it also affects multi-line string

```
example= """this is an example
of a string split over multiple lines
where the 2nd and third line is marked as not-covered and affect the coverage %

example2 = "this line is treated as covered" \
           "this line is not treated as being covered"
```

**Comment by nedbat** [comment]
I don't think this is something coverage.py should try to change.  There's only one opportunity to execute or not execute in a multi-line statement, so it should only produce one executed/missed signal.  If other tools need information provided in a different way so that they can produce correct visualizations, please open another issue with the details of what format would be best.

**Comment by webknjaz** [comment]
FTR, one case where we saw confusing coverage on the excluded lines was uploading both Coverage.py- and MyPy-generated coverage reports to Codecov, which would then show the lines as uncovered as opposed to skipped when MyPy marks them as not covered.

I don't think that Coverage.py can do anything about this, though. Just wanted to record this for history. This is probably something that tools like Codecov should improve data representation-wise.
