### ISSUE TITLE
cannot parse Cython when creating xml

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#601]
*Originally reported by* **Ioannis Filippidis (Bitbucket: [johnyf](https://bitbucket.org/johnyf), GitHub: [johnyf](https://github.com/johnyf))**

----------------------------------------

`coverage.py` cannot parse Cython code. Running `coverage xml -i` produces the warning `Coverage.py warning: Could not parse Python file /path/dd/dd/cudd.pyx`, which is a warning discussed in #396.

Without the `-i` option the output is `Couldn't parse '/path/github/dd/dd/cudd.pyx' as Python source: 'invalid syntax' at line 27`, where line 27 reads `from libcpp cimport bool`. (I am aware of [Cython's annotating capability for coverage results](http://cython.readthedocs.io/en/latest/src/tutorial/profiling_tutorial.html#enabling-coverage-analysis), but that too takes `xml` as input.)

Does `coverage.py` support Cython? If not, are there any future plans in that direction?

Relevant also to: https://github.com/cython/cython/issues/1508

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/601

**Comment by nedbat** [comment]
*Original comment by* **Ioannis Filippidis (Bitbucket: [johnyf](https://bitbucket.org/johnyf), GitHub: [johnyf](https://github.com/johnyf))**

----------------------------------------

It turns out that even though my `.coveragerc` included the Cython plugin, it was under the `tests/` directory (where I run tests on the installed package), but I was attempting to collect coverage measurements while outside the `tests` directory (because building in-place is required). Copying `.coveragerc` to the directory where I run `nosetests` resolved the issue.

It would be great to see #597 being resolved. For the time being I cannot get `[paths]` to work properly when running `nosetests` within the `tests/` directory, unless I manually edit the paths within the generated `.coverage` *and* copy the resulting `.coverage` file to outside the `tests/` directory (even when all the paths are absolute).

It is interesting that running from within `tests/` with the package installed as normal does collect statistics for `pyx` files, but does not insert `"file_tracers":{"/path/dd/dd/cudd.pyx"` in the `.coverage` file. Adding this to the file, replacing the paths with the correct absolute paths, then moving the resulting `.coverage` to the parent directory (from where the built-in-place `dd/*.so` are visible), and running `coverage xml` works.

**Comment by webknjaz** [comment]
Ref: https://github.com/cython/cython/issues/3636
