### ISSUE TITLE
Variable assignment with an if-else statement is not considered as branched

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#606]
*Originally reported by* **Federico Carrá (Bitbucket: [feferulo](https://bitbucket.org/feferulo), GitHub: Unknown)**

----------------------------------------

Hello.
In my code I have a variable assignment with a if-else statement as this one:

```
#!python


variable = 1 if some_condition else -1

```
When doing coverage --with-branches, it does not consider that this has branches.

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/606

**Comment by nedbat** [comment]
Branch coverage can only measure branching from one line to another, since Python's trace facility currently only supports per-line tracing.  3.7 introduces opcode-level tracing, though coverage.py will need significant changes to make use of it.

**Comment by nedbat** [comment]
This would be a huge amount of work (how do you report on this?), but it's a reasonable feature idea.

**Comment by nedbat** [comment]
*Original comment by* **Federico Carrá (Bitbucket: [feferulo](https://bitbucket.org/feferulo), GitHub: Unknown)**

----------------------------------------

Maybe you can enhance the original file replacing the if-else assignment with an expanded  if-else block of code before running it through coverage (as if the variable assignment where syntactic sugar).  It's beyond my comprehension the difficulty of such an "enhancement  operator".

**Comment by ngie-eign** [comment]
This is a duplicate of #509.
