### ISSUE TITLE
How to best generate coverage report for mixed Python, CPython C-API extensions

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#626]
*Originally reported by* **Christoph Reiter (Bitbucket: [lazka](https://bitbucket.org/lazka), GitHub: [lazka](https://github.com/lazka))**

----------------------------------------

This is more of a support request, I hope that's OK.

I work on two projects which are CPython extensions partially written in Python and C, using the Python C API. To get a nicely unified coverage report over all Python versions on Windows/macOS/Linux, I currently use coverage.py and gcov and send it to codecov.io, which looks something like this: https://codecov.io/gh/pygobject/pycairo

Question:

Does anyone know if there is a nice way to get something similar without using external services and without having separate html reports?

(Would it be possible to import gcov or the xml format into the internal coverage.py format and then merge everything to one report?)

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/626

**Comment by nedbat** [comment]
@lazka I don't know of any such service.  Is there a report format that would be easier to integrate with gcov?

**Comment by nedbat** [comment]
*Original comment by* **Christoph Reiter (Bitbucket: [lazka](https://bitbucket.org/lazka), GitHub: [lazka](https://github.com/lazka))**

----------------------------------------

No idea. I only found that every tool can export to the cobertura xml format but I didn't find anything which can actually work with it (merge, create reports).

I just went with coverage.py+lcov for now and let CI merge things and push it to gitlab pages: https://gnome.pages.gitlab.gnome.org/pygobject/ And I'm quite happy with that now.

Feel free to close this.

**Comment by abitrolly** [comment]
#587 may help at least generate the coverage info in the same format.

**Comment by nedbat** [comment]
We now have lcov support, as of 2e8c1910.

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.3](https://pypi.org/project/coverage/6.3).

**Comment by nedbat** [comment]
This is now released as part of [coverage 6.3](https://pypi.org/project/coverage/6.3).
