### ISSUE TITLE
Segmentation fault while running Python3.6 coverage on CentOS-7

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#662]
*Originally reported by* **Anonymous**

----------------------------------------

We are facing intermittent issue while running Travis build and test on CentOS-7 with Python3.6. It appears in 70-80% of the tests, but sometimes the test succeeds. I wonder if that is known and maybe fixed coverage issue. Any recommendations are appreciated.

References to the [Travis run](https://travis-ci.org/ygorelik/ydk-gen/jobs/379467178). The error appears [here](https://travis-ci.org/CiscoDevNet/ydk-gen/jobs/377473857#L6310).

Error signature:
**./test/tests.sh: line 56: 21250 Segmentation fault      (core dumped) coverage run --omit=/usr/* --branch --parallel-mode $@ > /dev/null**

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/662

**Comment by nedbat** [comment]
@ygorelik: do you know about this problem?  Is it possible to narrow down the cause?

**Comment by ygorelik** [comment]
The issue is happening randomly, mostly with Python3.6, but fairly often it breaks Travis run. We have to restart the Travis few times, until it gets cleared, which is really bothersome. 
Is there a way to turn on some debugging that would help you determine the root cause?

**Comment by nedbat** [comment]
@ygorelik Unfortunately I am not well-versed in C debugging tools, especially that could run in Travis. The crash seems to be during the shutdown of the process, which means pre-existing debug logging will probably be unhelpful.

Do these tests run any C++ code in your repo?  It's possible the bug is not in coverage itself, but that coverage is perturbing the environment to expose other bugs.

Do the crashes happen anywhere except in Travis?  Can you create a Travis job that runs fewer tests?

**Comment by nedbat** [comment]
If you come back to this, feel free to re-open this issue.
