### ISSUE TITLE
Allow configuration via pyproject.toml

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#664]
*Originally reported by* **pradyunsg (Bitbucket: [pradyunsg](https://bitbucket.org/pradyunsg), GitHub: [pradyunsg](https://github.com/pradyunsg))**

----------------------------------------

As per [PEP 518](https://www.python.org/dev/peps/pep-0518/#specification), tools can use `tool.<pypi-name>` namespace within the `pyproject.toml` file if they own `<pypi-name>` on PyPI.

Allowing configuration via the above mechanism would allow for users to have a single file in their root directory, for configuring this `coverage` (and other tools) for their project. Essentially, this would allow eliminating a `.coveragerc` file in the root of the project in favor of using `pyproject.toml`.

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/664

**Comment by nedbat** [comment]
This is a good idea.  One twist: coverage.py has no required dependencies.  It will need a toml parser to parse the pyproject.toml file.  My inclination is to implement this so that if the toml module is available, then coverage will try to read the pyproject.toml file.  Installing coverage won't install toml automatically, you'll have to do that yourself if you want to use pyproject.toml for configuration.

**Comment by butla** [comment]
@nedbat What about vendoring the toml library along with coverage? Would you be ok with that approach? Some projects do that (I think Pipenv does that with Pip, although there are probably examples in less chaotic projects as well [that's not to say that Pipenv is bad] ), to stay independent of other dependencies, and act as a self-contained dependency.

**Comment by butla** [comment]
Or on the other hand... your solution seems more sensible :) Just have to document that.

**Comment by mhozza** [comment]
You can also list it as optional dependency.

**Comment by zsiciarz** [comment]
+1 for optional dependency, isort does that for example: `pip install isort[pyproject]`.

**Comment by nedbat** [comment]
This is finished as of df744f8cbcad7ea7dca893be5017920afa4ce32f

**Comment by adithyabsk** [comment]
Awesome, @nedbat thanks for helping move this along. Assume this will land in the next release?

**Comment by nedbat** [comment]
Yes, if by next release you mean 5.0.

**Comment by nedbat** [comment]
This is available in 5.0b1: https://pypi.org/project/coverage/5.0b1/
