### ISSUE TITLE
Created at ignores local time

### ISSUE THREAD

**Issue by tschm** [coveragepy/coveragepy#673]
The result is always given in UTC. Is there a flag to change this and use the local system time?

**Comment by nedbat** [comment]
Can you elaborate? What is "created at"? What are you running, and where are you seeing it?

**Comment by nedbat** [comment]
When I generate an HTML report, I get a notation at the bottom of the page: "created at 2018-07-15 09:07", which is in local time.  If you see something different, feel free to re-open the issue.
