### ISSUE TITLE
Improve debugging support: "all", help

### ISSUE THREAD

**Issue by blueyed** [coveragepy/coveragepy#674]
1. `coverage run --help` should list available debug options, currently it only says:

> --debug=OPTS          Debug options, separated by commas

(with added ". [env: COVERAGE_DEBUG]" on master)

2. a new option `all` should be added to easily enable full debugging

3. some constant should be added that contains the full list (without "all"), so it can be used by configurer plugins (if they e.g. want to use all, but some known ones)

**Comment by nedbat** [comment]
1. You are right, it would be better to list the options.
2. "all" will not be useful, it will produce an overwhelming amount of information
3. I don't understand this idea.

**Comment by nedbat** [comment]
For (1), perhaps a link to the docs would be enough? http://coverage.readthedocs.io/en/coverage-4.5.1a/cmd.html#cmd-run-debug

**Comment by nedbat** [comment]
Looking at this again, a link to the docs is the best way to go.  I've changed the code so that every help message ends with a link to the full docs: https://github.com/nedbat/coveragepy/commit/bf86427e1861aa353d7e80de0d373d9a30edb462

**Comment by nedbat** [comment]
Testing: bf86427e1861aa353d7e80de0d373d9a30edb462
