### ISSUE TITLE
Additional tests getting added when using --with-coverage

### ISSUE THREAD

**Issue by lightclient** [coveragepy/coveragepy#680]
I have a project setup to do CI and it runs our tests using django and nose. When I am on my local host I have 31 passing tests. The CI creates its VM and runs the same command, but it comes up with 35 tests and the 4 tests that aren't accounted for anywhere are failing (`ERROR: Failure: AttributeError ('RelatedFilter' object has no attribute 'name')`).

By removing `--with-coverage` I am able to get it passing and back down to 31 tests. I am not sure what is causing this. Everything was working fine last night. Even things that were passing yesterday are failing.

Any ideas?

**Comment by nedbat** [comment]
@c-o-l-o-r Can you link me to the project and the CI runs?

**Comment by lightclient** [comment]
@nedbat 

Project: https://github.com/Bounties-Network/BountiesAPI/tree/experienceLevel-fix
CI run: https://circleci.com/gh/Bounties-Network/BountiesAPI/319

Even when I remove all `test.py` files, it still comes up with those 4 test which it fails.

**Comment by lightclient** [comment]
Finally determined that the issue was django-filters' 2.0.0 update. Carry on! 😄
