### ISSUE TITLE
Unable to install coverage on python3.6 on amazon AMI

### ISSUE THREAD

**Issue by devonhk** [coveragepy/coveragepy#682]
OS: Amazon AMI `ami-cfe4b2b0`
Python version: `Python 3.6.5`
pip version: `pip 10.0.1`

**Repro steps**
1. activate python3.6 virtualenv 
2. Run
 ```
(env) [ec2-user@ip-10-0-2-171 roofline-rec]$ pip install coverage
Collecting coverage
  Using cached https://files.pythonhosted.org/packages/3d/a0/b12090c40e0b8196b973962ec71c1c541a6c04af58ba5ad85683b3de251a/coverage-4.5.1-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: coverage
Successfully installed coverage-4.5.1
```

3. Test coverage install 
```
(env) [ec2-user@ip-10-0-2-171 roofline-rec]$ python
Python 3.6.5 (default, Apr 26 2018, 00:14:31) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import coverage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'coverage'
```

**Expected behavior**
Coverage should either fail explicitly or it be installed correctly.

**Notes**
Installed system python packages
```
(env) [ec2-user@ip-10-0-2-171 roofline-rec]$ yum list installed | grep python36
python36.x86_64                      3.6.5-1.9.amzn1               @amzn-updates
python36-devel.x86_64                3.6.5-1.9.amzn1               @amzn-updates
python36-libs.x86_64                 3.6.5-1.9.amzn1               @amzn-updates
python36-pip.noarch                  9.0.3-1.26.amzn1              @amzn-updates
python36-setuptools.noarch           36.2.7-1.33.amzn1             @amzn-main  
```

Let me know if more info is required. I can also provide a test env if someone wants an easy way to repro this issue.

**Comment by nedbat** [comment]
I don't understand why this would be.  In step 3, can you use "python -vv" to show what is happening?

**Comment by jambonrose** [comment]
Depending on your setup, it is possible for `pip` to refer to a different version of Python. 

@pydo: Are you still seeing this issue? If you install using `python -m pip install coverage` do you still run into this error? What is the output of `pip -V`?

**Comment by devonhk** [comment]
I can't repro anymore, it's really odd since amazon doesn't seem to have updated the pip yum repo in their AMI

```
(env) [ec2-user@ip-172-31-18-1 ~]$ yum list installed | grep pip
libpipeline.x86_64                   1.2.3-3.3.amzn1               installed    
python27-pip.noarch                  9.0.3-1.26.amzn1              installed    
python36-pip.noarch                  9.0.3-1.26.amzn1              @amzn-updates
```

The only possibility that comes to mind is that the import wasn't searching in the virtualenv's site-packages...
