### ISSUE TITLE
Using settrace

### ISSUE THREAD

**Issue by orenbenkiki** [coveragepy/coveragepy#683]
The documentation says, under "things that don't work":

> sys.settrace is the Python feature that coverage.py uses to see what’s happening in your program. If another part of your program is using sys.settrace, then it will conflict with coverage.py, and it won’t be measured properly.

And this is of course correct. That said... Is there a way to both do coverage measurement and also perform some package-specific tracing at the same time? In my case, I have a module which needs to do some tracing for its functionality, and I'd also like to have it (not to mention applications using it) be able to measure coverage.

I tried to naively do something along the following lines:

```python
prev_tracefunc = sys.settrace(my_tracefunc)
... run some code with my tracing ...
sys.settrace(prev_tracefunc)

def my_tracefunc(...):
    ... do my stuff ...
    if prev_tracefunc is not None:
        return prev_tracefunc(...)
    return None
```

However, when running the code under `coverage` (either directly or using `nose`), I discovered that `prev_tracefunc` was still `None`; in addition, while my code run and passed its tests, coverage was not collected for the relevant parts - as per the documentation, but still surprising.

So:

* Is there any magic incantation I could place in my code which would allow it to live peacefully with `coverage.py`?

* If not, would it be possible to tweak `coverage.py` so that such an incantation would become possible?

**Comment by nedbat** [comment]
Conceptually, it should work to chain the functions together, but I've never tried it, so I might be overlooking some subtle complications.  Can you provide me with a link to your attempt?

**Comment by orenbenkiki** [comment]
This is stuff I've just started to work on, internally, so it isn't in a public repository yet, has no docs, etc.
I'm struggling a bit with setup.py and tox and so on, but I have something basic working.
I'm attaching the sdist tarball: [ripe-0.0.1.tar.gz](https://github.com/nedbat/coveragepy/files/2206271/ripe-0.0.1.tar.gz)
See the `_tracefunc` in `ripe/__init__.py`.

Thanks!

**Comment by orenbenkiki** [comment]
Here is a minimal file demonstrating the problem:

```python
import sys

prev_tracefunc = None 

def outer_call(): 
    global prev_tracefunc 
    prev_tracefunc = sys.settrace(tracefunc) 
    inner_call() 
    sys.settrace(prev_tracefunc) 

def inner_call(): 
    pass 
 
def tracefunc(frame, event, arg): 
    if event == 'call': 
        print(frame.f_code.co_name) 
    global prev_tracefunc 
    if prev_tracefunc is not None: 
        return prev_tracefunc(frame, event, arg) 
    return None 

outer_call() 
```

Running `coverage` shows the `inner_call` as uncovered. The `tracefunc` is also reported as uncovered but this is to be expected.

**Comment by nedbat** [comment]
@orenbenkiki did you mean to close this issue?

**Comment by orenbenkiki** [comment]
Sorry, sticky fingers...

**Comment by orenbenkiki** [comment]
Ugh, this is my fault. Actually `sys.setrace` doesn't return the current tracefunc (it would be lovely if it did though...). I wishfully misread the sentence talking about the return value of the tracefunc and attributed it to the `settrace` itself (late night coding...). My bad.

When I set the prev_tracefunc to `sys._getframe(0).f_trace` before calling `sys.settrace` then the inner function is properly reported as covered. The tracefunc itself is not reported as covered, of course, as expected.

This time I'm intentionally closing the issue :-)
