### ISSUE TITLE
Test coverage data changed based on test case run sequence.

### ISSUE THREAD

**Issue by hubeiyichangzy** [coveragepy/coveragepy#687]
Hi team, 

I have two modules: "use_base.py" and 'base.py'. I write test cases for both moduels. If I run 
'**coverage run base.py**' 
it gives me **100% coverage for base.py**. If I run 
'**coverage run use_base.py**'
it gives me **20% coverage for base.py**. If I run them **both together**, the 'coverage report' will give me **20% coverage for base.py**.

Both of the files are under coverage source path. Seems later run test results overwrite the previous result if the testing covers the same testing file. Could you help take a look if there is any solution to the issue? Thanks for the help.

**Comment by hubeiyichangzy** [comment]
Found one solution is saving coverage data into the different data files. I **rename the coverage data from '.coverage' to '.coverage.use_base'** and '.coverage.base'. After all the tests run, execute '**coverage combine**' to merge the test result. It will give the 100% coverage for base.py.

Please let me know if there are better solution for this.

**Comment by nedbat** [comment]
Yes, `coverage run` by default clears out old data, so that running the program, fixing something, and running it again won't produce confusing overlapping results.

You can use `coverage run --append` if you want to collect results from a number of runs.
