### ISSUE TITLE
lock the coverage file before accessing?

### ISSUE THREAD

**Issue by notestaff** [coveragepy/coveragepy#688]
@nedbat Maybe, lock the coverage data file with something like https://pypi.org/project/filelock/ before reading/writing it?   When using pytest-cov on Travis-CI with --cov-append, several jobs from the job matrix might be using the file concurrently.

**Comment by nedbat** [comment]
If you are running concurrent tests, you need to use `--parallel` (or `[run] parallel=true`) to keep the data files separate.  Locking the file will just slow everything down.
