### ISSUE TITLE
Possible hash collision in Hasher function for object comparison

### ISSUE THREAD

**Issue by jpsenior** [coveragepy/coveragepy#692]
After a casual review of the code at 

https://github.com/nedbat/coveragepy/blob/master/coverage/misc.py#L196 I identified a possible hash issue with implementation of nested dict values:

Given a series of non-recursive, or recursive dict updates, we update the hashlib.md5 with hashlib.md5.update() which is basically composition of (input_string, md5_result).
When adding multiple (input, result) to the composed results it's possible that this provides collision on nested, recursive data structures with similar key names.

Thank you @nedbat for helping me on IRC by suggesting this function!

**Comment by nedbat** [comment]
I would love to see an actual reproduction case.  If you are right, it shouldn't be hard to create.

**Comment by nedbat** [comment]
Feel free to re-open this when you get more details. Thanks.
