### ISSUE TITLE
Wrongly treat statement as uncovered

### ISSUE THREAD

**Issue by whoiscc** [coveragepy/coveragepy#694]
Reproduction:

```python
class A:
    def __init__(self, xs):
        self._xs = xs

    def __getitem__(self, x):
        return x in self._xs


a1 = A([10])
a2 = A(list(range(42)))

for i in range(42):
    for j in range(42):
        if not a1[i] or not a2[j]:
            continue
```

After running `coverage run test.py` and `coverage report -m`:

```
Name      Stmts   Miss  Cover   Missing
---------------------------------------
test.py      11      1    91%   15
```

And line 15 is the single `continue` statement. If I add a `print('continue')` above it, tons of "continue" will be printed, and coverage report correctly back to 100%.

**Comment by nedbat** [comment]
This report is a duplicate of #198. It's a limitation of CPython's peephole optimizer, described in https://bugs.python.org/issue2506
