### ISSUE TITLE
AttributeError when specifying an outfile with report()

### ISSUE THREAD

**Issue by 0x0c72** [coveragepy/coveragepy#701]
The auto-generated documentation specifies the keyword argument as file.  But in the code it is specified as outfile.  Oddly enough, calling report with outfile as a keyword argument results in a TypeError: unrecognized argument; calling it with file as is specified in the documentation, results in AttributeError: 'str' object has no attribute write.  

In cmdline.py, the report option doesn't seem to have an option for specifying an output file.  Though I could be missing something there.

From what I can see in summary.py, the passed string representing the path for the file is never opened and therefore is not a file object.  What I'm unsure about is why the keyword argument is outfile in the code, but file in documentation.  Though neither of them work it does seem to recognize file.

Using the latest coverage and python 3.6.

**Comment by nedbat** [comment]
@shenkan Can you show me the code you are using, and the full error report?  Coverage.report() has a `file` argument.  What are you calling that has a `outfile`?

**Comment by 0x0c72** [comment]
@nedbat I’m calling it with file but in summary.py the keyword argument is named outfile. 

Here’s the error:  
Traceback (most recent call last):
  File "manage.py", line 25, in <module>
    cov.report(file='test-results/coverage/report')
  File "/usr/local/lib/python3.6/site-packages/coverage/control.py", line 1045, in report
    return reporter.report(morfs, outfile=file)
  File "/usr/local/lib/python3.6/site-packages/coverage/summary.py", line 95, in report
    writeout(header)
  File "/usr/local/lib/python3.6/site-packages/coverage/summary.py", line 35, in writeout
    outfile.write(line.rstrip())
AttributeError: 'str' object has no attribute 'write'
Exited with code 1

**Comment by 0x0c72** [comment]
I hope it’s not just me being stupid, I tested it as much as I could.  It just doesn’t seem to like when I specify a file when calling report.

**Comment by nedbat** [comment]
@shenkan The file argument should be an open file object, not the name of a file.  The docs could be more explicit about that.

**Comment by nedbat** [comment]
I've added more text to the report() docstring in ac7d7d9d0d10e52b4f45eded597ae962f63c4905
