### ISSUE TITLE
CoverageSqliteData.filename gets mutated with suffix

### ISSUE THREAD

**Issue by blueyed** [coveragepy/coveragepy#708]
While `CoverageJsonData.filename` will be kept as the initial basename, `CoverageSqliteData.filename` gets mutated with the suffix appended.

This is relevant for when using `combine()` on an already used Coverage object, where the suffix is included in the glob pattern then already when looking for files to combine.

This appears to be (one of) the reason(s) for pytest-cov to have a separate Coverage object for this (https://github.com/pytest-dev/pytest-cov/blob/7205428bfb9ab9f8dbcaeefe23ce5fe426bb06b9/src/pytest_cov/engine.py#L152-L155).

**Comment by nedbat** [comment]
My understanding is that the changed behavior in pytest-cov==2.6.0 also happens with coverage.py 4.5.1, so I don't think the SQLite storage code is part of the cause.

**Comment by blueyed** [comment]
Yes, that's correct.
I've just noticed this when looking into it, and I think coveragepy's API for both storages should behave the same in this regard.  That's why I've filed this issue only really.

IIRC I've looked into changing pytest-cov with regard to the new API (not really feasible, since coveragepy 4 should be supported of course).

As for pytest-django, where I've noticed and debugged this with I've gone with coveragepy directly now (https://github.com/pytest-dev/pytest-django/pull/657/commits/c72b10ad4dc3c31402fddb91465fb92492c95a1e).

**Comment by nedbat** [comment]
To be honest, I would rather change `.filename` into `._filename`. Help me understand why people are looking at `.filename` in the first place so I can get the API right.

**Comment by blueyed** [comment]
The use case is combining (see https://github.com/pytest-dev/pytest-cov/pull/226 - pytest-cov uses a separate Coverage instance just for having an unmodified `data_file` IIRC).

When looking into this I've tried to create `data_paths` manually, but `basename` is not available, and therefore this did not work - that's when I've noticed the inconsistency (this issue) - but I think it is fine to reflect the actual filename (i.e. it could stay as-is).

Instead I think `basename` should be stored additionally on the data instances, and then get used by `combine_parallel_data` (instead of `filename`):
https://github.com/nedbat/coveragepy/blob/6c14ffb41a1d1b053f8df52dc37c35f730a8666c/coverage/data.py#L685-L689

The problem currently is that `filename` gets used when looking for file's to combine, and with `CoverageSqliteData` would contain the suffix then already:
https://github.com/nedbat/coveragepy/blob/6c14ffb41a1d1b053f8df52dc37c35f730a8666c/coverage/data.py#L711-L712

**Comment by nedbat** [comment]
Heh, I ask for an example, and you show me my own code! :)

I'd like to write a failing test case for this.  It seems like the scenario is: use a Coverage object with parallel=true to run some code, then try to use that same object to combine, and it won't find all the data files?  I'm not sure that's a reasonable use case for the API, but help me understand.

**Comment by blueyed** [comment]
Yes, that't the use case.. :)

**Comment by nedbat** [comment]
I added a failing test to show the problem.  It passes with the JSON storage, and fails with SQLite.  I'm not entirely convinced this is an important case to keep working, but it shouldn't be hard to fix either.

**Comment by nedbat** [comment]
This is fixed in fdaf0356
