### ISSUE TITLE
Uphold coverage per file

### ISSUE THREAD

**Issue by lhupfeldt** [coveragepy/coveragepy#717]
Like a lot of other people I started using coverage after my projects had already reached size where it was impossible to focus on getting the coverage to my goal of 100%.
There are already ways of specifying coverage requirements and proposals for new features, e.g.  per file coverage threshold #691.

What I would like if I started implementing coverage on an existing project would be a way of guaranteeing that coverage never went down.

The way to achieve this would be to have coveragepy save the number of uncovered lines (statement/branches) per source file to a file which would then be referenced from the coverage config file and hopefully kept under revision control by the project.

If the number of uncovered lines in any source file grows then the build should fail.
There could also be a less strict coverage percent per file saved, or the even less strict covered lines per file if a project want to allow less coverage on new code then on old code.

E.g.:
```
[report]
fail_under_history = uncovered, 'my_fail_history'
```
or:
```
[report]
fail_under_history = %, 'my_fail_history'
```
or:
```
[report]
fail_under_history = covered, 'my_fail_history'
```
It needs to be possible to specify the filename so that coverage can be different for different executions, eg. different Python versions or program executed in different environments.

**Comment by nedbat** [comment]
I'm wondering if this needs to be a coverage feature? If it were easy to get the full coverage total number out, then your test-running script could do this logic on its own perhaps?

**Comment by lhupfeldt** [comment]
I think it would be difficult to parse the output and implement the logic outside of coverage. And a lot of people probably just run pytest and have no easy place to implement the logic.
I'm may try to implement it if you think it is a good idea (no delivery time promised:)

**Comment by nedbat** [comment]
I'm not a fan of trying to cram everything into a single pytest command line, but I know that people want that.  Perhaps it's a pytest plugin? 
If built-in to coverage, you'd need configuration for what to name this result, or something?

**Comment by lhupfeldt** [comment]
Yes, it should be possible to specify the filename in which the result is persisted, as described above.
You would not want this to be under the temporary .coverage directory as you would want to commit the file to your revision control system. And you want to be able to have multiple different files depending the test execution.

**Comment by krkd** [comment]
Hi i was looking for this feature and came across this issue. Wrote a quick prototype [https://github.com/krkd/pytest-cov-threshold](https://github.com/krkd/pytest-cov-threshold). Feel free to comment, modify or draw inspiration from that repository.

**Comment by nedbat** [comment]
Coverage now provides a json output file, which should make it possible to build this outside of coverage.  I think that is the way to go for now.

**Comment by nedbat** [comment]
This is a duplicate of #691.
