### ISSUE TITLE
Non existing path set in data_file causes an exception

### ISSUE THREAD

**Issue by butla** [coveragepy/coveragepy#721]
**Reproduction:**
1. Create an empty dir `/var/tmp/test`
2. In .coveragerc, section `[run]` set `data_file` to `/var/tmp/test/inner/.coverage`
3. Run any test with that.
4. FileNotFoundError is raised.

**My proposition:**
I'd like for that to just create the directory structure for the file. I think it can be done with `os.path.dirname()` and `os.makedirs()` here https://github.com/nedbat/coveragepy/blob/master/coverage/data.py#L495
Should that be OK?
Is there any reason not to implement that?

**More context:**
I'd use that when measuring coverage in an application's Docker container. Sadly, I can't just use whatever directory there is and then just issue a `docker cp` with a wildcard pattern to get all the `.coverage.*` files from the container before merging the data, because that's not implemented https://github.com/moby/moby/issues/7710 I can work around that, but maybe it'd just be nice if I didn't have to.

**Comment by nedbat** [comment]
Implemented in https://github.com/nedbat/coveragepy/commit/8271bf4c4d5272043677f37a65e16d21621133cb

**Comment by butla** [comment]
Thanks!

**Comment by nedbat** [comment]
This was released as part of 5.0a4.
