### ISSUE TITLE
Importing any library to coverage results in 0% coverage

### ISSUE THREAD

**Issue by AboudFayad** [coveragepy/coveragepy#722]
I am trying to add an inline-style css functionality to `coverage html`. I am doing that by modifying "./coverage/html.py" but when I add any python library to it, in this case `import inlinestyler`, tox tests start failing, and the output of `coverage html` is always 0% coverage and all the lines are red (missing), even though the original code of coverage have not been modified, other than adding an import statement.

**Comment by nedbat** [comment]
@AboudFayad I'm not sure how to help here. You haven't provided any details (links to your code, error reports, etc).  You shouldn't have to edit html.py to accomplish what you need.  Can you say more about what you are trying to do?

**Comment by AboudFayad** [comment]
So basically I want to convert referenced css classes into inline style. For example: 

Referenced css
~~~~
<html>
<style type="text/css">
h1 { border:1px solid black }
p { color:red;}
</style>
<h1 style="font-weight:bolder">Peter</h1>
<p>Hej</p>
</html>
~~~~
inline style css
~~~~
<html>
<h1 style="font-weight:bolder; border:1px solid black">Peter</h1>
<p style="color:red">Hej</p>
</html>
~~~~

This is done because some web hosting service don't allow css referencing and blocks it, hence the inline is needed. This could be done by by having a pipeline that takes the output of coverage and then converting the css, but I do not want having an extra pipeline to do this, therefore I added the functionality straight to coverage. You can check the code and changes here: https://github.com/AboudFayad/coveragepy

The thing that I am facing now is when I add a library to 'coveragepy/coverage/html.py' as follows:
~~~~
"""HTML reporting for coverage.py."""

import datetime
import json
import os
import re
import shutil
from inlinestyler.utils import inline_css  # added library

import coverage
from coverage import env
from coverage.backward import iitems
from coverage.data import add_data_to_hash
from coverage.files import flat_rootname
from coverage.misc import CoverageException, file_be_gone, Hasher, isolate_module
from coverage.report import Reporter
from coverage.results import Numbers
from coverage.templite import Templite
~~~~

This results in coverage not working properly, and when it is run, it outputs 0% coverage and highlights all the lines red on the html generated page. This occurs even without modifying html.py, just by adding the library (all other libraries I tried also gave the same behaviour eg. Numpy).

**Comment by nedbat** [comment]
You say:

> This occurs even without modifying html.py, just by adding the library

Do you mean you pip install a library, and coverage stops working?  That makes no sense to me.  People install libraries and use coverage successfully all the time.  Can you give me specific instructions to reproduce the scenario?  Exactly what packages did you install, and what commands did you run?

**Comment by AboudFayad** [comment]
I meant when you import a library in html.py

To reproduce my problem:

- Add `from inlinestyler.utils import inline_css` to html.py (you can get this library by `pip install inlinestyler`).

- Then run `python -m coverage html --directory ../test ../your_test.py`

- Check the results of the html file generated

Also, you can try running `tox` after adding the library and test will start failing.

**Comment by nedbat** [comment]
I cannot reproduce this problem with my own test code.  Something else is going on to change the results, perhaps something in the repo you are testing?

**Comment by AboudFayad** [comment]
I ran the tests using `tox` again after adding the library to pytest.pip and they are all passing now.

**Comment by nedbat** [comment]
That's good to hear :)
