### ISSUE TITLE
Class-level variable not covered

### ISSUE THREAD

**Issue by unformatt** [coveragepy/coveragepy#725]
coverage 4.5.1
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin

FWIW, it's a django model.

![image](https://user-images.githubusercontent.com/157132/47929545-bacd8e80-de9f-11e8-815d-1af992e88e8b.png)

**.coveragerc**
```
[run]
include = ./*

[report]
exclude_lines =
  pragma: no cover

    # Don't complain about missing debug-only code:
    # def __unicode__
    # def __repr__
    if self\.debug

    # Don't complain if tests don't hit defensive assertion code:
    raise AssertionError
    raise NotImplementedError

    # Don't complain if non-runnable code isn't run:
    if 0:
    if __name__ == .__main__.:

omit =
    */migrations/*
    */admin.py
    */management/commands/test_*

show_missing = True
skip_covered = True

[html]
directory = coverage_report
```

**Comment by nedbat** [comment]
Hmm, that looks odd. Can you give me instructions to reproduce it?

**Comment by nedbat** [comment]
Feel free to re-open if you can tell me how to reproduce the problem.
