### ISSUE TITLE
Impossible coverage result

### ISSUE THREAD

**Issue by pckroon** [coveragepy/coveragepy#726]
Hi all,

I got the following seemingly impossible coverage result.

![screenshot from 2018-11-05 13-55-59](https://user-images.githubusercontent.com/12967865/47999345-a1784c80-e102-11e8-80b1-58b197b5089d.png)

`violation` is a bool, and even though it is occasionally `True` (line 524 is covered), coverage claims line 525 (`if violation or ...`) is never true, and 526 is uncovered.
What am I missing?

**Comment by nedbat** [comment]
I will guess that this code is inside a for-loop, and that this is a duplicate of #198.

**Comment by pckroon** [comment]
Jep, correct in one try. Sorry for the noise and keep up the great work!
Closed as duplicate of #198
