### ISSUE TITLE
Outdated information in PyPI

### ISSUE THREAD

**Issue by Mariatta** [coveragepy/coveragepy#731]
I went to https://pypi.org/project/coverage/ and I noticed some information are outdated (referencing the old bitbucket repo)

On the left, under Project Links, the Homepage url is https://bitbucket.org/ned/coveragepy instead of https://github.com/nedbat/coveragepy/

On the right, under Project description, it says that "Code repository and issue tracker are on Bitbucket, with a mirrored repository on GitHub."

**Comment by nedbat** [comment]
Ugh, I missed the url in setup.py, and I just pushed a new version yesterday... :(

**Comment by nedbat** [comment]
Fixed in 059daf6a911cfe707dc407e8a476c3fe501346fd, though not sure when it will get to PyPI.

**Comment by Mariatta** [comment]
Thanks. Yeah I noticed the url because of the yesterday's new release. 😐
pyup-bot sent me a PR (https://github.com/Mariatta/check_python_cla/pull/31) with coverage 4.5.2, and it has the link to bitbucket. I figured that pyup got the link wrong from the PyPI metadata.
