### ISSUE TITLE
Regression: false positive in a function returning a function

### ISSUE THREAD

**Issue by sam-s** [coveragepy/coveragepy#733]
For the following code:
```python
def make_foo(...):
    def foo(...):
        pass
    return foo
```
the line with `pass` is now reported as `Missing` (it was not reported as such a month ago).
When I replace `pass` with `raise Value("missing coverage")`, I see many `ValueError: missing coverage` traces.

Version: `version 4.5.2 with C extension`.
Also present in `version 4.5.1 with C extension`.

**Comment by nedbat** [comment]
Thanks.  What version were you using a month ago?  4.5.1 came out in February 2018.

**Comment by sam-s** [comment]
I don't have a record of what I was using before, probably 4.5.1.
I am stumped too.

**Comment by nedbat** [comment]
Can you create a complete runnable example?  Links to large projects are fine if you have specific instructions of how to run them, and where to see the problem.

**Comment by sam-s** [comment]
Alas, the project is large and private, and the trivial test case does not exhibit the problem.

**Comment by sam-s** [comment]
Okay, I now have the commit in _my_ project which introduced the weirdness.
How would you like me to debug it?

**Comment by nedbat** [comment]
Can you share the commit diff?  Is it a requirements change, or a code change?

**Comment by sam-s** [comment]
It is a code change.
What was done in-process before, is now done via `joblib.Parallel(prefer="processes")`.
Here is the test example: `code/foo.py`:
```python
def make_foo(a):
    def foo():
        print(a)
    return foo
```
`tests/foo_test.py`:
```python
import unittest

import code.foo as f
import joblib

class TestFoo(unittest.TestCase):
    def test_foo(self):
        foo = f.make_foo("test_foo")
        self.assertTrue(hasattr(foo,"__call__"))
        with joblib.Parallel(n_jobs=3, prefer="processes") as pool:
            self.assertEqual([None],pool([joblib.delayed(foo)()]))
```
execute:
`coverage3 run --source=code -m unittest discover --pattern *_test.py && coverage3 report -m`
output:
```
test_foo
.
----------------------------------------------------------------------
Ran 1 test in 0.284s

OK
Name               Stmts   Miss  Cover   Missing
------------------------------------------------
code/__init__.py       0      0   100%
code/foo.py            4      1    75%   3
------------------------------------------------
TOTAL                  4      1    75%
```
note that `print(a)` in `foo.py` is reported as `Missing` while, in fact, it _is_ hit because you can see `test_foo` printed in the output.

**Comment by nedbat** [comment]
It sounds like the code is being run in a subprocess when it wasn't before?  Have you tried configuring subprocess measurement? https://coverage.readthedocs.io/en/v4.5.x/subprocess.html
