### ISSUE TITLE
Support [run] command_line configuration setting and command line simultaneously

### ISSUE THREAD

**Issue by crd** [coveragepy/coveragepy#735]
The newly-added ``[run] command_line`` configuration setting added with e57549076220764ace6f2b67da3600ff5ae33f02 in response to #695 is presently only considered if `args` is empty. That is, if the user provides any command line arguments at all (like `path/to/file.py`) the command_line setting is ignored.

It would be preferable if configuration could be spread across `.coveragerc` and the command line. This would allow users to (for example) specify a subset of tests:

```
[run]
source = .
omit = features/steps/*
command_line = -m behave
```

```
$ coverage run features/local/*
```

```
$ coverage run features/integrated/*
```

I have a contribution with tests for you, I just need to get another set of eyes on it first.

**Comment by nedbat** [comment]
Can you tell me precisely how the two sources are combined?

What if I have `command_line = foo.py`, and then do `coveage run bar.py`?  Is there precedent in other tools for how you want to do this?  Perhaps this should be handled similar to tox's `{posargs}`?

**Comment by crd** [comment]
Hey @nedbat -- `{posargs}` is interesting, but feels a bit like overkill. Concatenation seemed to be the most straightforward:

```
def test_run_module_from_config_with_commandline_arguments(self):
        self.cmd_executes("run arg1 arg2", """\
            .Coverage()
            .start()
            .run_python_module('mymodule', ['mymodule', 'arg1', 'arg2'])
            .stop()
            .save()
            """,
            options={"run:command_line": "-m mymodule"},
            )
```

```
        if not args:
            if options.module:
                # Specified -m with nothing else.
                self.help_fn("No module specified for -m")
                return ERR
    
        command_line = self.coverage.get_option("run:command_line")
        if command_line is not None:
            if args is not None:
                args = shlex.split(command_line) + args
            else:
                args = shlex.split(command_line)
            if args and args[0] == "-m":
                options.module = True
                args = args[1:]
        if not args:
            self.help_fn("Nothing to do.")
            return ERR
```

Happy to defer to you on how you'd like to handle this, though.

**Comment by crd** [comment]
Thinking about this a bit more, I feel like parameters passed on the command line should override those specified in a config file, rather than simple concatenation.

**Comment by nedbat** [comment]
OK, that's the way the code works now, right? I'm happy to leave it as is, and see what feedback we get.

**Comment by crd** [comment]
Happy to defer until the community has a chance to play around with the functionality
