### ISSUE TITLE
Confused by the release system

### ISSUE THREAD

**Issue by AdrienLemaire** [coveragepy/coveragepy#736]
I noticed that the pypi  coveragepy package had a release update from 4.5.1 to 4.5.2, but this doesn't match the release notes at https://github.com/nedbat/coveragepy/blob/master/CHANGES.rst

**Comment by AdrienLemaire** [comment]
Found https://coverage.readthedocs.io/en/v4.5.x/changes.html . Guess I'll bookmark that link instead

**Comment by nedbat** [comment]
Yup, the docs are the way to go.

Master is the 5.0 development line.  The v4.5.x branch in GitHub is for the 4.5.x maintenance line.
