### ISSUE TITLE
Documentation: Support for permalinks

### ISSUE THREAD

**Issue by mtlynch** [coveragepy/coveragepy#737]
Is there a supported way for permalinking to parts of documentation?

For example, a few months ago, I linked to:

* https://coverage.readthedocs.io/en/coverage-4.5.1a/config.html

But then that 404'ed when 4.5.1 came out and the new URL became:

* https://coverage.readthedocs.io/en/coverage-4.5.1/config.html

Now that 4.5.2 is out, the above URL is now broken.

I wrote a [tutorial](https://mtlynch.io/resurrecting-3/#adding-code-coverage) that I know works in 4.5.1a and 4.5.1. It would be great if I could link to the documentation for that specific version forever so that it doesn't break on the next update to `coverage`.

**Comment by nedbat** [comment]
You can always link to "latest" as the version number: https://coverage.readthedocs.io/en/latest/config.html , though that will currently refer to 5.0 alpha.  There's also "v4.5.x", which is a recent innovation.  I can keep those branch names working in the future, so we'd have "v4.5.x" and "v5.0.x".

Would that work?

**Comment by mtlynch** [comment]
Thanks for the response @nedbat!

The issue with "latest" is that there's a risk of the page name changing. Like if I like to `/latest/foo.html` in 5.0 alpha then you decide to change it to `/latest/bar.html` in 6.0, then my link breaks.

The 4.5.x solution should work as long as the risk of page name changes are low within minor version updates.
