### ISSUE TITLE
cython coverage fails for simple function

### ISSUE THREAD

**Issue by s-sajid-ali** [coveragepy/coveragepy#738]
I have a trivial function in a [repo](https://github.com/s-sajid-ali/cython_test_coverage) to test cython coverage.  

I've followed all the directives mentioned in the [cython docs](https://cython.readthedocs.io/en/latest/src/tutorial/profiling_tutorial.html).

I have in my repo : 
- enabled line tracing in the .pyx file - [1](https://github.com/s-sajid-ali/cython_test_coverage/blob/master/cython_test_coverage/basic_cython.pyx)
- passed the relevant macro to distutils - [2](https://github.com/s-sajid-ali/cython_test_coverage/blob/master/setup.py)
- included cython.coverage in .coveragerc - [3](https://github.com/s-sajid-ali/cython_test_coverage/blob/master/.coveragerc)
- included a cython directive for the html report in .travis.yml - [4](https://github.com/s-sajid-ali/cython_test_coverage/blob/master/.travis.yml)

Yet, I don't see any coverage report for the cython source file on codecov. What am I missing ?

Thank You.

**Comment by webknjaz** [comment]
@nedbat I think this can be closed since the example repo currently implements all that's needed and pyx module coverage shows up in codecov: https://codecov.io/gh/s-sajid-ali/cython_test_coverage/src/master/cython_test_coverage/basic_cython.pyx

**Comment by s-sajid-ali** [comment]
@webknjaz Yes, I'll close this. Sometime between asking for help here and the current state of the repository, I fixed the issue!
