### ISSUE TITLE
Coverage 5 not working on NFS

### ISSUE THREAD

**Issue by bykbrian** [coveragepy/coveragepy#741]
I am running coverage using `py-cov` as part of the `pytest` session. When running with `coverage-5.0a4` the process gets locked apparently due to my home dir being on NFS. This is not happening with `coverage-4.5.2` - that version completes smoothly.

This is the strace up to the lock:
```
lstat(".coverage", 0x7ffcf3ed9290)      = -1 ENOENT (No such file or directory)
getcwd("/home/bbyk/myprj", 511) = 35
getpid()                                = 3949
getpid()                                = 3949
openat(AT_FDCWD, "/home/bbyk/myprj/.coverage", O_RDWR|O_CREAT|O_CLOEXEC, 0644) = 8 
fstat(8, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0 
fstat(8, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
stat("/home/bbyk/myprj/.coverage", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0 
pread64(8, "", 100, 0)                  = 0 
fcntl(8, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=1}
```

**Comment by bykbrian** [comment]
btw. I understand some features on NFS can't work - just wondering whether this loss of functionality between the versions is legitimate/expected/worth it...

**Comment by nedbat** [comment]
It's definitely not intentional.  Do you have experience diagnosing these problems?  The big change in v5 is that .coverage is a SQLite file rather than a JSON file.

**Comment by bykbrian** [comment]
Ah, ok, that explains it - sqlite is not compatible with most NFS implementations. I guess I just need to point the `.coverage` to be stored outside of NFS.
