### ISSUE TITLE
Missing all lines when using run_all_tests_in_graph_and_eager_modes decorator

### ISSUE THREAD

**Issue by Bihaqo** [coveragepy/coveragepy#751]
When testing TensorFlow code and using run_all_tests_in_graph_and_eager_modes decorator to make it run each test twice with and without eager mode, running
`
coverage run test.py
`
`
coverage report -m
`
works correctly, but running
`
nosetests --with-coverage --cover-package=test
`
report all lines missing. Here is a smallest reproducing example: https://pastebin.com/39ZLz0f0
And here is the actual code I encountered it in: https://coveralls.io/builds/20928629/source?filename=t3f%2Futils_test.py#L9

Commenting run_all_tests_in_graph_and_eager_modes decorator out makes everything work properly (but I do want to use it).

**Comment by nedbat** [comment]
I can't reproduce this problem.  I get 100% with nose or without:
```
$ python -V
Python 3.6.7

$ pip freeze
absl-py==0.6.1
astor==0.7.1
coverage==4.5.2
gast==0.2.1
grpcio==1.17.1
h5py==2.9.0
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
Markdown==3.0.1
nose==1.3.7
numpy==1.15.4
protobuf==3.6.1
six==1.12.0
tensorboard==1.12.2
tensorflow==1.12.0
termcolor==1.1.0
Werkzeug==0.14.1

$ coverage run --source=. test.py
2019-01-06 17:39:57.489737: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
..
----------------------------------------------------------------------
Ran 2 tests in 0.003s

OK

$ coverage report -m
Name      Stmts   Miss  Cover   Missing
---------------------------------------
test.py       7      0   100%

$ nosetests --with-coverage --cover-package=test
.
Name      Stmts   Miss  Cover
-----------------------------
test.py       7      0   100%
----------------------------------------------------------------------
Ran 1 test in 4.489s

OK
```
BTW, I had to fix a typo in the pastebin (`s/name/__name__`), are you sure you ran it with the small sample?

In any case: if the problem only appears with nose, then the problem is probably with nose.  But nose is unmaintained.  If it continues to give you trouble, I recommend switching to pytest, or at least avoiding the nose coverage plugin.

**Comment by Bihaqo** [comment]
Thanks for a quick response! Weird, I can't reproduct it right now either, but I did experience it both locally and on coveralls...

Sure, I would be happy to switch to pytest if you say it's better. However, I just tried running it locally and `pytest` runs nicely, but `pytest --cov=t3f` reports every test to fail with the error


> ../miniconda3/lib/python3.6/site-packages/pytest_cov/plugin.py:289: AttributeError
> ____________________________________________ BatchKroneckerTestFloat64.testIsKronNonKron _____________________________________________

> self = <pytest_cov.plugin.CovPlugin object at 0x7fee98161898>, item = <TestCaseFunction testIsKronNonKron>

>    @compat.hookwrapper
>    def pytest_runtest_call(self, item):
>       if (item.get_marker('no_cover')
>                or 'no_cover' in getattr(item, 'fixturenames', ())):
> E               AttributeError: 'TestCaseFunction' object has no attribute 'get_marker'

**Comment by nedbat** [comment]
I don't know what that error means, and have no experience with Tensorflow, so I'm not sure what's going on.  Thanks for confirming my results.
