### ISSUE TITLE
4.5.2 update breaks TSTL CI tests

### ISSUE THREAD

**Issue by agroce** [coveragepy/coveragepy#755]
**Describe the bug**

TSTL Travis tests fail after the change, looks like what's causing it is:
`coverage.misc.CoverageException: Couldn't use data file '/home/travis/build/agroce/tstl/examples/bintrees/.coverage': UNIQUE constraint failed: file.path` and similar exceptions.

**To Reproduce**

See: https://travis-ci.org/agroce/tstl/builds/481037417

Contrast with: https://travis-ci.org/agroce/tstl/builds/481048070

Only change is to pin coverage to 4.5.1 in the setup.py

**Expected behavior**

The TSTL CI tests should pass, as they did before the update to 4.5.2.

**Additional context**

I'm just submitting this in case it's obvious; will update with more detail about the issue if I can find it.
Could be linux specific, in that I so far see no problems running the tests on my mac with latest TSTL and 4.5.2.

**Comment by nedbat** [comment]
Based on the error message, it looks like you upgraded to coverage 5.0alpha.  If you pin to 4.5.2, you won't have the problem.

**Comment by agroce** [comment]
Aha, interesting.  When I did a pip install coverage --upgrade on mac, I got 4.5.2, so assumed on travis it'd not be a pre-release beta.  I'll try pinning to 4.5.2!  Thanks!

**Comment by agroce** [comment]
(to confirm, pinning to 4.5.2 did fix)
