### ISSUE TITLE
Latest stable release not described at documentation website

### ISSUE THREAD

**Issue by bignose-debian** [coveragepy/coveragepy#758]
The [online documentation for Coverage.py](https://coverage.readthedocs.io/) currently says:

> This is a pre-release build. The usual warnings about possible bugs apply.
> The latest stable version is coverage.py 4.5.2, described here.

The “described here” is a link to the same document.

The documentation link “[Change history for Coverage.py](https://coverage.readthedocs.io/en/latest/changes.html)” currently does not have a changelog entry for version 4.5.2.

**Expected behavior**

* The default online documentation should be for the latest stable version (not an unreleased snapshot).

* The published changelog document should have changelog entries for all the published releases.

**Comment by nedbat** [comment]
I'm not sure if this is fixed now for real, or if it depends on whether I last published a stable or pre-release version.
