### ISSUE TITLE
specify my rcfile with COVERAGE_RCFILE environment variable, doesn't work

### ISSUE THREAD

**Issue by ruck94301** [coveragepy/coveragepy#763]
**Describe the bug**
docs say I can specify my rcfile with COVERAGE_RCFILE environment variable, but it doesn't work for me.

**Additional context**
I can’t make that work, and I searched the code (4.5.1), and I’m thinking that’s not yet true (or no longer true).
So based on quick look at the code, instead of
    cov = coverage.Coverage()
I do this:
    cov = coverage.Coverage(config_file=os.getenv('COVERAGE_RCFILE'))

Best regards,
John R.

https://media.readthedocs.org/pdf/coverage/latest/coverage.pdf
Coverage.py, Release 5.0a4 A different location for the configuration file can be specified with the --rcfile=FILE command line option or with the COVERAGE_RCFILE environment variable.

Ohhh, maybe not supported in 4.5.1, but supported in 5.0?
I’ve confused myself because the online docs (5.0a4) are fresher than the most recent release 4.5.2

**Comment by ruck94301** [comment]
to clarify, this doesn't get the rcfile defined by COVERAGE_RCFILE:
  cov = coverage.Coverage()
but this workaround works for me:
  cov = coverage.Coverage(config_file=os.getenv('COVERAGE_RCFILE'))
John R.

**Comment by nedbat** [comment]
Sorry for the delay: yes, COVERAGE_RCFILE is new in 5.0.
