### ISSUE TITLE
Canonical filename cache never hits.

### ISSUE THREAD

**Issue by strichter** [coveragepy/coveragepy#768]
**Describe the bug**
When looking up a canonical filename, the result should be stored in a cache. However during the computation, the cache key is modified causing the cache to never hit.

On our systems with a large `sys.path` we saw a 25x slowdown while merging coverage reports, which heavily utilizes this function, if an alias is specified.

Bugfix + Test Verification: https://github.com/nedbat/coveragepy/pull/767

**Comment by nedbat** [comment]
Fixed in 1655796d48cb67d7247b41a09fe5c2463b32d47a
