### ISSUE TITLE
When coverage is used, behavior for unittest.assertRaisesRegex differs depending on whether it is used as a context manager

### ISSUE THREAD

**Issue by SylvainDe** [coveragepy/coveragepy#773]
**Describe the bug**

In a particular situation `unittest.assertRaisesRegex` seems to have a different behavior when `coverage` is used.

The following unit tests:

```

    DESCRIPT_REQUIRES_TYPE_RE = r"descriptor '\w+' requires a 'set' object but received a 'int'"

    ...

    def test_assertRaisesRegex(self):
        self.assertRaisesRegex(TypeError, DESCRIPT_REQUIRES_TYPE_RE, set.add, 0)

    def test_assertRaisesRegex_contextman(self):
        with self.assertRaisesRegex(TypeError, DESCRIPT_REQUIRES_TYPE_RE):
            set.add(0)

```

have a different behavior when coverage is used or when it is not. When `coverage` is used, it looks as if the exception thrown had a different error message.

Also, the behavior seems to be different from one Python version to another. In particular: we have the following results so far (Versions numbers are retrieved with python -VV and python -c "import sys; print(sys._git)"):

    On some versions, both tests pass:
        Python 3.6 and before - coverage 4.5.2
        Python 3.7.0a4+ (heads/master:4666ec5, Jan 26 2018, 04:14:24) - [GCC 4.8.4] - ('CPython', 'heads/master', '4666ec5')) - coverage 4.5.2

    On some versions, both tests fail:
        Python 3.8.0a1+ (heads/master:8a03ff2, Feb 9 2019, 07:30:26) [GCC 5.4.0 20160609] - ('CPython', 'heads/master', '8a03ff2') - coverage 4.5.2

    On some versions, only test_assertRaisesRegex_contextman fails which is what I find confusing:
        Python 3.7.1 (default, Dec 5 2018, 18:09:53) [GCC 5.4.0 20160609] - ('CPython', '', '') - coverage 4.5.2
        Python 3.7.2+ (heads/3.7:3fcfef3, Feb 9 2019, 07:30:09) [GCC 5.4.0 20160609] - ('CPython', 'heads/3.7', '3fcfef3') - coverage 4.5.2

**To Reproduce**

The unit tests above can be used.
I have create a branch on my project to have the minimal setup to reproduce the issue and run Travis on it:
 - code: https://github.com/SylvainDe/DidYouMean-Python/blob/issue36_investigation/didyoumean/didyoumean_sugg_tests.py
 - last Travis build (so far): https://travis-ci.org/SylvainDe/DidYouMean-Python/builds/491814959

I'm happy to add any commit to have more debug information if needed.

How can we reproduce the problem?  Please *be specific*.

1. What version of Python are you running?
Various and behavior is different from one version to another - see Travis logs

2. What versions of what packages do you have installed? The output of `pip freeze` is very helpful.
Only `coverage` is installed.

3. What code are you running?  Give us a specific commit of a specific repo that we can check out.
A simple unit-test available above or on the dedicated branch on the Github repository.

4. What commands did you run?

The command to run is:

    coverage run -m unittest discover --start-directory=didyoumean --pattern=*.py

When:

    python -m unittest discover --start-directory=didyoumean --pattern=*.py

is used, the result is different (it corresponds to the expected behavior).

**Expected behavior**

I'd expect `coverage` to have no impact on the behavior of the code being run. Also, I'd expect `unittest.assertRaisesRegex` to have the same behavior regardless of how we run it.

**Additional context**

Originally opened as a ticket on my project ( https://github.com/SylvainDe/DidYouMean-Python/issues/36 ) then as a StackOverflow question ( https://stackoverflow.com/questions/54612348/different-error-message-when-unittest-assertraisesregex-is-called-as-a-context-m ) then as a Python bug ( https://bugs.python.org/issue35965 ) because I did not expect `coverage` to be responsible for the issue.

**Comment by SylvainDe** [comment]
The issue is reproduced with all coverage I've tested. Here is the list:

```
.travis.yml: - pip install coverage==3.7.1
.travis.yml: - pip install coverage==4.0
.travis.yml: - pip install coverage==4.2
.travis.yml: - pip install coverage==4.5.1
.travis.yml: - pip install coverage==4.5.2
.travis.yml: - pip install coverage==5.0a1
.travis.yml: - pip install coverage==5.0a2
.travis.yml: - pip install coverage==5.0a3
.travis.yml: - pip install coverage==5.0a4
```

Also, I'd like to pinpoint the exact commit in CPython leading to a different behavior using some `git bisect` but I was unable to create a venv based on my locally built cpython versions (which I do not want to install on my system). I'll give it another try if you think it may help.

**Comment by nedbat** [comment]
Something odd is going on here.  With or without coverage, Python 3.7.2 produces different exceptions for the same error:
```
$ python -V
Python 3.7.2

$ pip install coverage
Collecting coverage
  Using cached https://files.pythonhosted.org/packages/be/88/7e5e548329eda1f003b3ff34e57ba6b2b1f8b8983043e99a0ecf58ae0a06/coverage-4.5.2-cp37-cp37m-macosx_10_13_x86_64.whl
Installing collected packages: coverage
Successfully installed coverage-4.5.2

$ cat bug773a.py
set.add(0)

$ python bug773a.py
Traceback (most recent call last):
  File "bug773a.py", line 1, in <module>
    set.add(0)
TypeError: descriptor 'add' requires a 'set' object but received a 'int'

$ python -m coverage run bug773a.py
Traceback (most recent call last):
  File "bug773a.py", line 1, in <module>
    set.add(0)
TypeError: descriptor 'add' for 'set' objects doesn't apply to 'int' object
```

I don't know why that is, and I don't know why the context manager use of assertRaisesRegex affects the error produced.  I also don't know if I would try to fix this, whatever is causing it.  Python fiddles with how things get executed from version to version.

**Comment by nedbat** [comment]
OK, the difference in error message has to do with whether a trace function is set or not:
```
def trace(frame, event, arg):
    return trace
import sys
sys.settrace(trace)
set.add(0)
```
This produces the same message as with coverage:
```
$ python bug773_with_trace.py
Traceback (most recent call last):
  File "bug773_with_trace.py", line 5, in <module>
    set.add(0)
TypeError: descriptor 'add' for 'set' objects doesn't apply to 'int' object
```

**Comment by SylvainDe** [comment]
Hello @nedbat, thanks for your analysis.
It looks like this is actually a (Python/settrace/assertRaisesRegex) bug and not a coverage bug indeed.
I'll have another look at things with this new perspective. Eventually, I'll probably open a Python bug and close this one if it is fine for your.
Best regards

**Comment by nedbat** [comment]
I agree this is not a coverage.py issue, but a settrace, and somehow, a context manager issue.  I'll close this issue, thanks for reporting it with enough detail to diagnose it.

**Comment by SylvainDe** [comment]
FYI, the issue opened on the Python side is https://bugs.python.org/issue36026 . Sorry for the inconvenience and thanks for the very valuable input.
