### ISSUE TITLE
`--no-skip-covered` to negate `--skip-covered`

### ISSUE THREAD

**Issue by asottile** [coveragepy/coveragepy#779]
**Is your feature request related to a problem? Please describe.**

For test run outputs, I set `skip_covered = true` in my `.coveragerc` (for example [here](https://github.com/asottile/all-repos/blob/1a3d612bd90e826c99257ebf7ff6e1762742d479/.coveragerc#L14)).  I do this to avoid the terminal spew of the 50+ 100% covered files.

However, for html outputs, I'd still like to have files included when running `coverage html`, even if they are 100% covered.

**Describe the solution you'd like**

I think the _simplest_ solution would be to add `--no-skip-covered` options to the various `coverage html` / `coverage report` entrypoints which would override the `--skip-covered` option.

**Describe alternatives you've considered**

Not really seriously considered, but `sed -i /skip_covered/d .coveragerc` before running `coverage html` -- pretty haxy though ;)

**Additional context**

I'm mostly trying to target automated CI here, in particular azure pipelines coverage reporting

**Comment by asottile** [comment]
@nedbat alternatively, should `--skip-covered` change the output for `coverage html`? it doesn't change the output of `coverage xml` for instance

**Comment by asottile** [comment]
https://bitbucket.org/ned/coveragepy/issues/433/coverage-html-does-not-suport-skip-covered seems to be the opposite direction :thinking:

**Comment by nedbat** [comment]
This is now released as part of [coverage 5.2](https://pypi.org/project/coverage/5.2).
