### ISSUE TITLE
`Diff` two `.coverage` files?

### ISSUE THREAD

**Issue by nishit-parekh** [coveragepy/coveragepy#784]
Given two `.coverage` files, is it possible to create a third `.coverage` file showing the difference between the two? The most simple use case I can think of is seeing what parts of code are affected by one or the other test case only, like a XOR function.

Since the `.coverage` files say _"This is a private format, don't read it directly!"_, I wouldn't want to run some external `diff` tool on it directly. Which is why I want to know if there is some other way to do this.

**Comment by nedbat** [comment]
You can't diff the files directly, but you can use the [coverage data api](https://coverage.readthedocs.io/en/v4.5.x/api_coveragedata.html) to read the two files and produce the result you want.

**Comment by nishit-parekh** [comment]
Oh yes! Why did I not think of that earlier! Thank you @nedbat
