### ISSUE TITLE
Question: Detecting potential attribute access

### ISSUE THREAD

**Issue by muratabur** [coveragepy/coveragepy#786]
Hello, 
We are trying to test a large library of functions on heterogeneous data that may or may not have the required attributes for each function. 
Do you know of a means to dynamically detect potential attribute access within a function (either in coverage.py or otherwise)?

eg.
```python
def foo(object):
  if object.attr == "x":
    return object.other_attr
  else:
    return object.another_attr
```

So in this case, we would like to know that object needs to have "attr", "other_attr" and "another_attr" to avoid an AttributeError somewhere.

Thank you!
Murat

**Comment by nedbat** [comment]
This doesn't sound like something that coverage.py can help with.
