### ISSUE TITLE
Request to generate report without touching files.

### ISSUE THREAD

**Issue by Anakin-Hao** [coveragepy/coveragepy#794]
**Is your feature request related to a problem? Please describe.**
I need to run code coverage check in a container inside kubernetes.
Read access is limited inside that container. So, cov.save() and cov.html_report() would throw exception complaining about write access to "[Errno 30] Read-only file system: 'htmlcov'"

**Describe the solution you'd like**
I would like to have an function to report the result directly from memory without touching files.
E.g. cov.html_report(write_to_file=False)

**Describe alternatives you've considered**
I have considered to enable write access for that container. It's possible but very unpractical.

**Additional context**
N/A

**Comment by nedbat** [comment]
The HTML report includes a separate page for each source file.  I don't see how to do it without writing files. Even if it could all stay in memory, you'd need to somehow get the HTML to a browser, so coverage would have to serve it?

Have you tried a simple textual report like "coverage report" shows? It's `cov.report()` in the API.

**Comment by Anakin-Hao** [comment]
@nedbat Just tried cov.report(). Yes it writes the report into stdout.

Is there anyway I can get a json object instead of writing to stdout ?

**Comment by Anakin-Hao** [comment]
In fact i think it's more flexible if report() (and other *report functions) has an optional parameter for which reporter to invoke:
```
class Coverage(object):
    def report(
        self, 
        morfs=None,
        show_missing=None, 
        ignore_errors=None,
        file=None
        omit=None, 
        include=None, 
        skip_covered=None,
        reporter=None  # new parameter
    ):
```

The overall obstacle I have atm is to get the result data out as "data". Not as any format of files or console output.
Having such design would decouple coverage.py's reporting feature away from control functions.

**Comment by Anakin-Hao** [comment]
The overall obstacle I have atm is to get the result data out as "data". Not as any format of files or console output.

**Comment by nedbat** [comment]
It sounds like you want the Data api instead: https://coverage.readthedocs.io/en/v4.5.x/api_coveragedata.html

**Comment by Anakin-Hao** [comment]
Hi @nedbat Thanks.
Could you link an example somewhere ?

**Comment by Anakin-Hao** [comment]
Hi @nedbat, could you provide a link to an example?
Let me know if it's too much to ask. I noticed you have consultancy going.
