### ISSUE TITLE
macOS Python 2.7: coverage 5.0a5 binary wheel has broken tracer.so

### ISSUE THREAD

**Issue by jamadden** [coveragepy/coveragepy#809]
**Describe the bug**
The CTracer cannot be imported in 5.0a5 using [the binary wheel distributed on PyPI](https://files.pythonhosted.org/packages/c7/b8/5f158a568789a6e7bea4c6377c0e96ce415b6110d57aa0ad6b981cdaa557/coverage-5.0a5-cp27-cp27m-macosx_10_13_intel.whl):

```pycon
$ python
Python 2.7.16 (default, Apr  1 2019, 14:50:41)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import coverage.tracer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(//lib/python2.7/site-packages/coverage/tracer.so, 2): 
Symbol not found: _Py_XSETREF
  Referenced from: //lib/python2.7/site-packages/coverage/tracer.so
  Expected in: flat namespace
 in //lib/python2.7/site-packages/coverage/tracer.so
```

5.0a4 imports just fine:
```console
$ pip install coverage==5.0a4 && coverage --version
Collecting coverage==5.0a4
  Using cached https://files.pythonhosted.org/packages/09/78/c3551fea530182a8608cc084709bb9e0b90e238b3ce70bdd09f45e4af7ad/coverage-5.0a4-cp27-cp27m-macosx_10_13_intel.whl
Installing collected packages: coverage
  Found existing installation: coverage 5.0a5
    Uninstalling coverage-5.0a5:
      Successfully uninstalled coverage-5.0a5
Successfully installed coverage-5.0a4
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Coverage.py, version 5.0a4 with C extension
Full documentation is at https://coverage.readthedocs.io/en/coverage-5.0a4
```

5.0a5 works just fine (has the C tracer) in Python 3.7 on the same machine.

The above Python was built by MacPorts, but the system python has the same issue:

```console
$ mktmpenv -p /usr/bin/python2.7
...
$ pip install coverage==5.0a5
...
$ python
Python 2.7.10 (default, Feb 22 2019, 21:55:15)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import coverage.tracer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(//tmp-bd43eafaa85bb3ae/lib/python2.7/site-packages/coverage/tracer.so, 2):
 Symbol not found: _Py_XSETREF
  Referenced from: //tmp-bd43eafaa85bb3ae/lib/python2.7/site-packages/coverage/tracer.so
  Expected in: flat namespace
 in //tmp-bd43eafaa85bb3ae/lib/python2.7/site-packages/coverage/tracer.so
```

As does an official python.org build:
```cmdline
$ mktmpenv -p /usr/local/bin/python2.7
...
$ pip install coverage==5.0a5
...
$ python
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 29 2018, 20:59:26)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import coverage.tracer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(//tmp-d8b03208a2483064/lib/python2.7/site-packages/coverage/tracer.so, 2): 
Symbol not found: _Py_XSETREF
  Referenced from: //tmp-d8b03208a2483064/lib/python2.7/site-packages/coverage/tracer.so
  Expected in: flat namespace
 in /tmp-d8b03208a2483064/lib/python2.7/site-packages/coverage/tracer.so
```

Avoiding the wheel and building manually (`pip install --no-binary coverage coverage==5.0a5`) solves the problem.

**Comment by jamadden** [comment]
The macro `Py_XSETREF` was added to Python 2.7 on [Dec 24, 2015](https://github.com/python/cpython/commit/5951f2300f43d75d344d542e171daed47a0382a6). The next release of Python 2.7, which would have been the first to include that macro, was 2.7.12 on June 25, 2016. 

Extensions on macOS are linked with `-undefined dynamic_lookup`, which causes missing functions not to be a problem at compile time (though there should be a compiler warning)...and produces this error if they can't be found at runtime.

So I suspect the binary wheel was compiled with Python < 2.7.12, and the missing macro resulted in outputting a function call, which can't be resolved.

(cf https://github.com/nedbat/coveragepy/commit/b777c96f885b8d91b5339940a31a6a8ec4bfa3f9 for the commit that started using `Py_XSETREF`.)

**Comment by nedbat** [comment]
@jamadden Thanks for the report.  I'm trying to understand what I did differently between a4 and a5.  I'd like to fix my build process so that it doesn't happen again.  Are you saying I have to be sure to compile with Python >= 2.7.12?

(Oh: you already pointed out the coverage.py change that broke it.  I think I will revert that change.)

**Comment by nedbat** [comment]
Change reverted, fixing this bug, in 0911fe5e
