### ISSUE TITLE
Disabling exit code 5 when no-data-collected is disabled

### ISSUE THREAD

**Issue by fersarr** [coveragepy/coveragepy#812]
Following https://coverage.readthedocs.io/en/coverage-4.4.2/cmd.html#warnings

I found that you can disable the `no-data-collected` warning message by using the following `.coveragerc`

```
[run]
disable_warnings = no-data-collected
```

I was wondering if it would be possible to also stop having the exit code (`$?` in bash) be `5` when `no-data-collected` is disabled. I believe it should just be the `success` exit code of `0` since we asked for it to be ignored.

Currently, even though I disabled the message warning, my exit code is still `5`, as if the command failed.

**Comment by nedbat** [comment]
Can you show me how you are running coverage?  I don't think coverage.py exits with 5 as a status?

**Comment by fersarr** [comment]
Sure:

```
$ /venvpath/bin/python /venvpath/bin/coverage run -p --branch --source=xxx /venvpath/bin/py.test <PYTEST_ARGS> tests/unit/test_sample.py
...
collected 4 items / 4 deselected
...
Coverage.py warning: No data was collected. (no-data-collected)
$ echo $?
5
```

Let me know if you need something else

**Comment by fersarr** [comment]
Oh, I think you are right. I tried the command with only the pytest part and it exited with 5. So it's coming from pytest. Sorry about the confusion!

https://docs.pytest.org/en/latest/usage.html
```

Exit code 5: | No tests were collected
```
