### ISSUE TITLE
Branch coverage failure ``continue`` in nested ``if`` statements

### ISSUE THREAD

**Issue by chrisrossi** [coveragepy/coveragepy#817]
This test case show missing branch coverage despite every branch being covered, AFAICT. The problem seems to be related to the ``continue`` statement and the nested ``if`` statements.

AFAICT, this is *not* a duplicate of #496 but may have a similar root cause.

~~~~
def test_coverage_bug():
    did_something = False
    did_another_thing = False
    did_this_thing_first = False

    for i in range(5):
        if i > 0:
            if i < 5:
                if i % 2 == 0:
                    did_something = True
                else:
                    did_another_thing = True

                continue

        did_this_thing_first = True

    assert did_something
    assert did_another_thing
    assert did_this_thing_first
~~~~

**Comment by nedbat** [comment]
I think this is a duplicate of #198, which unfortunately I can't do anything about.

**Comment by chrisrossi** [comment]
Yes, that appears to be the case. Thanks!
