### ISSUE TITLE
How to merge coverage and unittest work together

### ISSUE THREAD

**Issue by Julius-ZCJ** [coveragepy/coveragepy#819]
**Is your feature request related to a problem? Please describe.**
We want to use unittest to test our code and use coverage to test our code coverage ,but we need to run unittest twice , One time to test code ,and one time run in coverage to test coverage. So ,we consider can unittest and coverage work together to test our code only once. 

**Describe the solution you'd like**
We hope if unittest test error , coverage also stop and push this error in the same time and make piplines failed. But now coverage can't do it . 

**Describe alternatives you've considered**

**Additional context**

If this can do ,how we need to config our code. Please tell us ,thank you!

**Comment by nedbat** [comment]
Does this work for you?
```
$ coverage run -m unittest discover
```

**Comment by Julius-ZCJ** [comment]
> Does this work for you?
> $ coverage run -m unittest discover
Thank you this command can make sense, but not adopt in our code, and we have resolved this problem.
