### ISSUE TITLE
5.0a6 failing with coverage.misc.CoverageException: Couldn't use data file '/root/project/tests/.coverage': wrong schema: 3 instead of 2

### ISSUE THREAD

**Issue by BartoszCki** [coveragepy/coveragepy#826]
**Describe the bug**
The test step in CircleCI fails because of codecov. This started to happen today and affected all tasks that used coverage==5.0a6. The 5.0a5 was fine. Also when I hardcodes coverage's version in .tox as coverage<5 it worked flawlessly. I have tests running under several versions of CPython: 2.7, 3.4, 3.5, 3.6 and 3.7 and it occurred only when using 3.4

**To Reproduce**
run tests with tox with coverage==5.0a6 and Python3.4

**Expected behavior**

> py34-pt44-ptc26 create: /root/project/.tox/py34-pt44-ptc26
> py34-pt44-ptc26 installdeps: codecov, mock, pytest==4.4.1, pytest-cov==2.6.1
> py34-pt44-ptc26 inst: /root/project/.tox/dist/gradient-0.2.2.zip
> py34-pt44-ptc26 installed: DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).,asn1crypto==0.24.0,atomicwrites==1.3.0,attrs==18.2.0,certifi==2019.6.16,cffi==1.12.3,chardet==3.0.4,Click==7.0,click-completion==0.5.1,click-didyoumean==0.0.3,click-help-colors==0.5,codecov==2.0.15,colorama==0.4.1,coverage==5.0a4,cryptography==2.7,cursor==1.2.0,datadog==0.29.3,decorator==4.4.0,future==0.17.1,gradient==0.2.2,gradient-sdk==0.0.3,gradient-statsd==1.0.1,halo==0.0.26,hyperopt==0.1.2,idna==2.8,importlib-metadata==0.18,Jinja2==2.10.1,log-symbols==0.0.13,MarkupSafe==1.1.1,marshmallow==2.19.5,mock==3.0.5,more-itertools==7.1.0,networkx==2.2,numpy==1.16.4,pathlib2==2.3.4,pluggy==0.12.0,progressbar2==3.42.0,prompt-toolkit==2.0.9,py==1.8.0,pycparser==2.19,pymongo==3.8.0,pyOpenSSL==19.0.0,pytest==4.4.1,pytest-cov==2.6.1,python-utils==2.3.0,requests==2.21.0,requests-toolbelt==0.9.1,scandir==1.10.0,scipy==1.2.2,shellingham==1.3.1,six==1.12.0,spinners==0.0.23,termcolor==1.1.0,terminaltables==3.1.0,tqdm==4.32.2,urllib3==1.24.3,wcwidth==0.1.7,zipp==0.5.2
> py34-pt44-ptc26 runtests: PYTHONHASHSEED='1260922597'
> py34-pt44-ptc26 runtests: commands[0] | pytest --cov=gradient --cov-append
> Traceback (most recent call last):
>   File "/root/project/.tox/py34-pt44-ptc26/bin/pytest", line 10, in <module>
>     sys.exit(main())
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/_pytest/config/__init__.py", line 60, in main
>     config = _prepareconfig(args, plugins)
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/_pytest/config/__init__.py", line 201, in _prepareconfig
>     pluginmanager=pluginmanager, args=args
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/pluggy/hooks.py", line 289, in __call__
>     return self._hookexec(self, self.get_hookimpls(), kwargs)
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/pluggy/manager.py", line 87, in _hookexec
>     return self._inner_hookexec(hook, methods, kwargs)
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/pluggy/manager.py", line 81, in <lambda>
>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/pluggy/callers.py", line 203, in _multicall
>     gen.send(outcome)
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
>     config = outcome.get_result()
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/pluggy/callers.py", line 80, in get_result
>     raise ex[1].with_traceback(ex[2])
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/pluggy/callers.py", line 187, in _multicall
>     res = hook_impl.function(*args)
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/_pytest/config/__init__.py", line 679, in pytest_cmdline_parse
>     self.parse(args)
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/_pytest/config/__init__.py", line 896, in parse
>     self._preparse(args, addopts=addopts)
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/_pytest/config/__init__.py", line 851, in _preparse
>     early_config=self, args=args, parser=self._parser
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/pluggy/hooks.py", line 289, in __call__
>     return self._hookexec(self, self.get_hookimpls(), kwargs)
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/pluggy/manager.py", line 87, in _hookexec
>     return self._inner_hookexec(hook, methods, kwargs)
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/pluggy/manager.py", line 81, in <lambda>
>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/pluggy/callers.py", line 208, in _multicall
>     return outcome.get_result()
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/pluggy/callers.py", line 80, in get_result
>     raise ex[1].with_traceback(ex[2])
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/pluggy/callers.py", line 187, in _multicall
>     res = hook_impl.function(*args)
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/pytest_cov/plugin.py", line 99, in pytest_load_initial_conftests
>     plugin = CovPlugin(early_config.known_args_namespace, early_config.pluginmanager)
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/pytest_cov/plugin.py", line 146, in __init__
>     self.start(engine.Central)
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/pytest_cov/plugin.py", line 168, in start
>     self.cov_controller.start()
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/pytest_cov/engine.py", line 157, in start
>     self.cov.load()
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/coverage/control.py", line 336, in load
>     self._data.read()
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/coverage/sqldata.py", line 409, in read
>     with self._connect():       # TODO: doesn't look right
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/coverage/sqldata.py", line 158, in _connect
>     self._open_db()
>   File "/root/project/.tox/py34-pt44-ptc26/lib/python3.4/site-packages/coverage/sqldata.py", line 145, in _open_db
>     self.filename, schema_version, SCHEMA_VERSION
> coverage.misc.CoverageException: Couldn't use data file '/root/project/tests/.coverage': wrong schema: 3 instead of 2
> ERROR: InvocationError for command '/root/project/.tox/py34-pt44-ptc26/bin/pytest --cov=gradient --cov-append' (exited with code 1)

@ me if you need more info

**Comment by BartoszCki** [comment]
BTW if you want to checkout the code or config - the project is open source
[https://github.com/Paperspace/gradient-cli](https://github.com/Paperspace/gradient-cli)

**Comment by vinays75-coder** [comment]
We are facing exactly the same Issue but we are using Python3.6.x so not sure if this is only restricted to Python 3.4.x

**Comment by nedbat** [comment]
@BartoszCki Thanks, I was able to reproduce this (tox is great!).  This is happening because the last version of coverage to support Python 3.4 (according to the package metadata) was 5.0a4.  So your py34 tox has 5.0a4 installed.  That expects a schema=2 database.  I'm not sure where the newer coverage database (schema=3) is coming from.

If you want to support 3.4, and don't need the coverage 5.0 features, I recommend pinning coverage to "<5.0" .

**Comment by nedbat** [comment]
@vinays75-coder Can you give me a way to reproduce your failure?  Are you sure it's the same error ("wrong schema: 3 instead of 2")?

**Comment by vinays75-coder** [comment]
it is very simple......I have this setup in my tox.ini......getting the same error ("wrong schema:3 instead of 2")

[tox]
envlist = py36
install_command = pip install --pre {opts} {packages}
deps=
    pyflakes
    nose
    coverage
    nosexcover
    safety
commands=
    - pyflakes <<my_module_name>>
    nosetests --with-xunit --with-xcoverage --cover-package=<<my_module_name>> --cover-xml

**Comment by nedbat** [comment]
@vinays75-coder Can you link me to your project? Or create a small reproducer that I can run?
