### ISSUE TITLE
"font-size 16px" is way too small

### ISSUE THREAD

**Issue by muellert** [coveragepy/coveragepy#847]
**Describe the bug**
The generated 'style.css' has a font size of 16 pixels instead of 16 points, which is illegible even if you do not have a HDPI monitor.

**To Reproduce**
How can we reproduce the problem?  Please *be specific*.
1. What version of Python are you running?

3.7.3

2. What versions of what packages do you have installed? The output of `pip freeze` is very helpful.

4.5.4

3. What code are you running?  Give us a specific commit of a specific repo that we can check out.

n/a

4. What commands did you run?

I run this software via pytest-cov.
 
**Expected behavior**

I expect to get a coverage report in HTML, which I actually get. Just the styling is wrong.

The incriminating element is this:

     html>body {
    -    font-size: 16px;
    +    font-size: 16pt;
     }

But I can't seem to upload a patch to fix it everywhere.

**Comment by nedbat** [comment]
You are right that the font-size should be defined in pt instead of px.  But unless my setup is very different from yours, 16pt seems too large.  I'm afraid there is no "right" answer to this question: it's going to depend on individual preferences.

You can define an extra_css file that will be included in your HTML report (https://coverage.readthedocs.io/en/v4.5.x/config.html#html) if you like, or you can use your browser controls to increase the size of the font.

**Comment by muellert** [comment]
I am currently (mostly) sitting in front of a 13" 1920x1080 machine, and there, the 16px amount to account for something like 2-4mm of text height (can't really tell, but it is very small). Yes, I can use browser controls, but I have to do that for every file I click on. I am not wedded to the 16pt, but please just make it something-point instead of always-wrong pixels (how about 14pt?). Having the font size in pt would allow the various desktops scale the fonts automatically, at least to some degree (I also have a HDPI laptop, where the font size would be probably like 1mm).

**Comment by nedbat** [comment]
Do you mind attaching a screenshot of what you are seeing? 

By way of reference, GitHub displays source code at the same size as coverage.py HTML reports (final size of 12px).  Does this page also look too small? https://github.com/nedbat/coveragepy/blob/master/coverage/html.py

**Comment by muellert** [comment]
Yes. The other fonts are also too small, esp. for permanent consumption. Effectively, the font size is about 1mm. Somehow, attaching a file does not seem to work, but I don't know why. I have to zoom in at ~180-200% for the text to be easily legible, which I can do by enforcing a minimum font size of 20pt - not something all websites can cope with. :|

**Comment by nedbat** [comment]
@muellert I don't know why your experience is so different than other developers'.  I encourage you to set an extra_css stylesheet.  It will be automatically applied to your coverage.py HTML reports.

**Comment by muellert** [comment]
I've done so already. Thanks for the pointer...
