### ISSUE TITLE
Statements counter and decorated functions

### ISSUE THREAD

**Issue by decaz** [coveragepy/coveragepy#852]
**Describe the bug**
Statements counter does not take into account function definition if it was decorated.

**To Reproduce**
1. CPython 3.7.4
2. `coverage==5.0a8`
3. `sample.py`:
```python
from contextlib import contextmanager

@contextmanager
def f():
    yield
```
4. `coverage html -d . sample.py`

**Expected behavior**
`4 statements` in report.

**Actual behavior**
`3 statements` in report.

**Additional context**
If decoration is commented out then there are still `3 statements` in report because function definition was taken into account.

**Comment by nedbat** [comment]
It does look odd that the decorator line is considered a statement, while the def line is not.  But that is the information that Python provides us with.  And it makes a certain amount of sense: those two lines together are really only one statement.  You can't make just one of those two lines execute, at least not in a way you're likely to encounter in a real-world situation.

I don't think coverage.py can do anything about this with a reasonable amount of effort.

**Comment by decaz** [comment]
@nedbat yes, I thought about inseparability of decoration and function definition. But when there is two or more decorations then statements counter is increasing and that is confusing for me..

**Comment by nedbat** [comment]
Yes, Python marks each decorator line as executable, which is confusing.  I'm not sure why it does that.
