### ISSUE TITLE
Combining Coverage for Same File

### ISSUE THREAD

**Issue by vishalkuo** [coveragepy/coveragepy#853]
**Is your feature request related to a problem? Please describe.**
We have a situation where we're running several tests for the same project in parallel and we have to merge several coverage files. However, some of these coverage files will have overlap as one parallel test runner might run tests in the same file as another. What I want to know is how will coverage deal with these when combining coverage files: will it merge the two as if we ran all the tests in serial or will it only use one of the results?

**Describe the solution you'd like**
Either the ability to merge coverage files as if they were run in serial or documented behaviour 

**Describe alternatives you've considered**
Currently, we're merging XML files with a hacky script but we'd prefer not to

**Comment by nedbat** [comment]
Coverage is fine with merging overlapping data files.  Even if you don't run tests in the same file as another shard, you will run the same product lines as another shard.  This happens all the time.
