### ISSUE TITLE
Popup for ctx in html reports is finicky

### ISSUE THREAD

**Issue by rpkilby** [coveragepy/coveragepy#855]
**Describe the bug**
For HTML reports, the popup for the new "Who Tests What" `ctx` element can be a bit finicky. If you attempt to mouse over the popup box (e.g., to copy the list of test names), the popup will close, as you are no longer hovering over the `ctx` element. If you move the mouse quickly, you may be able to hover over the popup before it disappears, but this is unreliable and annoying.

**Video** 
https://i.imgur.com/Zsgb3AA.mp4
The report was built using coverage v5.0a8

**Expected behavior**
I should be able to reliably mouse over the ctx popup so I can copy the list of test functions. 
One possible solution: clicking the `ctx` element could pin/unpin its popup. Clicking another `ctx` would close all other popups.

**Comment by nedbat** [comment]
You are right, it's not good the way it is now.  I'll try to improve it.

**Comment by rpkilby** [comment]
Thanks, and I'm really looking forward to the 5.0 release. The context feature is great.

**Comment by nedbat** [comment]
I did a big refactor of how the HTML report markup is structured, as of a58a8abd.  Give it a try.

**Comment by rpkilby** [comment]
The context expansion works great. Not sure if it's related to the changes, but there's a rendering issue with partially covered lines. 

<img width="808" alt="Screen Shot 2019-10-13 at 8 06 34 PM" src="https://user-images.githubusercontent.com/2370209/66727604-2ed51e00-edf5-11e9-847f-03ba37e365ec.png">

**Comment by nedbat** [comment]
Oops, forgot to check the two together.  Fixed in 168f1e75.  Thanks for the quick feedback! :)

**Comment by rpkilby** [comment]
Of course. Thanks again.

**Comment by nedbat** [comment]
This finished version of this is available in 5.0b1: https://pypi.org/project/coverage/5.0b1/
