### ISSUE TITLE
[BUG] When I used  coverage report -m got Error

### ISSUE THREAD

**Issue by nikul-serpentcs** [coveragepy/coveragepy#859]
When I run My program with `coverage run`  in python,
whenever I run `coverage report -m` or `coverage html`
 I got Error like this **Couldn't read data from '*/.coverage': ValueError: Expecting object: line 1 column 4033 (char 4032)**

**Comment by nedbat** [comment]
@nikul-serpentcs It sounds like you are running two different versions of coverage.py, one for measurement and another for reporting.  You haven't given any specifics about what versions of anything you have, or how you are running them.

What does `which coverage` report?  What command line are you using to run coverage in the first place?

**Comment by nikul-serpentcs** [comment]
@nedbat Thank you for a quick response

> What does which coverage report? What command line are you using to run coverage in the first place?

I run coverage in  `Ubuntu 18.04.3 LTS Terminal`  for python file with using `coverage run filename`

When all run is completed after I run ` coverage report -m ` for Codecov but that time got an error like this: **Couldn't read data from '*/.coverage': ValueError: Expecting object: line 1 column 4033 (char 4032)**

Then I try to `coverage html` for a report but it's Filed and Got same Error like this.

**Comment by Dangar-Serpentcs** [comment]
Same issue with 16.04 LTS even I get noting on my terminal.
![Selection_027](https://user-images.githubusercontent.com/38550879/67178609-03ec5a80-f3f1-11e9-9888-081ab0cd3ab1.png)

**Comment by Dangar-Serpentcs** [comment]
Can anyone lookout here, It's very argent to check our code into coverage.
Thanks in advance.

**Comment by nedbat** [comment]
If you could answer the questions in the bug template, that would be really helpful:

> 
> **To Reproduce**
> How can we reproduce the problem?  Please *be specific*.
> 1. What version of Python are you running?
> 2. What versions of what packages do you have installed? The output of `pip freeze` is very helpful.
> 3. What code are you running?  Give us a specific commit of a specific repo that we can check out.
> 4. What commands did you run?

@Dangar-Serpentcs You say you have the same problem, but you have a completely different error message. I'm guessing based on your user names that you two work together?  Try to help put together all the information I need so I can help you.

**Comment by Dangar-Serpentcs** [comment]
Thanks for your response @nedbat 
I'm using **Ubuntu 16.04 LTS**
Using this cmd **sudo pip install coverage** I just installed the coverage, Here I used the only **pip** so coverage package install for **python2.7** right!

Now I'm going to fire the coverage cmd:- **coverage run a.py**
After that I used the cmd:- **coverage report -m** & **coverage html** & **coverage html a.py**
It's just create one **a.html** file whenever I opened that file I get **0%** coverage and from command prompt I get **No data to Report**.
So Here I'm not able to check the how much code covered or not. Even re-install of coverage package I face same issue.
![Selection_027](https://user-images.githubusercontent.com/38550879/67201617-45e2c400-f424-11e9-8b4e-a9e466553df8.png)

**Comment by nedbat** [comment]
I would like to help, but I don't know how.  You have each reported different problems.  I don't have enough details to reproduce either issue.

**Comment by nedbat** [comment]
Feel free to re-open if you have a way to reproduce the problem.

**Comment by nikul-serpentcs** [comment]
@nedbat Some time we got error some time not.
That's why we did not have proper steps to how to reproduce the problem.
