### ISSUE TITLE
Expose numbits_to_nums() as a SQL function

### ISSUE THREAD

**Issue by simonw** [coveragepy/coveragepy#868]
The `register_sqlite_functions()` function currently adds four custom SQL functions:

https://github.com/nedbat/coveragepy/blob/694435b844760ca0443cf87bf73a537f06c37d7d/coverage/numbits.py#L153-L156

I'd appreciate it if it also exposed a version of the `numbits_to_nums()` function that returns a JSON array of line numbers. SQLite has built-in JSON functions that could take advantage of this, but more importantly it would make it easier to run queries that show a human-readable version of what's going on.

**Comment by simonw** [comment]
I'm planning a Datasette plugin which exposes these SQL functions (via [this hook](https://datasette.readthedocs.io/en/stable/plugins.html#prepare-connection-conn)), so I can use Datasette to muck around with my `.coverage` files.

This feature is by no means a blocker on what I'm planning to do - I can always register the exact same function in my own plugin - but I thought it would also make sense as a feature of the `register_sqlite_functions(connection):` function here.

**Comment by nedbat** [comment]
Fixed in #868
