### ISSUE TITLE
4.5.4: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [coveragepy/coveragepy#874]
<pre>+ cd coveragepy-coverage-4.5.4
+ /usr/bin/python3 setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing coverage.egg-info/PKG-INFO
writing dependency_links to coverage.egg-info/dependency_links.txt
writing entry points to coverage.egg-info/entry_points.txt
writing top-level names to coverage.egg-info/top_level.txt
reading manifest file &apos;coverage.egg-info/SOURCES.txt&apos;
reading manifest template &apos;MANIFEST.in&apos;
warning: no previously-included files found matching &apos;ci/appveyor.token&apos;
no previously-included directories found matching &apos;doc/_build&apos;
no previously-included directories found matching &apos;tests/eggsrc/build&apos;
no previously-included directories found matching &apos;tests/eggsrc/dist&apos;
no previously-included directories found matching &apos;tests/eggsrc/*.egg-info&apos;
warning: no previously-included files matching &apos;*.py[co]&apos; found anywhere in distribution
writing manifest file &apos;coverage.egg-info/SOURCES.txt&apos;
running build_ext
building &apos;coverage.tracer&apos; extension
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.8 -c coverage/ctracer/datastack.c -o build/temp.linux-x86_64-3.8/coverage/ctracer/datastack.o
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.8 -c coverage/ctracer/filedisp.c -o build/temp.linux-x86_64-3.8/coverage/ctracer/filedisp.o
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.8 -c coverage/ctracer/module.c -o build/temp.linux-x86_64-3.8/coverage/ctracer/module.o
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.8 -c coverage/ctracer/tracer.c -o build/temp.linux-x86_64-3.8/coverage/ctracer/tracer.o
gcc -pthread -shared -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -g -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -g build/temp.linux-x86_64-3.8/coverage/ctracer/datastack.o build/temp.linux-x86_64-3.8/coverage/ctracer/filedisp.o build/temp.linux-x86_64-3.8/coverage/ctracer/module.o build/temp.linux-x86_64-3.8/coverage/ctracer/tracer.o -L/usr/lib64 -o /home/tkloczko/rpmbuild/BUILD/coveragepy-coverage-4.5.4/coverage/tracer.cpython-38-x86_64-linux-gnu.so
Unknown command: &apos;test&apos;
Use &apos;setup.py help&apos; for help.
error: Bad exit status from /var/tmp/rpm-tmp.pdmujv (%check)
</pre>

Could you please consider change tagging convension from coveragepy-<version> ro just version because autogenerated gitlab tar ball comes with coveragepy-coverage-<version> base directory.
You can see that in  http://pypi.python.org/packages/source/c/coverage/coverage-4.5.4.tar.gz

**Comment by nedbat** [comment]
1) This repo doesn't support the "setup.py test" command. As you can see from the warning, the command will be removed completely in the future anyway.
2) I don't understand what you are showing me with the pypi.python.org link. That's a tarball that I built and uploaded. It doesn't contain a "coveragepy-coverage- base directory".

**Comment by kloczek** [comment]
Sorry wrong link. Please check content of the https://github.com/nedbat/coveragepy/archive/coverage-5.0b1.tar.gz

So how to execute in case of this project test suite?

Strange that you are going to removing support for something which supported by most of the python projects.

**Comment by nedbat** [comment]
Coverage.py has never supported "setup.py test". That message is not mine, it is from setuptools itself: https://github.com/pypa/setuptools/blob/master/setuptools/command/test.py#L217-L223

The Contributing section of the docs explains how to run the test suite: https://coverage.readthedocs.io/en/latest/contributing.html

I see what you mean about the GitHub archive.  I will consider changing the tagging scheme.

**Comment by kloczek** [comment]
OK .. so what exactly needs to be executed to start test suite of your project?

**Comment by nedbat** [comment]
There's a page in the docs specifically about how to set up a development environment and run the tests. I linked to it in my answer above. I'm not sure what else I could add to it.

**Comment by nedbat** [comment]
If something is unclear on that page, please let me know. I want it to be useful for everyone.

**Comment by kloczek** [comment]
Is it really so hard just write command which needs to be executed?

**Comment by nedbat** [comment]
@kloczek this is unbelievable. I have written the commands, in the docs. And given you a link to them. Is it really so hard to read the page?

**Comment by kloczek** [comment]
It is indeed unbelievable because only link which you've provided was ling https://github.com/pypa/setuptools/blob/master/setuptools/command/test.py#L217-L223 whoch poits to the code printing warning.
So again: Is it really so hard just write command which needs to be executed? :)

**Comment by habnabit** [comment]
I copy-pasted the command to run for you from https://coverage.readthedocs.io/en/latest/contributing.html: 

```
tox
```

**Comment by nedbat** [comment]
@kloczek I gave you two links. The second was:
> The Contributing section of the docs explains how to run the test suite: https://coverage.readthedocs.io/en/latest/contributing.html

You seem to be in a big hurry, too much of a hurry to read the comments I've put here.  This won't serve you well.  I don't know why you are running test suites of many packages, but you seem to be  writing a number of issues like this one where you don't bother to read the instructions about how to run the test suite:
- https://github.com/lsh123/xmlsec/issues/278#issuecomment-551149246
- https://github.com/HypothesisWorks/hypothesis/issues/2203
- https://github.com/sysstat/sysstat/issues/235
- https://github.com/google/re2/issues/218

Whatever you are trying to accomplish, you need to take a different approach.
