### ISSUE TITLE
coverage report wrong.

### ISSUE THREAD

**Issue by little-hang** [coveragepy/coveragepy#875]
when i input: coverage report -m
it tells me :
![image](https://user-images.githubusercontent.com/24517540/69786427-60634680-11f5-11ea-8279-4a8a41348a89.png)

 the web server is started by using flask+uswgi. And I start it in docker .

generate coverage file by using coverage api

**Comment by nedbat** [comment]
You'll need to give me a way to reproduce the problem.  You haven't provided any of the information asked for.  What version of coverage.py are you using?  Can you attach the .coverage file that wasn't readable?

**Comment by little-hang** [comment]
the coverage's veraion is v4.5.4。And I can open this .coverage file by vim。

**Comment by zhanghang06** [comment]
the coverage's veraion is v4.5.4。And I can open this .coverage file by vim。

**Comment by little-hang** [comment]
> You'll need to give me a way to reproduce the problem. You haven't provided any of the information asked for. What version of coverage.py are you using? Can you attach the .coverage file that wasn't readable?

the coverage's version is v4.5.4。And I can open this .coverage file by vim。

**Comment by nedbat** [comment]
It seems like your .coverage file has been truncated somehow. I can't know more without seeing the file and/or the code that generated the file.

**Comment by nedbat** [comment]
Feel free to re-open if you have a way to reproduce the problem.
