### ISSUE TITLE
Improve doc/subprocess.rst for multiprocessing module limitation

### ISSUE THREAD

**Issue by gzcf** [coveragepy/coveragepy#879]
**Is your feature request related to a problem? Please describe.**
I am developing a program which leverage `multiprocessing` module to do parallel tasks. After read `doc/subprocess.rst` and try, I figured out that documented solution doesn't work for  `multiprocessing.Process`.Fisrt, both `sitecustomize.py` and `.pth` file doesn't work in subprocesses created by `multiprocessing.Process`. It's because when use `multiprocessing.Process`, subprocesses won't import `site` module again, there is not chance to do `sitecustomize.py` or `.pth` file customization. Second, when these subprocesses exit, `atexit` functions get never called, `coverage` has no chance to write collected data.

**Describe the solution you'd like**
Maybe we could improve document and point out this limitation.

**Describe alternatives you've considered**
I came up with a workaround.

test.py
```
def func():
    try:
        import coverage
        coverage.process_startup()
    except:
        traceback.print_exc()
    # Emulate time-consuming work
    time.sleep(5)
    atexit._run_exitfuncs()

p = Process(target=func)
p.start()
p.join()
```

```
COVERAGE_PROCESS_START=.coveragerc coverage run test.py
```
This seems work. Apparently, there are many cons. 1. there may exists side-effects when other libraries depends on this atexit feature. 2. We call atexit protected method. 3. At most times, we can not (or want to avoid to) add such code into normal code.

**Additional context**
None

**Comment by nedbat** [comment]
Can you provide me with a way to reproduce the original failure?  A program that uses multiprocessing and isn't properly measured by coverage?

**Comment by gzcf** [comment]
Reproducible steps

1. Create a empty directory, then create those files in it

test.py
```
# -*- coding: utf-8 -*-
from multiprocessing import Process

def func():
    print("called func")

p = Process(target=func)
p.start()
p.join()
```

.coveragerc
```
[run]
branch = True
source = .
parallel = True
```

2. Run test.py through coverage

```
COVERAGE_PROCESS_START=.coveragerc coverage run test.py
```

This will create only one data file. (`.coverage.localhost.64619.127336` in my machine). However, we expected two data files because we started a subprocess.

3. Show coverage details

```
coverage combine && coverage html
```

Navigate to `test.py` detail page, we can see that the line calling print function is not covered.

And adding `sitecustomize.py` or *.pth file before step 2 doesn't affect this result.

**Comment by nedbat** [comment]
Have you tried using the ``--concurrency=multiprocessing`` switch? You shouldn't need the COVERAGE_PROCESS_START variable at all.

**Comment by gzcf** [comment]
Yes, `--concurrency=multiprocessing` switch works. Emm..., it's embarrassing. I overlooked this switch through my hours of attempt.

**Comment by nedbat** [comment]
I should add more mention of it to the docs.

**Comment by nedbat** [comment]
Done: 5379317ad73694099b7876797695bc76bd9cdce5
