### ISSUE TITLE
Documentation: 4.5.x links are now broken

### ISSUE THREAD

**Issue by mtlynch** [coveragepy/coveragepy#885]
Congrats on the 5.0 release!

Per the discussion on #737, I changed links in [my tutorial](https://mtlynch.io/resurrecting-3/#adding-code-coverage) to coveragepy's documentation using the recommended `4.5.x` format, like:

* https://coverage.readthedocs.io/en/v4.5.x/config.html

My understanding was that the 4.5.x format would be supported for permalinks, but they recently broke. Would it be possible to get the 4.5.x links live again? Otherwise, anyone who linked to any of the 4.5.x documentation now has broken links.

**Comment by nedbat** [comment]
Sorry about that, I've put them back for now.  I'd like a way to have docs available by URL, but not listed in the version picker.
Or, a better permalink that I should recommend for people?
