### ISSUE TITLE
Latest tag (5.0) creates corrupted .coverage file

### ISSUE THREAD

**Issue by jaredvasquez** [coveragepy/coveragepy#892]
**Describe the bug**
The latest tag of `coveragepy` creates a corrupted `.coverage` file. The resulting file is corrupted with lots of non-UTF characters and what looks like artifacts from sqlite3.

**To Reproduce**
I created a really minimal repo to demonstrate this bug. 
https://github.com/jaredvasquez/coverage-bug-example

Simply clone the repo and run the `make` command (with Docker running locally). It will build the image, run coverage and output the resulting `.coverage` file to you. By default in `requirements_dev.txt` it is using `coverage==5.0` which will reproduce the issue. You can replace this with an older version (e.g. `4.5.4`) and see the expected output.

1. What version of Python are you using? 
Python 3.6.9
1. What version of coverage.py are you using? The output of `coverage debug sys` is helpful.
5.0
1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.
See the linked repo.
1. What code are you running?  Give us a specific commit of a specific repo that we can check out.
Just a minimal example provided in linked repo.
1. What commands did you run?
See minimal repo

**Expected behavior**
A non-corrupted `.coverage` file with UTF-8 characters.

**Additional context**
Running this on top of a Docker image with Debian + Python. However I tried this with a few different images and don't think this issue is specific to the Debian OS.

**Comment by jaredvasquez** [comment]
Quick Update: Looks like I was using an older version of `coveragepy` locally. I'm also able to recreate this issue locally now on Mac OSX + Python 3.6.8

**Comment by gpotter2** [comment]
Yup, it's now stored as SQL. That's not backward compatible with older coveragepy versions.

From https://coverage.readthedocs.io/en/coverage-5.0/whatsnew5x.html

> Coverage’s data storage has changed. In version 4.x, .coverage files were basically JSON. Now, they are SQLite databases. The database schema is documented (Coverage.py database schema), but might still be in flux.

You're just using two incompatible coveragepy versions on the same file. If you use 5.0 to create the file, you can only use 5.0+ to read it

**Comment by nedbat** [comment]
@jaredvasquez Can you say more about why you think the .coverage file is corrupted? Using v5.0, it should be a SQLite database.

**Comment by jaredvasquez** [comment]
Sorry, didn't realize that this change was intentional with `coverage >= 5.0`. I use the `coveralls` tool to track code coverage and it anticipates a traditional `.coverage` file which was causing issues.

I'll go ahead and close the issue.
https://media.giphy.com/media/jUwpNzg9IcyrK/giphy.gif
