### ISSUE TITLE
coverage 5.0 fails with projects that use bokeh

### ISSUE THREAD

**Issue by jdlesage** [coveragepy/coveragepy#898]
**Describe the bug**
With the 5.0 version, there is a new error at coverage report generation in our project that uses bokeh: `Aborting report output, consider using -i.
fakesource   NoSource: No source for code: '<some_path>/fakesource'.`

Looking to .pyc of our project, it has been raised because of this line in bokeh project: https://github.com/bokeh/bokeh/blob/master/bokeh/plotting/helpers.py#L880

**To Reproduce**
How can we reproduce the problem?  Please *be specific*.
1. What version of Python are you using? Python3.6
1. What version of coverage.py are you using? The output of `coverage debug sys` is helpful.
```

-- sys -------------------------------------------------------
                   version: 5.0
                  coverage: /home/jd.lesage/venv/edatools/lib/python3.6/site-packages/coverage/__init__.py
                    tracer: -none-
                   CTracer: available
      plugins.file_tracers: -none-
       plugins.configurers: -none-
 plugins.context_switchers: -none-
         configs_attempted: .coveragerc
                            setup.cfg
                            tox.ini
                            pyproject.toml
              configs_read: tox.ini
               config_file: None
           config_contents: -none-
                 data_file: -none-
                    python: 3.6.9 (default, Dec  6 2019, 17:04:45) [GCC 9.2.1 20191109]
                  platform: Linux-5.2.0-3-amd64-x86_64-with-debian-bullseye-sid
            implementation: CPython
                executable: /home/jd.lesage/venv/edatools/bin/python3.6
              def_encoding: utf-8
               fs_encoding: iso8859-15
                       pid: 1523184
                       cwd: /home/jd.lesage/workspace_python/tools
                      path: /home/jd.lesage/venv/edatools/bin
                            /home/jd.lesage/usr/lib/python36.zip
                            /home/jd.lesage/usr/lib/python3.6
                            /home/jd.lesage/usr/lib/python3.6/lib-dynload
                            /home/jd.lesage/venv/edatools/lib/python3.6/site-packages
                            /home/jd.lesage/workspace_python/tools
               environment: -none-
              command_line: /home/jd.lesage/venv/edatools/bin/coverage debug sys
           sqlite3_version: 2.6.0
    sqlite3_sqlite_version: 3.30.1
```
1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.
bokeh==1.4.0
1. What code are you running?  Give us a specific commit of a specific repo that we can check out.
Private repository. But running tests with notebooks that do some bokeh plots.
1. What commands did you run?
```
    coverage erase
    coverage run -m pytest --junitxml=junit-{envname}.xml --ignore={toxworkdir} --ignore=venv --ignore=.venv
    coverage report --omit={toxworkdir}/*,venv/*,.venv/*
```

**Expected behavior**
I ignored (add it to the --omit option) fakesource to workaround the problem. I am wondering if the error is expected. We have this error with 5.0 (it was ok with previous versions of coverage). Could it be a regression ? Should I create a bug report on bokeh side ? What would be the change on their side ?

**Comment by nedbat** [comment]
I'm not sure why this is changed from 4.x, but a simple way to avoid the problem is to make the "fakesource" name more fake:  "\<fakesource>".  Coverage doesn't record filenames containing angle brackets, understanding that they will not be reportable later.
