### ISSUE TITLE
Contexts in reports are missing with relative_files=True

### ISSUE THREAD

**Issue by lazka** [coveragepy/coveragepy#899]
**Describe the bug**

When I enable relative_files the json and html reports no longer contain context information. I still see context info in the sqlite DB though.

**To Reproduce**

* coverage.py 5.0, py3.7.5
* Set `relative_files=True` 
* `python3 -m pytest --cov --cov-context=test tests/test_foo.py`
* `python3 -m coverage html --show-contexts`
* HTML report doesn't include any context infos

**Expected behavior**

HTML report contains context infos

**Comment by nedbat** [comment]
I'll mark this a dup of #900.

**Comment by nedbat** [comment]
This is now available in coverage==5.0.1
