### ISSUE TITLE
Lambda expression confuses branch measurement

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#90]
A line like this:
```
    fn = make_sortable or (lambda x: x) 
```
is marked as being a branch with a missing jump to "exit", maybe only if the lambda isn't used.

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/90

**Comment by nedbat** [comment]
*Original comment by* **Carl Meyer (Bitbucket: [carljm](https://bitbucket.org/carljm), GitHub: [carljm](https://github.com/carljm))**

----------------------------------------

I can verify that, at least in my case, the missing jump to exit disappeared when I ensured the lambda was used during the test run. Seems to me this could be considered useful coverage information, not a bug -- if anything, the branch-coverage report should special-case this to display a more informative label on the line?

**Comment by nedbat** [comment]
A particularly confusing form of this bug:

```
OPERATIONS = [
    operator.add,
    operator.sub,
    lambda x: 2*x,
    operator.mul,
]
```

The "OPERATIONS = " line will have a missed branch to "exit" if the lambda expression is never executed.

**Comment by nedbat** [comment]
Bug #460 is related to this.

**Comment by nedbat** [comment]
Perhaps the best we can do here is to report it as "Missed lambda" instead of "missed branch to exit."

**Comment by nedbat** [comment]
It's not as good as I would like, but as of now, the HTML shows "3 ↛ exit", and the hover text reads "line 6 didn't finish the lambda on line 6".

I think this provides enough information to the reader.  Getting more precise would require collecting data differently, to distinguish the line 6 execution during building the list, from line 6 execution during running the lambda.  We can distinguish them based on the co_firstlineno of the frame, but we don't have a way to record that data as we go.

**Comment by nedbat** [comment]
*Original comment by* **Daniel Hahler (Bitbucket: [blueyed](https://bitbucket.org/blueyed), GitHub: [blueyed](https://github.com/blueyed))**

----------------------------------------

Could this be reflected in the xml report, too?

**Comment by sigma67** [comment]
Has this been fixed? I'm still seeing issues.

```python
conversion_lookup: Dict[Type[Union[int, bool, float, str, Path]], Callable[[Any], str]] = {
        int: str,
        bool: str,
        float: str,
        str: str,
        Path: lambda x: str(x.as_posix()),
    }
```
coverage 7.2.7

**Comment by nedbat** [comment]
@sigma67 since this ticket is so old, it would be better to open a new issue with complete details of what the problem is and how to reproduce it.

**Comment by sigma67** [comment]
The issue was actually on my end, the lambda function in question was in fact not covered. Sorry for bothering you about it.
