### ISSUE TITLE
context labelled differently 

### ISSUE THREAD

**Issue by davidszotten** [coveragepy/coveragepy#901]
`pytest --cov=test_foo --cov-context=test; coverage report --contexts=test_foo`

environ identical to #900 

setting `dynamic_context = test_function` in `.coveragerc`, i get context reported as
`test_foo.test_foo`

but without that setting, the context is reported as 
`test_foo.py::test_foo|run`

**Comment by nedbat** [comment]
There's no single definition of what the context labels should be.  The built-in "test_function" uses one style, and the pytest plugin uses another more elaborate style.

I hadn't thought much about the situation where two different mechanisms are trying to set contexts. Maybe there could be some error handling or warnings in that case?

**Comment by davidszotten** [comment]
a warning sounds reasonable to me. happy to have a first pass at a pr (warning if setting a context means overriding on already set). does coverage already have a warnings system you could point me to?

**Comment by nedbat** [comment]
There is a warnings facility, for example: https://github.com/nedbat/coveragepy/blob/cecc5ddc2d1a95223ad708a3dcc27f7a7f4d54b9/coverage/control.py#L701-L702

But off the top of my head, I'm not sure how this will work.  pytest-cov sets a context by calling `Coverage.switch_context`, which I guess could warn if the coverage config already had a setting? We have to be careful of unintended interactions.

**Comment by davidszotten** [comment]
ah, i thought the api might have been enter/exit context

perhaps this is more of a documentation issue, e.g. recommending test runnings/plugins over `dynamic_context = test_function`

maybe most of my confusion is from following the alphas, and picking up the `dynamic_context` setting before there was support in `pytest-cov`

**Comment by davidszotten** [comment]
@nedbat having re-read the docs i'm happy to close this unless you think any action is needed

**Comment by nedbat** [comment]
I added a warning for this case in 16ef35f9.

**Comment by nedbat** [comment]
This is now available in [coverage 5.0.2](https://pypi.org/project/coverage/5.0.2/)
