### ISSUE TITLE
Ignore directories during "coverage combine" command

### ISSUE THREAD

**Issue by rsudarson** [coveragepy/coveragepy#923]
I've looked at the coverage combine help. I didn't see any options to ignore specific coverage data directories before combine the coverage data file.

Is there any option available to pass it to coverage combine ?

**Comment by nedbat** [comment]
@rsudarson can you tell me more about your use case?  You can omit directories from measurement (so the data isn't in the parallel data files to begin with), or from reporting (so they aren't reported from the combined files).  Would either of those work?
