### ISSUE TITLE
sqlite3.OperationalError: database schema has changed

### ISSUE THREAD

**Issue by Lucas-C** [coveragepy/coveragepy#924]
**Describe the bug**
While using `pytest` & `pytest-cov`, I get the following exception:
```
sqlite3.OperationalError: database schema has changed
```

**To Reproduce**
How can we reproduce the problem?  Please *be specific*.
1. What version of Python are you using?
`Python 3.6.7`
1. What version of coverage.py are you using?
`coverage-5.0.3-cp36-cp36m-manylinux1_x86_64.whl`
1. What versions of what packages do you have installed?
`Pygments-2.5.2 aspy.yaml-1.3.0 bleach-3.1.0 cfgv-2.0.1 coverage-5.0.3 docutils-0.16 identify-1.4.10 importlib-metadata-1.4.0 importlib-resources-1.0.2 nodeenv-1.3.4 packaging-20.0 pluggy-0.13.1 pre-commit-1.21.0 pre-commit-hooks-markup-1.0.0 pyparsing-2.4.6 pytest-5.3.4 pytest-cov-2.8.1 pyyaml-5.3 readme-renderer-24.0 toml-0.10.0 wcwidth-0.1.8 webencodings-0.5.1 zipp-2.0.0`
1. What code are you running?
I am executing the tests from repo https://github.com/Lucas-C/pre-commit-hooks-markup in Travis CI, through [pre-commit](https://pre-commit.com)
1. What commands did you run?
```
pip install -U . -r dev-requirements.txt
pre-commit run --all-files
```

**Expected behavior**
No error raised.

**Additional context**
Here is the full Travis CI execution log where I witnessed this, through a `pytest` execution:
https://travis-ci.org/Lucas-C/pre-commit-hooks-markup/builds/639831451

Given :
- the multiple layers of execution (`pre-commit` invoking `pytest` using `pytest-cov` invoking `coverage`), meaning the bug may not originate from `coverage.py`
- the fact that the bug only show up in Travis CI and not on my own machine

...I do not expect an immediate solution by posting my issue here, ony a few pointers maybe.
Also, given the error message, I though it would be best to report the issue in this project bug tracker.

I'm going to perform some more tests in Travis CI, but I have a simple question : could this be due to an old `coverage.py` DB remaining in Travis workspace from old test executions ?

**Comment by Lucas-C** [comment]
Apparently the issue only occur through `pre-commit`, not directly when using `pytest`:
https://travis-ci.org/Lucas-C/pre-commit-hooks-markup/builds/640352678

**Comment by Lucas-C** [comment]
This was resolved by adding a newline in `tests/__init__.py`:
- https://github.com/Lucas-C/pre-commit-hooks-markup/commit/516eaeb6380fa82b27f8255dc63cd0a68274ead7
- https://travis-ci.org/Lucas-C/pre-commit-hooks-markup/builds/640390785

**Comment by nedbat** [comment]
I don't understand what happened here. How can a missing newline in a source file cause coverage to fail internally?  Seems like something should be fixed.
