### ISSUE TITLE
Trouble understanding --source option

### ISSUE THREAD

**Issue by pbaughman** [coveragepy/coveragepy#930]
**Describe the bug**
Running `coverage run --source` does not seem to find all of the source files I would expect it to

**To Reproduce**
How can we reproduce the problem?  Please *be specific*.
1. What version of Python are you using?
  - Python 2.7.17
1. What version of coverage.py are you using? The output of `coverage debug sys` is helpful.
    ```
    coverage debug sys                                                                                                              [48/1886]
    -- sys -------------------------------------------------------                                                                                                       
                        version: 5.0.3                                                                                                                               
                       coverage: /usr/local/lib/python2.7/dist-packages/coverage/__init__.pyc                                                                        
                         tracer: -none-                                                                                                                              
                        CTracer: available                                                                                                                           
           plugins.file_tracers: -none-                                                                                                                              
            plugins.configurers: -none-                                                                                                                              
      plugins.context_switchers: -none-                                                                                                                              
              configs_attempted: .coveragerc                                 
                                 setup.cfg              
                                 tox.ini                                 
                                 pyproject.toml           
                   configs_read: -none-                    
                    config_file: None
                config_contents: -none-
                      data_file: -none-
                         python: 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
                       platform: Linux-5.3.0-26-generic-x86_64-with-Ubuntu-18.04-bionic
                 implementation: CPython

    ```
1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.
1. What code are you running?  Give us a specific commit of a specific repo that we can check out.
1. What commands did you run?

**Expected behavior**
I have a number of python packages in a directory like
```
+ pete_repo
    + python_project_1
        + setup.py
        + src
            + python_project_1
                + __init__.py
                + a.py
                + b.py
                + c.py
    + python_project_2
        + setup.py
        + src
            + python_project_2
                + __init__.py
                + d.py
                + e.py
```

Based on the documentation [here](https://coverage.readthedocs.io/en/coverage-5.0.3/source.html#source) I would expect to be able to do something like

```
coverage run --source=pete_repo empty_file.py
coverage report
```

And see 0% coverage for both `__init__.py` files, as well as a.py through e.py

What actually happens is I get an empty coverage report with no files at all.

Interestingly, if I get a bit more specific with the path, I can start to get results that approach what I expect.  For example:

```
coverage run --source=pete_repo/python_project_1/src empty_file.py
coverage report
Name                                                                 Stmts   Miss  Cover
----------------------------------------------------------------------------------------
python_project_1/src/python_project_1/__init__.py                      0      0   100%
python_project_1/src/python_project_1/a.py                             43     43    0%
python_project_1/src/python_project_1/b.py                             18     18    0%
python_project_1/src/python_project_1/c.py                             134    134   0%
----------------------------------------------------------------------------------------
. . .
```

However, if I go up one directory, things stop working again.  It finds the setup.py file, but
not any of the actual python files containing code
```
coverage run --source=pete_repo/python_project_1 empty_file.py
coverage report
Name                                                                 Stmts   Miss  Cover
----------------------------------------------------------------------------------------
python_project_1/setup.py                      0      0   100%
----------------------------------------------------------------------------------------
```

**Additional context**
I can probably work around this issue by finding all the __init__.py files and running 'coverage' for each directory that contains one, but I'd also like to understand why my expectations are off from reading the documentation.

Am I doing something to mess this up?

Thanks so much!

**Comment by nedbat** [comment]
The `--source` option tries to find importable Python files.  It guesses at what is importable, and a big factor is whether they are in a directory with an `__init__.py` file.  All of the behavior you've noted can be explained by that rule.  When exploring the tree, coverage will only look in directories that have `__init__.py` files.

**Comment by pbaughman** [comment]
@nedbat I guess I'm having trouble reconciling 

>When exploring the tree, coverage will only look in directories that have `__init__.py` files.

With

```
coverage run --source=pete_repo empty_file.py
```

. . .finding zero python files.

There are plenty of directories that have `__init__.py` files.   In the original example, specifically `./python_project_1/src/python_project_1/`and `./python_project_2/src/python_project_2/` both have `__init__.py` files in them.  Does it not recurse down?  If there's no recursion, what does "exploring the tree" mean in this context?

**Comment by nedbat** [comment]
@pbaughman it won't go into directories that don't have `__init__.py` files, because it believes that the files won't be importable from those directories.  Your repo is unusual in having two projects in two subdirectories, and also in having "src/python_project_1" in the project. Usually people have "python_project_1", or "src".

You should use `--source=src/python_project_1,src/python_project_2`.  But I'm not sure you want to run one coverage command to deal with both projects anyway.

**Comment by pbaughman** [comment]
@nedbat Ok thanks!  The work-around I'm using is

```
find pete_repo -name '__init__.py' -execdir coverage run -a --source=. "${PWD}/dummy.py" \;
```

So I let `find` locate all of my `__init__.py` files and then run 'coverage' in each directory where I find one.

It would be nice if I didn't have to run dummy.py (an empty file) but that's a minor nitpick.

**Comment by nedbat** [comment]
@pbaughman If your project grows more subdirectories, this is going to find too many.  I'm not sure why your command isn't to simply run coverage in the two directories you know you have?

**Comment by pbaughman** [comment]
@nedbat 

> I'm not sure why your command isn't to simply run coverage in the two directories you know you have?

I want it to find *all* the subdirectories with python files and those subdirectories might change.  The repo is a ROS project, and each top-level subdirectory is a ROS package.  Some are C++, and some are Python.  Sometimes new packages are created and I need to robustly compute code coverage for all python code in the repository, even if someone adds a new python project and forgets to update the 'coverage' command.

For C++ this is very easy - you build all the projects with the right compiler options and run `lcov -i` on the artifacts.  Then you start with a 0% coverage file for every c++ file that ran through the compiler and you're sure you're not missing anything.  Then you combine that 0% data with the data from running the tests and you get an accurate picture of c++ code coverage

For python, it's a bit harder.  If someone added a new python project with no tests at all, those python files could fly under the radar and not show up in the report.  That's why I'm using 'find' to locate all the `__init__.py` files, and then using the `coverage run` to generate an empty coverage report for those files

**Comment by pbaughman** [comment]
For a real world example of a repository that's set up that way, [here's a ROS2 repository](https://github.com/ros2/launch) with 4 different python packages in it (launch, launch_testing, launch_xml, and launch_yml).
