### ISSUE TITLE
Coverage decreases while no code is changed

### ISSUE THREAD

**Issue by frostming** [coveragepy/coveragepy#940]
**Describe the bug**
A clear and concise description of the bug.

I am developing a package manager [pdm](https://github.com/frostming/pdm.git) which provides a script runner, just like `pipenv run` or `poetry run`.  But when I tried to apply it to my other project, I noticed a significant decrease in the testing coverage: https://github.com/frostming/marko/pull/46, because I didn't change a line of the Python code, just changed the way how to invoke the testing to `pdm run`. `pdm run` will call a subprocess running `pytest --cov marko tests`, with the `__pypackages__/<major.minor>/lib` injected into `PYTHONPATH`.

Any help is appreciated.

**Comment by nedbat** [comment]
I don't understand what you are doing, or what you are seeing.  How can I help?

**Comment by frostming** [comment]
I put all lib files under `__pypackages__/<major.minor>/lib`, when running the tests, the path will be inserted into `sys.path`, the directory is like this:
```
foo
    __pypackages__
        3.8
            lib
                bottle
    foo/
    tests/
```
The configuration is
```
[coverage:run]
branch = True
parallel = True
source = foo/
omit =
    foo/cli.py

[coverage:report]
# Regexes for lines to exclude from consideration
exclude_lines =
    # Have to re-enable the standard pragma
    pragma: no cover

    # Don't complain about missing debug-only code:
    def __repr__

    # Don't complain if tests don't hit defensive assertion code:
    raise AssertionError
    raise NotImplementedError
    # Don't complain if non-runnable code isn't run:
    if __name__ == .__main__.:
```

Then I saw the coverage decreased by 13% compared with the old venv manner.
