### ISSUE TITLE
Unexpectedly missing coverage + strange report format (PyPy3 7.1.1)

### ISSUE THREAD

**Issue by vytas7** [coveragepy/coveragepy#943]
**Describe the bug**
Coverage is reportedly missing on one line.
Moreover, that line is reported using a strange format, just: `-96`.
The mentioned line 96 is whitespace, FWIW.
[The summary docs](https://coverage.readthedocs.io/en/coverage-5.0.3/cmd.html#coverage-summary) don't provide any similar example wrt the observed format.

**To Reproduce**
Run `tox` for this pull request on PyPy3 7.1.1: https://github.com/vytas7/falcon-sqla/pull/4.
Reproduced thrice by rerunning the job.
This is the original failure: https://travis-ci.org/vytas7/falcon-sqla/jobs/654144248#L285

**Expected behavior**
Expected 100% coverage.
If there was a bug in the code and/or the test suite, expecting to get a clear indication what was not covered.

**Comment by nedbat** [comment]
Hmm, that is weird.  The PyPy version in particular on Travis is pypy3.6-7.1.1 .  I'll try reproducing this myself.

**Comment by vytas7** [comment]
FWIW, we've resolved this by retargeting to PyPy 7.2.0 found on Travis Ubuntu 18.04. 7.3.0 is unavailable in Travis OoB but everything passes in the pypy:3 Docker image as well.

The only question remaining I guess is whether this is a pure PyPy bug, or it reveals any edge case in coveragepy as well.

**Comment by nedbat** [comment]
Thanks for the interesting bug!

Fixed (for PyPy 7.1) in 6f4c0dcd49c50ae393d30bd0b42c3df7661b50f2

**Comment by nedbat** [comment]
This is now available in [coverage v5.0.4](https://pypi.org/project/coverage/5.0.4/)
