### ISSUE TITLE
Documentation issue: ‘ws’ missing from source_token_lines description

### ISSUE THREAD

**Issue by snoopyjc** [coveragepy/coveragepy#947]
**Describe the bug**
Documentation issue: ‘ws’ missing from source_token_lines description

**Expected behavior**
‘ws’ Is shown in the example but it’s not defined in the list of tokens.  I assume it’s for white space and you put the type and amount of white space in the argument e.g. tabs vs spaces.

**Comment by nedbat** [comment]
Sorry, I'm not sure what documentation you are looking for? What drew your attention to source_token_lines in the first place?  The example shows a number of token classes, why call out "ws" particularly?

**Comment by snoopyjc** [comment]
Hi Ned. “ws” isn’t in the list of defined tokens. It’s shown in the little code snippet though:

(The image didn’t post but it should be in your email - here is what I’m talking about:

    Each pair has a token class, and the token text. The token classes are:

    'com': a comment
    'key': a keyword
    'nam': a name, or identifier
    'num': a number
    'op': an operator
    'str': a string literal
    'txt': some other kind of text

Notice ‘ws’ is missing from the list)

I’m looking to update my RiveScript Coverage Plugin to perform syntax highlighting so that’s why I was looking at that function. 

-joe

**Comment by nedbat** [comment]
Added in 78eb9ec26d6073a1655d51f7ca1d91e3fb60b169

**Comment by snoopyjc** [comment]
Thank you!  Can you please add the RiveScript Coverage Plugin to the list of available plugins?

-joe
