### ISSUE TITLE
Option to use relative file paths in xml report

### ISSUE THREAD

**Issue by kammala** [coveragepy/coveragepy#948]
**Is your feature request related to a problem? Please describe.**
There is an option for `run` command to store only relative file paths. It is very useful while running your tests inside one environment(e.g. docker) and using results in another one(e.g. on Jenkins node). It is also common to generate cobertura report in the same environment you are running tests, but this report always includes absolute path for sources(I think, because of [this line](https://github.com/nedbat/coveragepy/blob/master/coverage/xmlreport.py#L44)). This way it is impossible for tools like Jenkins Cobertura plugin or Sonarqube to find source files properly(Sonarqube either fails to parse coverage report at all or raises warning, for example).

**Describe the solution you'd like**
`json` reports use paths from `.coverage` file and thus respect this `relative_files` setting from `run` section.
It would be nice either to not canonicalize paths for sources or to have an option which will skip path normalization(this way it may be more backward compatible)

**Describe alternatives you've considered**
I tried to use `combine` and define sources in `[path]` section of config but it ends up with absolute path in the end report anyway.

**Comment by kammala** [comment]
inspired by discussion in #597

**Comment by nedbat** [comment]
This seems very reasonable :)

**Comment by roniemartinez** [comment]
Same issue here :( CodeClimate outside of docker fails as the report is using absolute path.

**Comment by nedbat** [comment]
As of f668d6f3, using `[run] relative_files=True` will make the XML report store relative file names.

**Comment by nedbat** [comment]
This is now available in [coverage v5.0.4](https://pypi.org/project/coverage/5.0.4/)
