### ISSUE TITLE
coverage pip default installation for python 3.8 does not include c extensions

### ISSUE THREAD

**Issue by andrewgill-dev** [coveragepy/coveragepy#949]
**Describe the bug**
When installing coverage via pip install coverage the version available for windows does not have c extensions compiled.

**To Reproduce**
How can we reproduce the problem?
1. What version of Python are you using? 3.8 (works fine in 3.7)
2. What version of coverage.py are you using? 5.0.3
3. What code are you running? coverage --version

run `pip install coverage` this works fine under 3.7 but under 3.8 it installs without c extensions making it incredibly slow.

**Expected behavior**
The default pip installed version of coverage should be compiled with c extensions.

**Additional context**
It is possible to use the compiled wheel from https://www.lfd.uci.edu/~gohlke/pythonlibs/#coverage, however if you have a cicd which runs tox and creates a new virtual environment it will install the without c extensions version and take 6-10 times as long to complete tests.

**Comment by andrewgill-dev** [comment]
This issue appears to be caused by the windows wheel for python 3.8 having the m ABI flag, which I believe should be removed for all python 3.8 wheel distributions.

**Comment by mjpieters** [comment]
Related pip issue: pypa/pip#6885, pip will no longer consider cp38m wheels.

**Comment by mjpieters** [comment]
I think that all that is needed is a newer version of `wheel`, see pypa/wheel#303

**Comment by mjpieters** [comment]
I've confirmed that a newer version of wheel should fix this. Currently coverge.py uses 0.33.1:

https://github.com/nedbat/coveragepy/blob/1148bf9118f9df3458cae933601a2638e0684218/requirements/wheel.pip#L8

but the 3.8 fixes dropping the `m` flag were part of [0.33.6](https://github.com/pypa/wheel/compare/0.33.4...0.33.5).

**Comment by nedbat** [comment]
Fixed in 907f0e8b.

**Comment by nedbat** [comment]
This is now available in [coverage v5.0.4](https://pypi.org/project/coverage/5.0.4/)
