### ISSUE TITLE
How could coverage.py xml report contains “methods” keyword？

### ISSUE THREAD

**Issue by leafonsword** [coveragepy/coveragepy#952]
I use coverage.py's xml report to combine with jenkins and Cobertura to generate code coverage rate, and command is `coverage xml sources/test_calc.py`

While Python and coverage.py's xml report just contains 5 indexes:
![image](https://user-images.githubusercontent.com/1754580/76294717-579f0800-62ee-11ea-9d22-699e60996e8b.png)

But Java and maven's xml report contains 6 indexes:
![image](https://user-images.githubusercontent.com/1754580/76294717-579f0800-62ee-11ea-9d22-699e60996e8b.png)

So could coverage.py's xml report contains “methods” keyword？

**Comment by nedbat** [comment]
I don't know what a methods count would be counting.  Python code doesn't need to live in methods as it does in Java.  What do you expect the methods information to show?

**Comment by leafonsword** [comment]
@nedbat I also don't know how a method shows in Python like Java, but our company's  inner system needs this; So I insert fake methods informathon, that works ok:
```
sed -i 's/<methods\/>/<methods>\n<method name="fakemethod" signature="" line-rate="100" branch-rate="100" complexity="0">/g' coverage.xml
sed -i '/fakemethod/a </method>\n</methods>' coverage.xml
```
