### ISSUE TITLE
Does this coverage tool can detect the code coverage of the web application code 

### ISSUE THREAD

**Issue by chunji08** [coveragepy/coveragepy#953]
Hi there, 
I am the beginner of this coverage tool and I have this question: 
1) We have a web application which is written in python, and deployed onto the AWS cluster. 
2) Now from my local, I have created UI automated test cases by selenium & python in the BDD format. 
Now If I was to run my testing as 

> coverage run -m behave  X1..feature
> coverage report -m

What code coverage would be reported ?  The % usage of my local python selenium script ? OR the % of this web application ? 

I was hoping the later one, right ?  If not, can someone give me the direction how I may achieve this ? 

Thanks a lot ! 

Chun

**Comment by nedbat** [comment]
That will record the coverage of your local selenium script.  If you want to record the coverage of the web application, then you need to use coverage to run the web application.  Coverage.py doesn't have special facilities to do this.  Typically, you wouldn't measure the coverage on a production site like AWS anyway: you would run your tests in a more local configuration.

**Comment by chunji08** [comment]
Thanks for the tips.
