### ISSUE TITLE
Using django_nose.NoseTestSuiteRunner, Dynamic Context is listed as `nose.case.Test.runTest`

### ISSUE THREAD

**Issue by graemeworthy** [coveragepy/coveragepy#954]
Dynamic Context is listed as  `nose.case.Test.runTest` rather than the expected `tests.models`

**Describe the bug**

Using django with django_nose as a Test Runner, setting `settings.py`
```
TEST_RUNNER = "django_nose.NoseTestSuiteRunner"
```

the .coveragerc contains:
```
[run]
dynamic_context = test_function
```
When I compile the coverage with the command line:
```
coverage html --show-contexts
```

The coverage ctx dropdown says only:
```
nose.case.Test.runTest
```
**To Reproduce**
How can we reproduce the problem?  Please *be specific*.
1. What version of Python are you using? `3.6`
1. What version of coverage.py are you using? `5.0.3`
1. What versions of what packages do you have installed? 
```
django_nose: 1.4.6
nose: 1.3.7
```
1. What commands did you run?
```
It's django:  ./manage.py test {test_filename}
```

**Comment by nedbat** [comment]
Hi @graemeworthy, sorry this has taken a long time.  Do you happen to have a complete runnable example I could use?  That is, "clone this, run this command"?

**Comment by nedbat** [comment]
Feel free to re-open this if you come back to it.
