### ISSUE TITLE
paths cannot be altered by plugins

### ISSUE THREAD

**Issue by gaborbernat** [coveragepy/coveragepy#967]
https://coverage.readthedocs.io/en/latest/config.html#paths shows how to user can set paths. This cannot be achieved by plugins due to paths not being defined as a set/get option; but rather directly as attribute on the configuration object. Due to https://github.com/nedbat/coveragepy/blob/master/coverage/control.py#L272-L276 the plugin cannot reliably access and extend this.

Came up while trying to address https://github.com/asottile/covdefaults/issues/3

**Comment by gaborbernat** [comment]
Any plans for a release anytime soon?☺️

**Comment by nedbat** [comment]
Fixed in edadbece.

**Comment by nedbat** [comment]
This is available in 5.1: https://pypi.org/project/coverage/5.1/

**Comment by gaborbernat** [comment]
Thanks!
