### ISSUE TITLE
Make `skip_empty` have an effect on XML reporting

### ISSUE THREAD

**Issue by ilkecan** [coveragepy/coveragepy#976]
**Is your feature request related to a problem? Please describe.**
It seems setting `skip_empty` to True in `.coveragerc` has no effect on XML reporting.

**Describe the solution you'd like**
I would like setting `skip_empty` to True to actually skip the empty files during XML reporting. 

**Describe alternatives you've considered**
I can currently omit the empty files, but this not very convenient.

**Additional context**
I have empty `__init__.py` files in my project (they are actually only created because Coverage.py requires them to include un-tested files in those directories in the report.) and when I generate an XML report while `skip_empty` is set to True, those empty files are also in the report. As a result, [cobertura plug-in in Jenkins](https://plugins.jenkins.io/cobertura/) shows wrong results (this might be unrelated).

**Comment by nedbat** [comment]
This is fixed in 97f05c988545f8ca588253fd325401c4834543b6

**Comment by nedbat** [comment]
This is now released as part of [coverage 5.2](https://pypi.org/project/coverage/5.2).
