### ISSUE TITLE
Support giving arbitrary paths to CoverageData's `basename` kwarg

### ISSUE THREAD

**Issue by spencerwilson-optimizely** [coveragepy/coveragepy#985]
**Is your feature request related to a problem? Please describe.**
Using the `coverage.CoverageData` API I would like to be able to load coverage data files from any directory, not just the current working directory.

I'm writing a script that loads a data file elsewhere on the filesystem, and it'd be valuable not to have to `os.chdir()` there and back again in order to load it.

**Describe the solution you'd like**
Document that arbitrary absolute and relative paths may be given to `CoverageData`'s `basename` kwarg.

**Describe alternatives you've considered**
Add an alternate kwarg to the `CoverageData` constructor, one whose name reflects its flexibility.

**Additional context**
Presently, `basename` is documented as "the base name of the data file, defaulting to “.coverage”." Since "base name" [generally means](https://en.wikipedia.org/wiki/Basename) "strip out leading directory components", this docstring seems to imply that one may only supply basenames to this kwarg. Additionally, there's no other kwarg on `CoverageData` relating to path to find the data file. This suggests (to me, anyway) that `CoverageData` only supports loading data files from the current working directory.

Incidentally the `basename` kwarg _can_ be used in this way, since as of coverage==5.1 it gets processed with `os.path.abspath` [here](https://github.com/nedbat/coveragepy/blob/coverage-5.1/coverage/sqldata.py#L199), whence the file gets loaded. So while the implementation appears to support giving arbitrary paths to `basename` today, to do so would be relying on implementation details of the library.

Thank you! P.S. contexts are an incredible feature.

**Comment by nedbat** [comment]
Hi, sorry I took so long to get to this.  As you saw, the basename can be a full path, and there have always been tests confirming that.  I've added a sentence to the docstring in a909ae3d.
