### ISSUE TITLE
Chromium does not persist sorting order in HTML report

### ISSUE THREAD

**Issue by ptoews** [coveragepy/coveragepy#986]
**Describe the bug**
When sorting the coverage report by a column in Chromium, clicking on a module report and then going back results in the table being sorted by the default order (name) again.

**To Reproduce**
1. What version of coverage.py are you using? The output of `coverage debug sys` is helpful
5.1
1. What commands did you run?
`coverage html -d tests/htmlcov`

Chromium Version: 81.0.4044.122

**Expected behavior**
Sorting order is persisted after navigation

**Additional context**
Does work in Firefox. Maybe related to #611

**Comment by nedbat** [comment]
The sorting is persisted in Chrome.  Do you know what the difference is here between Chrome and Chromium?

**Comment by ptoews** [comment]
No idea, but it might be something else.
Where is the sorting order supposed to be persisted? On the "Local Storage"? Because the Application Tab in the F12 menu doesn't show any values there.

**Comment by nedbat** [comment]
I can't be certain, but I think this is fixed with #1066.  Let me know if the problem persists.

**Comment by nedbat** [comment]
This is now released as part of [coverage 5.3.1](https://pypi.org/project/coverage/5.3.1).
