### ISSUE TITLE
Coverage Report not generated Python3.6 

### ISSUE THREAD

**Issue by nikul-serpentcs** [coveragepy/coveragepy#994]
**Describe the bug**
I installed paython3.6 and Successfully installed coverage-5.1 version

Whenever I run the python test file with **coverage run**
like. **python3.6 -m coverage run test_code.py**

**Error** 
Couldn't read data from '/home/.coverage': CoverageException: Doesn't seem to be a coverage.py data file

How to solve this issue??

**Comment by nedbat** [comment]
What is in the `.coverage` file?  If this is a bug in coverage.py, we're going to need to see a *lot* more information. I assure you that Python 3.6 generates coverage reports just fine.

**Comment by nedbat** [comment]
Feel free to re-open this if you have more information.
