### ISSUE TITLE
Fix exception causes

### ISSUE THREAD

**Issue by cool-RR** [coveragepy/coveragepy#998]
I was [going over](https://github.com/ipython/ipython/pull/12377) a few open-source Python packages and fixing the way exception causes are set, while a [failing CI run](https://gist.github.com/cool-RR/c57139f74ba38e6815a5ddfae537c60d#file-gistfile1-txt-L10) turned my attention to the fact that `coverage` has the same bug.

See line 10 of the traceback linked above. The line says "During handling of the above exception, another exception occurred" while it should say "The above exception was the direct cause of the following exception".

A fix would be trickier in the case of `coverage`, since it maintains Python 2.7 support. This can be done using a `raise`-like compatibility function that manually sets `new_exception.__cause__ = old_exception`. That's easy to write, and should probably be added in the `backward` module, the question is: Do you want this change in `coverage`?

**Comment by nedbat** [comment]
I've made these changes in https://github.com/nedbat/coveragepy/pull/1193 if you want to take a look.

**Comment by cool-RR** [comment]
Yes, that's good. And a rare sighting of a chained `SyntaxError` :)

**Comment by nedbat** [comment]
This is fixed in 4828872e19ee4e01eb390ba6dfae213cc22d928e
